### ISSUE TITLE
Products report using current price instead of price at time of sale

### ISSUE THREAD

**Issue by n9yty** [woocommerce/woocommerce-admin#4408] opened 2020-05-20 05:33 UTC
**Describe the bug**
When running a product report, in this case a single product and variations, the Net Sales column is based on the current product price, not the price of the item at the time of the sale.

**To Reproduce**
1) Run the report on a product for past sales
2) Change the product price
3) Compare the reports and see the numbers have changed

**Expected behavior**
Calculations should be done based on the price of the product/variation at the time of the sale in order to be meaningful.

**Comment by timmyc** [comment] 2020-08-05 21:22
Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the votes needed label and evaluate over time if this issue collects more feedback.

Don’t be alarmed if you don’t see any activity on this issue for a while.

**Comment by n9yty** [comment] 2020-08-05 21:27
I understand you have to have priorities, but this basically makes the report useless. I didn't sell it for the value of today, so you are changing history by using today's value. I can understand if it weren't available, but it is, so I would ask you to reconsider. Analysis is no good if you are, in effect, changing the past data.

**Comment by douglsmith** [comment] 2020-08-06 02:05
This really should be labeled as a bug and not votes needed.

**Comment by douglsmith** [comment] 2020-08-06 16:37
Thanks for changing the label, @timmyc. Can the issue be set back to open too?

**Comment by douglsmith** [comment] 2021-01-26 16:54
In case it wasn't clear, this analytics report is showing inaccurate results because it's pulling the wrong data.

**Comment by joshuatf** [comment] 2021-01-29 00:34
@n9yty @douglsmith I was unable to reproduce this issue.  Could you let me know if there are any other additional steps?  Here's what I did to try and recreate it:

1. Find an existing order and product from that order.
2. Note the price on the order.
3. Update the product price.
4. Note the `Net sales` column under `Analytics -> Products`.

I attempted this with both simple and variable products and in both cases the price in the analytics report remained unchanged.  Please let me know if there's anything I'm misunderstanding about the issue.

The product data from an order that's stored in the lookup tables is derived by:
`$net_revenue = round( $order_item->get_total( 'edit' ), $decimals );`

I think this would get the order amount and not the current product price from the looks of it, but maybe something else is happening.

**Comment by timmyc** [comment] 2021-01-30 00:55
This issue was linked to during the Woo Community Chat this week, so I've placed it into the 2.0 milestone in hopes that we can get some eyes on it quickly.

**Comment by n9yty** [comment] 2021-02-15 17:41
I am revisiting this, and I believe the issue does still exist.  I have run a "Variations" report, I have set the Date Range to encompass all history for our site (vs. Previous Period (which should not exist)). I set an Advanced Filter on Product to Include one specific product. The resulting report was set to chart "By year", with the intention of showing sales for the variations of this product.

The Variations section of the report does list the variations, with the Product / Variation Title, SKU, Items Sold, Net Sales, Orders, Status and Stock.

The problem is that, after we had stopped selling these variations, we had set the price to 999 to be sure none were purchased (we can debate that approach in another forum), but they were not at that price when they were sold.

However, the report is showing Items Sold of x where Net Sales is x * $999. 

This is what led us to report that the reporting was not using the price at the time of the original sale, but rather the current price in the system. In reality, for these orders of these variations of this product the Net Sales should not equal Items Sold * $999, it should equal Items Sold * ${price at time of sale}.

Does that clear things up?

**Comment by ilyasfoo** [comment] 2021-02-24 08:22
I have tried to reproduce the net revenue discrepancy in a test site and unable to do so.

>These orders were imported from a previous system, and it may have been the the price was set to $999 before the import. In looking at the metadata for the order lines of one order, there is a _line_subtotal of 999 and a _line_total of 9.95. When I view the order in WooCommerce admin it shows the item with a Cost of $999.00 x 1 with a Total of $9.95. It adds a note underneath "$989.05 discount".

@n9yty This is a very important detail that you've uncovered. I think this points to a flaw in the import & export plugin you've mentioned, and not in WooCommerce Admin's reports. If you're able to provide a step-by-step way to reproduce the issue with a fresh WooCommerce site, we may be able to help to raise this issue to the developers.

**Comment by timmyc** [comment] 2021-03-09 17:14
Based off the feedback from two different attempts to reproduce this, without being able to do so, It is sounding like this issue indeed might be specific to some legacy data on your site @n9yty - I'm going to close this out again. If we can get defined steps on how to reproduce this consistently on a fresh install of WooCommerce we can definitely re-open this issue and investigate further.

**Closed by timmyc** 2021-03-09 17:14 UTC
Labels: feature: analytics, needs feedback, type: bug
