### ISSUE TITLE
Nav disappeared after choosing "Set up manually" in tax task

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#5710] opened 2020-11-20 21:05 UTC
**Describe the bug**
I was testing the tax task today to update some styles and noticed that when I clicked through after selecting "Set up manually", I was redirected to the correct area **Settings > Tax > Standard rates** but the nav disappeared. 

It reappeared upon refreshing the page, so I'm not sure it's a huge issue but want to share the issue to make sure it's not something that happens when installing extensions if the top level nav item isn't created right away.

**To Reproduce**
Open new WooCommerce site with task list on Home screen.

1. Go to 'Set up tax'
2. Click on 'Set up manually'
3. See nav disappear

**Expected behavior**
The navigation should appear and be located on the **Settings > Tax** item.

**Screenshots**
![set up manually and nav disappears](https://user-images.githubusercontent.com/5121465/99849776-c735ea00-2b41-11eb-8bc9-f84ed733f8a2.gif)

**Comment by elizaan36** [comment] 2020-11-23 18:39
Also wanted to add that refreshing the page while on the tax task jumps to **Analytics > Stock**. I'd expect to stay on the Home screen.

![jump to analytics](https://user-images.githubusercontent.com/5121465/100001484-d9ee3000-2d88-11eb-9550-321a7dbc7be6.gif)

**Comment by joshuatf** [comment] 2020-11-23 19:03
@elizaan36 I was unable to reproduce on the latest dev branch.  It's very odd that it appeared on refresh since the tax page is not React-based so the original load should have triggered a full page reload.

Can you open your console and repeat this and take screenshots of any errors that pop up?

**Comment by elizaan36** [comment] 2020-11-23 21:43
hey @joshuatf I'm not seeing any errors but was able to reproduce the jump to *Analytics > Stock*. https://share.getcloudapp.com/BluQgQov

Looks like the nav doesn't disappear anymore after navigating to "Set up manually", so that's resolved itself on my site at least.

**Comment by joshuatf** [comment] 2020-11-24 22:37
I do see the active status being displayed wrong in a few places (though I'm seeing it work correctly for taxes).  When we're changing routes, often times there's not an exact match in the menu.

For context, this currently this will mark items active via match score (created by how many params in the URL match a given item's URL) to the final item matched (meaning if there's a match score of `5` for multiple items, it will mark the latter one as active).

This can be seen here, where the location URL is `/wp-admin/admin.php?page=wc-admin&task=tax` and we'd want it to match the item with a URL of `/wp-admin/admin.php?page=wc-admin` instead of matching `/wp-admin/admin.php?page=wc-admin&path=/payments/deposits`.

<img width="1049" alt="Screen Shot 2020-11-24 at 5 29 44 PM" src="https://user-images.githubusercontent.com/10561050/100159162-4184a800-2e7b-11eb-803d-342c745938d7.png">

I see several solutions to this:

* Use the first matched instead of the last.  Solves this current problem, but not necessarily all in the future.
* Update the match score to give more points for not having extra params in the URL (more exact match).  This may be the best, but needs to be tested against current item matching criteria.
* Implement some form of regex matching where items can manually declare what should be matched.  Most complex and introduces other problems; I'd prefer to avoid this route if we can.

/cc @joelclimbsthings since it looks like you've self-assigned this issue.

**Comment by psealock** [comment] 2020-11-25 03:06
The problem appears to come from the Home Screen item having query parameters also pointing to the same Nav item

* `/wp-admin/admin.php?page=wc-admin&task=*`
* `/wp-admin/admin.php?page=wc-admin`

Other times, an additional query parameter points to a new page but other times it does not. 

* `/wp-admin/admin.php?page=wc-settings` (General Settings)
* `/wp-admin/admin.php?page=wc-settings&tab=account` (Accounts & Privacy)

Admittedly, this may happen with extensions too and to go even further multiple query parameters may exist where each one pertains to either of the two scenarios above.

Given this, would this idea work:

If, at the end of the matching algorithm there are 5 possible urls with the same score can we re-run the algorithm amongst the 5 returned result, but remove one query parameter from the current URL that does not have a matching query parameter in any of the results.

For example

`example.com/path?color=green&size=large&tempo=fast` results in the following having the same score:

* `example.com/path?color=green`
* `example.com/path?color=green&size=small`
* `example.com/path?color=green&location=USA`

At this point, can we remove the `tempo` query parameter from the current URL given that there is no exact matching query parameter in any of the possiblities.

The algorithm runs again using `example.com/path?color=green&size=large` as the current URL returning the exact same 3 results:

* `example.com/path?color=green`
* `example.com/path?color=green&size=small`
* `example.com/path?color=green&location=USA`

We repeat the process, but remove `size` query parameter given there is no exact match and try again with `example.com/path?color=green` resulting in an exact match.

* `example.com/path?color=green`

Otherwise, we can ask `Menu::add_plugin_item` to provide additional potential query parameters, but that could get messy and error prone.

Thoughts?

**Comment by psealock** [comment] 2020-12-10 23:24
Fixed by https://github.com/woocommerce/woocommerce-admin/pull/5818

**Closed by psealock** 2020-12-10 23:24 UTC
Labels: Navigation
