### ISSUE TITLE
Dashboard summary numbers disagree with summary numbers in reports

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/woocommerce-admin#1874] opened 2019-03-21 22:04 UTC
**Describe the bug**
The summary numbers on the dashboard disagree with summary numbers in the various reports

**To Reproduce**

1. Limit the date range to a single day so it's easier to see what's going on. 
2. Note the totals in the dashboard summary numbers
3. Compare to summary numbers in report
4. Note that they are different

**Expected behavior**
They should match

**Screenshots**

Dashboard summary numbers

<img width="2012" alt="Screen Shot 2019-03-21 at 2 56 01 PM" src="https://user-images.githubusercontent.com/4500952/54787717-e13f5c80-4be9-11e9-9864-61ae16418e27.png">

Summary numbers in orders report

<img width="2012" alt="Screen Shot 2019-03-21 at 2 55 51 PM" src="https://user-images.githubusercontent.com/4500952/54787798-26fc2500-4bea-11e9-8d36-a9cdb6c81ddb.png">

Net Rev. and Orders are different than what's on the dashboard. Note the numbers in the reports are correct.

**Comment by psealock** [comment] 2019-03-21 22:35
I can reproduce this error only when looking at orders created today, which incidentally produced a database error. 

Is this your experience @LevinMedia? If so, there may be a problem recently introduced.

**Comment by LevinMedia** [comment] 2019-03-22 02:50
I'm seeing the issue on other date ranges as well - here's month to date:

Dashboard charts and individual reports agree, summary numbers don't

<img width="2022" alt="Screen Shot 2019-03-21 at 7 46 46 PM" src="https://user-images.githubusercontent.com/4500952/54797680-5757b980-4c12-11e9-8b86-3d7cf320cede.png">
<img width="2022" alt="Screen Shot 2019-03-21 at 7 46 54 PM" src="https://user-images.githubusercontent.com/4500952/54797686-5e7ec780-4c12-11e9-8b2b-80a125890ec6.png">

**Comment by psealock** [comment] 2019-03-22 03:20
From Slack conversation:

>Okay! Here is one thing I am seeing: wc-smooth creates orders for an entire day, ie if you do it at noon, then some will be in the future. The discrepency I noted earlier is shrinking, which means one query is looking at the entire day, while the other is looking at the day so far

>I bet on the 22nd, you'll see numbers for the 21st align correctly

Considering orders won't be placed in the future out in the wild, this is a non-issue. Lets wait a day and see.

**Comment by psealock** [comment] 2019-03-24 23:20
I have confirmed that after the passing of the day, the numbers are now in alignment. I feel ok closing this because its only affected by orders programatically placed in the future for testing.

**Closed by psealock** 2019-03-24 23:20 UTC
Labels: Analytics, [Type] Bug
