### ISSUE TITLE
Unable to delete cron job: wc_admin_unsnooze_admin_notes

### ISSUE THREAD

**Issue by ecomturbo** [woocommerce/woocommerce-admin#6920] opened 2021-05-04 03:35 UTC
We are Unable to delete cron job: wc_admin_unsnooze_admin_notes. After deletion, it re-appears.

We tried deleting it using the plugin: WP Control but the cron re-appear immediately after.

We are running WooCommerce Version 5.2.2.

When trying to delete it directly from phpMyAdmin data base we are not sure which line should be deleted: see https://tinyurl.com/yzzj45nl

Thanks for your assistance.

**Comment by adrianduffell** [comment] 2021-05-04 04:29
Hi @ecomturbo, thanks for raising this issue. I'm curious what the reason is for deleting this? 

> WP Control but the cron re-appear immediately after.

I'm not sure there is a reliable way to delete this at the moment because the behavior you observe is intended. A new cron event is scheduled hourly if it doesn't exist:

https://github.com/woocommerce/woocommerce-admin/blob/89816b0e9c74365fa063037edb1efff2c8c21c99/src/Notes/Notes.php#L223-L230

This is done so "snoozed" notes can be regularly checked and displayed again if the snooze has expired.

**Comment by ecomturbo** [comment] 2021-05-04 04:39
Hi @adrianduffell, It was clearly asked to be deleted here by @jeffstieler: https://github.com/woocommerce/woocommerce-admin/pull/3662#issuecomment-831216903

This Cron Job is empty which explains why we need to delete it. Moreover it triggers every hour.

Please see this screenshot: https://tinyurl.com/yzmf52mo

**Comment by adrianduffell** [comment] 2021-05-04 05:02
Hi @ecomturbo,

Thanks for pointing me to the previous issue.

I am able to reproduce the empty action with a clean install of WooCommerce 5.3.0, WC Admin, 2.3.0-beta.1, WP 5.7.1

![image](https://user-images.githubusercontent.com/9312929/116962086-a3252a00-acd7-11eb-8fd2-d346f5fb7e07.png)

It seems like there is a bug here where the action is not assigned to the event properly. I think this is likely to preventi snoozed notes from re-appearing.

Please correct me if I'm wrong, but I don't think you need to worry about deleting the event. While it will be scheduled hourly, nothing should run as a result of it being empty.

**Comment by ecomturbo** [comment] 2021-05-04 05:38
Thank you for your feedback @adrianduffell 

Yes you're very correct. We were just investigating this to ensure we maintain a clean and neat install.

**Comment by lukecav** [comment] 2022-01-03 18:42
Able to reproduce the same issue in WooCommerce 6.0.0, WordPress 5.8.2.

**Comment by chihsuan** [comment] 2022-01-20 03:20
I've looked into this. There was an action bound to `wc_admin_unsnooze_admin_notes` but it was removed in https://github.com/woocommerce/woocommerce-admin/pull/3936/commits/87d29d2a10d15285e21f57b13d649c6f97ab68ae#diff-9629281bfd9d7bc9363b02940377d6e73f7b122a9bcfa9e1ead3e6a90c196152L52

I cannot find the reason why we remove it but It seems that it is safe to remove the `schedule_unsnooze_notes` action or just close this since this doesn't cause any effects and it's over 6 months old.

@ilyasfoo Do you think we should remove it or close this?

**Comment by ilyasfoo** [comment] 2022-01-20 06:59
@chihsuan Thanks for asking! It feels like we're so close, but I think we can close this issue for now. I'll keep this in a list of issues in case we can revisit it anytime in the future.

**Comment by chihsuan** [comment] 2022-01-20 07:40
Okay, I'm closing this. Thanks!

**Closed by chihsuan** 2022-01-20 07:40 UTC
Labels: type: bug, feature: inbox, priority: low
