### ISSUE TITLE
'Free shipping' indicator is pushed out of the viewport in mobile screens

### ISSUE THREAD

**Issue by rodelgc** [woocommerce/woocommerce-admin#6390] opened 2021-02-21 10:34 UTC
**Describe the bug**
The 'Free shipping' text in the 'Shipping cost' input box is pushed out of view in mobile screens.

**To Reproduce**

1. Using a mobile device in portrait mode, go to 'Home'
2. Click on 'Set up shipping'
3. Notice that the "Free shipping" indicator is pushed all the way to the right and out of view of the mobile screen's viewport.

**Expected behavior**
'Free shipping' indicator should be completely visible in portrait mode of mobile screens.

**Screenshots**
https://user-images.githubusercontent.com/4509348/108622339-2245e880-7473-11eb-87a8-cf46840abf7b.jpg

**Smartphone:**

* Device: Samsung Galaxy Note9
* OS: Android v10
* Browser: Firefox
* Version: 85.1.3

**Comment by ilyasfoo** [comment] 2021-03-05 05:39
I was able to reproduce this issue with Firefox browser on both Android device and Macbook. Issue not reproducible in Safari and Chrome.

<img src="https://user-images.githubusercontent.com/3747241/110071817-b12dfb80-7db7-11eb-91b7-47ed7ec7295d.png" width="500">

**Comment by chihsuan** [comment] 2022-01-13 05:46
I cannot reproduce this on the Firefox browser with the main branch code.

![Screen Shot 2022-01-13 at 13 43 37](https://user-images.githubusercontent.com/4344253/149272755-6c704e4e-2536-4071-ab77-74c038d209e3.png)

I'm closing this since this is over 6 months old.

**Closed by chihsuan** 2022-01-13 05:46 UTC
Labels: type: bug, feature: activity panel
