### ISSUE TITLE
admin_notices not getting called in Orders page

### ISSUE THREAD

**Issue by crackTheCode** [woocommerce/woocommerce-admin#4140] opened 2020-04-15 21:57 UTC
the admin_notices action is not working in Orders page
WP 5.4
WC 4.0.1

Any ideas?

**Comment by timmyc** [comment] 2020-08-25 21:09
I am able to see admin notices on the Order page, so since I can't reproduce this I'm going to close this out

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/22080/91228096-83ffe280-e6dc-11ea-9f17-ec8b04e7bd2c.png">

**Closed by timmyc** 2020-08-25 21:09 UTC
