### ISSUE TITLE
Visiting "Personalize your store" popup skewed to the right on desktop

### ISSUE THREAD

**Issue by edwinho89** [woocommerce/woocommerce-admin#7090] opened 2021-05-29 05:13 UTC
**Describe the bug**
Visiting "Personalize your store", the popup notification skewed to the right on desktop, unable to click on the popup message to continue.

**To Reproduce**

1. Go to 'WooCommerce > Home'
2. Click on 'Personalize your store' which will lead you to /wp-admin/admin.php?page=wc-admin
3. See error

**Expected behavior**
A popup message on "We're here to help" which required us to click next to proceed.

**Screenshots**
The popup message got skewed to the right, hence not able to proceed to the next step.

Reported user was kind enough to share a screenshot on what they see below:

![image link 2](https://cldup.com/-EMP8OS_If.png)
image link: https://cloudup.com/cogZ97eQxj7

SU'd and was able to reproduce this behaviour on our end.

**Desktop (please complete the following information):**

* OS: OSX 11.4
* Browser Chrome
* Version 90.0.4430.212 

**Workaround**
By switching reducing window screen to mobile width, we're able to click on the popup message to continue with the page. (The popup continues to flicker constantly on mobile, though we did not had the chance to grab a screenshot/gif of it)

Click on "Got it" removes the popup notification, and user is able to proceed with the rest.

Reported in 29849937-hc

**Comment by samueljseay** [comment] 2021-06-01 01:00
@edwinho89 Thanks for raising this, I just can't view either of those screenshots, any chance you could upload some new ones?

**Comment by edwinho89** [comment] 2021-06-02 15:16
@samueljseay looks like the reported user had deleted the image from their media library :(

However, I was able to reproduce this on a fresh AT site with only WooCommerce (and recommended plugins when initiating Woo for the first time)

https://awesomefoodanddrink.blog/wp-admin/admin.php?page=wc-admin&task=appearance

I've just added you as an admin on my test site - maybe you'll be able to see similar results as I did. :D

**Comment by edwinho89** [comment] 2021-06-02 15:22
Here's a preview on mobile, where we were able to click on the "Got it" button to bypass this popup. You should see the popup notification flickering heavily on mobile.

https://cloudup.com/ciIPnXz3WRE

**Comment by moon0326** [comment] 2021-06-02 22:26
@edwinho89 Thank you for taking the time to report this issue. I was able to confirm the bug on an ecommerce plan site. I had to turn off the new WC navigation from Settings -> Advanced -> Features though.  

I also think this issue is related/duplicate to https://github.com/woocommerce/woocommerce-admin/issues/7035

**Comment by ilyasfoo** [comment] 2021-06-03 08:07
>Here's a preview on mobile, where we were able to click on the "Got it" button to bypass this popup. You should see the popup notification flickering heavily on mobile.

@edwinho89 I was able to reproduce this, but I think this problem is not related to the issue. This occurs for all screens with less than 360px width (namely iPhone 5). However, I also think this would be a low-priority issue.

**Comment by edwinho89** [comment] 2021-06-03 09:01
> It looks like this bug only shows up on an e-commerce plan site. I wasn't able to reproduce it on a business plan.

Hi @moon0326 ! The test site I have is on a Business plan, so looks like it is happening on AT sites (though I'm not sure why it isn't reproducible on your end. I've added you as an admin on the test site on Business plan, feel free to have a look! https://awesomefoodanddrink.blog/wp-admin/admin.php?page=wc-admin&task=appearance

> I was able to reproduce this, but I think this problem is not related to the issue. This occurs for all screens with less than 360px width (namely iPhone 5). However, I also think this would be a low-priority issue.

That's okay, thanks for looking @ilyasfoo 😄 Do let me know if you would like to create it as a separate GH on the mobile issue.

**Comment by ilyasfoo** [comment] 2021-06-04 03:59
>That's okay, thanks for looking @ilyasfoo 😄 Do let me know if you would like to create it as a separate GH on the mobile issue.

@edwinho89 Yes I'd appreciate that, thanks!

Btw the issue with the popup skewed to the right should be fixed soon, it's waiting for a release in wpcomsh. I'll let you know when the fix lands.

**Comment by ilyasfoo** [comment] 2021-06-08 02:08
@edwinho89 The fix has landed in WP.com, would you mind test to see if the issue is resolved?

**Comment by edwinho89** [comment] 2021-06-08 03:59
@ilyasfoo Yes, I can confirm it has been addressed, thank you! Feel free to close as duplicate on the issue.

Also, created separate GH on the flickering issue https://github.com/woocommerce/woocommerce-admin/issues/7135

**Closed** 2021-06-08 03:59 UTC
Labels: type: bug
