### ISSUE TITLE
Spaces are trimmed from concatenated strings

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#3619] opened 2020-01-23 07:08 UTC
**Describe the bug**
When concatenating multiple strings together, any whitespace around a string is trimmed by the translation build script.

This prevents us from creating sentences with spaces over multiple lines and may lead to very long lines in addition to unexpected behavior if not caught before merge.

**To Reproduce**

1. Create a sentence with a space that's concatenated in a component file.  E.g.:
```js
__( 'Here is one sentence.' + ' And this one will have its whitespace trimmed', 'woocommerce-admin' )
```
2. Run the i18n build scripts.
3. Note the translation for the string in the pot file.

**Expected behavior**
Expected spaces to be allowed in concatenated strings.

**Screenshots**

<img width="745" alt="Screen Shot 2020-01-23 at 3 04 51 PM" src="https://user-images.githubusercontent.com/10561050/72963283-ccc38600-3df1-11ea-9292-0f1a31160571.png">

**Comment by jeffstieler** [comment] 2020-07-21 18:11
I can't reproduce this. Is this still occurring for you @joshuatf ?

**Comment by timmyc** [comment] 2020-08-25 19:24
Since we haven't had further reports here, I'm going to close this out.

**Closed by timmyc** 2020-08-25 19:24 UTC
Labels: Build, [Status] Needs feedback, [Type] Bug
