### ISSUE TITLE
Setup wizard free features checkbox re-check itself

### ISSUE THREAD

**Issue by ilyasfoo** [woocommerce/woocommerce-admin#8163] opened 2022-01-13 03:53 UTC
### Describe the bug

Reproduced this in 3.1.0-rc.1. It seems after installing extensions via free features in the business features tab, all checkboxes are automatically checked just before navigating to the next step. I confirm the plugin is not actually installed, this is only a visual bug. However, users may think it's installed along, so I think this should be prioritized.

### To Reproduce

1. Go to Business Features tab in Setup Wizard
2. Deselect all extensions and reselect only 1
3. Click continue
4. Observe the other extensions are re-selected just before it navigates to the next screen

### Screenshots
<img src="https://cdn-std.droplr.net/files/acc_1119691/6SzAZY" width="600">

### Expected behavior
Checkbox stays the same until the end

**Comment by chihsuan** [comment] 2022-01-13 04:16
> However, users may think it's installed along, so I think this should be prioritized.

Agree! 👍  

Possible this is a duplicate of this issue woocommerce/woocommerce#32223. We can close them together once we fix this.

**Comment by chihsuan** [comment] 2022-01-14 10:33
> > However, users may think it's installed along, so I think this should be prioritized.
> 
> Agree! 👍
> 
> Possible this is a duplicate of this issue woocommerce/woocommerce#32223. We can close them together once we fix this.

It turns out they're different. To fix woocommerce/woocommerce#32223, we probably need to store the state on the global store to persist the state between steps.

**Closed** 2022-01-17 02:03 UTC
Labels: type: bug, needs cherry picking
