### ISSUE TITLE
[GlobalStep - 4.2 RC1][Windows] “There was error installing woocommerce-square. Please try again” error message is displayed while setting up CBD vertical On boarding Flow.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#4457] opened 2020-05-27 16:26 UTC
**Environment:**
Windows 10

**Steps to Reproduce:**
1. Create a site using Ninja tool.
2. Install all the plugins.
3. Tap on "Run the Setup wizard".
4. Complete Store Details.
5. On Industry page select "CBD and other hemp-driver products".
6. Complete all the introductory tabs i.e., Product types, Business details and Theme.
4. Go to dashboard.
5. Click on Setup Payment.
6. Click on "Setup up" button next to Square.
7. Wait for few seconds.
8. Observe that  “There was error installing woocommerce-square. Please try again” error message is displayed 

**Note:** Able to reproduce 2/5 times

**Actual Result:**
“There was error installing woocommerce-square. Please try again” error message is displayed while setting up CBD vertical On boarding Flow

**Expected Result:**
No error should be displayed and payment method should be setup properly.

<img width="960" alt="#26621" src="https://user-images.githubusercontent.com/41110392/83046720-07ba1c80-a065-11ea-8e63-797186d6e6ca.png">

**Comment by timmyc** [comment] 2020-06-05 17:03
This bug is likely caused by JN rebooting during testing. Closing out.

**Closed by timmyc** 2020-06-05 17:03 UTC
