### ISSUE TITLE
WC Dashboard - Performance section doesn't load, causing high server load resulting in server errors

### ISSUE THREAD

**Issue by derekakelly** [woocommerce/woocommerce-admin#3904] opened 2020-03-16 03:34 UTC
**Describe the bug**
While viewing the WooCommerce dashboard. The Performance section doesn't load, causing high server load resulting in 503 & 500 errors in my console.

**To Reproduce**

1. Go to https://www.yoursite.com/wp-admin/admin.php?page=wc-admin
2. The page loads, but the entire performance section doesn't.

**Expected behavior**
the performance section to load and not over load my website.

**Screenshots**
This screenshot shows my console with some of the errors
https://imgur.com/a/6LVp8Bp

**Desktop (please complete the following information):**

* OS: win 10
* Browser chrome
* Version 80.0.3987.132

**Additional context**+

I checked my server load while attempting to load the WC Dashboard and it was extremely high, 30+.

I have a fairly decent cloud VPS hosted on SiteGround's on Google Cloud services. I have the following dedicated resources.
4 x Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz CPU Cores, 6GB RAM, 70GB SSD

In an attempt to resolve my issue, I went into the settings, cleared my Historical Data and then reimported it all. It didn't resolve my issue.

I went through the rest of the plugin's pages in an attempt to recreate the issue somewhere else, but the only thing i found was an presumably unrelated issue where the product search doesn't display sales data when doing a search using "All products with titles that include XXXXX". Otherwise all other WC Admin pages load fine.

Here is a screenshot from phpmyadmin with information regarding the size of the db tables i believe are in use by your plugin. I don't see anything off here, they're not that big.
https://imgur.com/a/Axzhtu2

As expected my debug.log shows time outs for exceeding the max execution time.
```
[16-Mar-2020 03:04:20 UTC] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /XXXXXX/wp-content/plugins/woocommerce-admin/src/API/Reports/TimeInterval.php on line 323
[16-Mar-2020 03:04:33 UTC] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /XXXXXX/wp-content/plugins/woocommerce-admin/src/API/Reports/TimeInterval.php on line 323
[16-Mar-2020 03:04:40 UTC] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /XXXXXX/wp-content/plugins/woocommerce-admin/src/API/Reports/TimeInterval.php on line 323
[16-Mar-2020 03:04:40 UTC] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /XXXXXX/wp-content/plugins/woocommerce-admin/src/API/Reports/TimeInterval.php on line 323
[16-Mar-2020 03:04:43 UTC] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /XXXXXX/wp-content/plugins/woocommerce-admin/src/API/Reports/TimeInterval.php on line 323
[16-Mar-2020 03:04:53 UTC] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /XXXXXX/wp-content/plugins/woocommerce-admin/src/API/Reports/TimeInterval.php on line 152
[16-Mar-2020 03:04:57 UTC] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /XXXXXX/wp-content/plugins/woocommerce-admin/src/API/Reports/TimeInterval.php on line 307
[16-Mar-2020 03:05:11 UTC] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /XXXXXX/wp-content/plugins/woocommerce-admin/src/API/Reports/TimeInterval.php on line 321
```

Thank you for your time, keep up the good work.
Derek

**Comment by sgrizzle7** [comment] 2020-03-17 00:45
I am having the same issue on a client account. Whenever we click the dashboard link the server locks up. We spent hours troubleshooting settings and adjusting PHP-FPM settings to no avail.  I reached out to WooCommerce who sent me a link to a plugin to disable the dashboard. The plugin adds this filter: 

add_filter( 'woocommerce_admin_disabled', '__return_true' );

I really would like to use the dashboard but I don't believe it is an option for my site.  I have a dedicated server with plenty of memory and horsepower and should not be having this issue.

**Comment by derekakelly** [comment] 2020-03-17 08:46
I have tested with the updated version and I'm still experiencing this issue.

```
[17-Mar-2020 08:41:37 UTC] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /xxxx/wp-content/plugins/woocommerce-admin/src/API/Reports/TimeInterval.php on line 152
[17-Mar-2020 08:41:37 UTC] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /xxxx/wp-content/plugins/woocommerce-admin/src/API/Reports/TimeInterval.php on line 152
[17-Mar-2020 08:41:54 UTC] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /xxxx/wp-content/plugins/woocommerce-admin/src/API/Reports/TimeInterval.php on line 323
[17-Mar-2020 08:41:55 UTC] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /xxxx/wp-content/plugins/woocommerce-admin/src/API/Reports/TimeInterval.php on line 323
```

**Comment by dz0ny** [comment] 2020-03-19 18:47
I can confirm:
Following requests cause 20x CPU usage on PHP workers (no effect on DB)

```
/wp-json/wc-analytics/admin/notes?page=1&per_page=25&status=unactioned&type=error%2Cupdate&_locale=user
/wp-json/wc-analytics/admin/notes?order=desc&orderby=date&page=1&per_page=1&type=info%2Cwarning&_locale=user
```

**Comment by psealock** [comment] 2020-03-22 20:06
We are also getting reports of errors such as the one below. Seems to be related.

>There are multiple 500 and 524 errors coming up along with this fatal error logged:

```
2020-03-22T17:05:54+00:00 CRITICAL Uncaught Error: Call to a member function format() on bool in /home/nginx/domains/whatihavelearnedteaching.com/public/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/Coupons/DataStore.php:175
Stack trace:
#0 /home/nginx/domains/whatihavelearnedteaching.com/public/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/Coupons/DataStore.php(301): Automattic\WooCommerce\Admin\API\Reports\Coupons\DataStore->include_extended_info()
#1 /home/nginx/domains/whatihavelearnedteaching.com/public/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Leaderboards.php(84): Automattic\WooCommerce\Admin\API\Reports\Coupons\DataStore->get_data()
#2 /home/nginx/domains/whatihavelearnedteaching.com/public/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Leaderboards.php(346): Automattic\WooCommerce\Admin\API\Leaderboards->get_coupons_leaderboard()
#3 /home/nginx/domains/whatihavelearnedteaching.com/public/wp-content/plugins/woocommerce/packages/woocommerc in /home/nginx/domains/whatihavelearnedteaching.com/public/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/Coupons/DataStore.php on line 175
```

**Comment by jeffstieler** [comment] 2020-03-24 16:09
I found this code in the "Advanced Coupons for WooCommerce" plugin:

```php
        $schedule_expire = isset( $_POST[ 'expiry_date' ] ) ? sanitize_text_field( $_POST[ 'expiry_date' ] ) : '';
        update_post_meta( $coupon_id , 'expiry_date' , $schedule_expire );
```

This is likely the root of these errors from the ticket:

```
Uncaught Error: Call to a member function format() on bool in /home/nginx/domains/domain/public/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/Coupons/DataStore.php:175
```

I'll get a fix up for that and then dig into the `TimeInterval` errors.

**Comment by robertstaddon** [comment] 2020-03-24 17:12
I also have a dedicated server with plenty of memory and horsepower and I also have the same issue. Instead of disabling the entire Dashboard, I've found that I can disable all of the "Performance" widgets .

I've increased my PHP timeouts to 180, disabled Mod_Security, disabled CloudFlare, disabled LiteSpeed caching, set LiteSpeed noconntimeout to 1, set LiteSpeed noabort to 1, and none of those things have seemed to help.

When I look at the Network waterfall in the Google Chrome console, it appears that the timeout issue is happening with the following calls:
/wp-json/wc-analytics/reports/performance-indicators?after=2019-03-01T00%3A00%3A00&before=2019-03-24T23%3A59%3A59&stats=revenue%2Ftotal_sales&_locale=user

**Comment by dz0ny** [comment] 2020-03-24 17:17
Related with tracing enabled https://github.com/woocommerce/woocommerce-admin/issues/3943

**Comment by derekakelly** [comment] 2020-03-24 17:55
@robertstaddon I can confirm that if I switch it to the previous period option, it does load. However the data is incorrect. It's showing $25k in sales, whereas we've had $66k in sales so far this month.

**Comment by robertstaddon** [comment] 2020-03-24 18:15
What if you "Import Historical Data" under "Analytics > Settings"?

**Comment by derekakelly** [comment] 2020-03-24 18:32
I've recently cleared it and reimported previously. Perhaps it's not counting some orders because we have so many in the "processing" status, rather than "completed"?

**Comment by rrennick** [comment] 2020-03-24 18:34
> Perhaps it's not counting some orders because we have so many in the "processing" status, rather than "completed"?

@derekakelly You can choose the statuses included in the reports in Analytics -> Settings.

**Comment by derekakelly** [comment] 2020-03-24 19:04
I'm thinking it was likely due to the plugin being disabled with 
 `add_filter( 'woocommerce_admin_disabled', '__return_true' );`

Unfortunately my site is experiencing more than 10 times it's normal traffic right now, so it's not a good time for me to troubleshoot. When i get some more time i will look into it again.

**Comment by jeffstieler** [comment] 2020-03-30 21:15
Just wanted to give you all an update.

We've got several performance improvements in the works:

* https://github.com/woocommerce/woocommerce-rest-api/pull/155
* https://github.com/woocommerce/woocommerce-admin/pull/3969
* https://github.com/woocommerce/woocommerce-admin/pull/3977
* https://github.com/woocommerce/woocommerce-admin/pull/3997
* https://github.com/woocommerce/woocommerce-admin/pull/4017

**Comment by timmyc** [comment] 2020-08-25 19:50
Since we have shipped all of the aforementioned performance fixes, and no recent reports here. I'm going to close this out.

**Closed by timmyc** 2020-08-25 19:50 UTC
Labels: cooldown period

**Comment by pojke** [comment] 2021-09-29 20:47
Having the same problem. To solve it you need to remove WC Status widget from dashboard:
Add this code to functions.php and you're good to go
```
function remove_dashboard_widgets() {
        // remove WooCommerce Dashboard Status
        remove_meta_box( 'woocommerce_dashboard_status', 'dashboard', 'normal');
}
add_action('wp_user_dashboard_setup', 'remove_dashboard_widgets', 20);
add_action('wp_dashboard_setup', 'remove_dashboard_widgets', 20);

```

**Comment by AntonyXSI** [comment] 2021-10-03 20:39
Have seen this timeout issue occur on multiple sites in the TimeInterval.php file on line 321, while loading the WP dashboard. Mainly on sites with a lot of orders. 

Could it be related to daylight savings? It's happened on the day before and the day of daylight savings in NZ. Then the same for AU when their daylight savings started a week later. The timeout occurred consistently on those days but loads fine now. The timezone in WordPress is set to the city location rather than UTC.

**Comment by Ben-Atherton** [comment] 2021-10-04 08:18
I am also experiencing the same issue and can confirm that adding `add_filter( 'woocommerce_admin_disabled', '__return_true' );` resolves it (at least temporarily) so there is definitely some more investigation needed here

**Comment by ShaneGowland** [comment] 2021-10-05 06:03
Just started happening for me on 3 sites. 

@AntonyXSI might be onto something RE daylight saving time. Here in South Australia we just switched to DST as well.

**Comment by mrdigitalau** [comment] 2021-10-07 22:22
Yep, two of my sites are having issues as well. Based in Australia using AEST time. Woocommerce Admin hangs and eventually times out. If I disable WooCommerce admin in functions.php, it fixes it.

**Comment by ilyasfoo** [comment] 2021-10-08 04:27
Hey folks, chiming as I think this may be related to daylight saving, as said by @AntonyXSI and @ShaneGowland. I have a fix waiting for review here: https://github.com/woocommerce/woocommerce-admin/pull/7763.

As a workaround, you may try to change the timezone in WordPress's Settings > General > Timezone to a UTC-based timezone instead of a city/state. This should temporarily disable daylight saving. Let me know if it doesn't work for you

**Comment by mrdigitalau** [comment] 2021-10-08 04:31
@ilyasfoo Hi Ilyas, I can confirm that changing to a UTC +11 instead of Sydney/Australia fixes the admin timeout issue for both my sites

**Comment by ilyasfoo** [comment] 2021-10-08 04:38
Thanks for confirming, @mrdigitalau!
