### ISSUE TITLE
WooCommerce overwrote my theme customizations

### ISSUE THREAD

**Issue by fijoy** [woocommerce/woocommerce-admin#7625] opened 2021-05-27 01:42 UTC
Two days ago, I installed and set up WooCommerce on my website that was already live.

Yesterday, I just went through the “Personalize your store” steps in WooCommerce. I skipped the “Create a custom homepage” step and only did the “Uploaded a logo” step. My expectation was that whatever personalization would only apply to the WooCommerce pages (Shop, Cart, Checkout, etc.).

But instead, I saw that WooCommerce has changed my homepage entirely! All of the tedious customizations I had done were gone. I was unable to do any customizations afterwards, even through Appearance->Customize in my WordPress theme. It seemed like WooCommerce is overwriting my theme customizations.

I couldn’t wait to resolve this as my site was live, so I went ahead and deleted WooCommerce from my site (https://docs.woocommerce.com/document/installing-uninstalling-woocommerce/) and re-installed it. Once Woo was deleted, I was able to use my theme’s Appearance->Customize menu to set my home page back to the way it was before. Fortunately, my Woo was only a day old, so deleting, reinstalling, and setting it up took only an hour or so.

I had worked for days to customize by site just the way I wanted it, including a bunch of CSS code. It appeared that Woo overwrote all that, and took over my site!

What frustrated me most was that this happened without warning when I clicked on a benign-looking button in Woo’s settings. I think it’s unacceptable for any plugin to do this. I'd consider this a bug. 

I see that there are others that have had this issue: https://wordpress.org/support/topic/woocommerce-shop-deleted-my-theme-customizations/

Can we get this fixed? At the very least Woo should produce a warning, perhaps multiple warnings, before overwriting the user's customizations.

Thanks.

**Comment by joshuatf** [comment] 2022-01-27 22:32
@barryhughes Its been a while since you opened this issue, but do you recall if you were able to reproduce this?

I was not able to on 2.6.1; the existing theme mods should be destructured and saved along with the new logo - https://github.com/woocommerce/woocommerce-admin/blob/d4cf43f89e6eee136e06ab598b815571f1de59d6/client/task-list/tasks/appearance.js#L195-L198

While there's a chance that this data was not preloaded in time, this logic has also changed significantly recently and the theme data is returned along with the task data so we don't have any race conditions.  Unless anyone can reproduce this, we might want to close this one out.

**Comment by barryhughes** [comment] 2022-01-27 23:18
Hi @joshuatf: yes, at least when I left my previous comment, I was able to replicate and could see the `theme_mods_<THEME>` option being overwritten/reset. Perhaps it has since been fixed via other changes.

**Comment by joelclimbsthings** [comment] 2022-03-01 23:21
Closing as we prepare for the merge, as it is no longer reproducible and is likely fixed.

**Closed by joelclimbsthings** 2022-03-01 23:21 UTC
Labels: type: bug, feature: activity panel, feature: rest api, Needs triage
