### ISSUE TITLE
Onboarding - store profiler: error when trying to install Facebook and Mailchimp extensions

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3446] opened 2019-12-19 10:24 UTC
I'm testing the new onboarding with 3.9.0-beta.2 and using WP 5.3.2 on a Pressable website and in the Business Details step I'm getting an error when I try to move forward with the Facebook and Mailchimp install:

<img width="1440" alt="Captura de ecrã 2019-12-19, às 10 19 34" src="https://user-images.githubusercontent.com/3380168/71166159-0846bf80-224a-11ea-93aa-84013b87a9ab.png">

I'm seeing the following error in the console: Failed to load resource: the server responded with a status of 500 ()

It's weird because if I go to the plugins page I see that both extensions were installed.

I'm also getting a weird styling in the "continue without installing" link: https://d.pr/i/QmvdwK

**Comment by timmyc** [comment] 2019-12-23 17:50
I was able to reproduce this on a new jurassic ninja site, looks like it is mailchimp failing to install:

![image](https://user-images.githubusercontent.com/22080/71372406-2291dd80-2569-11ea-8948-65a1faa25483.png)

Clicking on the continue without installing worked for me:

![image](https://user-images.githubusercontent.com/22080/71372552-946a2700-2569-11ea-9fb6-01defe5b2556.png)

I was able to locate the mailchimp plugin in the .org repo browser and install it manually.

**Comment by timmyc** [comment] 2019-12-23 18:20
In another test, I am unable to reproduce the bug. This kind of feels like a duplicate of what was already discussed in #3265 - I feel we should bump a track when this happens in the wild so we can see how widespread the problem is, but outside of that seems like there isn't much more we can do that hasn't been tried already. /cc @joshuatf for your thoughts.

**Comment by joshuatf** [comment] 2019-12-24 01:47
@pmcpinto Does this happen to you on each new site?  I think we've all hit this error every once in a while, but can't seem to recreate it afterwards.

I think in the meantime, we can add back in the tracks and extra debug info added in https://github.com/woocommerce/woocommerce-admin/pull/3272.

**Comment by timmyc** [comment] 2019-12-24 18:16
> I think in the meantime, we can add back in the tracks and extra debug info added in 3272

➕ - given we haven't been able to determine what exact things have to be in place to reproduce this issue, I think adding in the tracking to see how often it is happening / maybe other things present on sites when it happens ( or hosts ) is our best option at this point.

**Comment by pmcpinto** [comment] 2019-12-26 11:07
> @pmcpinto Does this happen to you on each new site? I think we've all hit this error every once in a while, but can't seem to recreate it afterwards.

It just happened to me once.

> I think in the meantime, we can add back in the tracks and extra debug info added in #3272.

Adding tracks in order to verify how many people come across this bug, instead of spending more time trying to recreate it, sounds like the best option.

**Comment by joshuatf** [comment] 2019-12-30 11:22
Tracks added in https://github.com/woocommerce/woocommerce-admin/pull/3483 - going to unassign myself and leave the issue open until we get more data.

**Comment by timmyc** [comment] 2019-12-30 20:24
Had to hit retry on the Jetpack install step today during a new test site on jurassic.ninja - MailChimp install step worked fine.

**Comment by joshuatf** [comment] 2020-01-15 09:15
Hit this issue for the first time on a local site today using Local by Flywheel.

Had issues installing Jetpack and Facebook.  The errors pretty consistently seem to be "Destination folder already exists" when logged to the error log.

The Facebook install failure was especially odd; it seems like the curl request timed out half way.  On inspection of the folder, some of the plugin files were missing.  This prevented the install from working at all until manually deleting the plugin since the retry would attempt to install in the same folder and return an error since the `$installed_plugins` array did not contain this plugin (due to being incomplete).

The common error of the folder already existing makes me think there may be an issue with how we're checking to see if plugins already exist or not and potentially how `get_plugins()` caches installed plugins.

**Comment by timmyc** [comment] 2020-01-17 20:20
Had a flawless install on an ephemeral atomic site yesterday with all plugin installs ( Jetpack, WCS, MC, and FB ).

**Comment by pmcpinto** [comment] 2020-01-20 18:14
@joshuatf @timmyc I hit this issue again today in a Pressable website with WC-Admin 0.24.0 and WC Core 3.9.0-rc.3

<img width="1439" alt="Captura de ecrã 2020-01-20, às 18 11 43" src="https://user-images.githubusercontent.com/3380168/72748925-80d5ce80-3bb0-11ea-8eac-d89d7ff4e1bf.png">

After clicking on "Continue without installing" I went to the "Installed plugins" page and both extensions were there

**Comment by juliaamosova** [comment] 2020-02-26 15:40
Noting here that I could reproduce it with a pre-release of 4.0 rc1 just now on a brand new JN site:

- installed Query Monitor plugin
- installed Debug Bar plugin
- uploaded and activated rc1 zip
- I was selected for the new onboarding by default so didn’t have to change anything in that regard
- Next, I proceeded with new onboarding - selected to install WooCommerce Services and connected the site to WP.com account.
- selected all the paid extensions on the screen about what kind of products I want to sell

On the FB/Mailchimp step - selected both to be installed and got the following error:

<img width="775" alt="Screen Shot 2020-02-26 at 10 10 05 AM" src="https://user-images.githubusercontent.com/19143190/75360515-ebe78480-5883-11ea-8c45-6cc53e3ecc8a.png">

Also couldn't proceed after hitting `Retry` many times:

![](http://g.recordit.co/e5nS6p5rvB.gif)

Looked to see what could be going on:

<img width="1439" alt="Screen Shot 2020-02-26 at 10 17 50 AM" src="https://user-images.githubusercontent.com/19143190/75360625-1a655f80-5884-11ea-8c0e-03a2ddbaef96.png">

Also couldn’t proceed at all - the button disappeared if I toggled off the Mailchimp installation:

![](http://g.recordit.co/g5RPY905u0.gif)

@timmyc mentioned that it looked like a separate bug which I will file now. I will post the link here.

**Comment by juliaamosova** [comment] 2020-02-26 15:56
>it looked like a separate bug which I will file now. I will post the link here.

Here: https://github.com/woocommerce/woocommerce-admin/issues/3780.

**Comment by dechov** [comment] 2020-04-09 22:14
In one of my tests last night, Facebook wouldn't install (same after any number of retries), and then it suddenly went to the next screen and told me that plugins were successfully installed and activated, even though a) I don't think I clicked "Continue without installing" and b) Facebook still wasn't installed.

**Comment by pmcpinto** [comment] 2020-04-13 09:02
> In one of my tests last night, Facebook wouldn't install (same after any number of retries), and then it suddenly went to the next screen and told me that plugins were successfully installed and activated, even though a) I don't think I clicked "Continue without installing" and b) Facebook still wasn't installed.

cc @timmyc @joshuatf

**Comment by timmyc** [comment] 2020-04-17 18:40
I haven't experienced that myself of the screen progressing to the next step without clicking on the "continue without installing". I guess we'll just keep this open still and see if there are further reports. The download/install of plugins for me at least feels more stable. I haven't had issues with it at all during my testing in 4.1

**Comment by pmcpinto** [comment] 2020-04-20 10:59
+1 on keeping this issue opened, but I think it's not worth spending more time fixing this in the upcoming weeks

**Closed** 2020-05-27 07:28 UTC
Labels: Onboarding, [Type] Bug
