### ISSUE TITLE
Docs help tooltip appears twice during the new store setup flow

### ISSUE THREAD

**Issue by jarekmorawski** [woocommerce/woocommerce-admin#6379] opened 2021-02-19 11:23 UTC
**Describe the bug**
Help tooltip pointing to the docs appears twice in the setup flow (even after dismissing it for the first time).

**To Reproduce**

1. Go to Home > Finish setup > Set up tax
2. Click on Got it in the tooltip
3. Go back to Home > Finish setup > Set up shipping
4. See the same tooltip appear

**Expected behavior**
The tooltip should appear only once while going through the setup flow (or using WooCommerce in general).

**Screenshots**

![Frame 29](https://user-images.githubusercontent.com/79307566/108498341-05f84f00-72ad-11eb-8a1d-f42c50cc8f1c.png)
![Frame 32](https://user-images.githubusercontent.com/79307566/108498344-07c21280-72ad-11eb-9a9a-f2734773906b.png)

**Desktop (please complete the following information):**

* OS: macOS
* Browser: Chrome
* Version: 88.0.4324.150 (cookies enabled)

**Comment by elizaan36** [comment] 2021-02-21 02:08
The tooltip doesn't appear twice for me (on a new JN site) but it did appear the first time I opened one of the task lists. We had originally planned for it to only appear upon the second time visiting the same task and once dismissed it doesn't appear again. cc @pmcpinto

**Comment by pmcpinto** [comment] 2021-02-24 11:53
Weird. I just tested it again and it seems to be working fine: https://www.loom.com/share/c4fd05f21d9849cfa578e154d17f9799

**Comment by elizaan36** [comment] 2021-02-24 16:27
Same! I just tested with a fresh JN site and it works as expected.👍
I can't think of any reason why it would have appeared again for Jarek after being dismissed. @jarekmorawski let me know if you're still seeing the issue, otherwise if it's working as expected for all of us we can close the issue.

**Comment by ilyasfoo** [comment] 2021-02-25 08:53
I'm also unable to reproduce this with WooCommerce 5.0 and WooCommerce Admin 2.0.2. Closing this issue, @jarekmorawski please feel free to reopen if you're able to reproduce again!

**Closed by ilyasfoo** 2021-02-25 08:53 UTC
Labels: type: bug
