### ISSUE TITLE
Customers: Shows only one customer even when there are many; search does not return any result

### ISSUE THREAD

**Issue by arunsathiya** [woocommerce/woocommerce-admin#2465] opened 2019-06-20 06:50 UTC
**Describe the bug**

The `Customers` tab under WooCommerce Admin sidebar menu does not load all the customers. It shows only one customer, but the total count is much higher.

When searching for customers by their name, no results appear.

**To Reproduce**

- Start with a WooCommerce site with 2+ customers.
- Run the `Import Historical Data` option under `Settings`. 
- Visit the `Customers` tab on the `Analytics` menu on the left.
- Note that only one customer is shown (mostly the site owner account), even though the total count is much higher.
- Searching for customers does not show any results either. 

**Expected behavior**

- All customers are shown properly. 
- When searching, all results should appear as well.

**Screenshots**

![Screenshot 2019-06-20 at 12 15 33](https://user-images.githubusercontent.com/18581859/59827024-40318080-9355-11e9-853d-8ac4c1b0760b.png)

This is when searching for the customer by their name:

![Screenshot 2019-06-20 at 12 21 12](https://user-images.githubusercontent.com/18581859/59827338-09a83580-9356-11e9-8ec8-2b9fa940615a.png)

![Screenshot 2019-06-20 at 09 39 56](https://user-images.githubusercontent.com/18581859/59827048-4cb5d900-9355-11e9-9b6f-22d0074bc94c.png)

**Desktop (please complete the following information):**

* OS: macOS 10.14.5 - Mac OS Mojave 
* Browser: Google Chrome
* Version: Google Chrome Version 74.0.3729.169 (Official Build) (64-bit) 

**Additional context**

@warrendholmes was able to see this behaviour as well on their test site - p1561003973155500-slack-wc-admin

**Comment by psealock** [comment] 2019-06-21 02:37
I was able to replicate this on another test site using `0.13.2`. Only two customers are shown, but the count is much higher.

![Screen Shot 2019-06-21 at 2 17 22 PM](https://user-images.githubusercontent.com/1922453/59893588-88be6c00-9431-11e9-9166-15b8253e8d93.png)

I deleted historical data, updated to master branch, and re-imported historical data. There is now a customers count equal to the number of rows in the customers lookup table.

![Screen Shot 2019-06-21 at 2 27 23 PM](https://user-images.githubusercontent.com/1922453/59893683-d044f800-9431-11e9-9ddf-d734365fbbf0.png)

I'll double check this later tonight, but signs are pointing to this being resolved and out in `0.14.0`.

**Comment by psealock** [comment] 2019-06-21 07:45
I just re-confirmed to be sure. This problem will be resolved by 0.14.0, which is scheduled to go out before end of next week.

These two PRs by @joshuatf seemed to have addressed the issue:
https://github.com/woocommerce/woocommerce-admin/pull/2428
https://github.com/woocommerce/woocommerce-admin/pull/2418

I'm going to close this one, but if updating doesn't work, we can reopen.

**Closed by psealock** 2019-06-21 07:45 UTC
Labels: [Type] Bug

**Comment by joshuatf** [comment] 2019-06-21 07:56
Also confirmed with @arunsathiya's dataset.  Looks like I'm getting all customers and guest orders as well on the latest master.

**Comment by arunsathiya** [comment] 2019-06-21 07:57
So glad to hear this! Thanks for verifying!

**Comment by joshuatf** [comment] 2019-06-21 07:59
No problem, @arunsathiya  😄 

If you run into any more problems with this, feel free to post back here and we can reopen.

**Comment by timmyc** [comment] 2019-06-21 18:06
Thanks @joshuatf for the fixes and @psealock for helping verify. And again thanks @arunsathiya for relaying the bug reports.
