### ISSUE TITLE
My site returns 503 errors?

### ISSUE THREAD

**Issue by lammersma** [woocommerce/woocommerce-admin#4319] opened 2020-05-08 07:23 UTC
Since I installed Woocommerce admin plugin I receive a lot of 503 errors. And the admin pages of analytics show exclamation marks. According to my systemadmin I should remove this plugin asap, but I believe it is implemented in woocommerce now?
How do I disable this functionality?

**Comment by igorradovanov** [comment] 2020-05-08 09:55
This may be related to issue #3943

**Comment by lammersma** [comment] 2020-05-08 12:29
O yes, it does!

I installed a plugin that disables the WC analytics completely. That solved my issues.
My hosting provider, they host a lot WP sites, really struggle with these issues. They say it looks like a DDOS attack…

Van: Igor Radovanov <notifications@github.com>
Verzonden: vrijdag 8 mei 2020 11:55
Aan: woocommerce/woocommerce-admin <woocommerce-admin@noreply.github.com>
CC: lammersma <lammersma@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [woocommerce/woocommerce-admin] My site returns 503 errors? (#4319)


This may be related to issue #3943<https://github.com/woocommerce/woocommerce-admin/issues/3943>

**Comment by timmyc** [comment] 2020-06-05 17:19
Closing as duplicate of #3943

**Closed by timmyc** 2020-06-05 17:19 UTC
