### ISSUE TITLE
[Setup Wizard] - User is Able to give special characters as Input for all the fields on store details page.

### ISSUE THREAD

**Issue by raj007champ** [woocommerce/woocommerce-admin#7888] opened 2021-11-03 18:13 UTC
### Describe the bug
When the User is navigated to the WooCommerce Setup Wizard flow and is on the Store Profiler page, Then the user is able to give special characters as Input for all the fields present on the Welcome to WooCommerce store details page except email.

### To Reproduce
 1. Install WooCommerce plugin
2. Activate the WooCommerce plugin and wait for the WooCommerce Setup Wizard flow to open
3. Now on the Store Profile page, Try to put a special character as input for Address line 1, Address line 2, City, Postcode
4. Click on Continue

### Actual behavior:
 The user is allowed to move forward with the setup steps with these special characters as Input.

### Screenshots

https://user-images.githubusercontent.com/19307354/140167189-3e4f222f-c522-4c2c-93d3-12a4219e51d9.mp4

### Expected behavior
Ideally, Users should not be allowed to put special characters as input for fields like City, Postcode etc.

### Desktop (please complete the following information):

* OS: Windows OS
* Browser: Chrome
* Version: 95.0.4638.69

### Additional context
NA

**Comment by moon0326** [comment] 2021-11-04 01:45
Thank you @raj007champ for taking the time to report this issue. I was able to reproduce it on my end. We'll work on it as soon as possible.

**Comment by chihsuan** [comment] 2022-01-19 08:11
I think this might be a little tricky since some special characters are not special in some languages.

**Comment by joshuatf** [comment] 2022-01-27 22:13
I agree with @chihsuan.  Aside from the inability to have a comprehensive list of disallowed characters, many of the characters used in the above screenshot are usable characters for store addresses in certain countries.

Closing this issue.

**Closed by joshuatf** 2022-01-27 22:13 UTC
Labels: type: bug, feature: onboarding, Needs triage
