### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-admin#6463] opened 2021-02-26 21:05 UTC
**Describe the bug**

`PHP Warning: in_array() expects parameter 2 to be array, bool given in /srv/www/gitwooplugins/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/RemoteInboxNotifications/ComparisonOperation.php on line 36`

**To Reproduce**

1. Run the WC product import tool.
2. Use the WC sample data to import.
3. After the import is finished, the warning appears. Or check your PHP error log.

**Expected behavior**
Not to see any PHP warnings.

**Screenshots**

![](https://d.pr/i/w8KDQC+)

**Comment by moon0326** [comment] 2021-03-02 22:52
Hi @roykho,

Thank you for reporting the bug.

I was unable to see the error message. I also checked `wp-content/debug.log`. 

I tested it with WooCommerce 5.0, and the latest WooCommerce Admin (master branch).

Could you share your versions please?

**Comment by roykho** [comment] 2021-03-02 23:39
Hi @moon0326 - sorry totally forgot about the version.

* WC 5.1.0-rc.1
* WC Admin 2.1.0-dev as a separate plugin.

**Comment by moon0326** [comment] 2021-03-05 00:03
> Hi @moon0326 - sorry totally forgot about the version.
> 
> * WC 5.1.0-rc.1
> * WC Admin 2.1.0-dev as a separate plugin.

Thank you! I will test it further 👍

**Comment by moon0326** [comment] 2021-03-05 01:29
@roykho We've identified the cause and opened a [PR](https://github.com/Automattic/woocommerce.com/pull/9672). We will make another PR in WC Admin.

**Comment by moon0326** [comment] 2021-03-05 05:22
@roykho The issue should be fixed by now. Please try again. If you still see the same issue on the first try, please try again. I had to try twice (probably cache).

Closing this ticket for now.

**Closed by moon0326** 2021-03-05 05:22 UTC
Labels: type: bug
