### ISSUE TITLE
[Setup Wizard]- Clicking validation error message of Country/Region field is opening the Country/Region dropdown.

### ISSUE THREAD

**Issue by raj007champ** [woocommerce/woocommerce-admin#7906] opened 2021-11-06 06:39 UTC
### Describe the bug
On clicking Error message displayed for empty Country/Region field present on Store profile details page is opening the Country/Region field dropdown.

### To Reproduce
1. Install WooCommerce plugin
2. Activate the WooCommerce plugin and wait for the WooCommerce Setup Wizard flow to open.
3. On store profile page, Keep the Country/Region field empty and click on continue.
4. Look for validation error message displayed for empty Country/Region field-> `Please select a country / region`
5. Click on Error message and observe the behaviour.

### Actual behavior:
Clicking error message is opening the Country/Region field dropdown instantly.

### Screenshots

https://user-images.githubusercontent.com/19307354/140600433-20da0277-b191-4722-8bd7-3134fceb0471.mp4

### Expected behavior
Clicking error message should not open the Country/Region field dropdown.

### Desktop (please complete the following information):

* OS: Windows OS
* Browser: Chrome
* Version: 95.0.4638.69

**Comment by raj007champ** [comment] 2021-11-06 18:27
This issue is reproducible with all the dropdowns present on setup wizard flow, Please do check them as well.

**Comment by joelclimbsthings** [comment] 2021-11-08 22:55
Thanks for reporting this @raj007champ !

I've tested this on a few different elements in the latest release. I'm able to see that the drop-down is activated upon clicking on a validation message, although it happens smoothly and without the glitchy behavior I can seem to see in in the included video. As far as I can see on my end it looks like intended behavior. 

Can I ask which version of woocommerce you're looking at? I've tested with both Firefox and Chrome as well.

**Comment by raj007champ** [comment] 2021-11-09 18:00
Hi @joelclimbsthings , Thank you for your reply. So that glitchy behavior is coming when you try to do double click on the error message. As a user we do lot of double clicks for text messages on the screen, So while doing that I discovered that bug.
However please let me know, If this is the expected behaviour and I will close this.

**Comment by joelclimbsthings** [comment] 2021-11-09 18:54
Ah, understood @raj007champ . While double-clicking, I don't get exactly the same behavior, but I can see it still being confusing. If I double-click the label it basically opens the drop-down and immediately selects the visible option (closing the drop-down once again).

While this could still be considered intended behavior, I can see it being a little clumbsey . I'm curious what your impression would be, @elizaan36 ?

**Comment by elizaan36** [comment] 2021-11-10 00:09
> While this could still be considered intended behavior, I can see it being a little clumbsey . I'm curious what your impression would be, @elizaan36 ?

I agree that clicking the error message shouldn't open the dropdown because it does feel buggy and confusing. I'd remove any click target from the error message so that the dropdown only opens when the dropdown itself is clicked.

**Comment by raj007champ** [comment] 2021-11-10 18:59
Thank you @elizaan36 and @joelclimbsthings for the follow-up.

**Closed** 2022-01-04 03:00 UTC
Labels: type: bug
