### ISSUE TITLE
Deprecated warning when running core E2E tests

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#6992] opened 2021-05-14 18:53 UTC
**Describe the bug**
I'm seeing the following deprecated warning when running E2E tests in WC trunk. The core tests don't access admin pages with Gutenberg or front end pages with the products block. This looks like there is a remaining use of `woocommerce_shared_settings` in WC Admin.

```
  console.warn
    `woocommerce_shared_settings` filter in Blocks is deprecated. See https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/contributors/block-assets.md
```

**To Reproduce**

1. Run WC core E2E tests
2. Can also be seen in browser console on the Product edit page

**Comment by mattsherman** [comment] 2021-07-15 19:41
This issue is a duplicate of #6900. Closing this one.

**Closed by mattsherman** 2021-07-15 19:41 UTC
Labels: type: technical debt
