### ISSUE TITLE
If the site has no orders, no need to prompt me to "process" them (Historical Analytics Data)

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-admin#3185] opened 2019-11-06 20:11 UTC
**Describe the bug**

Installed on a fresh site with no orders. Got this banner. LOL'd

<img width="1440" alt="no-history" src="https://user-images.githubusercontent.com/1595739/68333996-88e0a080-008e-11ea-97a8-66ce29a1fca8.png">

**Comment by allendav** [comment] 2019-11-06 21:00
After clicking the (gray) Get Started button, I get navigated to here and can't do anything (clicking the (gray) Start button does nothing), but at least the banner is gone now:

<img width="1440" alt="historical" src="https://user-images.githubusercontent.com/1595739/68337451-669e5100-0095-11ea-9869-5525142a9e8d.png">

**Comment by joshuatf** [comment] 2019-11-08 06:30
@allendav Is the on the master branch?  Spun up a jurassic ninja site and wasn't able to replicate.

Here's the check that should hopefully be blocking this notification from showing on a site without orders - https://github.com/woocommerce/woocommerce-admin/blob/9590a74fb7def9d19448536d1335cd0e46d03257/src/Notes/WC_Admin_Notes_Historical_Data.php#L39

**Comment by timmyc** [comment] 2019-12-02 22:44
I can't reproduce this either, closing out.

**Closed by timmyc** 2019-12-02 22:44 UTC
Labels: [Type] Bug

**Comment by allendav** [comment] 2019-12-05 18:51
@joshuatf this was using whatever was on .org at the time - I'll try repro'ing it again sometime
