### ISSUE TITLE
[GlobalStep - 2.6.0 Beta 2][Safari, Firefox] "Welcome Modal" appears every time upon refreshing the "Home" screen when task list is disabled.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#7478] opened 2021-08-06 15:16 UTC
## Bug Description:
When Setup Task list and Extended task list both are disabled then "Welcome Modal" appears every time upon refreshing the "Home" screen.

## Environment:
WooCommerce Admin: v2.6.0 Beta-2
Woocommerce Version : WooCommerce 5.5.2

PC:
Windows 10, Mac 10.14.6
Firefox(Version 88.0)
Safari: v14.1.2

## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all the required plugins
1. Install and activate WooCommerce Admin 2.6.0 Beta-2. 
1. Go to WooCommerce->Home.
1. Hide the task list and "Things to do next" banner.
1. Click on orders option.
1. Again Go to WooCommerce->Home.
1. Observe that Welcome modal appears.

## Actual Result:
"Welcome Modal" appears every time upon refreshing the "Home" screen when task list is disabled..

## Expected Result:
Welcome modal should appears only once after fresh site setup.

## Video:

https://user-images.githubusercontent.com/41110392/128533207-ed306f54-3385-4538-9778-1e12256b8eee.mp4

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 5.5.2
REST API Version: ✔ 5.5.2
WC Blocks Version: ✔ 5.3.3
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.6.0-beta.2
Log Directory Writable: ✔
WP Version: 5.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.48 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.21
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.5.2
WC Database Prefix: wp_
Total Database Size: 11.84MB
Database Data Size: 9.04MB
Database Index Size: 2.80MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.47MB + Index: 0.23MB + Engine InnoDB
wp_postmeta: Data: 0.16MB + Index: 0.11MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 29
mailpoet_page: 1
page: 6
post: 2
product: 22
product_variation: 10
shop_coupon: 2
shop_order: 10

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

Query Monitor: by John Blackbourn – 3.7.1
Companion Plugin: by Osk – 1.18
Google Listings and Ads: by WooCommerce – 1.3.0
Jetpack: by Automattic – 10.0
Mailchimp for WooCommerce: by Mailchimp – 2.5.2
MailPoet 3 (New): by MailPoet – 3.65.1
WooCommerce Admin: by WooCommerce – 2.6.0-beta.2
WooCommerce: by Automattic – 5.5.2
WP Crontrol: by John Blackbourn & crontributors – 1.10.0

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 4.1.10
Gutenberg: by Gutenberg Team – 11.2.1
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.7.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 97
Oldest: 2021-08-06 07:36:40 +0000
Newest: 2021-08-06 14:32:43 +0000

### Status report information ###

Generated at: 2021-08-06 15:08:16 +00:00
`

</details>

**Comment by adrianduffell** [comment] 2021-08-09 04:52
I was able to reproduce this on a JN site.

Steps to reproduce:

1. Delete the following options if they exist:

- `woocommerce_task_list_welcome_modal_dismissed`
- `woocommerce_task_list_hidden`
- `woocommerce_extended_task_list_hidden`

e.g. `$ wp option delete woocommerce_task_list_welcome_modal_dismissed woocommerce_task_list_hidden woocommerce_extended_task_list_hidden`

2. Visit Woocommerce Home screen
3. Dismiss Welcome Modal
4. Hide "Get ready to start selling"

<img width="530" alt="Screen Shot 2021-08-09 at 12 44 38 pm" src="https://user-images.githubusercontent.com/9312929/128661303-cd0d4cfd-82ca-43c7-a7a5-d10a27867838.png">

5. From Display menu, **untick** "Show things to do next"

<img width="253" alt="Screen Shot 2021-08-09 at 12 45 42 pm" src="https://user-images.githubusercontent.com/9312929/128661368-19cb2ab1-06ce-4476-94b8-d52e94792867.png">

6. Go to WooCommerce Orders screen.
7. Return Woocommerce Home screen. 
8. See that Welcome Modal renders on page load.

**Comment by adrianduffell** [comment] 2021-08-09 04:59
It looks like a REST API request is made where the `options` parameter value is missing.

<img width="1332" alt="Screen Shot 2021-08-09 at 12 53 29 pm" src="https://user-images.githubusercontent.com/9312929/128661798-1de5dd1f-d78b-43e2-89ee-deb65f4a3eb5.png">

JSON response from this request:

<img width="419" alt="Screen Shot 2021-08-09 at 12 54 16 pm" src="https://user-images.githubusercontent.com/9312929/128661761-8e71ec6b-9669-4178-a9b9-9faaa99a39f3.png">

**Comment by ilyasfoo** [comment] 2021-08-09 10:19
Unfortunately, I was unable to reproduce with the exact steps above, in both `2.6.0-beta.2` with a JN and in `main` in local.  I've checked all 3 options requests, none of them were empty

![image](https://user-images.githubusercontent.com/3747241/128691744-069cf90d-bbd9-44e5-89d3-009f92ad91eb.png)

Also, in my local the request does not go to `/wp-json/wc-admin/options?_locale=user` but instead goes to `/index.php?rest_route=%2Fwc-admin%2Foptions&_locale=user`. Could be something in my local though.

At this point I'm out of time, will resume debugging tomorrow if no one picks it up.

**Comment by moon0326** [comment] 2021-08-09 16:40
I wasn't able to reproduce it either.

I think we need more details. When I first visit WooCommerce -> Home, the modal pops up and it requests the option endpoint as soon as I close the modal. I'm not sure why we even need the extra steps of hiding the task list 🤔

**Comment by adrianduffell** [comment] 2021-08-10 00:56
@moon0326 @ilyasfoo

Hmm, I'm still able to reproduce this. I'll see if I can create some simpler steps.

I think the issue is caused by a race condition on `optionNames` in the `setTimeout` code here: https://github.com/woocommerce/woocommerce-admin/blob/ada7466a75148b4404a5ddbf02c5916d08dec6a6/packages/data/src/options/controls.js#L27-L47

I could reproduce this in an older version as well (WC Admin 2.3 bundled in WC 5.4).

> Also, in my local the request does not go to /wp-json/wc-admin/options?_locale=user but instead goes to /index.php?rest_route=%2Fwc-admin%2Foptions&_locale=user. Could be something in my local though.

@ilyasfoo My local does that too. It's caused by the permalink settings in WordPress so this should be ok.

**Comment by adrianduffell** [comment] 2021-08-10 03:48
Labelling this as high priority, but it doesn't need to be fixed for 2.6.

A similar report was made internally recently where the new navigation modal would continue to appear on page loads despite being dismissed: p1625030439175600-slack-CBKK5KM41

**Comment by ilyasfoo** [comment] 2021-11-18 05:34
Fixed in #7947

**Closed by ilyasfoo** 2021-11-18 05:34 UTC
Labels: type: bug, priority: high
