### ISSUE TITLE
[WC 4.5 RC3] Home Screen: `Add my products` task / `Add manually (recommended)` redirects the user to WooCommerce Payments set up page

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#5084] opened 2020-09-03 01:09 UTC
**Describe the bug**

After completing OBW, on Home Screen, if the user selects `Add my products` task / `Add manually (recommended)` the user gets redirected to WooCommerce Payments set up page. 

**To Reproduce**

1. Start OBW on the brand new site. 
2. Fill in the `Store Details` section with the US address.  
3. Select `Fashion, apparel, and accessories` in the Industries section.
4. In the `Tell us about your business` section, select checkbox next to `Install recommended free business features` to install all the recommended plugins. 
5. On Home Screen, click on `Add my products` task and then select `Add manually (recommended)`. 
6. See that you will be redirected to WooCommerce Payments set up screen instead of the product editor. 
7. If you go back to Home Screen and try `Add my products` task / `Add manually (recommended)` again, you will be redirected to product editor as you should. 

See the gif below that shows the behavior (I was able to replicate it 3 times on JN site):

https://recordit.co/N1JTWQAIOH

**Expected behavior**

I expected to be redirected to product editor when clicked on `Add my products` task and then select `Add manually (recommended)`. 

**Screenshots**

See the gif above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.6
* Browser: Chrome
* Version: Version 85.0.4183.83 (Official Build) (64-bit)

**Additional context**

N/A

**Comment by thenbrent** [comment] 2020-09-08 00:21
This should be fixed now that WC Pay 1.4.1 has been released. Details: p7bje6-2nW-p2#comment-5139

**Comment by becdetat** [comment] 2020-12-16 05:13
I can't reproduce this on WC 4.8.0, I'll close this for now.

**Closed by becdetat** 2020-12-16 05:13 UTC
