### ISSUE TITLE
Custom filter analytics / reports not working

### ISSUE THREAD

**Issue by Sidlegionair** [woocommerce/woocommerce-admin#6842] opened 2021-04-21 12:12 UTC
Hi,

Extending admin reports is no longer working. I tried following this article: https://developer.woocommerce.com/2020/02/20/extending-wc-admin-reports/

I created a repo with my code here: https://github.com/Sidlegionair/filter-reports-by-vendor/

Error in JS console:
`react_devtools_backend.js:2557 TypeError: Cannot read property 'settings' of undefined
    at r.value (analytics-report-taxes.js?ver=2.0.2:1)
    at Ie (react-dom.min.js?ver=16.13.1:104)
    at rh (react-dom.min.js?ver=16.13.1:103)
    at zj (react-dom.min.js?ver=16.13.1:228)
    at Th (react-dom.min.js?ver=16.13.1:152)
    at tj (react-dom.min.js?ver=16.13.1:152)
    at Te (react-dom.min.js?ver=16.13.1:146)
    at react-dom.min.js?ver=16.13.1:61
    at unstable_runWithPriority (react.min.js?ver=16.13.1:25)
    at Da (react-dom.min.js?ver=16.13.1:60)
overrideMethod @ react_devtools_backend.js:2557
Me @ react-dom.min.js?ver=16.13.1:125
Jh.f.componentDidCatch.c.callback @ react-dom.min.js?ver=16.13.1:139
Wg @ react-dom.min.js?ver=16.13.1:67
oj @ react-dom.min.js?ver=16.13.1:127
Aj @ react-dom.min.js?ver=16.13.1:160
unstable_runWithPriority @ react.min.js?ver=16.13.1:25
Da @ react-dom.min.js?ver=16.13.1:60
ab @ react-dom.min.js?ver=16.13.1:154
Te @ react-dom.min.js?ver=16.13.1:146
(anonymous) @ react-dom.min.js?ver=16.13.1:61
unstable_runWithPriority @ react.min.js?ver=16.13.1:25
Da @ react-dom.min.js?ver=16.13.1:60
Pg @ react-dom.min.js?ver=16.13.1:61
U @ react.min.js?ver=16.13.1:16
B.port1.onmessage @ react.min.js?ver=16.13.1:24
`

possibly related: #6339

**Comment by jeffstieler** [comment] 2021-04-21 17:38
Hello @Sidlegionair!

Thank you for reporting this issue - you've definitely found a bug - here's the problematic line: https://github.com/woocommerce/woocommerce-admin/blob/087b9fad197c561119960def835650671e6f6e04/client/analytics/report/taxes/index.js#L42

For the time being, you can work around it by adding your filter to **end** of the filters array, e.g.:

```javascript
return [
    ...filters,
    { /* new filter here */ },
];
```

**Comment by jeffstieler** [comment] 2021-04-21 17:41
Closing this as it is a duplicate of https://github.com/woocommerce/woocommerce-admin/issues/6339. Let's continue discussion over there.

**Closed by jeffstieler** 2021-04-21 17:41 UTC
Labels: category: extensibility, type: bug
