### ISSUE TITLE
[WC 4.6.1 & 4.7 Beta1] `Set up tax` & `Set up shipping` tasks get undone if user tries to `Set up WC Payments` task

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#5433] opened 2020-10-20 20:33 UTC
**Describe the bug**

<strike>Seems to happen on Atomic only:</strike> `Set up tax` & `Set up shipping` tasks get undone if user tries to `Set up WC Payments` task. 

**To Reproduce**

1. Create a new Atomic site.
2. Upload WC 4.7 Beta1.
3. Complete onboarding (US store + select to install free business extensions).
4. Once on the Home Screen, complete `Set up tax`, `Set up shipping` & `Purchase & Install extensions` tasks. 
5. Click on the task to `Set up WC Payments`. See the connection modal but click on the back browser button to go back to the site as you changed your mind and want to do it later. 
6. When you are back to Home Screen, note that `Purchase & Install extensions` is marked as completed but the `Set up tax` and `Set up shipping` tasks are undone:

![](http://g.recordit.co/De31EDEQ1V.gif)

**Expected behavior**

I expected `Set up tax` and `Set up shipping` tasks to remain completed after I tried to the task to `Set up WC Payments`. 

**Screenshots**

See gif above. 

**Desktop (please complete the following information):**

OS: macOS Catalina 10.15.6
Browser: Chrome
Version: 86.0.4240.80 (Official Build) (x86_64)

**Additional context**

N/A

**Comment by juliaamosova** [comment] 2020-10-21 16:34
Noting here that it happens in WC 4.6.1 (since both include WC Admin 1.6.2) as well and not only in Atomic but JN site too. The task that was completed last before proceeding with the `Set up WC Payments` task gets undone. Please see the video below taken from the JN site (I used the browser's back button when I got the WC Payments/Stripe connection modal):

http://g.recordit.co/mmQvTgWkTb.gif

**Comment by samueljseay** [comment] 2021-01-15 01:31
I can't reproduce this on JN now.

It's an interesting one that I'm not sure how much control we have over. If the user presses the back button what usually happens is that the cached page is presented, JS is not run as far as I know. So if the page was cached before the back button was pressed with the wrong state of the tax task then it would display incorrectly. 

There are some wide spanning impact ways that we could address this (I believe we could force a page refresh every time we detect a backwards navigation), but first I'd like to see if anyone can still reproduce this since it has been a while since this was last talked about.

**Comment by moon0326** [comment] 2021-01-15 01:51
I tested it for three different scenarios and I was able to reproduce it only the first time.

1. Created a new JN site and installed WC Admin -- I was able to reproduce the bug.
2. Tested the bug again on the same JN site -- I was not able to reproduce it.
3. Created a new JN site -- I was not able to reproduce it

**Comment by samueljseay** [comment] 2021-01-15 02:02
Thanks @moon0326 for testing this!

I think for now I'm going to close this one for a few reasons:

1. its fairly low severity/impact
2. it happens only on occasion based on testing and a page refresh fixes it.
3. if its caching caused by back button, its going to be significant effort to fix for a minor issue

If anyone has different feelings on this then please reopen. 

Thanks.

**Closed by samueljseay** 2021-01-15 02:02 UTC
Labels: feature: onboarding, status: blocked, type: bug
