### ISSUE TITLE
Report Variations table names: Investigate inconsistencies

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#1044] opened 2018-12-09 21:16 UTC
Discovered in https://github.com/woocommerce/wc-admin/pull/987#pullrequestreview-181446577, sometimes Variation names aren't coming back complete, only the product name.

Should we go back to constructing on the name clientside?

**Comment by timmyc** [comment] 2019-06-11 11:41
Since the parent issue you referenced in core above is now merged @psealock did you want to revisit this and test again? I haven't seen the issue myself. I'm going to close this out for now since we haven't had any other reports of it, but if you want to try and test again and find that the bug is still present and reproducible, please re-open.

**Comment by timmyc** [comment] 2019-06-11 11:42
Since the parent issue you referenced in core above is now merged @psealock did you want to revisit this and test again? I haven't seen the issue myself. I'm going to close this out for now since we haven't had any other reports of it, but if you want to try and test again and find that the bug is still present and reproducible, please re-open.

**Closed** 2019-06-11 11:49 UTC
