### ISSUE TITLE
"Unexpected output" error when activating WooCommerce Admin (and all subsequent plugin activations)

### ISSUE THREAD

**Issue by chrisoko7** [woocommerce/woocommerce-admin#6467] opened 2021-02-27 12:21 UTC
**Describe the bug/How to reproduce**
Tested in a several themes, and have isolated the issue to this:
WooCommerce is activated, I activate WooCommerce Admin, and promptly receive this error upon activation at the top of the Plugin screen: 

"The plugin generated 261 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin."
This error continues to occur with every subsequent plugin activation. With WooCommerce Admin deactivated, this error never appears. This error message doesn't seem to affect any functionality of the website on the front-end, but makes me wonder what exactly is going on. 

**Screenshots**
![image](https://user-images.githubusercontent.com/79750493/109386909-3b7ce800-78fe-11eb-85b8-197d89f1b925.png)

**Desktop (please complete the following information):**

* Windows 10 (20H2/19042.804)
* Chrome (88.0.4324.182/64-bit)
* Wordpress 5.6.2
* PHP 7.4.15

**Comment by ilyasfoo** [comment] 2021-03-01 05:31
Hello @chrisoko7, thank you for reporting this issue. Unfortunately, I'm unable to validate this issue without reproducible steps. Are you able to provide your logs? Here's [a guide ](https://docs.woocommerce.com/document/finding-php-error-logs/) on how to obtain them.

**Comment by chrisoko7** [comment] 2021-03-01 08:51
Sure, here is what I managed to find in the logs for just now when I experienced the error: this is what the log showed for today. 
[php_errorlog march 1.txt](https://github.com/woocommerce/woocommerce-admin/files/6060292/php_errorlog.march.1.txt)

**Comment by ilyasfoo** [comment] 2021-03-01 22:53
Thank you @chrisoko7. Looks like your issue might be related to a recently reported https://github.com/woocommerce/woocommerce-admin/issues/6463.

**Comment by ilyasfoo** [comment] 2021-03-02 06:24
I'm going to close this issue, as I think it's a duplicate. If you have any reason to think otherwise, do let me know. You can track the progress of your issue by following  #6463. Thanks, @chrisoko7!

**Closed by ilyasfoo** 2021-03-02 06:24 UTC
Labels: category: duplicate
