### ISSUE TITLE
Manually discounted order isn't counted in 'Coupon' revenue

### ISSUE THREAD

**Issue by jrick1229** [woocommerce/woocommerce-admin#6383] opened 2021-02-19 16:55 UTC
### Describe the bug

When manually changing the product line item total of an order, the price change is calculated as a 'Coupon'.
The problem here is that the 'Coupon' used to alter the Order Total is not recorded in the Revenue tab as an actual coupon discount.

### To Reproduce

1. Go to a 'Pending Payment' order
2. Click the pencil icon next to the product line item
3. Change the 'Total' to less than the 'Before discount': https://d.pr/i/CvxOOM
4. Click on 'Save'
5. Order will now have a coupon applied
6. Save the overall changes in the order
7. Go to the 'Revenue' tab in Analytics
8. You'll see that this fake coupon is not logged in the 'Coupons' box: https://d.pr/i/tZUCgT
   - the $40.00 shown in my screenshot is from another order that had an actual coupon applied
9. Change order to 'Processing'
10. You'll see that the 'Coupon' still is not included

### Expected behavior

While this isn't an actual coupon applied during checkout or order creation, it's logged by WooCommerce as a coupon, so it should be counted in the 'Revenue' reports for Coupons.

### Screenshots

Order: https://d.pr/i/eJ4fF1

'Revenue': https://d.pr/i/tZUCgT ($40.00 is from another order with an actual coupon)

### Additional context

<details>

```
WC Database Version: 5.0.0

WooCommerce: by Automattic – 5.0.0
WooCommerce Admin: by WooCommerce – 2.0.1
```
</details>

Ticket: 3756104-zen

**Comment by ilyasfoo** [comment] 2021-03-04 09:21
I'm able to reproduce this. I think it's a bug and might not be straightforward to fix.

**Comment by chihsuan** [comment] 2022-01-18 09:14
We can include the discounts from the virtual coupons but the "Revenue" and "Coupons" reports might have inconsistent data.

I just created two orders. One is manually applied discounts `order_id =6`. Another is to use an actual coupon `order_id=18`. 

You can see below that both of them are listed on the `wp_wc_order_product_lookup` table with the coupon_amount values.

```
# select order_id, product_net_revenue, coupon_amount from wp_wc_order_product_lookup;
order_id|product_net_revenue|coupon_amount|
--------+-------------------+-------------+
      16|             3400.0|        100.0|
      18|              31.25|         10.0|
```

But only the actual coupon one is in the `wp_wc_order_coupon_lookup` table which we used to aggregate report data.

```
# select * from wp_wc_order_coupon_lookup;
order_id|coupon_id|date_created       |discount_amount|
--------+---------+-------------------+---------------+
      18|       17|2022-01-18 08:33:17|           10.0|
```

We can use `coupon_amount` column instead to get the total discounts for the revenue report but then the value will be different from the coupon report. 

Another way to fix this is to create an actual coupon when a user changes the 'total'  of the order in WooCommerce Core.

**Comment by chihsuan** [comment] 2022-02-07 08:42
Closing this for now since this bug is over 6 months old. p90Yrv-2Bc-p2

**Closed by chihsuan** 2022-02-07 08:42 UTC
Labels: type: bug, feature: analytics, needs feedback
