### ISSUE TITLE
Analytics report table header style is inconsistent

### ISSUE THREAD

**Issue by hsingyuc** [woocommerce/woocommerce-admin#7215] opened 2021-06-21 18:49 UTC
**Describe the bug**
The products, orders, variations, coupons, and downloads analytics report table's header style is inconsistent.
`Button` fonts have bold styling, with padding, and `span` doesn't.

**To Reproduce**

1. Go to 'Analytics'
2. Click on 'Products'  
     ( as well as orders, variations, coupons, and downloads )
3. Scroll down to 'Product report table'  
     ( as well as orders, variations, coupons, and downloads )
4. See header errors

**Expected behavior**
Consistent padding, color, font-weight style.

**Screenshots**
<img width="838" alt="螢幕快照 2021-06-21 下午2 15 47" src="https://user-images.githubusercontent.com/56378160/122811530-97e58800-d29e-11eb-9d6f-7e8981e76758.png">

**Desktop (please complete the following information):**
* Browser [chrome]

**Comment by octaedro** [comment] 2021-06-22 17:04
Thank you @hsingyuc for reporting this bug.

I can reproduce the mentioned errors but I couldn't see the same as what's in the shared screenshot.

I see every title in `bold`
![Captura de Pantalla 2021-06-22 a la(s) 13 57 03](https://user-images.githubusercontent.com/1314156/122968421-e9a31680-d361-11eb-805e-301d799e2f30.png)

**Comment by mattsherman** [comment] 2021-11-15 20:39
I can reproduce this. It is still an issue.

**Comment by chihsuan** [comment] 2021-12-29 07:33
The different padding style is intentional.

> This has been a nagging issue in wc admin analytics tables for some time. We should right align numbers, and text align left. - [#7431](https://github.com/woocommerce/woocommerce-admin/pull/7431)

**Comment by chihsuan** [comment] 2021-12-29 07:58
I'm not sure if the header color and font-weight style are also intentional or we should make them consistent. cc @pmcpinto @elizaan36

**Comment by chihsuan** [comment] 2022-01-24 08:52
I'm closing this since this is over 6 months old.

**Closed by chihsuan** 2022-01-24 08:52 UTC
Labels: type: bug, feature: analytics
