### ISSUE TITLE
[WC 4.5 RC3] `Connect your store to activate WooCommerce Services` is redundant 

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#5089] opened 2020-09-03 02:31 UTC
**Describe the bug**

`Connect your store to activate WooCommerce Services` is redundant after completing OBW and connecting to WP.com account right after OBW. 

**To Reproduce**

1. Start OBW on the brand new site. 
2. Fill in the `Store Details` section with the US address.  
3. Select `Fashion, apparel, and accessories` in the Industries section.
4. In the `Tell us about your business` section, select checkbox next to `Install recommended free business features` to install all the recommended plugins. 
5. Proceed with any theme. 
6. Note that you will be prompted to go through the process of connecting your site to WP.com account at the end of onboarding and before you get to the Home Screen:

![wpcm](https://user-images.githubusercontent.com/19143190/92064389-67624b00-ed6b-11ea-8651-07fd57054a6f.jpg)

7. Click on the `Approve` button and complete the process of connecting to your WP.com account. 
8. Once OBW is completed, note that there will be a notice throughout WooCommerce pages to `Connect your store to activate WooCommerce Services` which is now redundant since we already completed the connection. 
9. If you click on the `Connect` button, nothing would happen and the notice will go away. This notice usually supposed to take the user through the flow of connecting to the WP.com account. In this particular case, the notice shouldn't be here in the first place. 

See gif below showing the behavior:

![](http://g.recordit.co/7eiiOYgmOH.gif)

**Expected behavior**

I expected not to see the `Connect your store to activate WooCommerce Services` notice at all since I already connected my site to my WP.com account after completing OBW. 

**Screenshots**

See gif above. 

**Desktop (please complete the following information):**

- OS: macOS Catalina 10.15.6
- Browser: Chrome
- Version: Version 85.0.4183.83 (Official Build) (64-bit)

**Additional context**

N/A

**Comment by timmyc** [comment] 2020-09-03 21:48
This is pretty much a duplicate of #5087 - something is amiss with the flow of installing WCS + Jetpack in the bundle step which results in a state where the site **is Jetpack connected** but WCS is not aware of the connection. So really at this point, the message being shown above ( which is in WCS not wc-admin ) is indeed valid.

@c-shultz any ideas what might cause WCS to think a site is not connected when it is indeed connected to Jetpack?

**Comment by c-shultz** [comment] 2020-09-03 23:24
@timmyc, behind the scenes "Connect" just marks the terms-of-service as being accepted. If Jetpack was not connected, a different message banner is shown. 

It looks like there as been some discussion in the past about the "Connect" nomenclature being confusing: https://github.com/Automattic/woocommerce-services/issues/1192

I'll re-open that and get some design feedback on it since this is coming up again.

**Comment by juliaamosova** [comment] 2020-09-04 14:45
>This is pretty much a duplicate of #5087 - something is amiss with the flow of installing WCS + Jetpack in the bundle step which results in a state where the site is Jetpack connected but WCS is not aware of the connection.

Thanks @timmyc! Yep, I figured that this notice could be a consequence of 5087 but wasn't sure and decided to open a separate issue. Following it to see what will be decided and what could be going on here.

**Comment by becdetat** [comment] 2020-09-07 00:47
#5087 has been potentially fixed by #5101, which is being included in WCA 1.5.0, so this could potentially be closed.

**Comment by adrianduffell** [comment] 2020-09-16 04:48
This looks like it was fixed by the work #5101. With the current version of WooCommerce (v4.5.2 from the .org repository), the `Connect your store to activate WooCommerce Services` is no longer present after reproducing the steps.

![Screen Shot 2020-09-16 at 12 24 08 pm](https://user-images.githubusercontent.com/9312929/93292195-91117c80-f817-11ea-9dd2-90d9a95e5397.png)

**Closed by adrianduffell** 2020-09-16 04:48 UTC
Labels: Onboarding, [Type] Bug
