### ISSUE TITLE
WC Admin pages (Home, OBW, Analytics) show as blank with Gutenberg + WP Log Viewer activated

### ISSUE THREAD

**Issue by tammullen** [woocommerce/woocommerce-admin#5680] opened 2020-11-18 21:43 UTC
**Describe the bug**
WC Admin pages (Home, OBW, Analytics) show as blank with Gutenberg + WP Log Viewer **both** activated. Deactivating **either** Gutenberg or WP Log Viewer fixes the issue.

I am seeing this happen when activating WooCommerce 4.7.0 or WooCommerce 4.8.0 Beta 1

**To Reproduce**

1. Create a new Jurassic Ninja site with just Gutenberg (9.4.0) and WP Log Viewer (1.2.1) installed.
2. Install WooCommerce 4.7.0 or 4.8.0 Beta 1
3. Click Activate WooCommerce
4. `wp-admin/admin.php?page=wc-admin` is displayed as blank.
5. Visit Analytics and observe it is also blank
6. Observe `Uncaught TypeError: Cannot read property` errors in Console
6. Deactivate **either** Gutenberg or WP Log Viewer and the pages will load as expected. 

**Screenshots**
![Screenshot 2020-11-18 at 21 23 40](https://user-images.githubusercontent.com/24649833/99591523-d48a9180-29e6-11eb-9ba8-d6aa498a5d1b.png)

**Additional context**
This happens with both WordPress 5.5 and 5.6 RC

**Comment by timmyc** [comment] 2020-11-18 22:12
Thanks for the report @tammullen - just wanting to confirm that this is the plugin in question: https://wordpress.org/plugins/wp-log-viewer/

If so, looks like it hasn't been updated in 3 years, so not sure if this is something we want to spend time tracking down or not... especially if deactivating the log viewer plugin remedies the issue.

**Comment by tammullen** [comment] 2020-11-18 22:27
Thanks @timmyc, yes that is the plugin.
I agree if it specifically is related to that plugin then it isn't a high priority. I wanted to report it here as all the console errors appear to be related to WP Admin and Gutenberg so was just in case there was something else going on.

**Comment by timmyc** [comment] 2020-11-19 20:30
Thanks for confirming @tammullen - I'm going to close this as a won't fix since the issue is being caused by the older plugin here. If this were happening with just gutenberg, then I'd say we would want to pursue it. I like logging issues like this though so it will come up as a known issue if anyone is seeking info about the error message.

**Closed by timmyc** 2020-11-19 20:30 UTC
Labels: [Priority] Low
