### ISSUE TITLE
[4.9.0-RC.1] Notice shown when RazorPay is installed from task list

### ISSUE THREAD

**Issue by vedanshujain** [woocommerce/woocommerce-admin#5974] opened 2020-12-29 14:21 UTC
**Describe the bug**
If you install RazorPay and set the keys in via task list after completing OBW, looks like `title` and description properties are not set. This causes notices during the whole site. See screenshot:

![](https://d.pr/i/T8ygwr+)

**To Reproduce**

1. Install RazorPay via tasklist
2. Set razor pay keys during the task list setup.
3. Visit the frontend, you will see those notices

**Expected behavior**
No notices.

**Desktop (please complete the following information):**

* OS: [e.g. iOS] macOS Big Sur
* Browser [e.g. chrome, safari] Safari
* Version [e.g. 22] 14.0.1

**Additional context**
Root cause looks like title and description setting options are not set via task list.

**Comment by juliaamosova** [comment] 2020-12-29 15:32
This issue is a duplicate of https://github.com/woocommerce/woocommerce-admin/issues/5963 where @moon0326 already did some investigation.

**Comment by moon0326** [comment] 2020-12-29 15:36
@juliaamosova The layout part is duplicate, but I think the error message is new. I will test out the error message and work in this issue if I can reproduce it.

**Comment by juliaamosova** [comment] 2020-12-29 15:39
Thanks @moon0326!

**Comment by moon0326** [comment] 2020-12-29 16:54
I was able to reproduce it locally.  I opened a [PR](https://github.com/razorpay/razorpay-woocommerce/pull/173) in Razorpay github as this should be handled in the plugin.

**Comment by timmyc** [comment] 2020-12-29 19:33
@pmcpinto @MechielCouvaras - we have encountered a few issues with the Razorpay gateway plugin during testing of 4.9 - do we have a contact there we can escalate these issues to?

**Comment by pmcpinto** [comment] 2020-12-30 07:47
I don't have a contact and Mechiel is afk this week. Probably we'll need to wait until he comes back next Monday.

**Comment by moon0326** [comment] 2021-01-05 00:42
The [PR](https://github.com/razorpay/razorpay-woocommerce/pull/173) has been approved by Razorpay. I also left a comment for the release date.

**Comment by isaumya** [comment] 2021-01-06 15:27
@timmyc You can mention all the issues that you have faced either mention them here or provide the respective issue IDs and I can forward the thinks to the Razorpay Senior Management and Product Managers to look at those issues with priority.
Hope this helps. 😃

**Comment by moon0326** [comment] 2021-01-06 22:12
@isaumya Sure thing! Yup, the latest version (2.6.0) fixed the problem.

**Comment by timmyc** [comment] 2021-01-06 23:46
Excellent, since the fix has been released in the plugin, I think it is safe to close out this issue now.

**Closed by timmyc** 2021-01-06 23:46 UTC
Labels: priority: high, type: bug
