### ISSUE TITLE
REST API: Migrate wc-admin Endpoints

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#2181] opened 2019-05-07 20:17 UTC
Background: p7bje6-1lz-p2

This task involves migrating the v4 REST API endpoints that were created for the wc-admin project, their supporting Data Stores, Interfaces, and Query classes to WooCommerce Core.

Please view the p2 post for more discussion and some ideas.

**Comment by psealock** [comment] 2019-08-11 22:15
@mikejolley wc-admin needs to eventually migrate REST API endpoints to https://github.com/woocommerce/woocommerce-rest-api before a merge to core, is that right?

My understanding is development would continue in the rest api repo and each release of wc-admin while its still a feature plugin will bundle the dev version (or a portion of it) in its release. Once merged to core, development will continue in the rest api repo. 

Have I got the gist of it?

**Comment by mikejolley** [comment] 2019-08-12 06:58
@psealock possibly..the issue is the API in WC admin has many supporting components such as sync, so we need to make sure they are finalised and moved also. Some of the APIs such as onboarding are not suitable for a public rest API and should remain private (own namespace, not in the rest API repo).

**Comment by psealock** [comment] 2019-08-18 23:16
I moved this to the backlog because, while needed for the merge, it will create some friction by having code in two repos. Postponing this one for later.

**Comment by rrennick** [comment] 2019-11-11 20:08
Closing in favour of #3205

**Closed by rrennick** 2019-11-11 20:08 UTC
Labels: On Merge to WC Core, REST API, [Status] Blocked, [estimate] 8
