### ISSUE TITLE
[WC 4.5 RC3] Home Screen: `Set up tax` task doesn't get completed and the automated taxes don't get enabled if the user selects that option

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#5087] opened 2020-09-03 01:52 UTC
**Describe the bug**

After completing OBW, on Home Screen, if the user selects the `Set up tax` task and then selects to enable automated taxes, the `Set up tax` task first gets marked as completed. But the automated taxes don't get enabled if you check Tax Settings and the `Set up tax` task gets undone when you get back to Home Screen. 

**To Reproduce**

1. Start OBW on the brand new site. 
2. Fill in the `Store Details` section with the US address.  
3. Select `Fashion, apparel, and accessories` in the Industries section.
4. In the `Tell us about your business` section, select checkbox next to `Install recommended free business features` to install all the recommended plugins. 
5. On Home Screen, select `Set up tax` task. You will be presented with the `Good News!` popup - click on `Yes please` button to enable automated taxes:

![Screen Shot 2020-09-02 at 9 43 21 PM](https://user-images.githubusercontent.com/19143190/92061961-8827a200-ed65-11ea-842c-47e4ea3e2a21.png)

6. Note the notice at the bottom letting you know that you have one fewer to-do items and also note that `Set up tax` task gets marked as completed. 
7. Navigate to `WooCommerce/Settings/Tax/Tax Options` and see that automated taxes were not enabled as they were supposed to. Instead, you will see the following (regular tax settings):

![Screen Shot 2020-09-02 at 9 48 29 PM](https://user-images.githubusercontent.com/19143190/92062173-1734ba00-ed66-11ea-9021-45310e5e2c0d.png)

8. Navigate back to Home Screen and you will see that the `Set up tax` task is reverted back to not being done. 

See gif below that showcases the behavior (replicated it 3 times on JN site):

https://recordit.co/lL1AoVUKOE

**Expected behavior**

When navigated to `WooCommerce/Settings/Tax/Tax Options` in step 7, I expected to see that automated taxes have been enabled:

![taxes](https://user-images.githubusercontent.com/19143190/92062251-421f0e00-ed66-11ea-94f1-12bea61858b1.jpg)

**Screenshots**

See above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.6
- Browser: Chrome
- Version: Version 85.0.4183.83 (Official Build) (64-bit)

**Additional context**

N/A

**Comment by timmyc** [comment] 2020-09-03 21:37
Confirmed this issue myself, and it only happens when using the bundled extension install. It seems that with the bundled extension flow, when the benefits page is skipped and we direct people to connect to Jetpack, WCS is somehow not connected after that process.

The behavior of the bundled install in 1.4/4.4 skips the benefits screen entirely, and the JP connect process, and instead on the tax step you are prompted to Install and Enable Jetpack & WCS:

<img width="679" alt="image" src="https://user-images.githubusercontent.com/22080/92175693-f7e36e80-edf1-11ea-8c0a-ac1bc51b8fae.png">

after install

<img width="704" alt="image" src="https://user-images.githubusercontent.com/22080/92175755-09c51180-edf2-11ea-898f-12f684cb895e.png">

and the Jetpack connect screen:

<img width="1396" alt="image" src="https://user-images.githubusercontent.com/22080/92175823-22352c00-edf2-11ea-8ca9-456e853fe1c1.png">

So this is definitely a regression since the last release. I don't know if we will have enough time to pursue a fix.

@pmcpinto - what was the outcome of the conversation around the bundled UI? Are we going to be making more changes here or continuing to use it?

One obvious fix is to disable the bundle UI in this release, while drastic, it does fix this flow.

**Comment by c-shultz** [comment] 2020-09-03 23:34
@timmyc , I haven't dug deeply on this, but one thing to check into is a long-ago added option that triggers the ToS accept for WCS: `woocommerce_setup_jetpack_opted_in`. wc-admin sets that in some flows. 

The naming of that option doesn't make it clear, but that's one way that the ToS acceptance can be triggered for WCS: https://github.com/Automattic/woocommerce-services/blob/5fb693f816d44f1b6c63b591b4c846cf6062f01c/woocommerce-services.php#L502

**Comment by pmcpinto** [comment] 2020-09-04 10:08
> @pmcpinto - what was the outcome of the conversation around the bundled UI? Are we going to be making more changes here or continuing to use it?

@timmyc the results are positive, I'm going to P2 them today. We discussed an intermediate approach, where we also let folks deselect some of the options. I'll talk with Elizabeth to see if it's possible to create a mock-up of this, so it can be implemented in the upcoming cycle. We should keep the bundled UI for the time being.

**Comment by timmyc** [comment] 2020-09-04 19:48
@c-shultz brilliant, I think that is absolutely it. We [set that option](https://github.com/woocommerce/woocommerce-admin/blob/main/client/profile-wizard/steps/benefits/index.js#L101-L103) on the benefits screen, but do not do the same when we "bundle install" the extensions.

So seems like we could add that little bit of logic to the bundle process, and this bug ( and the others related to it ) should be fixed up.

**Comment by timmyc** [comment] 2020-09-04 21:33
Okay possible fix up for review here: https://github.com/woocommerce/woocommerce-admin/pull/5101

**Closed** 2020-09-06 23:38 UTC
Labels: Onboarding, [Type] Bug
