### ISSUE TITLE
Customer Search is Broken

### ISSUE THREAD

**Issue by Luminus** [woocommerce/woocommerce-admin#7486] opened 2021-08-09 12:05 UTC
### Describe the bug

When searching for a customer using the search bar at **WooCommerce → Customers** nothing is returned

### To Reproduce

1. Go to **WooCommerce → Customers**
2. In the search bar, type part (or all) of the name of a customer
3. Click the resulting "All customers with names that include {whatever you typed}"
4. See a blank table with the message **No data to display**

### Actual behavior:

When searching for a customer using the search bar at **WooCommerce → Customers** nothing is returned. Instead, there's a **No data to display** message

### Screenshots

* You can see that I have a user with the name Steve Jobs
![Steve-Jobs](https://user-images.githubusercontent.com/248077/128702930-2dc78a40-7321-4fe7-bb3d-e9ae6abaa887.png)

* When I search for "Steve" or "Jobs" I get the error:
![No-Steve-Jobs](https://user-images.githubusercontent.com/248077/128703112-8ed340fd-a93c-4c0a-a826-19465a6241fd.png)

### Expected behavior

When searching for a customer using the search bar at **WooCommerce → Customers**, all customers with names matching the search parameter should be returned.

### Desktop (please complete the following information):

* OS: macOS
* Browser Brave
* Version 1.24.85

### Additional context

31039654-hc

**Comment by sukafia** [comment] 2021-08-09 13:51
I can also confirm that for customers whose names are returned, clicking on the name also returns "No data to display " message

**Comment by moon0326** [comment] 2021-08-09 16:10
Thank you @Luminus and @sukafia for taking the time to report the bug. We really appreciate it. I was also able to reproduce it up to WC Admin version 2.5.0 RC 2. It looks like the bug has been fixed in the 2.6.0-beta version by this [PR](https://github.com/woocommerce/woocommerce-admin/pull/7355). 

I'll leave this issue open for the next couple of days just in case.

**Comment by PARIS64** [comment] 2021-08-09 16:41
Hello, would it be possible to know when will the problem be fixed? or what do i have to do to help????
Im the one how reported

**Comment by moon0326** [comment] 2021-08-09 18:45
> Hello, would it be possible to know when will the problem be fixed? or what do i have to do to help????
> Im the one how reported

Hi @PARIS64 ✋, thank you for reporting the bug initially. 

WooCommerce Admin 2.6.0 will be included in the upcoming WooCommerce 5.7.0. Unfortunately, WooCommerce 5.7.0 won't ship until September. 

If you're comfortable using a beta version of WooCommerce Admin, you can download [WooCommerce Admin 2.6.0 Beta 2](https://github.com/woocommerce/woocommerce-admin/releases/download/v2.6.0-beta.2/woocommerce-admin.zip) and install it. 

Let us know if there is anything we can help with further.

**Comment by PARIS64** [comment] 2021-08-10 08:10
Hello,

I just install it like a nother plugin? and after this it will work ok?

**Comment by PARIS64** [comment] 2021-08-10 10:41
Hello, I've installed the  WooCommerce Admin 2.6.0 Beta 2 and the search bar does not work, I type the name, clic on the purple name i whant and i doesn't show anything.

https://imgur.com/fmlkEpZ

**Comment by moon0326** [comment] 2021-08-10 14:17
> Hello, I've installed the WooCommerce Admin 2.6.0 Beta 2 and the search bar does not work, I type the name, clic on the purple name i whant and i doesn't show anything.
> 
> https://imgur.com/fmlkEpZ

Hello,

I tested it locally with a fresh installation of WooCommerce and it worked for me. I've recorded a video just to make sure we're on the same page. 

Could you watch the following gif and see if I'm missing a step? I test the bug without WooCommerce Admin 2.6.0 first then test the bug again with 2.6.0 beta activated.

https://d.pr/i/sYMCQd

**Comment by moon0326** [comment] 2021-08-13 22:04
Closing this issue as there is no response from the reporter and this issue is fixed in 2.6.0.

**Closed by moon0326** 2021-08-13 22:04 UTC
Labels: type: bug, needs feedback
