### ISSUE TITLE
Analytics: dropdown arrows behavior is inconsistent across browsers

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4275] opened 2020-05-01 19:32 UTC
**Describe the bug**

Analytics: dropdown arrows' behavior is inconsistent across browsers. 

Tested using WC 4.1 rc.2. 

Chrome - when you click on dropdown, the arrow goes up and when you click on it again - it goes down:

![](http://g.recordit.co/Uvk2ZConFD.gif)

Firefox - when you click on dropdown, the arrow goes up and down immediately without the 2nd click:

![](http://g.recordit.co/NhlniccQHd.gif)

**Expected behavior**

I think Chrome's behavior is expected. 

**Additional context**

N/A.

**Comment by timmyc** [comment] 2020-08-25 21:23
I am not able to reproduce this with Firefox, closing out.

**Closed by timmyc** 2020-08-25 21:23 UTC
