### ISSUE TITLE
Page title too far right in the top bar on mobile

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#6248] opened 2021-02-02 21:14 UTC
**Describe the bug**
When the new navigation is enabled, on mobile the top bar page title is shifted to the right so the gap between the `W` icon and title is too large. Visually it looks unbalanced now, but as we begin including longer page titles in the app bar with the back button (i.e. task list screens), the text will be more likely to get cut off and become illegible.

**To Reproduce**
Open any site with the new navigation enabled. (I tested on an Ecom plan site)

1. Go to 'WooCommerce Home' or any top level page in WooCommerce on a mobile device
4. See error (Page title too far right)

**Expected behavior**
When the nav isn't enabled, the page title placement is correct. In the designs in Figma I'm showing 28px between the page title and left edge of the top bar, and the same distance between the back button and page title.

**Screenshots**
https://share.getcloudapp.com/2NuE2PQE
https://share.getcloudapp.com/NQuJd7nA
https://share.getcloudapp.com/llu9zkbm

**Smartphone (please complete the following information):**

* Device: Pixel 4 XL
* OS: Android 11
* Browser: Chrome

**Comment by joshuatf** [comment] 2021-02-03 21:26
Potentially resolved by https://github.com/woocommerce/woocommerce-admin/pull/6247

**Comment by joshuatf** [comment] 2021-02-12 18:57
@joelclimbsthings Are you sure this one isn't resolved by #6247 ?  I can't seem to reproduce on `main` anymore.

<img width="434" alt="Screen Shot 2021-02-12 at 1 57 05 PM" src="https://user-images.githubusercontent.com/10561050/107810171-40586e00-6d3a-11eb-8635-4345e259e4bd.png">

**Comment by joelclimbsthings** [comment] 2021-02-12 19:54
Actually, it looks like I was looking at something unrelated and never reproduced in in the first place. Closing.

**Closed** 2021-02-12 19:54 UTC
Labels: feature: navigation
