### ISSUE TITLE
WooCommerce Analytics Bug

### ISSUE THREAD

**Issue by bi1012037** [woocommerce/woocommerce-admin#7177] opened 2021-06-13 06:00 UTC
**Describe the bug**
The total value of Items Sold and Net sales in the parent category becomes 2 times the total value of all subcategories

**To Reproduce**

1. Go to 'wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Foverview'
2. Click on 'categories'
3. Scroll down to 'categories'
<img src="https://ppt.cc/fQfcgx@.jpg" >
<img src="https://ppt.cc/fSpoXx@.jpg">
Bug：A=2(A->B + A->C)
Correct ：A=A->B + A->C

**Desktop (please complete the following information):**
* OS: [windows 10]
* Browser [chrome]
* Version [91.0.4472.77]

**Additional context**
The classification has a parent-child relationship, and the parent category should delete the repeated values (the calculation should not be repeated), otherwise the final result will be doubled.

**Comment by joshuatf** [comment] 2021-06-14 21:03
Thanks for opening this issue, @bi1012037!

I had trouble even before reproducing this issue with the category lookup tables not being generated.  This may be specific to my personal install, but had to forcibly generate them to get category data to work.

After doing that, I was able to see the issue which I suspect is related to how the lookup tree works:

| category_tree_id | category_id |
|--|--|
| 1 | 1 |
| 1 | 2 |
| 1 | 3 |
| 2 | 2 |
| 3 | 3 |

The category tree ID is used to help us sum up parent category items, but upon joining the term and product tables, we're probably duplicating data based on the tree IDs.  We'll need to take a deeper into those queries to solve the issue.  cc @jeffstieler in case anything immediately pops out as an issue to you; I think you may have worked on the category tree a bit IIRC.

**Comment by chihsuan** [comment] 2022-01-17 02:34
Duplicate of https://github.com/woocommerce/woocommerce-admin/issues/7710

Fixed in https://github.com/woocommerce/woocommerce-admin/pull/8153

**Closed by chihsuan** 2022-01-17 02:34 UTC
Labels: type: bug, feature: analytics
