### ISSUE TITLE
Edit product issue

### ISSUE THREAD

**Issue by bathrick** [woocommerce/woocommerce-admin#2376] opened 2019-06-08 21:21 UTC
**Describe the bug**
The new bar across the top obscures the top of the edit product page (and I suspect other pages) interfering with my ability to easily edit the products. It should be hideable so I can access the top of the page.

**To Reproduce**

Edit a product.
Scroll down to work on the listing.
Top part of the edit section that should remain available, the line starting with "add media" scrolls behind the new bar (with inbox, orders, stock, reviews).

**Expected behavior**
Entire edit page should be available as it used to be.

**Screenshots**

**Desktop (please complete the following information):**

* OS: [e.g. iOS] windows 10
* Browser [e.g. chrome, safari] firefox
* Version [e.g. 22] 67

**Smartphone (please complete the following information):**

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Additional context**

**Comment by timmyc** [comment] 2019-06-11 15:44
@bathrick thanks for the bug report. I've confirmed the issue, here are a few screen grabs - you need to have a product with a large description ( or a bunch of whitespace ) to trigger the pinning of the add media and edit bars in tinymce on the product page:

__Without wc-admin__
![add-media-no-wc-admin](https://user-images.githubusercontent.com/22080/59286613-e62e0e00-8c24-11e9-87fc-554bcfd5b100.gif)

__With wc-admin__
![add-media-with-wc-admin](https://user-images.githubusercontent.com/22080/59286685-078efa00-8c25-11e9-8fe0-6ef99287dadc.gif)

**Comment by timmyc** [comment] 2019-06-11 16:11
Duplicate of #2337, closing this in favor of the earlier report.

**Closed by timmyc** 2019-06-11 16:11 UTC
Labels: [Type] Bug
