### ISSUE TITLE
JS part of CES runs even when disabled

### ISSUE THREAD

**Issue by szepeviktor** [woocommerce/woocommerce-admin#6415] opened 2021-02-23 00:56 UTC
**Describe the bug**
`woocommerce_ces_tracks_queue` option does not exist, I see requests in the webserver's log
`GET /wp-json/wc-admin/options?options=woocommerce_ces_tracks_queue&_locale=user` like this.

With response status 200 for admins, 403 for shop managers.

**To Reproduce**

1. Visit `/wp-admin/admin.php?page=wc-settings`
2. See broswers console

https://github.com/woocommerce/woocommerce-admin/blob/247d10a02920ba8d04f191062b904689375a4ff4/client/customer-effort-score-tracks/data/resolvers.js#L13-L15

Please advise.

**Comment by samueljseay** [comment] 2021-02-23 01:22
@woocommerce/mothra Perhaps one of you could investigate next steps here?

**Comment by ilyasfoo** [comment] 2021-02-26 04:23
I've found that CES feature flag is only checked at the component level, `CustomerEffortScoreTracks` but not in the container, `CustomerEffortScoreTracksContainer`. Adding an extra check in container should be able to rectify this issue.

Thanks for reporting @szepeviktor!

Estimate: 1

**Comment by psealock** [comment] 2021-03-01 01:54
Estimate 1

**Comment by moon0326** [comment] 2021-03-10 03:26
I think the described behavior is expected when the CES feature flag is enabled since we include CES survey in the setting page. `woocommerce_ces_tracks_queue` always gets queried if the flag is enabled.

I double confirmed that the settings page does not query `woocommerce_ces_tracks_queue` option if the feature flag is turned off.

The flag is checked in this [file](https://github.com/woocommerce/woocommerce-admin/blob/main/client/index.js#L80)

I think we can close this issue as the behavior is expected. What do you think @woocommerce/mothra @ilyasfoo ?

**Comment by szepeviktor** [comment] 2021-03-10 04:24
@moon0326 Thank you for your response.
So you leave me here with HTTP/403 for shop managers?

**Comment by szepeviktor** [comment] 2021-03-10 04:28
The problem appears when `woocommerce_ces_tracks_queue` WordPress option does not exist in `wp_options` table.

**Comment by ilyasfoo** [comment] 2021-03-10 05:40
@moon0326 If I understand correctly, the feature flag is used by developers to turn on/off features at build time. I don't think a general WooCommerce user would have the ability to turn it off without having to modify `includes/feature-config.php` directly.

So I think a fix is still required, maybe we can just add another line below the feature flag to check the `woocommerce_allow_tracking` option like what's done [in here](https://github.com/woocommerce/woocommerce-admin/blob/c1cd9b76ca67e760b17203bfa4a5a0721fad38be/src/Features/CustomerEffortScoreTracks.php#L67-L70).

**Comment by szepeviktor** [comment] 2021-03-10 05:57
> add another line below the feature flag to check the `woocommerce_allow_tracking` option

As far as I understand the **checking itself** causes HTTP/403 for non-admins.

**Comment by szepeviktor** [comment] 2021-03-10 05:59
See this dirty work-around for Apache.

```apache
<Location "/wp-json/wc-admin/options">
    ErrorDocument 200 '{"woocommerce_ces_tracks_queue":false}'
</Location>
RewriteCond "%{QUERY_STRING}" "options=woocommerce_ces_tracks_queue"
RewriteRule "^/wp-json/wc-admin/options$" - [R=200,L]
```

**Comment by ilyasfoo** [comment] 2021-03-11 04:30
>As far as I understand the checking itself causes HTTP/403 for non-admins.

This is true for checking wc-admin options via `wp-json/wc-admin/options`, but not WordPress options. My previous suggestion would do a check in WordPress options, which is allowed for shop managers AFAIK.

Anyway, since shop managers use WooCommerce admin interfaces, it would be logical to allow the role to view options somewhere around [here](https://github.com/woocommerce/woocommerce-admin/blob/55b0e58b8ce43d4ca2405d2558417d9092bafb12/src/API/Options.php#L69).

**Comment by moon0326** [comment] 2021-03-11 07:13
> @moon0326 Thank you for your response.
> So you leave me here with HTTP/403 for shop managers?
> 
> Querying the `woocommerce_ces_tracks_queue` option causes HTTP/403: `GET /wp-admin/admin.php?page=wc-settings`

I think I misunderstood your original post. My apologies. It should not throw 403.

**Closed** 2021-03-12 04:01 UTC
Labels: feature: customer effort score, type: bug
