### ISSUE TITLE
OOS Products Admin Performance

### ISSUE THREAD

**Issue by jedkirby** [woocommerce/woocommerce-admin#7358] opened 2021-07-15 08:56 UTC
### Describe the bug
When a client has a large set of products, and the WooCommerce Admin feature "Analytics" is enabled, there are huge performance issues which result in never-ending MySQL queries to check for stock levels of products. This issue is almost identical to the issue: https://github.com/woocommerce/woocommerce-admin/issues/3664, which has since been "resolved".

There are a number of other people having this issue, which can be found here: https://wordpress.org/support/topic/5-5-1-security-patch-causing-database-issues and here: https://wordpress.org/support/topic/endless-query-after-upgrading-from-4-x-to-5-4-1.

### To Reproduce
With a fresh install of WooCommerce (5.5.1), remove all other plugins, and ensure there is a very large set of products installed across the site - one of my clients has over 7k products, with roughly 30k variations.

### Actual behavior:
Browse the admin of the site, and watch the process list of MySQL (mysql > show processlist;) fill up with a new query for each admin page load, which will look like this: `SELECT SQL_CALC_FOUND_ROWS wp_posts.*, low_stock_amount_meta.meta_value AS low_stock_amount, MAX...`.

These queries will never end, and will ultimately eat up the entire CPU and MySQL threads, causing the site too take too long to respond.

### Screenshots
![Screenshot 2021-07-15 at 09 47 27](https://user-images.githubusercontent.com/1528691/125759097-2a615fd8-42e6-4aad-a04b-9d482e8cc235.png)

### Expected behavior
The queries should complete, therefore not block up the CPU and MySQL threads, allowing customers to browse the site.

### Desktop:

* OS: macOS Big Sur (11.4)
* Browser: Google Chrome
* Version: 91.0.4472.114 (Official Build) (x86_64)

### Additional context
To temporarily resolve this issue, install the plugin https://en-gb.wordpress.org/plugins/disable-dashboard-for-woocommerce and utilise the feature to switch off the "WooCommerce Admin".

Other have suggested to downgrade to version `5.4.2`, however, with the recent security notice, that's not advised.

**Comment by vedanshujain** [comment] 2021-07-15 09:18
> Other have suggested to downgrade to version 5.4.2, however, with the recent security notice, that's not advised.

While we are investigating, note that for recent security notice, its safe to stay at 5.4.2 (basically the last version for any X.Y release)

**Comment by thuautp** [comment] 2021-07-15 12:30
Other affected users in forum: https://wordpress.org/support/topic/5-5-1-security-patch-causing-database-issues/

**Comment by Masque** [comment] 2021-07-15 13:27
In case it's helpful, the full problematic SQL query is:

`SELECT SQL_CALC_FOUND_ROWS  wp_posts.*, low_stock_amount_meta.meta_value AS low_stock_amount, MAX( product_lookup.date_created ) AS last_order_date FROM wp_posts  LEFT JOIN wp_wc_product_meta_lookup wc_product_meta_lookup ON wp_posts.ID = wc_product_meta_lookup.product_id  LEFT JOIN wp_postmeta AS low_stock_amount_meta ON wp_posts.ID = low_stock_amount_meta.post_id AND low_stock_amount_meta.meta_key = '_low_stock_amount'  LEFT JOIN wp_wc_order_product_lookup product_lookup ON wp_posts.ID = CASE
				WHEN wp_posts.post_type = 'product' THEN product_lookup.product_id
				WHEN wp_posts.post_type = 'product_variation' THEN product_lookup.variation_id
			END WHERE 1=1  AND wp_posts.post_type IN ('product', 'product_variation') AND ((wp_posts.post_status = 'publish'))
			AND wc_product_meta_lookup.stock_quantity IS NOT NULL
			AND wc_product_meta_lookup.stock_status IN('instock','outofstock')
			AND (
				(
					low_stock_amount_meta.meta_value > ''
					AND wc_product_meta_lookup.stock_quantity <= CAST(low_stock_amount_meta.meta_value AS SIGNED)
				)
				OR (
					(
						low_stock_amount_meta.meta_value IS NULL OR low_stock_amount_meta.meta_value <= ''
					)
					AND wc_product_meta_lookup.stock_quantity <= 2
				)
			) GROUP BY wp_posts.ID ORDER BY wp_posts.post_date DESC, wp_posts.ID DESC LIMIT 0, 1 `

**Comment by yulumadavid** [comment] 2021-07-15 13:29
We've downgraded to 5.4.2 and the problem is gone, i took our server down because of the endless queries.

**Comment by louwie17** [comment] 2021-07-15 15:42
Another user is experiencing this, more info here 4139170-zd-woothemes

**Comment by jcatello** [comment] 2021-07-15 19:18
We are seeing this as well running 5.5.1 causing entire server to go down.

Query example:

`SELECT SQL_CALC_FOUND_ROWS  wp_posts.*, low_stock_amount_meta.meta_value AS low_stock_amount, MAX( product_lookup.date_created ) AS last_order_date FROM wp_posts  LEFT JOIN wp_wc_product_meta_lookup wc_product_meta_lookup ON wp_posts.ID = wc_product_meta_lookup.product_id  LEFT JOIN wp_postmeta AS low_stock_amount_meta ON wp_posts.ID = low_stock_amount_meta.post_id AND low_stock_amount_meta.meta_key = '_low_stock_amount'  LEFT JOIN wp_wc_order_product_lookup product_lookup ON wp_posts.ID = CASE
                                WHEN wp_posts.post_type = 'product' THEN product_lookup.product_id
                                WHEN wp_posts.post_type = 'product_variation' THEN product_lookup.variation_id
                        END WHERE 1=1  AND wp_posts.post_type IN ('product', 'product_variation') AND ((wp_posts.post_status = 'publish'))
                        AND wc_product_meta_lookup.stock_quantity IS NOT NULL
                        AND wc_product_meta_lookup.stock_status IN('instock','outofstock')
                        AND (
                                (
                                        low_stock_amount_meta.meta_value > ''
                                        AND wc_product_meta_lookup.stock_quantity <= CAST(low_stock_amount_meta.meta_value AS SIGNED)
                                )
                                OR (
                                        (
                                                low_stock_amount_meta.meta_value IS NULL OR low_stock_amount_meta.meta_value <= ''
                                        )
                                        AND wc_product_meta_lookup.stock_quantity <= 2
                                )
                        ) GROUP BY wp_posts.ID ORDER BY wp_posts.post_date DESC, wp_posts.ID DESC LIMIT 0, 1 | 0.000    |
`

**Comment by nicdwilson** [comment] 2021-07-16 02:39
4152302-zd-woothemes

**Comment by DanielB1990** [comment] 2021-07-16 06:23
Hello,

I can confirm that this exact MySQL query is causing issues, I’m a representative of a dutch Webhosting company and we are seeing these queries causing full (100%) load spikes on our database servers too, we’ve identified at least 2 websites that have this issue.

- Website 1:
   - WordPress Core: 5.7.2
   - WooCommerce: 5.5.1
   - WooCommerce Admin: 2.4.1

- Website 2:
   - WordPress Core: 5.7.2
   - WooCommerce: 5.5.1
   - WooCommerce Admin: 2.4.1

Since it is a shared-hosting environment, we’ve tried to make improvements by adding indexes to several columns to see if that would make any changes, but unfortunately it didn’t resolve the issue.

Here’s the formatted SQL Query:

```
SELECT
	SQL_CALC_FOUND_ROWS wp_posts.*,
	low_stock_amount_meta.meta_value AS low_stock_amount,
	MAX(product_lookup.date_created) AS last_order_date
FROM wp_posts
	LEFT JOIN wp_wc_product_meta_lookup wc_product_meta_lookup ON wp_posts.ID = wc_product_meta_lookup.product_id
	LEFT JOIN wp_postmeta AS low_stock_amount_meta ON wp_posts.ID = low_stock_amount_meta.post_id AND low_stock_amount_meta.meta_key = '_low_stock_amount'
	LEFT JOIN wp_wc_order_product_lookup product_lookup ON wp_posts.ID = CASE
		WHEN wp_posts.post_type = 'product' THEN product_lookup.product_id
		WHEN wp_posts.post_type = 'product_variation' THEN product_lookup.variation_id
	END
WHERE
	1 = 1
	AND wp_posts.post_type IN ('product', 'product_variation')
	AND ((wp_posts.post_status = 'publish'))
	AND wc_product_meta_lookup.stock_quantity IS NOT NULL
	AND wc_product_meta_lookup.stock_status IN('instock', 'outofstock')
	AND (
			(
				low_stock_amount_meta.meta_value > ''
				AND wc_product_meta_lookup.stock_quantity <= CAST(low_stock_amount_meta.meta_value AS SIGNED)
			)
			OR (
				(
					low_stock_amount_meta.meta_value IS NULL
					OR low_stock_amount_meta.meta_value <= ''
				)
				AND wc_product_meta_lookup.stock_quantity <= 2
			)
		)
GROUP BY wp_posts.ID
ORDER BY wp_posts.post_date DESC, wp_posts.ID DESC
LIMIT 0, 1
```

Please look into this further as it causes load issues, and this notification could just be the tip of an iceberg.
One of our customers has successfully downgraded WooCommerce to 5.4.2 which has resolved the problem ( for now )

Kind regards, Daniël

**Comment by solstudioim** [comment] 2021-07-16 06:32
4152153-zen

**Comment by adrianduffell** [comment] 2021-07-16 07:09
Thanks for the reports about this. We are focused on improving the performance of this query. The team has identified the root cause and is now working towards a fix.

A downgrade to version 5.4.2 looks to be the best workaround at present.

I will provide further updates here as more information becomes unavailable.

**Comment by fitimvata** [comment] 2021-07-16 10:36
If you are using latest version 5.5.1 bellow you can find a snippet to temporally disable the query.
https://gist.github.com/fitimvata/09b177f8c822c8a2ffedf987058f0fe3

**Comment by skullo27** [comment] 2021-07-16 11:09
We are seeing the same issue, we have 120K orders and 20K products in the DB which is obviously big! These queries result in server time outs and then we need to restart PHP to get access to the site again. 

The best temporary workaround we found was the plugin suggested above "Disable WooCommerce Bloat".

**Comment by jgbyvan** [comment] 2021-07-16 13:27
We hit this, we cannot follow the downgrade process as we have a highly active site and winding back the database is not an option (the key problem didn't show its head until too late.)

As a temporary fix we have disabled the `get_items` function in `woocommerce/packages/woocommerce-admin/src/API/Products.php` by inserting a `return ";` at the top... everything seems to be working fine on the website now, and it's faster than it was before. But I've presumably broken something somewhere by amputating a random chunk of code in what I assume is a REST API used by AJAX stuff... 

Looking forward to a proper fix.

**Comment by oscarh2485** [comment] 2021-07-16 15:05
> 
> 
> If you are using latest version 5.5.1 bellow you can find a snippet to temporally disable the query.
> https://gist.github.com/fitimvata/09b177f8c822c8a2ffedf987058f0fe3

Same issue here. This workaround is working, Thanks!!

**Comment by DSCreative** [comment] 2021-07-16 15:59
Snippet works perfectly here too. Thanks. I've been going mad all day trying to figure this one out.

**Comment by mjameswh** [comment] 2021-07-16 19:29
Same thing here.

Based on my investigation, the cause of this issue is the following join:
```
LEFT JOIN wp_wc_order_product_lookup product_lookup
    ON wp_posts.ID =
        CASE
            WHEN wp_posts.post_type = 'product' THEN product_lookup.product_id
            WHEN wp_posts.post_type = 'product_variation' THEN product_lookup.variation_id
        END
```

There are actually two things here. First, the database has no index to support efficient query on `wp_wc_order_product_lookup` based on column `variation_id`. This can be demonstrated by reducing the condition to `wp_posts.ID = product_lookup.product_id` (which use an index and is very efficient) vs `wp_posts.ID = product_lookup.variant_id` (which doesn't use an index and make the whole query very slow). Adding an index on `wp_wc_order_product_lookup.variation_id` easily fix that.

The second problem is that even with such an index, MySQL doesn't know how to resolve a single JOIN using two alternative indices, which is exactly what the CASE condition does here. This force the engine to do a full table scan and a filesort, which is ridiculously slow. Now, this is harder to resolve.

I had success here by modifying the query to this:

```
SELECT SQL_CALC_FOUND_ROWS
		wp_posts.*,
		low_stock_amount_meta.meta_value AS low_stock_amount,
		IF( MAX( product_lookup.date_created ) > MAX( product_variation_lookup.date_created ),
			MAX( product_lookup.date_created ),
			MAX( product_variation_lookup.date_created )
		) AS last_order_date
	FROM wp_posts  
  LEFT JOIN wp_wc_product_meta_lookup wc_product_meta_lookup
	    ON wp_posts.ID = wc_product_meta_lookup.product_id
	LEFT JOIN wp_postmeta AS low_stock_amount_meta
	    ON wp_posts.ID = low_stock_amount_meta.post_id AND
			   low_stock_amount_meta.meta_key = '_low_stock_amount'
	LEFT JOIN wp_wc_order_product_lookup product_lookup
	    ON wp_posts.ID = product_lookup.product_id AND wp_posts.post_type = 'product'
	LEFT JOIN wp_wc_order_product_lookup product_variation_lookup
	    ON wp_posts.ID = product_variation_lookup.variation_id AND wp_posts.post_type = 'product_variation'
	WHERE
		1=1  AND
		wp_posts.post_type IN ('product', 'product_variation') AND
		((wp_posts.post_status = 'publish')) AND
		wc_product_meta_lookup.stock_quantity IS NOT NULL AND
		wc_product_meta_lookup.stock_status IN('instock','outofstock') AND
		(
			( low_stock_amount_meta.meta_value > '' AND
			  wc_product_meta_lookup.stock_quantity <= CAST(low_stock_amount_meta.meta_value AS SIGNED)
      ) OR (
			  ( low_stock_amount_meta.meta_value IS NULL OR low_stock_amount_meta.meta_value <= '' ) AND
				wc_product_meta_lookup.stock_quantity <= 2
      )
	  )
  GROUP BY wp_posts.ID
	ORDER BY wp_posts.post_date DESC, wp_posts.ID DESC
	LIMIT 0, 1;
```

Basically, the difference here is that I use two JOIN, that is one for products and another for product variations. I then merge dates for each one in the field specification.

With this change, query time is around ~0.3 seconds rather than 150 to 300 seconds.

Alternatively, this could be resolved using a subquery, but I don't think this would be simpler.

---

In case someone is interested, here is my modifications:
```
diff -r ./old/htdocs/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Products.php ./new/htdocs/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Products.php
178c178
< 				'IF( MAX( product_lookup.date_created ) > MAX( product_variation_lookup.date_created ), MAX( product_lookup.date_created ), MAX( product_variation_lookup.date_created )) AS last_order_date',
---
> 				'MAX( product_lookup.date_created ) AS last_order_date',
245,252c245,248
< 
< 			// Original query used would use a single join for both products and products variation, using either
<                         // product_lookup.product_id or product_lookup.variation_id foreing key. However, this made it impossible for MySQL
<                         // to use an index for this part of the query, making queries using this condition very slow (150 to 300 seconds).
<                         // We fixed this issue by using two distinct JOIN (one for products, another for variations). Thanks to this, query
<                         // time is down to ~0.3s.
< 			$join .= " LEFT JOIN {$product_lookup_table} product_lookup ON {$wpdb->posts}.ID = product_lookup.product_id AND {$wpdb->posts}.post_type = 'product' ";
< 			$join .= " LEFT JOIN {$product_lookup_table} product_variation_lookup ON {$wpdb->posts}.ID = product_variation_lookup.variation_id AND {$wpdb->posts}.post_type = 'product_variation' ";
---
> 			$join .= " LEFT JOIN {$product_lookup_table} product_lookup ON {$wpdb->posts}.ID = CASE
> 				WHEN {$wpdb->posts}.post_type = 'product' THEN product_lookup.product_id
> 				WHEN {$wpdb->posts}.post_type = 'product_variation' THEN product_lookup.variation_id
> 			END";
```

**Comment by adrianduffell** [comment] 2021-07-17 03:16
### Update

First of all I would just like to say thank you ❤️ to everyone for providing alternative workarounds and feedback here. It is much appreciated and has been helping shape our solution to this issue.

We think the root cause is twofold:

1. A slow SQL query used to retrieve the products that are low in stock. This SQL has been in WooCommerce for a number of releases.

2. A REST API request, which executes this SQL query, is called more frequently in WooCommerce 5.5 than in previous versions.

A combination of both these is causing the degraded server performance when updating to WooCommerce 5.5.

We are working on improvements to both the SQL and REST API request. We have had promising results optimizing the SQL and are currently narrowing our testing down to two different approaches. Please bare with us while we take some time to perform this testing. We are striving to ensure the optimized query is accurate and returns the same results as previously. It is currently being tested against a database with 10K products and 230K orders.

Meanwhile, we are also investigating caching the REST API request and progress can be seen in PR #7364. I welcome any feedback and testing of this approach if you are in a position to do so.

Again, thank you! I appreciate this is a difficult issue to be navigating at the moment. I will provide the next update on Monday (UTC) with our progress.

**Comment by DtheRock** [comment] 2021-07-17 09:21
Since this is caused by the woocommerce admin and analytics, I have found a temporary solution by disabling woocommerce admin and analytics functionality. It's a simple process, you can follow the instructions described here https://www.webroomtech.com/how-to-disable-woocommerce-admin-dashboard-and-woocommerce-analytics/ 

I did it on my site and worked fine.

**Comment by bretdugmore** [comment] 2021-07-17 09:45
Just registered, to jump in here, to THANK YOU for finding and reporting this bug.  

We run a fairly big DB - 17k products.  

This has been a nightmare.

**Comment by pcball** [comment] 2021-07-18 05:48
Thanks for the solutions and workaround.

**Comment by adrianduffell** [comment] 2021-07-19 13:45
### Update

We have released WooCommerce Admin 2.4.2, which includes a partial fix for this issue. It seeks to reduce the frequency of requests made to the problematic REST API endpoint by using lazy loading and caching. The fix can be applied now via the [WooCommerce Admin plugin](https://wordpress.org/plugins/woocommerce-admin/). 

It is expected that stores with larger amounts of products may still be impacted after this fix. In these cases, existing workarounds should still be applied.

We are continuing to work on providing a full fix by improving the SQL query performance. Our progress can be seen in PR #7377. If you are in a position to test this PR, particularly against a large database, please feel welcome to do so. Any feedback is also welcome.

**Comment by Ehrenboeck** [comment] 2021-07-20 10:09
> 
> 
> If you are using latest version 5.5.1 bellow you can find a snippet to temporally disable the query.
> https://gist.github.com/fitimvata/09b177f8c822c8a2ffedf987058f0fe3

Thanks - saved my "life"!

**Comment by rickdroio** [comment] 2021-07-21 01:51
FYI just tested on Wordpress 5.8 - same issue.... I'm using this workaround https://gist.github.com/fitimvata/09b177f8c822c8a2ffedf987058f0fe3... works like a charm!!

**Comment by adrianduffell** [comment] 2021-07-21 05:46
### Update

I am pleased to announce we have released WooCommerce Admin 2.4.4, which includes our full fix for this issue. The fix can be applied now via the [WooCommerce Admin](https://wordpress.org/plugins/woocommerce-admin/) plugin.

A new REST API endpoint `/wc-analytics/products/low-in-stock` has been added utilizing a more performant query for retrieving stock levels. We have kept the behavior of the existing `/wc-analytics/products/?low_in_stock=true` REST API endpoint in tact, including the slow SQL query. However all WooCommerce Admin usage has been updated to use the new, more performant endpoint. In the future we plan to review the consumers of the old endpoint and provide guidance to transition from it.

We will now turn our attention to releasing this fix in WooCommerce Core.

I will keep this issue open to provide further updates. Please continue to let us know your feedback in the comments.

**Comment by adrianduffell** [comment] 2021-07-23 10:43
### Update

WooCommerce 5.5.2 has been released containing WooCommerce Admin 2.4.4 and the fix for this issue.

https://developer.woocommerce.com/2021/07/23/woocommerce-5-5-2-fix-release/

Once updated, previous workarounds should be removed.

I will now close this issue. Thanks again to everyone who provided workarounds and feedback.

**Closed by adrianduffell** 2021-07-23 10:43 UTC
Labels: impact: high, priority: critical, type: bug

**Comment by rickdroio** [comment] 2021-07-23 11:48
I just removed the workarounds... it works as expected now. Thanks!!!

**Comment by adrianduffell** [comment] 2021-07-24 03:15
I'm glad to hear that @rickdroio!

**Comment by Masque** [comment] 2021-07-26 18:09
Many thanks for this fix.

**Comment by adrianduffell** [comment] 2021-07-27 02:53
You're welcome @Masque 👍
