### ISSUE TITLE
Chips in table search component are broken

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/woocommerce-admin#4712] opened 2020-06-26 19:23 UTC
**Describe the bug**
The chips in the customer report are broken.

**To Reproduce**

1. Navigate to the customer report
2. Enter a search term
3. Note the remove button (x) in the search term is miss-aligned

**Expected behavior**
The remove button should be inline with the text in the chip

**Screenshots**

This bug is manifesting itself in all the other places that are using the search components, this screen shot is from the transaction table in wc-pay. 

![84506315-19cbca00-acb7-11ea-89c9-9528c30f35c5](https://user-images.githubusercontent.com/4500952/85893354-98406580-b7a7-11ea-94c0-b30489b7228f.png)

HT to @jrodger and @luizreis for bringing it to my attention

**Comment by timmyc** [comment] 2020-06-29 20:03
Thanks for the report @LevinMedia - looks like this might be a duplicate of #4648 and was fixed in #4651 - which will go out in 1.3/4.3

**Closed by timmyc** 2020-06-29 20:03 UTC
Labels: Components, Design, [Type] Bug
