### ISSUE TITLE
Sorting the Analytics product table by SKU makes all products disappear from table, showing "No data to display"

### ISSUE THREAD

**Issue by stevedeckert** [woocommerce/woocommerce-admin#8134] opened 2022-01-07 22:02 UTC
### Describe the bug
While on the WooCommerce Analytics Products page, sorting the results table by SKU makes all the products in the results table disappear and it shows "No data to display". The totals at the bottom still show the number of products that it should be displaying, and it still displays "Page 1 of 2". Sorting by any other column correctly shows the products, which all have SKUs.

### To Reproduce

1. Go to WooCommerce Admin > Analytics > Products
2. Select a start and end date that includes orders
3. Sort the results table by SKU

### Actual behavior:
The table displays "No data to display", shows totals at the bottom row, and displays pagination. No product data is shown in the table.

### Screenshots
![woo_analytics_sku_sort_bug](https://user-images.githubusercontent.com/7725938/148613148-203513ea-f33e-47a7-850b-c9ed3e59f2b2.gif)

### Expected behavior
The table should sort by SKU and continue to display product data

### Desktop (please complete the following information):

Confirmed twice:
* OS: MacOS
* Browser Safari
* Version 15.1

* OS: MacOS
* Browser Chrome
* Version 96.0.4664.93

### Additional context
https://woothemes.zendesk.com/agent/tickets/4665322

**Comment by moon0326** [comment] 2022-01-10 21:13
Thank you for taking the time to report the bug @stevedeckert.

Unfortunately, I wasn't able to reproduce it on my end.

I might have missed something. Could you please check my screencast? I tested with WooCommerce 6.0 (latest)

![Screen Capture on 2022-01-10 at 13-11-30](https://user-images.githubusercontent.com/4723145/148840174-21ae6f99-a44d-4030-82d7-19d24d52a201.gif)

**Comment by mattsherman** [comment] 2022-01-23 13:10
I too cannot reproduce this with WooCommerce 6.1.1.

I'm going to close this one as the linked ZD ticket also doesn't provide more information and was closed.

@stevedeckert If this issue crops up again, or you have additional information to help us track this down, please re-open this issue and let us know!

**Closed by mattsherman** 2022-01-23 13:10 UTC
Labels: needs feedback, Needs triage
