### ISSUE TITLE
WooCommerce Analytics > Stock showing stock in long decimalisation when using the Measurement Price Calculator.

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#7078] opened 2021-05-26 16:05 UTC
@stuartduff commented on [Wed May 26 2021](https://github.com/woocommerce/woocommerce/issues/29990)

**Reported in ticket:** 4020182-zen

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When using the Measurement Price Calculator plugin for WooCommerce to sell products ( Fabric ) in meters Analytics > Stock can show stock quantities like this example below.

![Screen Shot on 2021-05-26 at 15:10:16](https://user-images.githubusercontent.com/1190565/119674904-7f678680-be34-11eb-8b5f-163a9ef2fce8.png)

**Expected behavior**

We would expect to see the remaining stock quantity rounded up as is displayed on the product itself.

![Screen Shot on 2021-05-26 at 15:11:27](https://user-images.githubusercontent.com/1190565/119675141-b0e05200-be34-11eb-9657-5434a6c7f8c9.png)

**Actual behavior**
Instead, we see a long unrounded number when viewing Analytics > Stock like this below.

![Screen Shot on 2021-05-26 at 15:10:16](https://user-images.githubusercontent.com/1190565/119674904-7f678680-be34-11eb-8b5f-163a9ef2fce8.png)

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Install the [Measurement Price Calculator](https://woocommerce.com/products/measurement-price-calculator/) plugin.
2. Configure a product like within the screenshots provided below.
3. Purchase the product using a length of 3.35 Meters or similar.
4. View Analytics > Stock to see the issue.

**Screenshots**

Product > Measurement configuration. Make sure to enable the **Calculate inventory** checkbox.

![Screen Shot on 2021-05-26 at 15:15:45](https://user-images.githubusercontent.com/1190565/119675832-48de3b80-be35-11eb-8bb6-c70a3e3070b3.png)

Inventory tab configuration.

![Screen Shot on 2021-05-26 at 15:16:47](https://user-images.githubusercontent.com/1190565/119676010-6dd2ae80-be35-11eb-8e6f-a39a9a26df9e.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

The latest version of WordPress, WooCommerce, Measurement Price Calculator and Storefront.

---

@rodelgc commented on [Wed May 26 2021](https://github.com/woocommerce/woocommerce/issues/29990#issuecomment-848842659)

Hi @stuartduff,

Thank you for reporting the issue. Seems like this issue only happens in `Analytics > Stock` and not in `WP Admin > Products` page and customer pages. 

`Analytics` is being developed in another repository: [woocommerce-admin](https://github.com/woocommerce/woocommerce-admin).

I am going to move your bug report there so that the right team could take a look further.

**Comment by moon0326** [comment] 2021-06-02 21:02
Thank you @juliaamosova for taking the time to report this bug. We'll take a look at this as soon as possible.

**Comment by samueljseay** [comment] 2021-06-03 02:35
I'm not an expert here but my gut reaction is trying to fix this might be fraught. It might make sense to fix this case, but if you were dealing with some kind of plugin that dealt with quantities in different significant figures (maybe cryptocurrencies would be a good example), how would we know what rounding to display?

**Comment by ShaimaaElbanna** [comment] 2021-06-18 13:09
Hello,
I wanted to check if there is any update regarding this case as I was the one who first reported it to the plugin support and haven't heard about it so far.

**Comment by moon0326** [comment] 2021-06-30 17:34
> Hello,
> I wanted to check if there is any update regarding this case as I was the one who first reported it to the plugin support and haven't heard about it so far.

Sorry for the delay in response. Unfortunately, I wasn't able to reproduce it exactly how it is described.

I think one of your testing steps is missing.

I added a product with 40 stock then placed an order with 3.35 meters. I see the remaining stock as 36.35, which is correct.

I also placed a few more orders and now I see the stock as 32.3158 on both the frontend and backend.

Could you please provide the exact step to make the number 34.94999999999999999999?

**Comment by joshuatf** [comment] 2022-01-19 22:24
I'm closing this issue since it's over 6 months old, but if you still need help with this, @ShaimaaElbanna feel free to post back here with any more steps we can use to reproduce this and we can revisit this.

**Closed by joshuatf** 2022-01-19 22:24 UTC
Labels: type: bug, feature: analytics, priority: low, Needs triage
