### ISSUE TITLE
Infinite loop in RemoteInboxNotificationsEngine::run when update_option fails unexpectedly

### ISSUE THREAD

**Issue by ilyasfoo** [woocommerce/woocommerce-admin#6181] opened 2021-01-26 07:34 UTC
**Describe the bug**
The following is an excerpt from the investigation of issue https://github.com/woocommerce/woocommerce-admin/issues/6168 done by @moon0326:

1. [RemoteInboxNotificationsEngine](https://github.com/woocommerce/woocommerce-admin/blob/1ef907907d3f43930dfc13fdabe45c9bc5dfe24c/src/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php#L83) checks `wc_remote_inbox_notifications_specs` option value and see if it exists and has data.
2. If `wc_remote_inbox_notifications_specs` is empty or does not exist, [RemoteInboxNotificationsEngine](https://github.com/woocommerce/woocommerce-admin/blob/1ef907907d3f43930dfc13fdabe45c9bc5dfe24c/src/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php#L83) tries to fetch the data from its data sources and [update option](https://github.com/woocommerce/woocommerce-admin/blob/1ef907907d3f43930dfc13fdabe45c9bc5dfe24c/src/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php#L80) value and calls [RemoteInboxNotificationsEngine::run()](https://github.com/woocommerce/woocommerce-admin/blob/1ef907907d3f43930dfc13fdabe45c9bc5dfe24c/src/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php#L80) again.
3. The problem was that `update_option` never updated the option value because the data contained a Unicode and the `wp_options` table collation was `utf_general_ci`, but the function still returned true since the data was fetched successfully.
4. When [RemoteInboxNotificationsEngine::run() ](https://github.com/woocommerce/woocommerce-admin/blob/1ef907907d3f43930dfc13fdabe45c9bc5dfe24c/src/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php#L80) called again, it repeats the step 2 because the option value is still empty.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a fresh WordPress installation
2. Using a database manager (ex: phpmyadmin), connect to the database of your WordPress instance 
3. Edit `wp_options` table, set `option_value` collation to `utf8_general_ci`
4. Install & activate WooCommerce & WooCommerce Admin
5. In the WordPress instance, edit data source URL in WooCommerce Admin's [DataSourcePoller.php](https://github.com/woocommerce/woocommerce-admin/blob/main/src/RemoteInboxNotifications/DataSourcePoller.php#L17) from `https://woocommerce.com/wp-json/wccom/inbox-notifications/1.0/notifications.json` to `https://jsonkeeper.com/b/70K2` to simulate a unicode data from source
6. Create a new product and save
7. Observe the page will load indefinitely and may end up with timeout or other errors, depending on server configuration

If your local machine is running the WordPress instance, you might want to consider restarting php-fpm or apache service if the timeout/memory limit configuration is set generously   

**Expected outcome**
A good solution should provide an exit condition to `RemoteInboxNotificationsEngine::run()` so it will never run into an infinite loop. A simple one would be by adding a static variable that counts up to a limit and then will bail if it reaches it.

**Comment by ilyasfoo** [comment] 2021-03-28 23:34
Not stale bot, thank you

**Comment by Kataklizmic** [comment] 2021-10-23 00:38
According the [a comment](https://wordpress.org/support/topic/cannot-edit-pages-or-products-with-woocommerce-after-updates/#post-13963139) in [this support article](https://wordpress.org/support/topic/cannot-edit-pages-or-products-with-woocommerce-after-updates/#post-14998071), WooCommerce breaking the post & page editor is related to this issue. The issue has continued to occur for months.

The website this is happening for me with is [www.burninghotevents.com](https://www.burninghotevents.com)

**Comment by moon0326** [comment] 2022-01-18 21:50
I'm tempted to close this issue and the problematic unicode char has been removed and the issue is not reproducible anymore.

What do you think @ilyasfoo?

**Comment by ilyasfoo** [comment] 2022-01-19 01:07
@moon0326 Since the infinite loop can still be caused by external issues, I think we can add a guard condition, like a loop counter that will trigger exit once it's reached a limit.

**Comment by moon0326** [comment] 2022-01-19 02:27
> 

Sounds good. Let's leave it open.

**Comment by moon0326** [comment] 2022-01-19 02:29
> Since the infinite loop can still be caused by external issues, I think we can add a guard condition, like a loop counter that will trigger exit once it's reached a limit.

Sounds good. Let's leave it open 👍

**Comment by chihsuan** [comment] 2022-02-09 06:31
@ilyasfoo Looks like we've no longer called `RemoteInboxNotificationsEngine::run()` inside itself so it should not have an infinite loop. Is it okay to close this?

https://github.com/woocommerce/woocommerce-admin/blob/0f47b159d1b960e45066328e2dc0f966b4a12691/src/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php#L91-L103

**Comment by ilyasfoo** [comment] 2022-02-10 03:07
Yes, sounds good! Thanks for looking into it, @chihsuan!

**Comment by chihsuan** [comment] 2022-02-10 03:09
Thanks for confirming!

**Closed by chihsuan** 2022-02-10 03:09 UTC
Labels: type: bug
