### ISSUE TITLE
Private products not displayed in the Analytics Single Category report

### ISSUE THREAD

**Issue by dani-elo** [woocommerce/woocommerce-admin#6896] opened 2021-04-28 03:19 UTC
**Describe the bug**

Private products sales are not counted in the **Analytics > Categories > Single Category** report
**To Reproduce**

1. Create a product and set it as private. Add it to a new category
2. Create an order including that product.
3. Go to '**Analytics > Categories > Single Category**'
4. Select the category that includes the private product
5. There are no sells there

**Expected behavior**
The sales for that product should be there

**Screenshots**
Product: ![https://d.pr/i/lRG8BR](https://d.pr/i/lRG8BR+) 
Full Size: https://d.pr/i/lRG8BR

Single category report: ![https://d.pr/i/IK9wF5](https://d.pr/i/IK9wF5+) 
Full Size: https://d.pr/i/IK9wF5

**Additional context**
Sales for that product can be seen in the **Analytics > Product** report.
Product report: ![https://d.pr/i/5QH8M8](https://d.pr/i/5QH8M8+) 
Full Size: https://d.pr/i/5QH8M8

**Comment by dani-elo** [comment] 2021-04-28 03:19
Please notify this user when the issue gets fixed: 3933871-zen

**Comment by jeffstieler** [comment] 2021-05-18 16:10
I'm unable to reproduce this with both a private product and a password protetected one:

<img width="832" alt="Screen Shot 2021-05-18 at 12 06 52 PM" src="https://user-images.githubusercontent.com/63922/118686244-11cab300-b7c1-11eb-8d62-1f15fb801525.png">
<img width="832" alt="Screen Shot 2021-05-18 at 12 05 37" src="https://user-images.githubusercontent.com/63922/118686333-2313bf80-b7c1-11eb-9aef-5814db9fe2fb.jpg">

**Comment by louwie17** [comment] 2021-11-30 14:01
Closing this as there has been no feedback and no other issue's have come in, in relation to this issue.

**Closed by louwie17** 2021-11-30 14:01 UTC
Labels: type: bug, feature: analytics, needs feedback
