### ISSUE TITLE
Review the wcadmin_tasklist_task_completed event

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5994] opened 2021-01-04 11:53 UTC
As it was reported in the 4.8 early insights post (pbIJXs-vP-p2) we saw an increase in the % of users viewing the store setup tasks and in the % of users doing actions within each task, however the % of users completing the tasks decreased (wcadmin_tasklist_task_completed). This difference is a bit strange. 

As a follow up, I created a funnel to calculate the % of users that viewed the store setup tasks and triggered `wcadmin_product_add_publish` or `wcadmin_product_import_complete` vs the % of users that viewed the store setup tasks and triggered `wcadmin_tasklist_task_completed`with the add product task value. In theory the % should be similar, but the funnels show that 55% triggered that add product or the import product event and only ~34% triggered the add products task completion event.

It's important to validate if everything is working properly with the `wcadmin_tasklist_task_completed` event, `wcadmin_tasklist_task_completed` is one of the most important events that we track regarding new users. Is there anything that we could do to make sure that the event is working properly? Add e2e testing, improve the logic, etc

**Comment by joshuatf** [comment] 2021-01-04 18:57
There were some bugs found in https://github.com/woocommerce/woocommerce-admin/pull/5794 that may be related and I believe should be resolved by https://github.com/woocommerce/woocommerce-admin/pull/5941.

@pmcpinto Does this percentage discrepancy only occur in recent versions and looks closer in previous versions?

The other possibility here is that users are not visiting the homescreen after adding a product.  The homescreen task list will only track completed tasks after its been visited.  So if a user were to visit the homescreen, afterwards add a task, and then no revisit the homescreen, the track for the task completion would never get triggered.

**Comment by pmcpinto** [comment] 2021-01-05 10:33
> There were some bugs found in #5794 that may be related and I believe should be resolved by #5941.

Thanks for the heads up. This will be shipped in 4.9, correct?

> @pmcpinto Does this percentage discrepancy only occur in recent versions and looks closer in previous versions?

There's a similar discrepancy in a funnel that I created before the 4.8 release.

> The other possibility here is that users are not visiting the homescreen after adding a product. The homescreen task list will only track completed tasks after its been visited. So if a user were to visit the homescreen, afterwards add a task, and then no revisit the homescreen, the track for the task completion would never get triggered.

Good point. Let me create a funnel that includes visiting the home screen as a step after adding/importing products.

**Comment by pmcpinto** [comment] 2021-01-05 11:01
> Good point. Let me create a funnel that includes visiting the home screen as a step after adding/importing products.

So about 66% of users returned to the home screen within 3 days after adding/importing products. This is definitely having an impact on the discrepancy. We track completed tasks even if users only visit the home screen let's say 7 days after, right?

**Comment by samueljseay** [comment] 2021-01-15 02:15
> We track completed tasks even if users only visit the home screen let's say 7 days after, right?

I just checked this in the code, yes there is no limit on the time frame.

**Comment by samueljseay** [comment] 2021-01-19 00:18
What would you like to do as a follow up here @pmcpinto ?

**Comment by pmcpinto** [comment] 2021-01-19 10:21
@samueljseay `wcadmin_tasklist_task_completed` is one of the most important events that we track regarding new users. Is there anything that we could do to make sure that the event is working properly? Add e2e testing, improve the logic, etc

Where's the best place to check the existing logic?

**Comment by louwie17** [comment] 2021-01-26 15:11
> Where's the best place to check the existing logic?

Each task has it's own `completed` logic [defined here](https://github.com/woocommerce/woocommerce-admin/blob/main/client/task-list/tasks.js#L138), and search `completed` to see each one.

The `wcadmin_tasklist_task_completed` gets triggered when we update the `woocommerce_task_list_tracked_completed_tasks` option. This gets updated in the task list component, which seems to check this quite regularly (too much even, in my opinion), just on the homescreen.
So if the user does do an import, or create a product, they would have to return to the homescreen for the tracks to be triggered.
The logic is: get all the task items, and see which one's are set to `completed`, check the difference with `woocommerce_task_list_tracked_completed_tasks` option, and if they are different update it.

Given it took me a little while to piece all of this together, we probably want to consolidate some of this logic, which hopefully will also make it more reliable (if the issue is with the `tasklist_task_completed` track event).

**Comment by joshuatf** [comment] 2021-01-28 21:12
Estimate: 3

I'm still not certain that anything is "broken" here, but some refactoring may be worthwhile as well as investigation into why the stats aren't reaching expectations.

**Comment by timmyc** [comment] 2021-01-30 00:45
Per discussion in the sprint planning hangout today, we are going to go back to the drawing board a bit on this issue. Removing from this cycle.

**Comment by joelclimbsthings** [comment] 2022-03-02 00:53
Closing this in favor of more recent discussions on the topic:

p90Yrv-2CH-p2
p90Yrv-2O7-p2

**Closed by joelclimbsthings** 2022-03-02 00:53 UTC
Labels: needs design, feature: onboarding, Needs triage
