### ISSUE TITLE
Jetpack 404 on connection

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#4399] opened 2020-05-19 17:57 UTC
**Describe the bug**
When attempting to walk through the profiler and redirect to the Jetpack connection flow, the connection flow occassionally gets stuck on the Jetpack screen with a `404` or other error.

Upon refresh, the error is resolved and the page is redirected to WordPress.com to finish the connection.

This seems to mostly happen on JN or ephemeral sites and may be a race condition due to installing Jetpack and immediately attempting to connect after installation is complete.  There may be a race condition occurring where Jetpack has not fully initialized and prevents the redirect to wpcom.

This may be a problem that needs to be resolved in Jetpack, but further investigation is required.a

**To Reproduce**

Note that you may need to do this quickly or on a slower server to reproduce.

1. On a new (non-local) site without Jetpack installed, walk through the onboarding profiler.
1. Click "Yes please" on the final step to redirect to the Jetpack flow.
1. Note that you land on the Jetpack screen with an error.

**Expected behavior**
Expected to get redirected directly to connect my site.

**Screenshots**
<img width="670" alt="Screen Shot 2020-05-19 at 8 10 47 PM" src="https://user-images.githubusercontent.com/10561050/82361217-3b68c700-9a13-11ea-9ccc-e34b70db2a4b.png">
<img width="865" alt="Screen Shot 2020-05-19 at 7 44 15 PM" src="https://user-images.githubusercontent.com/10561050/82361232-3d328a80-9a13-11ea-85f6-7bb04a808ab6.png">

**Comment by becdetat** [comment] 2020-05-20 02:13
In Jetpack the error `Verification secrets not found` happens in either https://github.com/Automattic/jetpack/blob/master/class.jetpack.php#L5402 or possibly https://github.com/Automattic/jetpack-connection/blob/master/src/class-manager.php#L1443

The cause of the error being generated is that the `jetpack_authorize_$user_id` option isn't present, which could be because the plugin isn't fully activated before hitting the connect step, but I can't see how that would be possible.

I also couldn't reproduce this on an ephemeral site.

**Comment by timmyc** [comment] 2020-08-25 21:31
Since we haven't seen further reports of this, I'm going to close this out. Side-note, wondering if this may be related to Jurassic Ninja reloading itself.

**Closed by timmyc** 2020-08-25 21:31 UTC
Labels: Onboarding, [Priority] High, [Type] Bug
