### ISSUE TITLE
Onboarding - store profiler: unable to proceed in the Theme selector step with an active theme

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3460] opened 2019-12-20 16:18 UTC
It seems that in some cases the users are not able to proceed in the Theme selector step when they already have an active theme using a Jurassic ninja site. I wasn't able to replicate this error. More info here pb22l9-5T-p2 (comment 236) and here pb22l9-5F-p2 (comment 264)

**Comment by timmyc** [comment] 2019-12-23 18:17
I was not able to reproduce this bug. @pmcpinto should we add a "Skip this step" button to this page just as a safe-guard?

**Comment by pmcpinto** [comment] 2019-12-23 18:41
@timmyc a couple of days ago I created an issue about this (#3450). The only concern that I have from implementing the "skip this step" right away is that if the user skips it without having any theme installed we should extend the task list to include a new step to install a theme.

Maybe we can implement the skip the step for the first release and then implement the new task to cover the theme install flow in phase 2. What do you think?

**Comment by timmyc** [comment] 2019-12-23 19:04
Well I had a local test site where this bug was happening, but now it is working again.

> The only concern that I have from implementing the "skip this step" right away is that if the user skips it without having any theme installed we should extend the task list to include a new step to install a theme.

I think that is a fair concern, but I also fear people being trapped in this step if something goes sideways.

Granted I'm really having a hard time reproducing the bug, have just tried on 2 more clean installs on different hosts.

**Comment by pmcpinto** [comment] 2019-12-26 11:30
Can we display the "skip this step" link just upon verifying if the user has a theme installed? Or is it going to overcomplicate the logic?

**Comment by timmyc** [comment] 2019-12-27 17:12
> Can we display the "skip this step" link just upon verifying if the user has a theme installed? Or is it going to overcomplicate the logic?

I think that should be manageable @pmcpinto - but to clarify we can show "skip this step" if a theme is installed/active that has woocommerce support? Because a theme is going to be installed/active no matter what.

**Comment by pmcpinto** [comment] 2019-12-27 17:38
> but to clarify we can show "skip this step" if a theme is installed/active that has woocommerce support?

Ok, that seems to be a great solution. Ideally we should add event tracking to that link. Do you want me to open a new issue about that?

**Comment by timmyc** [comment] 2019-12-27 17:48
Nope I'll just revise this issue since we can not always reproduce this bug. Thanks @pmcpinto for the feedback here.

**Comment by vedanshujain** [comment] 2020-01-21 10:19
Note: This is happening with WC 3.9 RC4 on Bluehost account. Not seeing a link to skip the step.

**Comment by pmcpinto** [comment] 2020-01-21 10:42
@timmyc I updated the wc-admin version to 0.24.0 in bluehost but I'm not seeing the "skip this step" link. Also:

- When I click to proceed with the installed theme I'm getting this error message: The requested theme `avada` could not be installed. Theme API call failed.
- With a free them I'm getting this error message: Invalid theme.
- With a paid theme it displays the purchase & install modal as expected

Do you want me to open a new issue about this or maybe reopen this one?

**Comment by juliaamosova** [comment] 2020-04-20 20:51
Another occurrence of not being able to proceed with the active theme. Ref: pb22l9-8V-p2#comment-395. 

Quoting Austin L. who tested WC 4.1 beta.2 on JN site (via reference above):

>Two times during the theme selection process in setting up my store, I tried to select Continue with my active theme for Twenty Twenty and the barber poll progress bar just kept scrolling and scrolling for minutes before activating. This wasn’t the case for the .zip file upload or selecting Storefront theme. The first time it happened I thought it was a fluke, then when it happened again during another store onboarding process, I thought I should flag.

**Comment by timmyc** [comment] 2020-08-05 23:21
I think the most recent report of this bug ( yowza in April ) is due to the known issue with JN sites throwing errors when the webserver reloads when another user is setting up a new site. So closing this out.

**Closed by timmyc** 2020-08-05 23:21 UTC
Labels: Onboarding, [Type] Bug
