### ISSUE TITLE
Inconsistent data on the Payments task

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5602] opened 2020-11-11 18:04 UTC
I was checking the setup tasks events, completions rate, etc after the 4.6 release and I noticed something strange:

- There's an increase in the `wcadmin_tasklist_task_completed` event, which was expected as we started auto-completing shipping and taxes in some use cases. But then I segmented by `task_name` and I noticed a spike in the Payments value.
- I then took a look at the events that we track within the payments task (`wcadmin_task_view`, `wcadmin_tasklist_payment_setup`, `wcadmin_tasklist_payment_connect_method`) and the numbers are going in the opposite direction (dropping).
- I created a funnel to check the % of task list views that originated a payments task view before/after 4.6 and it was possible to see a drop in the conv. rate after 4.6
- There's a similar drop in the Add product task views %.
- Curiously all the `Customize Appearance` events started increasing after 4.6

I already considered several options:
- There's a problem with tracking
- We introduced a regression and we're not showing some tasks in some countries: this doesn't seem likely as the payments task view conv. dropped in all the countries
- Users are seeing the inbox notifications to review the shipping and taxes smart defaults and get distracted after being redirected to the shipping or tax settings: I'm not seeing significant differences in the shipping and taxes settings views
- Some hosting company removed some tasks from the setup task list: it would be a bit weird for a hosting company to just remove one task.

After pondering around a bit more here's what I think is happening:
- We have a problem with Tracks due to the mismatch between task completion and all the other events in the payments task
- The shipping and tax smart defaults are causing an unexpected distraction due to the following: when we reorganized the task list in August (placing the payments task right after the add products and the customize appearance task at the bottom) we saw immediately an increase in the activity within the payments task and a decrease in the personalize my store. Mainly because personalize my store is kind of out of sight: https://d.pr/i/EzmmU5. But now when the Shipping and Tax tasks are auto-completed the personalize my store task is right below the add products and payments task, diverging users from those two tasks: https://d.pr/i/WZ6xSi 
The only way that I'm seeing to validate this 2nd hypothesis is by revert the smart defaults implementation

**Comment by pmcpinto** [comment] 2020-11-11 18:04
cc @timmyc

**Comment by timmyc** [comment] 2020-11-11 19:23
Just adding a few notes here.

- `wcadmin_tasklist_task_completed` tracks are handled server-side [here](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Features/OnboardingTasks.php#L373-L381). The method is fired off whenever the `woocommerce_task_list_tracked_completed_tasks` site option is either added or updated [#](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Features/OnboardingTasks.php#L46-L47)
- The only place in wc-admin where this site option gets added or updated is in the [task list component itself](https://github.com/woocommerce/woocommerce-admin/blob/main/client/task-list/index.js#L93-L102)
- The logic that updates this option client side is triggered by React lifecycle methods, first in [componentDidMount](https://github.com/woocommerce/woocommerce-admin/blob/main/client/task-list/index.js#L52) and again in [componentDidUpdate](https://github.com/woocommerce/woocommerce-admin/blob/main/client/task-list/index.js#L67). Could there be a possibility that the state in the component could result in repeated update scenarios that could result in multiple tracks being recorded?

In a cursory Git Blame check of the above code paths, I don't see any recent changes in those exact areas that stick out as a possible source of any change... but the tracking being tied to lifecycle events could mean that any other changes within that component, and its tree, could perhaps cause some sort of regression.

> I then took a look at the events that we track within the payments task (wcadmin_task_view, wcadmin_tasklist_payment_setup, wcadmin_tasklist_payment_connect_method) and the numbers are going in the opposite direction (dropping).

How big of a drop off are we seeing of the tracks inside the payment task Pedro? On that same note, can we pull a similar set of data to see if tracks related to setting up WCPay have increased at about the same amount? I'm still wondering if this is at all related to us replacing the Payments Task with WCPay when it has been installed. If users go through that flow, they will never have a chance to do any of the tracked tasks within the payment step since they are whisked away to the WC Pay KYC flow.

**Comment by pmcpinto** [comment] 2020-11-12 12:36
> How big of a drop off are we seeing of the tracks inside the payment task Pedro?

About 30%

> On that same note, can we pull a similar set of data to see if tracks related to setting up WCPay have increased at about the same amount? 

The number of people installing the bundle on a daily basis remains fairly the same

**Comment by samueljseay** [comment] 2020-11-16 08:56
@pmcpinto I'm just reading through your hypotheses and wondering if there are specific actions to take here.

The first thing I looked at was the payment tracking and at least in local development all the tracks for individual payment tasks happen reliably.

> We have a problem with Tracks due to the mismatch between task completion and all the other events in the payments task

What are you saying here exactly? That we don't really define this task as complete? If thats what you mean I do think that is true. For example if you choose the manual payment method toggle we don't record a task complete event of any kind. In the task list it is considered complete at that stage, but no track is recorded to indicate that. I kind of think we'd need to change the UI here maybe to have a "finish" point, like have a "finish" button that we can record the completion? Thats very naive and it doesn't seem very useful to the user.

> The only way that I'm seeing to validate this 2nd hypothesis is by revert the smart defaults implementation

Do you want to do this? To me this seems like the only logical step forward here, even if I'd rather not undo the work 😄

**Comment by pmcpinto** [comment] 2020-11-16 12:01
@samueljseay thanks for your feedback.

> What are you saying here exactly? That we don't really define this task as complete? If thats what you mean I do think that is true. For example if you choose the manual payment method toggle we don't record a task complete event of any kind. In the task list it is considered complete at that stage, but no track is recorded to indicate that. I kind of think we'd need to change the UI here maybe to have a "finish" point, like have a "finish" button that we can record the completion? Thats very naive and it doesn't seem very useful to the user.

I'm saying it's weird to see the Payments task completion event going up while all the other events decreased. When is the `wcadmin_tasklist_task_completed` event with the `task_name`: `Payments` triggered?

> Do you want to do this? To me this seems like the only logical step forward here, even if I'd rather not undo the work 😄

Yes, I think it's the only option we have 😟

**Comment by samueljseay** [comment] 2020-11-18 00:42
Summarising the decided actions:

We haven't found a good convincing reason why this is happening, therefore the best path forward is to attempt a revert of the smart defaults functionality. It is a bit of a guess at this stage if its the cause but we don't have other ideas. We'll revert the smart defaults work then see if the data normalises afterwards.

**Comment by timmyc** [comment] 2020-11-18 01:24
Quick note to document some of my testing on this today. I did two JN sites, one was doing the bundled extensions flow using US/Fashion, the other was doing a non-bundled flow, but JP connected.

I tried to get the bundled flow with WCPay being shown to do odd things - including setting up payment methods outside of the context of the setup checklist, but that route seems really sound in not being a contributor to this data discrepancy.

The second scenario though, so the Payments task that is shown to most users does have a possible scenario where the payments task could be marked as complete/and track recorded accordingly, without ever viewing the payment task. The flow is as follows:

- *With the Setup Checklist enabled/active and not hidden*
- Setup a payment method via WooCommerce > Settings, does not matter, just any old method will do
- Then visit the home screen, and note the Payment task is marked as complete. This is because the "done" state of this task looks to see if any payment methods are active, if so, the task is marked as done and the [logic that watches the task list done option](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Features/OnboardingTasks.php#L373-L381) takes over and does its thing to record the track.

This code though has been in place since March of this year, so it being the likely culprit behind this change seems unlikely to me. I did also mention that pretty much all online support documentation around Woo, and setting up payment types, all point towards WooCommerce > Settings, so I'm certain some users opt to setup payments in this manner.

The only other odd idea I was wondering is if perhaps a hosting provider out there configures some payment methods by default for users. If we could compile a list of sites that this flow has happened on, we could dive into those tracks a bit deeper and see if there is some other pattern that emerges around hosting, or locale perhaps. @pmcpinto do you have a way of creating this "odd" funnel in tracks and pulling a list of site IDs to work from?

**Closed** 2020-11-25 02:09 UTC
