### ISSUE TITLE
[WC 4.6 RC1] Upgrade from WC 4.5.2 to WC 4.6 RC1 doesn't seem to work correctly

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#5269] opened 2020-10-05 13:56 UTC
**Describe the bug**

The upgrade from WC 4.5.2 to WC 4.6 RC1 doesn't seem to work correctly. I tested it twice on different brand new JN sites and got the same result both times.

**To Reproduce**

1. Crete a brand new JN site.
2. Add WooCommerce by searching the plugin directory within the site (`Plugins` section in the sidebar). 
3. Install and activate WooCommere (should be 4.5.2)
4. The OBW will start as soon as you activate WooCommerce. Select to skip the Setup Wizard so that you could go through the wizard when you switch to 4.6 RC1. 
5. Look for WooCommerce Beta Tester plugin in the plugins directory (through (`Plugins` section in the sidebar).
6. Install and activate the WooCommere Beta Tester plugin. 
7. Switch WooCommerce version from 4.5.2 to 4.6 RC1 using the WooCommerce Beta Tester plugin. 
8. You will see that no onboarding is starting and I am getting redirected to Home Screen where I see no tasks to complete (it looks as they are already completed):

<img width="1434" alt="Screen Shot 2020-10-02 at 6 09 34 PM" src="https://user-images.githubusercontent.com/19143190/95087754-150ca500-06f0-11eb-882d-e1d7407bd490.png">

9. Enable OBW by clicking on `Help` in the top right corner. Select Setup Wizard/Enable. 
10. OBW starts, but when it gets to the Product Types section, I am seeing the following (reproduced it twice on different sites to make sure it is not a fluke):

<img width="1433" alt="Screen Shot 2020-10-02 at 6 17 25 PM" src="https://user-images.githubusercontent.com/19143190/95087984-5ac96d80-06f0-11eb-9d84-da755e60e28a.png">

11. Continue button here is non-clickable so can’t move on any further.

**Expected behavior**

In step 8 of the reproduction steps, I expected to see a clear way for me to get back to onboarding. I think it should not start automatically on the switch but it should be clear where to activate it. Customers don't know that they heed to click on  `Help` or that they need to complete onboarding at all. There are also no Home Screen tasks that I expected to see after the switch since the user did not complete any of the setup steps before switching from 4.5.2 to 4.6 RC1. 

**Screenshots**

See above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.6
* Browser: Chrome
* Version: 85.0.4183.121 (Official Build) (64-bit)

**Additional context**

N/A. 

<hr>

cc @pmcpinto

**Comment by timmyc** [comment] 2020-10-06 16:23
@juliaamosova and @tammullen thanks for all the details here. I'm trying to determine the severity of this bug right now, and while I totally understand that it impacts our test flows for manual testing ( GlobalStep internal etc ) which flows above are likely to be hit by real-world users?

The removal of the legacy OBW from woocommerce/woocommerce, and the supporting alerts is the root cause of much of the above so really wondering if the "easy way out" of all of this - if we deem these flows critical enough - is to revert the PR that removed/deprecated the code there. cc @rodrigoprimo

**Comment by timmyc** [comment] 2020-10-06 23:56
One more aside here, if the primary impact of these flows is our manual testing, we could also just add the test step of going to the Orders Listing page, and launching the OBW via the Help tab there.

**Comment by tammullen** [comment] 2020-10-07 10:23
@timmyc I agree the change in behaviour in not launching the OBW for beta tester wouldn't be critical if it is only affecting beta tester which I think so far seems to be the case from the flows I tested above.

> The removal of the legacy OBW from woocommerce/woocommerce, and the supporting alerts is the root cause of much of the above so really wondering if the "easy way out" of all of this - if we deem these flows critical enough - is to revert the PR that removed/deprecated the code there.

If the `Continue Store Setup` prompt is fixed in https://github.com/woocommerce/woocommerce-admin/issues/5251 I think this can replace the the alerts that have been removed. Although the `Continue Store Setup` only seems to appear on completely new installs and not when the OBW was skipped in an earlier version then upgraded to 4.6 (Which I guess makes sense as the new prompt is only going to be there from 4.6 onwards).

Elsewhere e.g for this https://github.com/woocommerce/woocommerce/issues/27770 it has been decided the expected behaviour should be only applying to brand new installs so maybe that is the same for this.

> One more aside here, if the primary impact of these flows is our manual testing, we could also just add the test step of going to the Orders Listing page, and launching the OBW via the Help tab there.

This results in the problem in step 10) of the original issue. I have confirmed this also happens **without Beta tester** using a snippet to simulate the upgrade prompt in plugins to go from 4.5.2 to 4.6.0. I tested using a US store address.

![Screenshot 2020-10-07 at 11 22 33](https://user-images.githubusercontent.com/24649833/95319168-74ed8200-088f-11eb-89ce-73ad8cbfb0b0.png)

**Comment by joshuatf** [comment] 2020-10-07 18:42
This issue has more to do with how "Skipping" is handled than removal of the old onboarding or updates in WC 4.6.  For some background on how skipping the onboarding flow works, when a user opts to skip onboarding, 2 things happen:

* The onboarding profiler (setup wizard) is marked as skipped.  In newer versions of WCA, the profiler can still be visited, but no links directly to this exist outside of the Help tab.
* The task list is marked as hidden.  This was an intentional decision since the user wanted to skip onboarding, they should not be shown the onboarding task list.

I do agree with @timmyc that if the primary concern is beta testing here, then using the "Help" tab is the correct choice.  If we're concerned that there are enough users skipping and we want to nudge them to do the onboarding, we could try an inbox notification to remind them to complete this.

We could also retroactively enable the wizard or unhide the task list during upgrade if no other onboarding information was collected, however, I imagine this might be a little frustrating to users who genuinely wanted to skip the process.

**Comment by tammullen** [comment] 2020-10-07 19:05
Thanks @joshuatf for the extra context.

> I do agree with @timmyc that if the primary concern is beta testing here, then using the "Help" tab is the correct choice.

Doing this gives the issue with the `3) Product Types` screen above. We have only reproduced it with an upgrade to 4.6, not with a fresh install. Should we move it into a separate issue?

**Comment by joshuatf** [comment] 2020-10-07 19:10
I do see the error in step 10 on the product types step.  It seems some of the data needed for that step is not passed to the server when onboarding has been disabled.  

We'll still need this data in the event the onboarding is directly visited as it is in testing; working on a fix for that now.

**Closed** 2020-10-09 00:10 UTC
