### ISSUE TITLE
Selects go over the breadcrumb on order page

### ISSUE THREAD

**Issue by dimitriBouteille** [woocommerce/woocommerce-admin#4163] opened 2020-04-19 00:30 UTC
**Describe the bug**
Style problem : Selects go over the breadcrumb

**To Reproduce**
Go order page

**Screenshots**
![woocommerce](https://user-images.githubusercontent.com/34821762/79674607-12230400-81e5-11ea-9159-ee1f8de457d0.PNG)

**WordPress Environment**
<details>
```
Version 4.0.1
```
</details>

**Comment by jeffstieler** [comment] 2020-07-21 20:00
Hello @dimitriBouteille,

Are you still experiencing this issue? I was unable to reproduce it.

If you are, can you provide use with your browser information and the system report from WooCommerce > Status > Get Status Report? Thank you!

**Comment by dimitriBouteille** [comment] 2020-07-21 21:12
Hi  @jeffstieler ,

The bug still exists even with the new version of Woocommerce ... I’m on Chrome (v84.0.4147.89)

![bug](https://user-images.githubusercontent.com/34821762/88107454-630d1480-cba7-11ea-9ab0-090817ec1ee3.PNG)

Here is the Woocommerce report: 

```
### WordPress Environment ###

WordPress address (URL): [private]
Site address (URL): [private]
WC Version: 4.3.0
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.3.0
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.37 (Win64) PHP/7.2.14
PHP Version: 7.2.14
PHP Post Max Size: 1 TB
PHP Time Limit: 120
PHP Max Input Vars: 2500
cURL Version: 7.61.1
OpenSSL/1.1.1a

SUHOSIN Installed: –
MySQL Version: 5.7.24
Max Upload Size: 147 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.0
WC Database Prefix: eol_wp_659efe
Taille totale de la base de données: 0.76MB
Taille de la base de données: 0.52MB
Taille de l’index: 0.24MB
eol_wp_659efewoocommerce_sessions: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efewoocommerce_api_keys: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efewoocommerce_attribute_taxonomies: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efewoocommerce_downloadable_product_permissions: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efewoocommerce_order_items: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efewoocommerce_order_itemmeta: Données : 0.01MB + Index : 0.01MB + Moteur MyISAM
eol_wp_659efewoocommerce_tax_rates: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efewoocommerce_tax_rate_locations: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efewoocommerce_shipping_zones: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efewoocommerce_shipping_zone_locations: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efewoocommerce_shipping_zone_methods: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efewoocommerce_payment_tokens: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efewoocommerce_payment_tokenmeta: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efewoocommerce_log: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efeactionscheduler_actions: Données : 0.01MB + Index : 0.02MB + Moteur MyISAM
eol_wp_659efeactionscheduler_claims: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efeactionscheduler_groups: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
eol_wp_659efeactionscheduler_logs: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efecommentmeta: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efecomments: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
eol_wp_659efeeol_registration_order: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efelinks: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efeoptions: Données : 0.41MB + Index : 0.03MB + Moteur MyISAM
eol_wp_659efepostmeta: Données : 0.05MB + Index : 0.05MB + Moteur MyISAM
eol_wp_659efeposts: Données : 0.04MB + Index : 0.02MB + Moteur MyISAM
eol_wp_659efepost_files: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efetermmeta: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
eol_wp_659efeterms: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
eol_wp_659efeterm_relationships: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efeterm_taxonomy: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efeusermeta: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
eol_wp_659efeusers: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
eol_wp_659efewc_admin_notes: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efewc_admin_note_actions: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efewc_category_lookup: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efewc_customer_lookup: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
eol_wp_659efewc_download_log: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efewc_order_coupon_lookup: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efewc_order_product_lookup: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
eol_wp_659efewc_order_stats: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
eol_wp_659efewc_order_tax_lookup: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efewc_product_meta_lookup: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
eol_wp_659efewc_reserved_stock: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
eol_wp_659efewc_tax_rate_classes: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
eol_wp_659efewc_webhooks: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM

### Post Type Counts ###

attachment: 5
customize_changeset: 2
nav_menu_item: 5
page: 8
post: 1
product: 9
registration: 13
registration_cat: 13
revision: 10
shop_order: 13

### Security ###

Secure connection (HTTPS): ❌
					Votre boutique n’utilise pas HTTPS. En savoir plus sur HTTPS et les certificats SSL.
Hide errors from visitors: ❌Les messages d’erreur ne doivent pas s’afficher aux visiteurs.

### Active Plugins (1) ###

WooCommerce: par Automattic – 4.3.0

### Inactive Plugins (0) ###


### Must Use Plugins (4) ###

Bedrock Autoloader: par Roots – 1.0.1
Disallow Indexing: par Roots – 1.0.0
Eol - Administration: par Dimitri BOUTEILLE – 1.0.0
Register Theme Directory: par Roots – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la boutique: #85 - /boutique/
Panier: #86 - /panier/
Commander: #87 - /commander/
Mon compte: #88 - /mon-compte/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: [private]
Version: 1.0
Author URL: https://www.dimitri-bouteille.fr
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Terminé: 24
Oldest: 2020-07-09 23:01:25 +0200
Newest: 2020-07-21 22:58:54 +0200

En attente: 1
Oldest: 2020-07-22 13:26:17 +0200
Newest: 2020-07-22 13:26:17 +0200
```

**Comment by timmyc** [comment] 2020-08-25 21:16
<img width="945" alt="image" src="https://user-images.githubusercontent.com/22080/91228688-87479e00-e6dd-11ea-8df8-aece2f95dfa4.png">

I'm not able to reproduce this either so I'm going to close this out.

**Closed by timmyc** 2020-08-25 21:16 UTC
Labels: Good First Issue, [Status] Needs feedback, [Type] Bug
