### ISSUE TITLE
Reviews Not Showing in Reviews Tab

### ISSUE THREAD

**Issue by EricaKuschel** [woocommerce/woocommerce-admin#2795] opened 2019-08-14 21:26 UTC
**Describe the bug**

Reviews showing on Comments page, but nothing shows when clicking on the Reviews Star from WC Admin. Was able to verify this was the case on my test site.

**To Reproduce**

1. Create a review. 
2. Go to WooCommerce Settings page (or any page that WooCommerce Admin shows up on)
3. Select star/Reviews from the menu at the top of the screen.
4. See window stating that there are no comments to be reviewed.

**Expected behavior**
The reviews found in the Comments page would show up in the window.

**Screenshots**
![image](https://user-images.githubusercontent.com/6961918/63057022-ed84c880-beae-11e9-85eb-6dc7b25cfb35.png)

![image](https://user-images.githubusercontent.com/6961918/63057046-f4abd680-beae-11e9-9c4d-b9b84a1d406f.png)

![image](https://user-images.githubusercontent.com/6961918/63057276-7dc30d80-beaf-11e9-9536-bbea1a5d71cb.png)

**Desktop (please complete the following information):**

* OS: Sierra - 10.12.6
* Browser Chrome
* Version Version 76.0.3809.100 (Official Build) (64-bit)

**Additional context**
Had the following active: 

WC Version: 3.7.0

### Active Plugins (3) ###

WooCommerce Admin: by WooCommerce – 0.16.0 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.2.3 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.7.0

**Comment by psealock** [comment] 2019-08-16 03:54
Thanks for the bug report @EricaKuschel 

I have the same setup and can't reproduce the bug. When I create a comment (approved or unapproved) I get the notice in the "Reviews" activity panel. 

Anyone else able to reproduce?

**Comment by psealock** [comment] 2019-08-28 23:32
Wow, nice find @cojennin! Thanks for the detailed write up too. I'll see if we can address this in the next sprint.

**Comment by rrennick** [comment] 2019-10-21 20:02
There are 3 comment enabled states
- Disabled
- Unmoderated
- Moderated

If comments are disabled the panel should show a message indicating that and include a link/instructions on enabling them.

If comments are unmoderated then the panel should load reviews if they exist.

The current logic works for moderated comments except for the setting flag calculation.

**Comment by joshuatf** [comment] 2019-11-26 10:12
>If comments are disabled the panel should show a message indicating that and include a link/instructions on enabling them.

Great idea.

>If comments are unmoderated then the panel should load reviews if they exist.

I'm wondering if we should show all reviews when moderation is not active or also display a similar message to the one above to enable moderation.  Since the activity panel is meant to be more "actionable" items (like orders that need an action, stock that is low, or reviews that need moderation), I feel it may be more in the nature of this component to limit these to only items that need moderation.

What do you think @rrennick?

**Comment by joshuatf** [comment] 2019-11-26 10:51
Also, the "Reviews" is hidden when reviews are disabled.  Are we want to unhide this and display the message to enable instead?  /cc @rrennick @Aljullu

**Comment by rrennick** [comment] 2019-11-26 11:54
> I feel it may be more in the nature of this component to limit these to only items that need moderation.

I agree. From #3276, we are going to need to make the activity panel header more conditional. It's probably best to wait until #3203 lands before starting that. This could be done at the same time.

**Comment by rrennick** [comment] 2019-11-26 11:57
> Are we want to unhide this and display the message to enable instead?

Would this be better as a notice on the Analytics settings screen?

**Comment by joshuatf** [comment] 2019-11-27 03:21
>I agree. From #3276, we are going to need to make the activity panel header more conditional. It's probably best to wait until #3203 lands before starting that. This could be done at the same time.

It does look like there's some overlap with #3203 that would make rebasing a bit more challenging.  Will unassign and we can wait for that PR to be merged in.

>Would this be better as a notice on the Analytics settings screen?

I think that's a good option if we have an "Activity Panels" section in the settings page, but otherwise it feels a little out place to me.

Since disabling reviews is not the default setting, I would think if someone had opted to disable reviews, they wouldn't expect to see a "Reviews" activity panel.

Open to opinions here though.

**Comment by jeffstieler** [comment] 2019-12-20 16:00
I'm going to remove the check for `commentModeration` from the `getUnapprovedReviews` selector because:
1. You can still have previously unapproved/pending reviews if comment moderation is turned off
1. Turning off comments doesn't turn off the ability to review products

**Comment by joshuatf** [comment] 2019-12-23 07:59
@jeffstieler I think https://github.com/woocommerce/woocommerce-admin/pull/3459 solves part of this issue, but doesn't solve the confusion for some users.

Do you think we should update the message for an empty state Reviews to inform users that comment moderation may be turned off?  Or do you think this is a non-issue.

**Comment by jeffstieler** [comment] 2019-12-23 21:28
> Do you think we should update the message for an empty state Reviews to inform users that comment moderation may be turned off? Or do you think this is a non-issue.

The change in #3459 removes the coupling of the reviews panel to the comment moderation settings, so I don't think we should mention those settings.

**Comment by joshuatf** [comment] 2019-12-24 03:34
@jeffstieler #3459 appears to show comments that require moderation regardless of the current comment moderation setting being on or off, is that right?

That solves part of this issue, but the other piece is helping to solve confusion for users not realizing that comment moderation is off and that this tab does not show all comments. (See the original comment for an example of this).

I think if you read the message carefully and have a good understanding of WooCommerce it's possible to figure out that only reviews needing moderation will show up here.  But based on our discussion above, a very explicit message telling users that they won't receive future reviews here since comment moderation is off (and providing a link to turn that on if they choose), would prevent confusion.

<img width="512" alt="Screen Shot 2019-12-24 at 11 27 47 AM" src="https://user-images.githubusercontent.com/10561050/71391873-f184dc00-2640-11ea-8ef7-8e1f9d628bf5.png">

**Comment by jeffstieler** [comment] 2020-01-02 15:21
> #3459 appears to show comments that require moderation regardless of the current comment moderation setting being on or off, is that right?

That is correct.

> I think if you read the message carefully and have a good understanding of WooCommerce it's possible to figure out that only reviews needing moderation will show up here. But based on our discussion above, a very explicit message telling users that they won't receive future reviews here since comment moderation is off (and providing a link to turn that on if they choose), would prevent confusion.

Gotcha. I'll test to see what different combinations of comment and review settings produce different moderation scenarios and will come up with alternate copy for that message based on the current settings (when there are no pending reviews).

**Comment by jeffstieler** [comment] 2020-01-02 16:04
> they won't receive future reviews here since comment moderation is off

In testing, I've come to realize that comment moderation can't really be turned off wholesale. Even with "comments must be manually approved" disabled, a comment can end up in the moderation queue by:

* The author not having a previously approved comment (and that setting enabled)
* The comment containing X or more links (another setting)
* The comment containing one or more specified words

Perhaps we can just change the message (for all scenarios) to mention moderation settings if the user was expecting to see reviews?

Something like:

> **You have no reviews to moderate**
> 
> Awesome, you've moderated all of your product reviews. How about responding to some of those negative reviews? Check your discussion settings if you expected to see reviews here.
>
> [View all reviews]    [Discussion settings]

**Comment by joshuatf** [comment] 2020-01-09 13:39
>Perhaps we can just change the message (for all scenarios) to mention moderation settings if the user was expecting to see reviews?

I think this is a great way to handle it.

**Comment by psealock** [comment] 2020-06-30 04:59
Fixed in https://github.com/woocommerce/woocommerce-admin/pull/3459

**Closed by psealock** 2020-06-30 04:59 UTC
Labels: Activity Panel, [Many] Medium, [Much] Medium, [Priority] High, [Type] Bug
