### ISSUE TITLE
Home Screen layout should be one-column for new users

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5565] opened 2020-11-09 11:44 UTC
**Describe the bug**
According to the acceptance criteria of #5223, the home screen layout should be one-column for brand new stores.
 
**To Reproduce**

1. Start a new store with wcadmin 1.7 installed 
2. Complete the store profiler (you can also skip it)
3. Visit the home screen and see that the default option is the two column layout.

**Expected behavior**
To see the one-column layout by default if I'm a new store.

**Screenshots**
https://www.loom.com/share/41037af874844953955478989cbd53b2

**Comment by jeffstieler** [comment] 2020-11-09 14:46
If you're testing this on a JN site, or any other new site - you need to activate WooCommerce and WooCommerce Admin simultaneously. If you activate WooCommerce core first, the activation of WooCommerce Admin will trigger the database update routine (because the plugin version is newer than the bundled version in core) and the store will be considered "existing" not "new".

For JN specifically:
- Don't select WooCommerce when creating the site
- Install WooCommerce core (but do not activate) through the plugins screen
- Upload the WooCommerce Admin .zip
- Use the bulk actions to activate both at the same time:

![Screen Shot 2020-11-09 at 8 44 12 AM](https://user-images.githubusercontent.com/63922/98555799-5b659e80-2270-11eb-876b-a63b4fc66617.png)

**Comment by timmyc** [comment] 2020-11-09 20:52
Thanks for the explanation @jeffstieler - I simulated the bundled install using the steps you outlined above and confirmed that single column is indeed shown for a fresh install:

![image](https://user-images.githubusercontent.com/22080/98595089-61687900-228a-11eb-875f-eb5dba7868b6.png)

Closing since this is working as expected.

**Closed by timmyc** 2020-11-09 20:52 UTC
Labels: Homescreen 2.0, [Status] Needs feedback

**Comment by pmcpinto** [comment] 2020-11-10 15:26
Thanks for the update. That's exactly what was happening: activating WooCommerce core first and only then activating the wcadmin beta plugin
