### ISSUE TITLE
Categories report not listing categories in tabular data

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/woocommerce-admin#6861] opened 2021-04-22 19:21 UTC
**Describe the bug**
When viewing the categories report, the tabular data is missing

**To Reproduce**
- Create a fresh install - add products and make sure they have categories assigned. 
- Generate a number of orders using smooth generator
- View the category report and note that it's missing category data

**Expected behavior**
The tabular data should list categories

**Screenshots**

Categories not appearing in category report
<img width="1884" alt="Screen Shot 2021-04-20 at 7 56 31 AM" src="https://user-images.githubusercontent.com/4500952/115773302-fe186200-a364-11eb-9aaf-de29a6e6864f.png">

Products in store have categories
<img width="1884" alt="Screen Shot 2021-04-20 at 7 57 28 AM" src="https://user-images.githubusercontent.com/4500952/115773310-007abc00-a365-11eb-93fd-48b2a23e4744.png">

**Comment by joshuatf** [comment] 2021-09-29 18:57
I'm not able to reproduce this on the current `main` branch.  @LevinMedia would you mind seeing if you can reproduce this using the latest WooCommerce Admin?  I think the WP.org version should be okay for testing.

**Comment by joshuatf** [comment] 2021-09-29 18:58
Ah, scratch that.  I believe it was resolved by @moon0326 in https://app.zenhub.com/workspace/o/woocommerce/woocommerce-admin/issues/7290.  Closing this issue for now.  Feel free to reopen if you're still able to recreate!

**Closed by joshuatf** 2021-09-29 18:58 UTC
Labels: type: bug, feature: analytics
