### ISSUE TITLE
[GlobalStep - 4.2 RC1]: On Business details page, "There was an error installing MailChimp. Please try again." error message is displayed 

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#4419] opened 2020-05-21 14:57 UTC
**Environment:**
Windows 10- Google Chrome (Version 81.0.4044.138)
Mac Mojave -10.14.6 -Safari(v13.0.5 )

**Steps to Reproduce:**
1. Create a site.
2. Add all the plugins.
3. Tap on "Run the setup wizard".
4. Go to Business Details page.
5. Enter all the details.
6. Observe that "There was an error installing MailChimp. Please try again." error message is displayed.

**Actual Result:**
There was an error installing Mailchimp. Please try again." error message is displayed

**Expected Result:**
MailChimp Plugins should get installed upon tapping "Continue" button.

![#26576](https://user-images.githubusercontent.com/41110392/82572225-af38da00-9ba1-11ea-9762-9495334bc35e.jpg)

**Comment by tammullen** [comment] 2020-05-21 16:01
Hi @gglobalstep 

Thank you for reporting the issue. WooCommerce Admin is being developed in another repository: https://github.com/woocommerce/woocommerce-admin.
I am going to move your bug report there so that the right team could take a look further.

**Comment by timmyc** [comment] 2020-06-05 16:57
Closing out due to this being caused by JN rebooting. There is work happening around making the plugin install step more fail proof too.

**Closed by timmyc** 2020-06-05 16:57 UTC
Labels: Onboarding, [Type] Bug
