### ISSUE TITLE
Admin Inbox - messages can't be permanently dismissed and can be spammed

### ISSUE THREAD

**Issue by kdevnel** [woocommerce/woocommerce-admin#6211] opened 2021-01-28 06:12 UTC
**Is your feature request related to a problem? Please describe.**
It seems that it is possible for the inbox on the WooCommerce Admin homepage to be spammed by messages by either WooCommerce or extensions. 

This also leads to another issue where if you dismiss the messages then they reappear on page refresh so there is no way to permanently dismiss messages in there. 

As a side-note - this inbox also keeps going in a long list which can feel like it wasn't an intentional design but something that was missed.

**Describe the solution you'd like**
Some way of either permanently dismissing specific messages and/or a way to prevent spamming of repeated messages.

Also, perhaps a more defined paging interface so that larger inboxes don't increase the length of the page too far.

**Additional context**
Here is a specific example:

![Markup on 2021-01-27 at 09:26:01](https://user-images.githubusercontent.com/22053773/106098076-16e7f180-6141-11eb-929b-db1ddabc4115.png)

cc: @joshuatf @elizaan36

**Comment by elizaan36** [comment] 2021-01-29 02:06
Thanks for creating this issue @kdevnel 

Wanted to add that I spoke to this customer in a user interview and he had deleted the AST plugin but the Inbox messages were still showing up. He kept selecting "Dismiss all" but then upon refresh the messages appeared again. One possibility could be that the extension added so many messages that "Dismiss all" doesn't even make a dent in them?

> Also, perhaps a more defined paging interface so that larger inboxes don't increase the length of the page too far.

We should look into this. I could imagine a "Load more" being useful after maybe 10 messages rather than the endless scroll.

**Comment by joshuatf** [comment] 2021-01-29 14:55
Thanks for taking the time to outline this issue @kdevnel!  Just a note for whenever we're ready to work on this, we can probably break this down into 2 issues:

1. Preventing spam in the inbox.
2. Pagination for the inbox.

(1) from above may require lengthier discussion via p2, but some of our previous discussions around this were rate limiting the number of messages added.  However this becomes pretty problematic since one plugin could use up the entire quota for the day.

The next iteration on this of course is limiting the number of notes by plugin.  We currently have a `source` attribute on notes which can be manually set.  However, maybe this needs to be automatically created from the offending plugin folder to prevent abuse so we can monitor how many notes are added in a given time frame by a plugin.

Also in `NoteTraits` we prevent notes with identical slugs from being added, but maybe this should be moved into the notes API in case that is what's happened in this particular plugin.

**Comment by kdevnel** [comment] 2021-01-29 15:28
> One possibility could be that the extension added so many messages that "Dismiss all" doesn't even make a dent in them?

When I checked the site I actually managed to click to dismiss all a few times until no other notifications showed. As soon as I refreshed they all came back.

Could still be that there are too many notifications but hoping this helps.

**Comment by joelclimbsthings** [comment] 2022-03-02 21:55
I believe this has likely been resolved as I'm unable to reproduce any issues with persistence in dismissing inbox messages. Closing this in preparation for the merge.

**Closed by joelclimbsthings** 2022-03-02 21:55 UTC
Labels: type: enhancement, feature: inbox
