### ISSUE TITLE
Blank Screen when WC Pay is active

### ISSUE THREAD

**Issue by leonardola** [woocommerce/woocommerce-admin#8030] opened 2021-11-17 21:56 UTC
Related to https://github.com/Automattic/woocommerce-payments/issues/3333

**Describe the bug**
Blank Screen is displayed after clicking WooCommerce > Home when WC Pay is active.

This bug started happening after WooCommerce version 5.9.0 was released. 
As far as I could dig this bug starts on version 6.1.2 of @woocommerce/components
The only differences between 6.1.1 to 6.1.2 are inside the file package.json :
<img width="1539" alt="Screen Shot 2021-11-11 at 5 58 37 PM" src="https://user-images.githubusercontent.com/6342964/141368144-1cc7903d-fa32-4355-80ea-1fea1b1c1849.png">
Which means it started to use some packages bundled inside WooCommerce instead of using a fixed version. This leads me to thinks this is the best repository to post this issue. If it is not I am glad to repost on the appropriate repository

This is the console output:
`index.min.js?ver=b8562bacc5e29120481c959c17d91751:1 An error occurred while running 'mapSelect': o is not a function`
Which lead me to [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/data/src/components/use-select/index.js#L139). Apparently the registry is not being created

**Steps to reproduce the bug:**

https://user-images.githubusercontent.com/6342964/142286151-331f49bd-dd1e-4d5c-970d-4e3aab56f2fc.mp4

- Install WooCommerce 5.9.0
- Install and activate WooCommerce Payments - [3.3.0 - test 2](https://github.com/Automattic/woocommerce-payments/releases/download/3.3.0-test-2/woocommerce-payments.zip).
- Click on WooCommerce home page.
- Observe Blank Screen.

**Comment by mcampal** [comment] 2021-12-22 14:14
While I'm not able to replicate this from my end on a testing site, I came across a user experiencing this issue when only WooCommerce and WooCommerce Payments are active on their site while running the Storefront theme and everything is updated. 

I can see that they are also not able to run the WooCommerce Payments setup wizard. See the screencast for reference: 

![Screen Capture on 2021-12-22 at 11-03-52](https://user-images.githubusercontent.com/72819905/147105343-9ce865d9-b311-436c-9738-a7dfd02544dc.gif)

This issue has been recently moved to the woocommerce/admin repository, so I thought of pointing this out.

4631039zen

**Comment by leonardola** [comment] 2021-12-22 14:53
@mcampal the original issue only happens on a specific branch/test release of WC Pay. This should not happen on stable version as the change was reverted. So not sure if this is 100% related.

**Comment by mcampal** [comment] 2021-12-22 15:37
I see. In this case, the user has the following setup: 

WC Version: 6.0.0
WC Admin Version: 2.9.4
WooCommerce Payments: 3.4.0

Would you suggest opening a new issue, @leonardola? 

I noticed that a similar issue has been reported [here](https://github.com/Automattic/woocommerce-payments/issues/2806), but it is now closed since we weren't able to replicate the issue. I can see that you were able to replicate the broken page behavior with the production plugin. Can you clarify if this is expected behavior?

**Comment by leonardola** [comment] 2021-12-22 16:56
@mcampal I created a fresh install with the same plugins and storefront theme but I could not reproduce the error you reported. The errors can be related but I am sure yet. Does any error show up on console when opening the page?

**Comment by mcampal** [comment] 2021-12-22 17:40
There are no errors on the console when opening the page. 

When trying to access **WooCommerce > Home** or the '**Payments**' section (that would trigger the setup wizard) from their WP-Admin, they are being redirected to `/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fconnect` and the page loading as seen [here](https://user-images.githubusercontent.com/47186013/131077507-557a9c7d-578c-4017-b51d-02e01484f922.png).

The same behavior is occurring when trying to access the **/wp-admin/admin.php?page=wc-admin** URL on the user's site.

I'm also not able to replicate this from my end, but the user's site is only running WooCommerce and WooCommerce Payments with the Storefront theme. 

Any thoughts?

**Comment by pauljacobson** [comment] 2021-12-23 09:26
Hi there. In 4631039-zen, our user came back wiht the following feedback:

>Update: Hostgator support was able to solve it. Maybe the (to me cryptic) message I got from it helps: .htaccess file had too much code, and he removed some of that. Unfortunately he did not give me more hints. (you may understand better than I to which degree this may square with the fact that the issue had been replicated on a blank WP install)

I've asked them to reach out to Hostgator for more details in case this is helpful here.

**Comment by leonardola** [comment] 2021-12-23 13:28
@pauljacobson That confirms that it was not related to the original issue. I used the [default .htaccess](https://wordpress.org/support/article/htaccess/) file during all the tests.

**Comment by csmcneill** [comment] 2021-12-23 21:25
In 4631039-zen, our user came back wiht the following feedback:

>
Yes, I finally got htis extra information:
>
Related to the ".htaccess" file of WordPress:
>
"Due to plugin there were unwanted scripts like deny codes which was removed by previous agent, I would suggest you optimize the website."

**Comment by moon0326** [comment] 2021-12-24 02:48
It sounds like this is not an issue on our end. Is it okay to close this issue?

**Comment by leonardola** [comment] 2021-12-27 12:29
@moon0326 do not close the issue. The bug that @mcampal brought up is not related to the original issue

**Comment by joelclimbsthings** [comment] 2022-03-01 21:47
I believe if the second issue is still a relevant one, we'll want to create a separate issue to capture that (either in this repo or WCPay). To avoid confusion during the merge I'm closing this one.

**Closed by joelclimbsthings** 2022-03-01 21:47 UTC
Labels: type: bug, Needs triage
