### ISSUE TITLE
[GlobalStep - 4.1 beta 1] "Service Unavailable" error message is displayed upon clicking "WooCommerce" after updating tax setup.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#4137] opened 2020-04-09 16:34 UTC
**Step to Reproduce:**
1. Create a test site using JN. 
2. Complete initial screens and go to dashboard.
3. Click on "Setup Tax".
4. Click on "Configure" button.
5. Click on "Tax".
6. Update Tax Options as per mentioned in "https://github.com/WooCommerce/WooCommerce/wiki/Release-Testing-Instructions#40" document.
7. Click on "Save Changes".
8. Click on "WooCommerce".
9. Observe that "Service Unavailable" error message is displayed.

**Actual Result:**
"Service Unavailable" error message is displayed upon clicking "WooCommerce" after updating tax setup.

**Expected Result:**
WooCommerce plugin should perform gracefully without encountering such errors.

![14](https://user-images.githubusercontent.com/41110392/78918486-1e54e600-7aae-11ea-8f57-175c923e94b2.png)

**Comment by juliaamosova** [comment] 2020-04-20 18:04
The same issue was experienced by Austin L. during his testing on Jurassic Ninja. Reference: pb22l9-8V-p2#comment-395. 

Quoting:

"When I tried to manually load taxes in the CBD store setup, I got a 503 error. I was able to go back in my browser and it worked going through the motions again."

![503](https://user-images.githubusercontent.com/19143190/79783948-7e018b80-830f-11ea-9fdd-bc8c7638f399.png)

@timmyc pinging you here for visibility. Looks like many testers experienced the same error. I can't tell if this is JurassicNinja site-related but it was experienced by many on JN site.

**Comment by timmyc** [comment] 2020-04-20 20:21
@juliaamosova it sounds like this might be specific to JN, perhaps a timeout happening when doing the JP connect flow on this step. Do you still have access to the JN site where it happened so we can view the log files to confirm though?

**Comment by juliaamosova** [comment] 2020-04-20 20:26
@timmyc I though the same and originaly closed this issue but then reopened because so many people reported it. I did not experience it myself though so I can't provide a test site. Looks like everyone tested on JN site so it could be hard to get access to the site. @denho provided the following in [his comment](https://github.com/woocommerce/woocommerce-admin/issues/4137#issuecomment-614106843) though:

"After refreshing, it worked normally. Couldn’t reproduce it on the new site installation. PHP error logs are empty, the Apache logs show these entries:"

```
[Tue Apr 14 09:14:44.830445 2020] [proxy:error] pid 652:tid 140376442664704No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /srv/users/user4c2da1d7/run/user4c2da1d7.php-fpm.sock (localhost) failed
[Tue Apr 14 09:14:44.830483 2020] [proxy_fcgi:error] [pid 652:tid 140376442664704] [client 50.3.71.173:0] AH01079: failed to make connection to backend: httpd-UDS, referer: https://surviving-sawfish.jurassic.ninja/wp-admin/admin.php?page=wc-setup
```

I realize there are not many details in this issue to troubleshoot.

**Comment by oskosk** [comment] 2020-04-29 22:57
This error is indeed specific to JN, and is due to the web server restarting for reloading new config when another site is being launched.

More context about it in p6jOYE-1Ar-p2.

I'd propose to close this issue again as it's very specific to a Jurassic Ninja problem and not inherent to Woo (Unless one assigns the responsibility of error handling to Woo's codebase which IMO shouldn't be the case here for this weird situation coming from the design choices around Jurassic Ninja itself: My bad basically).

**Comment by juliaamosova** [comment] 2020-04-30 14:14
Thanks for clarification @oskosk! @timmyc I think it is safe to close this one.

**Comment by timmyc** [comment] 2020-05-04 16:50
Thanks @juliaamosova and @oskosk that is *really good to know*! I just hit this myself when testing on JN, but had never encountered it on ephemeral or local test sites.

**Closed by timmyc** 2020-05-04 16:50 UTC
