### ISSUE TITLE
GET wp-json 403

### ISSUE THREAD

**Issue by goferit** [woocommerce/woocommerce-admin#2339] opened 2019-05-29 14:10 UTC
Sorry not a developer. See screenshot:

http://snpy.in/Mn3pDy

Occurs in Chrome and Safari on a Mac, does not occur in Firefox.

Caused our server to blacklist our IP (failed attempts accumulate about 1x per 5 seconds).

Disabled Admin plugin and problem ceased.

Only occurs in WP backend when browsing Woo subpages.

**Comment by melek** [comment] 2019-06-10 18:14
We had a similar issue, though I'm not positive it is the same since the URL seems quite different. Our host said we had an enormous amount of 403 errors causing an automatic blacklist of our workplace IP. Here were the sample error lines they provided me:
```
420 /wp-json/wc/v4/reports/revenue/stats?after=2018-12-17T00%3A00%3A00&before=2018-12-26T23%3A59%3A59&interval=day&order=asc&per_page=100&_locale=user
420 /wp-json/wc/v4/reports/revenue/stats?after=2017-12-17T00%3A00%3A00&before=2017-12-26T23%3A59%3A59&interval=day&order=asc&per_page=100&_locale=user
270 /wp-json/wc/v4/reports/revenue/stats?after=2018-12-17T00%3A00%3A00&before=2018-12-26T23%3A59%3A59&interval=day&order=desc&orderby=refunds&page=1&per_page=25&_locale=user
```

**Comment by rrennick** [comment] 2019-06-10 18:25
Duplicate of #2365

**Closed by rrennick** 2019-06-10 18:25 UTC
