### ISSUE TITLE
Category Report and Overview Don't Match Actual Order Details

### ISSUE THREAD

**Issue by billrobbins** [woocommerce/woocommerce-admin#6376] opened 2021-02-18 23:10 UTC
**Describe the bug**
At least in some situations, the overview and category reports don't match the actual order data.

**To Reproduce**

1. Place an order using an existing product that's in only one category.
2. Create a new product and create two new categories for it.  Make it expensive so it should at the top of the category list.
3. Place an order for the new product.
4. Edit the product and remove one of the two categories.
5. Clear analytics data and reimport.
6. View the overview and notice how the category for the new product isn't on the list.  

**Expected behavior**
I expect the category list and overview to show which category is top in sales.

**Screenshots**
![overview](https://cdn-std.droplr.net/files/acc_705319/cmqOC8)
(Link to screenshot:  https://d.pr/i/cmqOC8)

![category](https://cdn-std.droplr.net/files/acc_705319/tF3k2z)
(Link to screenshot:  https://d.pr/i/tF3k2z)

**Desktop (please complete the following information):**

* OS: MacOS 11.2.1
* Browser Chrome
* Version 88.0.4324.150

**Comment by ilyasfoo** [comment] 2021-03-02 05:05
I was able to reproduce this even without step 4 & 5

![image](https://user-images.githubusercontent.com/3747241/109600312-e0dec880-7b57-11eb-839a-4f5dbe51baa0.png)

Products:

![image](https://user-images.githubusercontent.com/3747241/109600226-b4c34780-7b57-11eb-9096-5969334724b0.png)

**Comment by chihsuan** [comment] 2022-01-18 08:10
I believe this has been fixed on the main branch. I couldn't reproduce this by following the instructions.

Everything works as expected now. I'm going to close this. Please free feel to reopen this if I'm wrong. Thanks.

![Screen Shot 2022-01-18 at 16 05 08](https://user-images.githubusercontent.com/4344253/149896311-39e3b62b-aeba-43cb-a612-5cfa321e5a5f.png)
![Screen Shot 2022-01-18 at 16 05 25](https://user-images.githubusercontent.com/4344253/149896317-584f1b6a-e6b2-424e-8232-d6b630704075.png)

**Closed by chihsuan** 2022-01-18 08:10 UTC
Labels: type: bug, feature: analytics, Needs triage
