### ISSUE TITLE
[GlobalStep - WooCommerce 4.6 Beta 1][iOS] Website fails to display "Install" button for mobile app banner.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#5192] opened 2020-09-23 15:51 UTC
## Bug Description:
Website fails to display "Install" button for mobile app banner

## Environment:
iOS
Devices: iPhone 6: 12.4.4 (16G140)
             iPhone 11 Pro - v13.2.2 (17B102).

## Steps To Reproduce:
1. Create a Jurassic Ninja test site
1. Install and Activate WooCommerce, Query Monitor and WooCommerce Beta Tester Plugin.
1. Switch the version to 4.6.0 Beta 1 with help of WooCommerce Beta Tester plugin
1. Login to the Jurassic Ninja Site on any one of the iPhone-Safari browser
1. Go to WooCommerce->Home
1. Note that "View" banner is displayed, after clicking on View, user is navigated to AppStore
1. After installing the app, re-visit the website on Safari, note that "Open" banner is displayed
1. Refresh the page and note that banner disappears.
1. Observe that website fails to display "Install" button for mobile app banner
 
**Note:**
On iPhone- Website displays "WooCommerce" banner instead of "Run your Store Anywhere" banner.

## Actual Result:
Website fails to display "Install" button for mobile app banner

## Expected Result:
As per the document, Website should display "Install" button for mobile banner.

## Artifacts:
![#27760](https://user-images.githubusercontent.com/41110392/94037315-dc60f780-fde2-11ea-8e6d-f9785a5f935e.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by timmyc** [comment] 2020-09-24 13:32
@samueljseay I _think_ this is working as designed but wanted to verify with you.

**Comment by samueljseay** [comment] 2020-09-24 19:06
Hey folks, yes this is working as designed. On Apple devices we display the "Smart App Banner", which is content that apple controls and is linked directly to the WooCommerce store listing. Sorry for the confusion.

The custom banner we made ourselves (the one with the install button) should show on Android devices.

**Comment by juliaamosova** [comment] 2020-09-24 19:55
Noting here that I tested it as wel and confirm that there is a prompt to **Install** the app on the Android device. But on iOS, there is a banner with a **View** prompt. 

**Android:**

![android](https://user-images.githubusercontent.com/19143190/94193377-47abd780-fe7e-11ea-8b11-fee39893d91c.jpg)

**iOS:**

![ios](https://user-images.githubusercontent.com/19143190/94193387-4bd7f500-fe7e-11ea-9b44-974b590784fe.jpg)

Both are expected as mentioned by @samueljseay.

**Comment by jeffstieler** [comment] 2020-09-25 15:02
Closing this since it's working as designed/expected.

**Closed by jeffstieler** 2020-09-25 15:02 UTC
Labels: [Type] Question
