### ISSUE TITLE
[WC 4.4 beta1] OBW:  `Install recommended free business features` checkbox appears only if the user selects `Fashion, apparel, and accessories` or `Health and beauty` product types

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4888] opened 2020-07-29 22:01 UTC
**Describe the bug**

In OBW, the`Install recommended free business features` checkbox appears only if the user selects `Fashion, apparel, and accessories` or `Health and beauty` product types. If the user selects any other product type, an older version of the `Business Details` section is being shown where the user can toggle on/off the FB, Mailchimp and Google Ads options. 

**To Reproduce**

1. Start OBW. 
2. On the `In which industry does the store operate?` page select either `Fashion, apparel, and accessories` or  `Health and beauty` options:

![1](https://user-images.githubusercontent.com/19143190/88857737-d1179400-d1c4-11ea-9fc8-db9510c0b84b.jpg)

3. Proceed further. On the `Tell us about your business` page, you should see the`Install recommended free business features` checkbox:

![2](https://user-images.githubusercontent.com/19143190/88857747-d543b180-d1c4-11ea-827a-747db63da4c0.jpg)

4. Go back to the `In which industry does the store operate?` page using the browser's back button. 
5. On the `In which industry does the store operate?` page select any other industry than `Fashion, apparel, and accessories` or  `Health and beauty`. For example, `Art, music, and photography`:

![3](https://user-images.githubusercontent.com/19143190/88857907-189e2000-d1c5-11ea-8715-6c78d80dd49c.jpg)

6. Proceed further. On the `Tell us about your business` page, you will see an older version of that page where you can toggle on/off the FB, Mailchimp and Google Ads options:

![4](https://user-images.githubusercontent.com/19143190/88857955-35d2ee80-d1c5-11ea-810e-9ec15b4d612f.jpg)

**Expected behavior**

I expected to see the new `Install recommended free business features` checkbox on the `Tell us about your business` page regardless of the type of the product I select on the `In which industry does the store operate?` page. 

**Screenshots**

See above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.5
* Browser: Chrome
* Version: 84.0.4147.89 (Official Build) (64-bit)

**Additional context**

N/A.

**Comment by timmyc** [comment] 2020-07-29 22:41
@juliaamosova this behavior is by design at the moment. It is our way of limiting this new flow to a subset of users to see how it performs against the existing design of allowing users to select which extensions to install. The other requirement for the new recommended features is the store must be based in the US - because one of the extensions installed in this flow is WooCommerce Payments.

/cc @pmcpinto

**Comment by juliaamosova** [comment] 2020-07-29 23:11
@timmyc interesting! Thanks for the explanation. Noted.

**Comment by pmcpinto** [comment] 2020-07-30 11:08
Yep. It's an experiment that we're doing. So I'm going to close this issue. Thanks!

**Closed by pmcpinto** 2020-07-30 11:08 UTC
