### ISSUE TITLE
[WC 4.5 RC3] Home Screen: completing `Set up additional payment providers` Inbox card marks `Set up WooCommerce Payments` task of the Home Screen as done

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#5086] opened 2020-09-03 01:34 UTC
**Describe the bug**

After completing OBW, on the Home Screen, completing `Set up additional payment providers` Inbox card marks `Set up WooCommerce Payments` task of the Home Screen as done. 

**To Reproduce**

1. Start OBW on the brand new site. 
2. Fill in the `Store Details` section with the US address.  
3. Select `Fashion, apparel, and accessories` in the Industries section.
4. In the `Tell us about your business` section, select checkbox next to `Install recommended free business features` to install all the recommended plugins. 
5. On `Home Screen`, select `Set up WooCommerce Payments` task and note that this task opens up the flow to connect WooCommerce Payments through Stripe. Don't complete the process. Instead, go back to the site by clicking the browser's back arrow. `Set up WooCommerce Payments` task should be still marked as not done. 
6. In the Inbox section, select `Set up additional payment providers` Inbox card:

![payments1](https://user-images.githubusercontent.com/19143190/92061163-91177400-ed63-11ea-8585-433fb0ed01b6.jpg)

7. On the next screen, select `Cash on Delivery` and click on `Done` button. 
8. You will be redirected back to Home Screen and you will see that the `Set up WooCommerce Payments` task is now completed although the WooCommerce Payments were not set up. 

See gif below that shows the behavior (replicated 3 times on the JN site):

![](http://g.recordit.co/juCH0vgi5A.gif)

**Expected behavior**

I expected the `Set up WooCommerce Payments` task to not be marked as done if you set any other payment method using `Set up additional payment providers` Inbox card. 

**Screenshots**

See above. 

**Desktop (please complete the following information):**

- OS: macOS Catalina 10.15.6
- Browser: Chrome
- Version: Version 85.0.4183.83 (Official Build) (64-bit)

**Additional context**

N/A

**Comment by timmyc** [comment] 2020-09-03 22:00
Duplicate of #4884 - and has been fixed in #4917 already. So I suppose we can either cherry pick in that fix, or just mark this as resolved since it will be in the next release.

**Comment by juliaamosova** [comment] 2020-09-04 14:39
Thanks @timmyc! My bad because I am also the one who filed 4884 🤦‍♀️ .

**Comment by timmyc** [comment] 2020-09-04 19:12
No worries at all @juliaamosova - and since we do have a fix in `main` - I'm going to close this out. Noting again that @becdetat and I chatted and opted to *not* pull in that PR with the fix into the 1.5 release since we are so late in the testing cycle at this point. And this bug doesn't seem critical enough to assume the risk with adding in the code in the fix branch.

**Closed by timmyc** 2020-09-04 19:12 UTC
Labels: Onboarding, [Type] Bug

**Comment by juliaamosova** [comment] 2020-09-04 19:15
>No worries at all @juliaamosova - and since we do have a fix in main - I'm going to close this out. Noting again that @becdetat and I chatted and opted to not pull in that PR with the fix into the 1.5 release since we are so late in the testing cycle at this point. And this bug doesn't seem critical enough to assume the risk with adding in the code in the fix branch.

Sounds good, thanks @timmyc! Noted.
