### ISSUE TITLE
JS console warning when visiting products screen

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-admin#6561] opened 2021-03-10 18:11 UTC
**Describe the bug**

Seeing JS console warning: `Warning: Received NaN for the "max" attribute. If this is expected, cast the value to a string.`

**To Reproduce**

1. WP 5.7, WC 5.2.0-dev, WC Admin 2.2.0-dev standalone
2. Go to Analytics->Products screen.
3. See warning in JS console.

**Expected behavior**
Not to see any JS warnings.

**Comment by psealock** [comment] 2021-03-11 03:06
Thanks @roykho !

Interestingly enough, I can't reproduce this on the latest of `main`.  I can, however, on `main` as of this PR https://github.com/woocommerce/woocommerce-admin/pull/6508 branched only a week ago.

Taking a look at pull requests merged between then and now, nothing looks like it affects those files except maybe this update to Babel https://github.com/woocommerce/woocommerce-admin/pull/6300.

I'm going to close this because it appears to have resolved itself, but keep an eye on it and may re-open

**Closed by psealock** 2021-03-11 03:06 UTC
Labels: type: bug
