### ISSUE TITLE
Regressions from coding standards PR

### ISSUE THREAD

**Issue by jeffstieler** [woocommerce/woocommerce-admin#3752] opened 2020-02-21 01:18 UTC
**Describe the bug**

Several issues were found when smoke testing the latest WP monorepo renovate PR that are actually all issues on `master` - and look to be the result of https://github.com/woocommerce/woocommerce-admin/pull/3674.

**To Reproduce**

- dashboard leaderboards don't finish loading
- activity panel - "order #undefined"
- categories report compare chart header doesn't load
- profiler industry step: "Invalid parameter(s): industry"
- theme step doesn't finish (choose currently active theme button stays busy)

**Screenshots**

![Screen Shot 2020-02-20 at 6 16 48 PM](https://user-images.githubusercontent.com/63922/74995130-30e76300-540d-11ea-90aa-4802c6c76547.png)

![Screen Shot 2020-02-20 at 6 15 44 PM](https://user-images.githubusercontent.com/63922/74995073-05fd0f00-540d-11ea-9bf5-525c968539aa.png)

![Screen Shot 2020-02-20 at 6 17 28 PM](https://user-images.githubusercontent.com/63922/74995151-452b6000-540d-11ea-8bc7-2fb7c4fee8ab.png)

![Screen Shot 2020-02-20 at 6 14 40 PM](https://user-images.githubusercontent.com/63922/74995024-e665e680-540c-11ea-91c6-434872f7f8e6.png)

![Screen Shot 2020-02-20 at 6 15 10 PM](https://user-images.githubusercontent.com/63922/74995038-f1b91200-540c-11ea-86e1-f7ae9a2b25cb.png)

**Comment by jeffstieler** [comment] 2020-02-22 01:32
> profiler industry step: "Invalid parameter(s): industry"

This turned out to be left over data from testing https://github.com/woocommerce/woocommerce-admin/pull/3730

> theme step doesn't finish (choose currently active theme button stays busy)

This no longer occurs. :)

**Comment by psealock** [comment] 2020-02-24 02:46
Thanks @jeffstieler ! 

I have a fix coming up for the top 3 but am unable to reproduce the Onboarding issues. Was there anything noteworthy with your setup to reproduce?

**Comment by psealock** [comment] 2020-02-25 03:03
Closed by https://github.com/woocommerce/woocommerce-admin/pull/3763

**Closed by psealock** 2020-02-25 03:03 UTC
Labels: Activity Panel, Analytics, Dashboard, [Type] Bug
