### ISSUE TITLE
Submenu text color black = unreadable

### ISSUE THREAD

**Issue by jphansendk** [woocommerce/woocommerce-admin#6996] opened 2021-05-17 08:55 UTC
**Describe the bug**
Submenu text color unreadable

**To Reproduce**
Upgraded to v. 2.3.0

1. Go to 'WP-Admin'
2. Click on 'WooCommerce'
3. See error

**Expected behavior**
The text of the submenu items is suddenly all black on a really dark background color.

**Screenshots**
![WooCommerce_text_color](https://user-images.githubusercontent.com/68819320/118461531-0ebabe80-b6fe-11eb-9be7-c3354c88b58f.jpg)

**Desktop (please complete the following information):**

* OS: MacOS 11.3.1
* Browser Chrome
* Version 90.0.4430.212

**Comment by mattsherman** [comment] 2021-05-17 17:43
This appears to be similar (or, the exact same issue even) as https://github.com/WordPress/gutenberg/pull/28619

**Comment by mattsherman** [comment] 2021-05-17 17:58
@jphansendk Thanks for reporting this issue. I am currently unable to reproduce this. In order to help me narrow down what may be causing this in your environment, can you please share your site's System Report?

1. Visit `/wp-admin/admin.php?page=wc-status&tab=status`
2. Click "Get system report"
3. Copy the report in the comments here. You can remove any information you do not wish to share. The information that will be the most useful, likely, is the active plugins (including version numbers), so please make sure to include those.

In addition, if you have not already, please try this with another browser to see if you get different results. And, please try clearing your browser cache.

Thanks!

**Comment by jphansendk** [comment] 2021-05-18 08:23
WTF?!?! This morning the problem has disappeared. It must have been some weird cache problem.. 
The plugin has been deactivated overnight from the WooCommerce settings and I reactivated it to generate the report for you. All good now.. Sorry for your trouble.

**Comment by mattsherman** [comment] 2021-05-18 17:27
@jphansendk I'm glad all is well now! I'm going to close this issue. If you run across any other troubles in the future, please don't hesitate open a new issue.

**Comment by mattsherman** [comment] 2021-05-18 17:28
Closed this issue as it was unreproducible.

**Closed by mattsherman** 2021-05-18 17:27 UTC
Labels: feature: navigation, needs feedback
