### ISSUE TITLE
[WC 4.6 RC1] Home Screen: "Continue Store Setup" button shown when the user exits OBW doesn't work

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#5251] opened 2020-10-01 20:53 UTC
**Describe the bug**

If you exit onboarding without completing it, you are taken to the Home Screen and there is a prompt where you can select to `Continue Store Setup`. My first impression is that if I click on that button indicating that I want to continue Store Setup, I will be taken back to onboarding. But when I click on it, the page reloads and nothing happens. Does this button suppose to take us to Home Screen? If so, it feels a bit redundant that this notice is on the Home Screen:

![setup](https://user-images.githubusercontent.com/19143190/94861721-fbc0db80-0405-11eb-9082-461a7fd7e5e0.jpg)

The URL contains `enable_onboarding=1` which makes me think I should be going back to the Setup Wizard:

![](http://g.recordit.co/tKqUspMQ2q.gif)

**To Reproduce**

1. Create a brand new test site and upload WC 4.6 RC1. 
2. On the very first screen of onboarding select to `Skip Setup Wizard`.
3. You'd be taken to Home Screen where you'd see the notice in question. 
4. Click on `Continue Store Setup` and observe that the page reloads without taking you anywhere. 

**Expected behavior**

I expected to be taken back to the Setup Wizard upon clicking on that `Continue Store Setup` button in the notice on the Home Screen if I exited onboarding earlier. 

**Screenshots**

See above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.6
* Browser: Chrome
* Version: Version 85.0.4183.121 (Official Build) (64-bit)

**Additional context**

N/A.

**Comment by tammullen** [comment] 2020-10-01 21:19
I also get this button even after completing the onboarding wizard and it remains while going through the other tasks (and as mentioned if you click on Continue Store Setup and the page reloads without taking you anywhere.)
![Screenshot 2020-10-01 at 22 16 37](https://user-images.githubusercontent.com/24649833/94864434-e19df200-0433-11eb-9daf-a12a993991fe.png)
![Screenshot 2020-10-01 at 22 16 08](https://user-images.githubusercontent.com/24649833/94864455-e95d9680-0433-11eb-94e1-ee2a39cac7ee.png)
![Screenshot 2020-10-01 at 22 17 57](https://user-images.githubusercontent.com/24649833/94864583-1f027f80-0434-11eb-827f-bc22f13e423d.png)

**Comment by pmcpinto** [comment] 2020-10-02 09:53
I'm not sure if this banner is in the wcadmin repo or core 🤔

**Comment by tammullen** [comment] 2020-10-05 16:55
Related https://github.com/woocommerce/woocommerce-admin/issues/5080

**Comment by octaedro** [comment] 2020-10-07 15:12
Hi,
The button's action bug is solved in the [PR 5200](https://github.com/woocommerce/woocommerce-admin/pull/5200)

> I also get this button even after completing the onboarding wizard for a US based store and it remains while going through the other tasks (and as mentioned if you click on Continue Store Setup and the page reloads without taking you anywhere.)

I tried to reproduce the bug described in the comments (the note that invites users to finish the setup wizard is visible after completing the onboarding process) but I couldn't.

In my tests, I used an ephemeral site (`jurassic.ninja` instance), the `WC 4.6 RC1` zip file in a US-based store. Did I forget anything?

@tammullen do you have more information about this bug?

**Comment by tammullen** [comment] 2020-10-08 15:36
Thanks @octaedro!

> I tried to reproduce the bug described in the comments (the note that invites users to finish the setup wizard is visible after completing the onboarding process) but I couldn't.

I tried recreating this again and wasn't able to do, and unfortunately I don't that have site anymore or my recording of it so apologies I'm unsure what combination of inputs I used. I have tried multiple options and wasn't able to recreate. I wonder if it was a JN blip that caused it. If I manage to recreate I will report back here with full details.

**Comment by timmyc** [comment] 2020-10-08 16:43
Fixed in #5200

**Comment by rodrigoprimo** [comment] 2020-10-10 12:54
@timmyc, I'm not sure if this is entirely fixed. I could confirm that now the "Continue Store Setup" button works. But, as @juliaamosova pointed out, I also think that we shouldn't display the "Welcome to WooCommerce! Setup your store and start selling" notice, that includes the "Continue Store Setup" button, if the user already skipped the setup wizard. Are we intentionaly showing this notice even for users that opted to skip the setup wizard?

![Peek 2020-10-10 09-47](https://user-images.githubusercontent.com/77215/95655522-68129d80-0ade-11eb-8541-beddfe40e48b.gif)

Reopening this issue for visibility. Please close it again if this is the intended behavior. I don't think this is a blocker for WooCommerce 4.6, but please let me know if you disagree (cc @tammullen, @juliaamosova and @claudiosanches).

**Comment by pmcpinto** [comment] 2020-10-12 09:26
I think that banner should be removed, as the users can always access the store details flow through the task list.

**Comment by samueljseay** [comment] 2020-11-16 07:18
I don't know when this was solved exactly, but I think this is not an issue anymore (as of latest wc-admin), the banner does not exist in wc-admin or wc as far as I can tell. I tested this today with latest wc-admin and skipping store setup does not show the banner. Closing as "fixed" for now, but feel free to reopen if you discover otherwise.

**Closed by samueljseay** 2020-11-16 07:18 UTC
Labels: [Priority] High, [Type] Bug
