### ISSUE TITLE
do_cron_sync() Error

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#3401] opened 2019-12-09 14:53 UTC
WP Core error catching sent me emails 2x about the following problem on two different sites:

WordPress version 5.3
Current theme: Radcliffe 2 (version 2.0.8-wpcom)
Current plugin: WooCommerce Admin (version 0.23.0)
PHP version 7.2.25

Error Details
=============
An error of type E_ERROR was caused in line 616 of the file /srv/htdocs/wp-content/plugins/woocommerce-admin/src/Features/Onboarding.php. Error message: Uncaught Error: Call to undefined function Automattic\WooCommerce\Admin\Features\wc_get_screen_ids() in /srv/htdocs/wp-content/plugins/woocommerce-admin/src/Features/Onboarding.php:616
Stack trace:
#0 /wordpress/core/5.3/wp-includes/class-wp-hook.php(288): Automattic\WooCommerce\Admin\Features\Onboarding->update_help_tab(Object(WP_Screen))
#1 /wordpress/core/5.3/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#2 /wordpress/core/5.3/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /wordpress/core/5.3/wp-admin/includes/class-wp-screen.php(412): do_action('current_screen', Object(WP_Screen))
#4 /wordpress/core/5.3/wp-admin/includes/screen.php(241): WP_Screen->set_current_screen()
#5 /wordpress/plugins/jetpack/8.0/vendor/automattic/jetpack-sync/src/class-sender.php(365): set_current_screen('sync')
#6 /wordpress/plugins/jetpack/8.0/vendor/automattic/jetpack-sync/src/class-sender.php(457): Automattic\Jetpack\Sync\Sender->get_items_to_send(Object(Automattic\Jetpack\Sync\Queue_Buffer), true)
#7 /wordpress/plugins/jetpack/8.0/vendor/automattic/jetpack-sync/src/class-sender.php(326): Automattic\Jetpack\Sync\Sender->do_sync_for_queue(Object(Automattic\Jetpack\Sync\Queue))
#8 /wordpress/plugins/jetpack/8.0/vendor/automattic/jetpack-sync/src/class-sender.php(293): Automattic\Jetpack\Sync\Sender->do_sync_and_set_delays(Object(Automattic\Jetpack\Sync\Queue))
#9 /wordpress/plugins/jetpack/8.0/vendor/automattic/jetpack-sync/src/class-actions.php(482): Automattic\Jetpack\Sync\Sender->do_sync()
#10 /wordpress/plugins/jetpack/8.0/vendor/automattic/jetpack-sync/src/class-actions.php(437): Automattic\Jetpack\Sync\Actions::do_cron_sync_by_type('sync')
#11 /wordpress/core/5.3/wp-includes/class-wp-hook.php(288): Automattic\Jetpack\Sync\Actions::do_cron_sync()
#12 /wordpress/core/5.3/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
#13 /wordpress/core/5.3/wp-includes/plugin.php(544): WP_Hook->do_action(Array)
#14 /wordpress/core/5.3/wp-cron.php(138): do_action_ref_array('jetpack_sync_cr...', Array)
#15 {main}
  thrown

========

WordPress version 5.3
Current theme: Twenty Sixteen (version 1.8-wpcom)
Current plugin: WooCommerce Admin (version 0.23.0)
PHP version 7.2.25

Error Details
=============
An error of type E_ERROR was caused in line 616 of the file /srv/htdocs/wp-content/plugins/woocommerce-admin/src/Features/Onboarding.php. Error message: Uncaught Error: Call to undefined function Automattic\WooCommerce\Admin\Features\wc_get_screen_ids() in /srv/htdocs/wp-content/plugins/woocommerce-admin/src/Features/Onboarding.php:616
Stack trace:
#0 /wordpress/core/5.3/wp-includes/class-wp-hook.php(288): Automattic\WooCommerce\Admin\Features\Onboarding->update_help_tab(Object(WP_Screen))
#1 /wordpress/core/5.3/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#2 /wordpress/core/5.3/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /wordpress/core/5.3/wp-admin/includes/class-wp-screen.php(412): do_action('current_screen', Object(WP_Screen))
#4 /wordpress/core/5.3/wp-admin/includes/screen.php(241): WP_Screen->set_current_screen()
#5 /wordpress/plugins/jetpack/8.0/vendor/automattic/jetpack-sync/src/class-sender.php(365): set_current_screen('sync')
#6 /wordpress/plugins/jetpack/8.0/vendor/automattic/jetpack-sync/src/class-sender.php(457): Automattic\Jetpack\Sync\Sender->get_items_to_send(Object(Automattic\Jetpack\Sync\Queue_Buffer), true)
#7 /wordpress/plugins/jetpack/8.0/vendor/automattic/jetpack-sync/src/class-sender.php(326): Automattic\Jetpack\Sync\Sender->do_sync_for_queue(Object(Automattic\Jetpack\Sync\Queue))
#8 /wordpress/plugins/jetpack/8.0/vendor/automattic/jetpack-sync/src/class-sender.php(293): Automattic\Jetpack\Sync\Sender->do_sync_and_set_delays(Object(Automattic\Jetpack\Sync\Queue))
#9 /wordpress/plugins/jetpack/8.0/vendor/automattic/jetpack-sync/src/class-actions.php(482): Automattic\Jetpack\Sync\Sender->do_sync()
#10 /wordpress/plugins/jetpack/8.0/vendor/automattic/jetpack-sync/src/class-actions.php(437): Automattic\Jetpack\Sync\Actions::do_cron_sync_by_type('sync')
#11 /wordpress/core/5.3/wp-includes/class-wp-hook.php(288): Automattic\Jetpack\Sync\Actions::do_cron_sync()
#12 /wordpress/core/5.3/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
#13 /wordpress/core/5.3/wp-includes/plugin.php(544): WP_Hook->do_action(Array)
#14 /wordpress/core/5.3/wp-cron.php(138): do_action_ref_array('jetpack_sync_cr...', Array)
#15 {main}
  thrown

**Comment by jeffstieler** [comment] 2019-12-09 15:00
Duplicate of #3394

**Closed by jeffstieler** 2019-12-09 15:00 UTC
Labels: [Type] Bug
