### ISSUE TITLE
[Globalstep- WooCommerce Admin 2.2.0 Beta 2 ] Creative Mail option is toggle "ON" by default on "Business Details step" for African countries during OBW setup.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#6663] opened 2021-03-24 17:33 UTC
**Bug Description:**
Creative Mail option is toggle "ON" by default on "Business Details step" for African countries during OBW setup.

**Test Instructions:**
Store profiler - Added MailPoet to Business Details step #6503:
https://github.com/woocommerce/woocommerce-admin/blob/main/TESTING-INSTRUCTIONS.md#store-profiler---added-mailpoet-to-business-details-step--6503

**Environment:**
Woocommerce Version : WooCommerce 5.1
WordPress version: (v5.7)
WooCommerce Admin version: v2.2.0-Beta-2

PC:
Windows 10, Mac 10.14.6
Chrome(Version 88.0.4324.104) 
Firefox(Version 86.0)
Safari: v13.1.1
IE 11(Version 11.55.17763.0)

**Steps To Reproduce:**
1. Create any test site using JN site.
1. Install and activate all the required plugins 
1. Enter store address for "South Africa" country.
1. Complete and Proceed ahead till "Business Details" step
1. Observe that Creative Mail option is toggle ON by default on "Business Details step" during OBW setup

**Note:**
As per test instructions, for Store address, countries apart from " US | BR | FR | ID | GB | DE | VN | CA | PL | MY | AU | NG | GR | BE | PT | DK | SE | JP " should have "Creative Mail option toggled off by default"

**Actual Result:**
Creative Mail option is toggle "ON" by default on "Business Details step" for African countries during OBW setup.

**Expected Result:**
As per test instructions, Creative Mail option should have been toggled "OFF" by default on "Business Details step" for African countries during OBW setup

## Video:
https://user-images.githubusercontent.com/41110392/112361954-ea43f680-8cf9-11eb-9580-c0df78fe55da.mp4

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://melted-nurse.jurassic.ninja
Site address (URL): https://melted-nurse.jurassic.ninja
WC Version: 5.1.0
REST API Version: ? 5.1.0
WC Blocks Version: ? 4.4.3
Action Scheduler Version: ? 3.1.6
WC Admin Version: ? 2.2.0-beta.2
Log Directory Writable: ?
WP Version: 5.7
WP Multisite: ñ
WP Memory Limit: 256 MB
WP Debug Mode: ?
WP Cron: ?
Language: en_US
External object cache: ñ

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.16
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: ñ
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ?
fsockopen/cURL: ?
SoapClient: ?
DOMDocument: ?
GZip: ?
Multibyte String: ?
Remote Post: ?
Remote Get: ?

### Database ###

WC Database Version: 5.1.0
WC Database Prefix: wp_
Total Database Size: 5.55MB
Database Data Size: 4.07MB
Database Index Size: 1.48MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 3.05MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
page: 6
post: 2
product: 18
product_variation: 7

### Security ###

Secure connection (HTTPS): ?
Hide errors from visitors: ?

### Active Plugins (15) ###

Query Monitor: by John Blackbourn ñ 3.6.7
Companion Plugin: by Osk ñ 1.18
Creative Mail by Constant Contact: by Constant Contact ñ 1.3.5
Facebook for WooCommerce: by Facebook ñ 2.3.3
Jetpack by WordPress.com: by Automattic ñ 9.5
Google Ads & Marketing by Kliken: by Kliken ñ 1.0.7
Mailchimp for WooCommerce: by Mailchimp ñ 2.5.1
My Custom Functions: by Space X-Chimp ñ 4.49
Paystack WooCommerce Payment Gateway: by Tunbosun Ayinla ñ 5.7.2
WooCommerce Admin: by WooCommerce ñ 2.2.0-beta.2
WooCommerce Admin Test Helper: by WooCommerce ñ 0.1.0-dev
WooCommerce Beta Tester: by WooCommerce ñ 2.0.2
WooCommerce Payments: by Automattic ñ 2.1.1
WooCommerce Shipping & Tax: by Automattic ñ 1.25.9
WooCommerce: by Automattic ñ 5.1.0 (update to version 5.2.0-beta.1 is available)

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic ñ 4.1.9
Hello Dolly: by Matt Mullenweg ñ 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: ñ
Force SSL: ñ
Currency: ZAR (R)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ñ

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ? Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ? ñ If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ?

### Templates ###

Overrides: ñ

### Action Scheduler ###

Complete: 5
Oldest: 2021-03-24 14:03:34 +0000
Newest: 2021-03-24 14:48:43 +0000


### Status report information ###

Generated at: 2021-03-24 16:16:04 +00:00
`
```
</details>

**Comment by louwie17** [comment] 2021-03-25 17:53
I can't reproduce this on a fresh install, going through the OBW flow for the first time shows Mailpoet as selected and Creative mail as unselected.
From the video it appears that it is showing persisted values from a previous OBW completion.

This is expected behaviour in my opinion, as each step is not reset when going through the flow again.
Closing this.

**Closed by louwie17** 2021-03-25 17:53 UTC

**Comment by gglobalstep** [comment] 2021-04-14 10:20
> I can't reproduce this on a fresh install, going through the OBW flow for the first time shows Mailpoet as selected and Creative mail as unselected.
> From the video it appears that it is showing persisted values from a previous OBW completion.
> 
> This is expected behaviour in my opinion, as each step is not reset when going through the flow again.
> Closing this.

@louwie17 I am able to reproduce this issue on a fresh install when going through the OBW setup for the first time.
Please refer to the video for reference

https://user-images.githubusercontent.com/41110392/114695336-21298d00-9d39-11eb-8d4f-67f803ff4893.mp4
