### ISSUE TITLE
[4.0 beta1] New OBW: Tax doesn't get enabled when selected to be automatically setup via Tax Task

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#3692] opened 2020-02-10 12:04 UTC
**Describe the bug**

Testing 4.0 beta1 pre-public release. New OBW: Tax doesn't get enabled when selected to be automatically setup via Tax Task. 

**To Reproduce**

1. Go through the new OBW;
2. Make sure to select to proceed with WooCommerce Services activated on the site during OBW:

![Screen Shot 2020-02-10 at 11 26 47 AM](https://user-images.githubusercontent.com/19143190/74148017-5b127700-4bfc-11ea-95a5-93a0f817481b.png)

3. On the task list, select to setup tax:

![tax1](https://user-images.githubusercontent.com/19143190/74148214-cc522a00-4bfc-11ea-8d2c-25d734e3f9a3.jpg)

4. On the presented screen to select `Yes please` to enable automatic taxes:

![tax2](https://user-images.githubusercontent.com/19143190/74148243-e2f88100-4bfc-11ea-91f5-b1cc21265fde.jpg)
 
5. Note that you'd get a message that it was done:

![tax3](https://user-images.githubusercontent.com/19143190/74148266-f86dab00-4bfc-11ea-98cb-b03411503530.jpg)

6. Navigate to `WooCommerce / Settings / General` and note that taxes actually didn't get enabled. I waited longer (10 minutes) in case there is a delay but taxes don't get enabled:

![tax4](https://user-images.githubusercontent.com/19143190/74148326-1b985a80-4bfd-11ea-86cb-60b82bb78223.jpg)

7. If you enable taxes on that screen manually ^, the automated tax is selected as a default option which is expected:

![tax5](https://user-images.githubusercontent.com/19143190/74148467-63b77d00-4bfd-11ea-8bde-c501af6715c8.jpg)

**Expected behavior**

I expected taxes to be enabled automatically when the Tax task is setup via OBW task list. 

**Screenshots**

See above. 

**WordPress (please complete the following information):**

* Core version: 5.3.2
* Gutenberg version (if installed): not installed
* WooCommerce version: 4.0 beta1
* WooCommerce Blocks version: not installed
* Site language: English
* Any other plugins installed: Jetpack by WordPress.com

**Desktop (please complete the following information):**

* OS: macOS Catalina v 10.15.3
* Browser: Chrome
* Version: 80.0.3987.87 (Official Build) (64-bit)

**Additional context**

Beta 4.0 was not released to the public yet - this is found during testing the package we tagged before tagging beta and releasing it to the public.

**Comment by timmyc** [comment] 2020-02-13 18:57
@joshuatf could this possibly be related to the cache issues?

**Comment by joshuatf** [comment] 2020-02-13 20:20
@timmyc Probably not since the caching issue we ran into before only affects getting, but POST requests to update data _usually_ works as expected.

Will test this one more tomorrow- having a little trouble with Jetpack on JN sites at the moment.

**Comment by psealock** [comment] 2020-02-14 03:36
I can reproduce this one using Ephemeral sites

**Comment by joshuatf** [comment] 2020-02-14 08:37
>I can reproduce this one using Ephemeral sites

On second thought, maybe @timmyc's suspicion was correct.  @psealock If you flush the object cache on that site, does that resolve the issue?

**Comment by psealock** [comment] 2020-02-16 23:00
I flushed the object cache before clicking "Yes, please" and the request to save settings with the following payload returns 🍏 200.

![Screen Shot 2020-02-17 at 11 31 29 AM](https://user-images.githubusercontent.com/1922453/74614084-b357f480-5179-11ea-86df-70923d126f88.png)

I can confirm the option is saved correctly

```
wp option get wc_connect_taxes_enabled
// yes
```

But the "Enable tax rates and calculations" settings remains unchecked.

**Comment by joshuatf** [comment] 2020-03-06 11:37
Thanks for taking the time to outline this issue, @juliaamosova!  This issue is resolved via https://github.com/woocommerce/woocommerce-admin/pull/3795.

**Closed by joshuatf** 2020-03-06 11:37 UTC
Labels: Onboarding, [Type] Bug
