### ISSUE TITLE
Variable Product analytics shows variations of all products instead of the selected product's variations.

### ISSUE THREAD

**Issue by anant1811** [woocommerce/woocommerce-admin#6230] opened 2021-01-29 10:00 UTC
**Describe the bug**

When you go to Analytics > Products and select a single variable product, it would show variations of all the products under the "Variations" section. Previously (WooCommerce version 4.5.0) only used to show the variations of the selected product in "Variations" section. 

Screenshot with WooCommerce version 4.9.2:

![https://d.pr/i/9AONVp](https://d.pr/i/9AONVp+) 
Full Size: https://d.pr/i/9AONVp

Screenshot with WooCommerce version 4.5.0:

![https://d.pr/i/3Xkdsp](https://d.pr/i/3Xkdsp+) 
Full Size: https://d.pr/i/3Xkdsp

**To Reproduce**

1. On a store, make sure that you have orders for multiple variable products (say Variable Product 1, Variable Product 2)
2. Go to Analytica > Products, and filter only the report for "Variable Product 1". 
3. You will notice that variations of Variable Product 2 is also showing under the "Variations" section. 
4. Now roll back WooCommerce to version 4.5.0 and check the same report. You will see the "Variations" section only shows variations of "Variable Product 1". 

**Expected behavior**

The variations section should only show variations of the selected variable product. 

Reported in 3661403-zen

**Comment by adrianduffell** [comment] 2021-02-11 05:17
Hi @anant1811 ,

Thanks for raising the issue and providing the steps to reproduce. Confirming we can reproduce the behavior.

The issue is also reported in https://github.com/woocommerce/woocommerce-admin/issues/6006.  I have now linked the issues together and will close this one down to consolidate efforts. Please continue tracking the progress in the other issue.

**Closed by adrianduffell** 2021-02-11 05:17 UTC
Labels: type: bug
