### ISSUE TITLE
after i installed a new admin plugin, backend not work

### ISSUE THREAD

**Issue by hamtek4me** [woocommerce/woocommerce-admin#2097] opened 2019-04-22 14:34 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

**Smartphone (please complete the following information):**

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Additional context**

**Comment by hamtek4me** [comment] 2019-04-22 14:36
Hi,

after i installed  alpha admin plugin , backend not working
Warning: require_once(/home/zeyaara5/public_html/wp-content/plugins/woocommerce-admin-master//includes/feature-config.php): failed to open stream: No such file or directory in /home/zeyaara5/public_html/wp-content/plugins/woocommerce-admin-master/woocommerce-admin.php on line 237

Fatal error: require_once(): Failed opening required '/home/zeyaara5/public_html/wp-content/plugins/woocommerce-admin-master//includes/feature-config.php' (include_path='.:/usr/local/php71/pear') in /home/zeyaara5/public_html/wp-content/plugins/woocommerce-admin-master/woocommerce-admin.php on line 237

**Comment by rrennick** [comment] 2019-04-22 15:10
Duplicate of #2053.

**Closed by rrennick** 2019-04-22 15:10 UTC
