### ISSUE TITLE
Add e2e test coverage for Marketing Hub flows

### ISSUE THREAD

**Issue by jconroy** [woocommerce/woocommerce-admin#4266] opened 2020-05-01 07:59 UTC
One task we need to loop back to as a follow up to the Marketing Tab MVP work is adding e2e test coverage.

This will become increasingly important for shorter release cycles.

**Comment by ecgan** [comment] 2020-10-22 16:39
Useful reference: [WooCommerce End to End Tests](https://github.com/woocommerce/woocommerce/blob/master/tests/e2e/README.md)

**Comment by ecgan** [comment] 2020-10-22 16:44
@becdetat , I followed your instruction at the [README for end-to-end tests](https://github.com/woocommerce/woocommerce-admin/#end-to-end-tests), when I run `npm run docker:up`, I see the following error message: 

```text
> @woocommerce/admin-library@1.7.0-dev docker:up /Users/engchin/Sites/ganwp1/wp-content/plugins/woocommerce-admin
> npm explore @woocommerce/e2e-environment -- npm run docker:up


> @woocommerce/e2e-environment@0.1.5 docker:up /Users/engchin/Sites/ganwp1/wp-content/plugins/woocommerce-admin/node_modules/@woocommerce/e2e-environment
> ./bin/docker-compose.js up

internal/child_process.js:407
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOTDIR
    at ChildProcess.spawn (internal/child_process.js:407:11)
    at spawn (child_process.js:553:9)
    at Command.executeSubCommand (/Users/engchin/Sites/ganwp1/wp-content/plugins/woocommerce-admin/node_modules/commander/index.js:562:14)
    at Command.parse (/Users/engchin/Sites/ganwp1/wp-content/plugins/woocommerce-admin/node_modules/commander/index.js:488:17)
    at Object.<anonymous> (/Users/engchin/Sites/ganwp1/wp-content/plugins/woocommerce-admin/node_modules/@woocommerce/e2e-environment/bin/docker-compose.js:27:6)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  errno: 'ENOTDIR',
  code: 'ENOTDIR',
  syscall: 'spawn'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @woocommerce/e2e-environment@0.1.5 docker:up: `./bin/docker-compose.js up`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @woocommerce/e2e-environment@0.1.5 docker:up script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Not sure if you are able to shed some light on this please?

**Comment by becdetat** [comment] 2020-10-26 23:14
@ecgan Sorry, I can't reproduce this on `main`. A bit of googling found [this](https://github.com/sindresorhus/execa/issues/164#issuecomment-450264954) which seems to indicate that perhaps something is not installed. Probably an obvious question, but do you have docker installed?

**Comment by ecgan** [comment] 2020-10-27 06:35
@becdetat , thanks for checking out. Yeah I do have Docker Desktop for Mac installed.

**Comment by rrennick** [comment] 2020-10-28 18:23
The latest version of `@woocommerce/e2e-environment` is [0.1.6](https://www.npmjs.com/package/@woocommerce/e2e-environment). Do you have mismatched versions due to stale branches or installed packages?

**Comment by ecgan** [comment] 2020-10-29 09:41
@rrennick , yeah I do have @woocommerce/e2e-environment at version 0.1.6.

To be sure, here's what I did just now: 

1.  Checkout the main branch. 
2. Run `composer install`, `npm install` and `npm run build`.
3. Make sure my Docker Desktop for Mac is running.
4. Run `npm run docker:up`, and I see the error message posted above.

**Comment by rrennick** [comment] 2020-10-29 10:50
@becdetat I got a warning on `npm run build`

```
WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
```

@ecgan I followed your steps after doing a `git pull` on `main`:

```
$ npm run docker:up

> @woocommerce/admin-library@1.7.0-dev docker:up /Users/ronrennick/Sites/solaris/woocommerce-admin
> npm explore @woocommerce/e2e-environment -- npm run docker:up


> @woocommerce/e2e-environment@0.1.6 docker:up /Users/ronrennick/Sites/solaris/woocommerce-admin/node_modules/@woocommerce/e2e-environment
> ./bin/docker-compose.sh up

WordPress 5.5.1
PHP 7.4.11
MariaDB 10.5.6
Creating network "e2e-environment_default" with the default driver
Creating volume "e2e-environment_db" with default driver
Creating volume "e2e-environment_wordpress" with default driver
Building wordpress-cli
.... Step 1 - 13
Successfully built ca1a7deb86e2
Successfully tagged e2e-environment_wordpress-cli:latest
Creating woocommerce-admin_php ... done
Creating woocommerce-admin_db  ... done
Creating woocommerce-admin_wordpress-www ... done
Creating woocommerce-admin_wordpress-cli ... done
Docker exit code: 0
```

The error message above shows version 0.1.5 where my log has 0.1.6

```
@woocommerce/e2e-environment@0.1.5 docker:up: `./bin/docker-compose.js up`
```

**Comment by ecgan** [comment] 2020-11-02 17:05
@rrennick , thanks for checking out, you have a sharp eye there! 😄 

I was looking into the WooCommerce core repository just now and trying to run e2e for it too, and I'm seeing the same error (you can see I have `@woocommerce/e2e-environment@0.1.6` below): 

```text
engchin@engchin-mbp16 woocommerce % npm run docker:up                                           

> woocommerce@4.8.0 docker:up /Users/engchin/Sites/ganwp1/wp-content/plugins/woocommerce
> npm explore @woocommerce/e2e-environment -- npm run docker:up


> @woocommerce/e2e-environment@0.1.6 docker:up /Users/engchin/Sites/ganwp1/wp-content/plugins/woocommerce/tests/e2e/env
> ./bin/docker-compose.sh up

WordPress 5.5.1
PHP 7.4.12
MariaDB 10.5.6
internal/child_process.js:366
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOTDIR
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at spawn (child_process.js:551:9)
    at Command.executeSubCommand (/Users/engchin/Sites/ganwp1/wp-content/plugins/woocommerce/tests/e2e/env/node_modules/commander/index.js:776:14)
    at Command.parse (/Users/engchin/Sites/ganwp1/wp-content/plugins/woocommerce/tests/e2e/env/node_modules/commander/index.js:692:17)
    at Object.<anonymous> (/Users/engchin/Sites/ganwp1/wp-content/plugins/woocommerce/tests/e2e/env/bin/docker-compose.js:27:6)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @woocommerce/e2e-environment@0.1.6 docker:up: `./bin/docker-compose.sh up`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @woocommerce/e2e-environment@0.1.6 docker:up script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/engchin/.npm/_logs/2020-11-02T16_58_58_046Z-debug.log
npm ERR! weird error 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! woocommerce@4.8.0 docker:up: `npm explore @woocommerce/e2e-environment -- npm run docker:up`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the woocommerce@4.8.0 docker:up script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/engchin/.npm/_logs/2020-11-02T16_58_58_069Z-debug.log
```

**Comment by rrennick** [comment] 2020-11-02 17:24
@ecgan did you follow the setup instructions on https://github.com/woocommerce/woocommerce/blob/master/tests/e2e/README.md.

**Comment by ecgan** [comment] 2020-11-03 10:16
@rrennick , yeah I did. 

Specifically:

- I already have Docker Desktop for Mac installed and running. 
- I use valet+ for my local development site, and I use `valet stop` to stop the service already. 
- I use nvm and I'm using node v10.23.0. 
- Then I followed the steps in the [Running Tests section](https://github.com/woocommerce/woocommerce/blob/master/tests/e2e/README.md#running-tests), and I'm stucked at `npm run docker:up` with `Error: spawn ENOTDIR`.

On a slightly related note, last week I tried out [wp-env](https://github.com/WordPress/gutenberg/tree/master/packages/env) and it works like a charm for me. At least this means that my Docker Desktop installation is working okay.

**Comment by rrennick** [comment] 2020-11-03 12:54
@ecgan The error is occurring on this [`program.parse`](https://github.com/woocommerce/woocommerce/blob/master/tests/e2e/env/bin/docker-compose.js#L27) so it's unrelated to docker. If you updated your OS recently did you update/reinstall `Xcode`?

**Comment by tomalec** [comment] 2020-11-03 13:29
I had a different error when tried to run `npm run docker:up`.

<details>
<summary>full trace of my 500 error</summary>
<pre><code>
tomalec@tomalecMBP   ~/repos/woocommerce-admin     main    npm run docker:up

> @woocommerce/admin-library@1.7.0-dev docker:up /Users/tomalec/repos/woocommerce-admin
> npm explore @woocommerce/e2e-environment -- npm run docker:up


> @woocommerce/e2e-environment@0.1.6 docker:up /Users/tomalec/repos/woocommerce-admin/node_modules/@woocommerce/e2e-environment
> ./bin/docker-compose.sh up

WordPress 5.5.3
PHP 7.4.12
MariaDB 10.5.6
Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 259, in _raise_for_status
  File "site-packages/requests/models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 205, in _retrieve_server_version
  File "site-packages/docker/api/daemon.py", line 181, in version
  File "site-packages/docker/api/client.py", line 265, in _result
  File "site-packages/docker/api/client.py", line 261, in _raise_for_status
  File "site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'dial unix docker.raw.sock: connect: connection refused'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 123, in perform_command
  File "compose/cli/command.py", line 69, in project_from_options
  File "compose/cli/command.py", line 132, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "site-packages/docker/api/client.py", line 188, in __init__
  File "site-packages/docker/api/client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: 500 Server Error: Internal Server Error ("b'dial unix docker.raw.sock: connect: connection refused'")
[22547] Failed to execute script docker-compose
Docker exit code: 255
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! @woocommerce/e2e-environment@0.1.6 docker:up: `./bin/docker-compose.sh up`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the @woocommerce/e2e-environment@0.1.6 docker:up script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tomalec/.npm/_logs/2020-11-03T13_18_20_836Z-debug.log
npm ERR! weird error 255
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @woocommerce/admin-library@1.7.0-dev docker:up: `npm explore @woocommerce/e2e-environment -- npm run docker:up`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @woocommerce/admin-library@1.7.0-dev docker:up script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tomalec/.npm/_logs/2020-11-03T13_18_21_143Z-debug.log
</code></pre>
</details>

What helped me, I run `npm run test:e2e-dev` first then `npm run docker:up`.

**Comment by ecgan** [comment] 2020-11-03 13:47
@rrennick , 

> If you updated your OS recently did you update/reinstall Xcode?

Is Xcode required? Apparently I don't have Xcode installed, I only have the Xcode command line tools.

```text
engchin@engchin-mbp16 woocommerce % xcodebuild --version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
engchin@engchin-mbp16 woocommerce % xcode-select -p     
/Library/Developer/CommandLineTools
```

**Comment by rrennick** [comment] 2020-11-03 14:24
> I only have the Xcode command line tools.

That should be fine. OS updates can break that implementation too. It would be worth trying to reinstall the command line tools.

**Comment by samueljseay** [comment] 2021-04-08 09:32
@pmcpinto I see this issue keeps getting reopened, but what is the actual responsibility for us here at this stage?

The original description says

> One task we need to loop back to as a follow up to the Marketing Tab MVP work is adding e2e test coverage.
> This will become increasingly important for shorter release cycles.

I don't think this is enough information to act on right now, maybe we can gather some more detail. @jconroy is there some more detail you can add for us here?

**Comment by pmcpinto** [comment] 2021-04-08 16:20
@samueljseay I think this should be handled by Ventures. @jconroy can you confirm if you want to leave this open?

**Comment by moon0326** [comment] 2022-01-18 21:10
Pining @jconroy 👋  

Do you still want to leave this issue open?

**Comment by ilyasfoo** [comment] 2022-01-24 08:53
Hey, @ecgan!

Is this being worked on? I'm going to close this issue if not since we're grooming our repo.  p90Yrv-2Bc-p2

**Comment by ecgan** [comment] 2022-01-25 08:18
@ilyasfoo , it's not being worked on. I'll proceed to close this issue. Thanks for pinging me on this! 🙏

**Closed by ecgan** 2022-01-25 08:18 UTC
Labels: feature: marketing, Needs triage
