### ISSUE TITLE
Home Screen: Mobile Viewport Header Glitch

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#5980] opened 2020-12-29 19:58 UTC
**Describe the bug**
When scrolling down the Home page on mobile chrome ( but guessing would happen on any narrow viewport ), the wc-admin nav bar, and on an android device the nudge to install the android app, scroll down the screen with me, but the WP Core masterbar does not which creates an odd behavior:

https://cloudup.com/cEdWGqqyBTM

**Smartphone (please complete the following information):**

* Device: Pixel 5
* OS: Android 11
* Browser Chrome

**Comment by louwie17** [comment] 2021-01-26 16:07
Tried to reproduce this on IOS, and in my chrome devtools simulating a Galaxy S5, both places it worked as expected. The WP Core Nav stayed stuck at the top and so did the WooCommerce nav.
![IMG_8EDA683E0C36-1.jpeg](https://images.zenhubusercontent.com/5fa15baa8c308be7f0496579/9a70f7a2-cfe4-4f7d-8caa-716c79f0abb6)

**Comment by timmyc** [comment] 2021-01-27 21:22
I just tested again on my Android device ( Pixel 5 ) and the bug is still present in 4.9.

**Comment by joshuatf** [comment] 2021-01-28 21:14
Estimate: 1

However, this is the 5th bug related to header height in this sprint.  I'd strongly recommend we look at a way to better get and set the height of the header.  And in that case, the estimate is closer to a 3.

**Comment by timmyc** [comment] 2021-01-30 00:46
Removing from this cycle per the discussion to do the header height management spike instead in #6235

**Comment by samueljseay** [comment] 2021-04-08 09:43
If this is closed: https://github.com/woocommerce/woocommerce-admin/issues/6235 can we close this ticket?

**Comment by chihsuan** [comment] 2022-01-17 06:25
I'm going to close this since the issue has been fixed in #6235 and it's over 6 months without any updates.

**Closed by chihsuan** 2022-01-17 06:25 UTC
Labels: type: bug, feature: home screen
