### ISSUE TITLE
There was an error installing Jetpack. Please try again.

### ISSUE THREAD

**Issue by thenbrent** [woocommerce/woocommerce-admin#4428] opened 2020-05-22 03:00 UTC
**Describe the bug**

When completing the onboarding Wizard (OBW) for a new store with WooCommerce v4.1.1, I receive the following error when after attempting to install Jetpack:

> There was an error installing Jetpack. Please try again.

This error occurs frequently, but not always. Out of 8-10 tests, all on JN, I was able to successfully install Jetpack once. All other plugins appear to install without error.

**To Reproduce**

Video reproducing issue: https://d.pr/v/Bybw1g

1. Go to JN Special Ops PCYsg-g6b-p2
2. Click on **Include Jetpack** to uncheck it (we want it to be installed during WC's OBW)
3. Click **Include WooCommerce**
4. Click **Launch single site**
5. Wait.
6. Click **The new WP is ready to go, visit it!**
7. Click **Run the setup Wizard**
8. Fill in details...
9. On the Jetpack step, click **Yes please!**

**Expected behavior**

I expected Jetpack to be installed and the connection flow to begin.

**Screenshots**

![Image upload on 2020-05-22 at 12-55-58](https://user-images.githubusercontent.com/235523/82626617-a12f9b80-9c2b-11ea-9d63-63591afad877.png)

Full video: https://d.pr/v/Bybw1g

**Desktop (please complete the following information):**

* Mac OS
* Firefox
* 76.0.1

**Additional context**

Related to #4363. Possibly related to: #4399.

**Comment by joshuatf** [comment] 2020-05-22 09:26
Hey @thenbrent thanks for logging this issue and for the video!

I think this may be related or a duplicate of https://github.com/woocommerce/woocommerce-admin/issues/3470. I think there are quite a few issues related to this floating around, but more reproducible steps, like that in this issue, are always a good thing.

If you have time, can you try this branch out and see if it resolves things for you?  https://github.com/woocommerce/woocommerce-admin/pull/4411. After checking out run `npm run test:zip` in the plugin's root directory to build a zip file for upload.

I've tested a number of times on JN and so far it seems to be installing without fail. 🤞

**Comment by samueljseay** [comment] 2020-11-18 02:53
I'm going to close this one for now due to inactivity, please feel free to reopen if you can still reproduce this.

**Closed by samueljseay** 2020-11-18 02:53 UTC
Labels: Onboarding, [Type] Bug
