### ISSUE TITLE
Get warning on Coupon page

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#5066] opened 2020-08-31 20:01 UTC
@kishanjasani commented on [Mon Aug 31 2020](https://github.com/woocommerce/navigation/issues/71)

Reproduce issue steps: 
Install the latest WordPress version
Theme: Twenty Twenty 

- Now Click on `Woo-Commerce`.
- Inside that Click on `Coupons`.
- Now Check the console of your browser.

You will get 2 Warnings: 
- `Warning: Invalid DOM property fill-rule. Did you mean fillRule?`
- `Warning: Invalid DOM property clip-rule. Did you mean clipRule?`

---

@joshuatf commented on [Mon Aug 31 2020](https://github.com/woocommerce/navigation/issues/71#issuecomment-684006365)

Hi @kishanjasani - thanks for noting that issue.  This repository is for the new WooCommerce navigation experience.  I think the issue you mentioned may be stemming from the new marketing pages in WooCommerce Admin, so I'll move this issue over there.

**Comment by jconroy** [comment] 2020-09-01 04:59
Possibly a dupe of https://github.com/woocommerce/woocommerce-admin/issues/4864 ?

Fixed in https://github.com/woocommerce/woocommerce-admin/pull/4889

I don't think those edits made it into 1.4

**Comment by becdetat** [comment] 2020-09-01 23:47
Correct, this has been fixed in WooCommerce Admin 1.5.0 which should be released next week for inclusion in WooCommerce 4.5. Thanks for reporting it @kishanjasani 👍

**Closed by becdetat** 2020-09-01 23:47 UTC
