### ISSUE TITLE
Analytics' "Orders" View Shows Duplicates if Filtering by Multiple Products

### ISSUE THREAD

**Issue by dphyled** [woocommerce/woocommerce-admin#6499] opened 2021-03-03 05:48 UTC
**Describe the bug**
If you have an order with multiple products, and you view **Analytics > Orders** then apply an Advanced Product Filter for multiple products, the list of orders will show a line in the results for each of the products that matches in that order.

**To Reproduce**

1. Place an order for 2 different products
2. Go to **Analytics > Orders**, and add a filter for those two products:

![Screenshot](https://d.pr/i/kAkh9Q+)
Screenshot direct link: https://d.pr/i/kAkh9Q

3. Check the list of orders, and see that it lists the order multiple times:

![Screenshot](https://d.pr/i/MlxQV6+)
Screenshot direct link: https://d.pr/i/MlxQV6

**Expected behavior**
I would expect it to filter out the list of orders for each product added, but still only show each Order once in the list.

**Desktop (please complete the following information):**

* OS: MacOS
* Browser Chrome
* Version 88.0.4324.192

**Comment by ilyasfoo** [comment] 2021-03-05 04:40
I'm able to reproduce this. It seems that the query is producing a union-like resultset that simply combines all orders from each of the filter value. I've tried adding a grouped product to the filter, and it just adds another row of the same order.

![image](https://user-images.githubusercontent.com/3747241/110068039-d4ed4380-7daf-11eb-96bc-8151200cc3f4.png)

**Comment by AashikP** [comment] 2021-08-17 04:17
Another report in 4210472-zen

**Comment by chihsuan** [comment] 2022-02-08 06:27
I was not able to reproduce this on the main branch. I think this has been fixed.

![Screen Shot 2022-02-08 at 14 20 45](https://user-images.githubusercontent.com/4344253/152930434-1ca369ce-7402-4e5f-abaa-4fdedb12bd58.png)

**Comment by chihsuan** [comment] 2022-02-08 06:28
I'm going to close this. @dphyled  Please feel free to reopen this if you're still encountering this issue with the latest version. Thanks!

**Closed by chihsuan** 2022-02-08 06:28 UTC
Labels: type: bug, feature: analytics, Needs triage
