### ISSUE TITLE
[WC 4.6] Store setup shortcut briefly appears on existing activity panel and after dismissing the setup tasks

### ISSUE THREAD

**Issue by tammullen** [woocommerce/woocommerce-admin#5395] opened 2020-10-15 13:04 UTC
**Describe the bug**
Just a minor annoyance, when loading a page that would contain the activity panel you briefly see the store setup icon before it vanishes.
 
**To Reproduce**

1. Upgrade an existing site with activity panel to 4.6
2. Click on a page with activity panel e.g `Orders`
3. See `Inbox` and `Store Setup` shortcut appear briefly in activity panel before the full expected activity panels of `Inbox`, `Orders`, `Stock`, `Reviews` appear. 

or

1. On a new install of 4.6 dismiss the setup task list before completing
2. Click on a page with activity panel e.g `Orders`
3. See `Inbox` and `Store Setup` shortcut appear briefly in activity panel before only (as noted in https://github.com/woocommerce/woocommerce-admin/issues/5393) `Inbox`appears. 

**Expected behavior**
We don't see Store Setup shortcut at all when we aren't expecting it.

**Screenshots**
![Screen Recording 2020-10-15 at 13 35 17 2020-10-15 13_53_24](https://user-images.githubusercontent.com/24649833/96129626-c5e42280-0eee-11eb-8f0b-173077076499.gif)
![Screen Recording 2020-10-14 at 18 44 33 2020-10-15 13_56_03](https://user-images.githubusercontent.com/24649833/96129635-c8df1300-0eee-11eb-9a18-2884a59ed0ad.gif)

**Desktop (please complete the following information):**

MacOS and Chrome

**Comment by timmyc** [comment] 2020-10-20 22:25
Since the activity panels are going to migrate to the home screen in the next release, I'm thinking this one will likely not be fixed. Confirmed it is still happening in 4.6.1

**Comment by pmcpinto** [comment] 2020-11-25 16:51
I agree with Timmy. I'll close this one

**Closed by pmcpinto** 2020-11-25 16:51 UTC
