### ISSUE TITLE
Calling statistics for orders five years back let server crash

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce-admin#4919] opened 2020-08-03 15:14 UTC
I use the new admin in WC seldom, statistics module too. But today I thought I could use it and requested a list of products from a category five years back. After few minutes of seeing the rotating arrow I tried moving back to other page in admin. But the arrow stayed on screen, even I tried to go back to frontend.

Then I tried to go another of my sites on same server – it is a rented managed server for only my sites –, no site was responding. Than I went over to server management and there I called mySQL admin. But same. Datebase did not respond. It seems, I crashed with this action the whole server.

Any idea?

**Comment by ajgw** [comment] 2020-08-03 16:30
@juliaamosova you are right. But because it is now part of WC and I have no way to ban it from my store I like to submit this issue here.

**Comment by timmyc** [comment] 2020-08-04 17:36
@ajgw - thanks for taking the time to submit the issue and sorry you encountered a performance problem. I'd like to ask a few more questions to get a sense of what led to the performance issue if possible.

> I thought I could use it and requested a list of products from a category five years back

To clarify here, when you did this, did you select a date range of five years - i.e. set the start date in the date range picker to a date in say July of 2015, and the end date in July 2020?

Also could you give me a rough estimate of the quantity of orders your store has on an annual basis, and also maybe an average number of products per orders would be insightful too.

> But because it is now part of WC and I have no way to ban it from my store I like to submit this issue here.

The feature can be disabled via a filter if you would rather it not be present on the site, but it would remove a great deal of new functionality in WooCommerce.

I'm also curious if you have encountered any other performance issues with reports in smaller date ranges ( less than a year ).

Thanks in advance for any further info.

**Comment by ajgw** [comment] 2020-08-05 07:54
Hi @timmyc 
well in shop are only orders from 2017 to today. In summary there are about 300 orders with 5400 items. This is really a small store. If I call dashboard page under WooCommerce it needs two to five seconds to display totals and orders for the actual month. Very slow.
If I call orders for the range from 2015 to 2020 under old reports page, the results display instantly. So I can report that in my case the new statistics and reports coming from wc-admin are very, very slow.

I have a managed server for around 30 sites with low traffic. My site has 512 MB of RAM associated from a total of 2 GB of RAM in server and I use PHP 7.4.x. It seems that MySQL, which runs on a dedicated SSD, is the bottleneck in case of wc-admin.

**Comment by timmyc** [comment] 2020-08-05 18:44
Thanks so much for the further details @ajgw - definitely seems like something is not performing well indeed. Would it be possible for you to share a WooCommerce System Status Report with us? That might yield some clues, or at the very least allow us to try and reproduce the slow-down because given the stats you shared of the quantity of orders it seems like it should be able to handle that just fine as we have tested out the reports on much higher volume stores than that ( like on WooCommerce.com ).

**Comment by ajgw** [comment] 2020-08-06 06:41
Hi Timmy, this is the report. But beware, I have few client sites on other hardware but same hoster which has same issue. So I think it is more a server setup which your code not fetch.



Mit Gruss aus Bremerhaven an der Nordsee,
Adrian Wackernah

Tel. 0151-2404 3961

https://atelier-an-der-muehle.de <https://atelier-an-der-muehle.de/>

**Comment by timmyc** [comment] 2020-08-06 16:28
Thanks @ajgw - interesting so perhaps something in the database config on the host that might be causing the issues.

**Comment by austress99** [comment] 2020-08-08 08:53
Yes I'm sorry

**Comment by chihsuan** [comment] 2022-01-17 04:20
I'm going to close this since this bug is over 6 months old without updates and it seems that we don't have things to help.

**Closed by chihsuan** 2022-01-17 04:20 UTC
Labels: type: bug, feature: analytics, category: performance
