### ISSUE TITLE
More Net-Revenue issues -- might be related to issue #2855

### ISSUE THREAD

**Issue by JScott-MSI** [woocommerce/woocommerce-admin#2918] opened 2019-09-12 00:20 UTC
**Describe the bug**
Look for a single product sold under the Analytics -> Products report. The report gives Net- Revenue and the total orders and total items sold. 

Run the same report using the Legacy reporting and the Net Revenue is different.

In the Analytics -> Products report, click on the Orders link, which opens into the Analytics -> Orders and the Net-Revenue is different (and matches the Legacy report). If you look at the specific orders listed, in certain orders, the product searched on was fulfilled at no charge and is the difference.

**Expected behavior**
Net Revenue totals should match in the reports... and should match the Legacy reports where appropriate.

**Screenshots**
Screen #1 Shows Legacy Report of Sales by Product
![Products Sold Net legacy](https://user-images.githubusercontent.com/52297130/64744167-9aa32e80-d4b7-11e9-940d-fbadfae1c79d.jpg)

Screen # 2 Shows Analytics-> Product Report - Net Revenue does not match Legacy or Order Drill-down
![Products Sold Net](https://user-images.githubusercontent.com/52297130/64744203-ba3a5700-d4b7-11e9-810d-b7ed23fd4f2d.jpg)

Screen # 3 Shows Drill-down into Orders from the Analytics-> Product report -- Matches Legacy but not Analytics Product Report -- If you add the Retail price of $399.95 for each of the $0.00 orders to the $1,064.90 it totals $2,664.70
![Orders Sold Net_1](https://user-images.githubusercontent.com/52297130/64744243-db02ac80-d4b7-11e9-83e6-12769fe75b8f.jpg)

**Desktop (please complete the following information):**

* OS: IOS
* Browser Firefox
* Version Latest

**Additional context**
This may be related to  issue #2855 where Net Revenue totals did not match.

**Comment by psealock** [comment] 2019-09-24 23:07
Thanks again @JScott-MSI for the detailed report!

I can reproduce this. It appears Coupons are not calculated correctly in the Product Report.

1. Create an order for a product today and use a coupon to cover 100% of the cost.
2. Revenue > Date Range > Today
3. See the Net revenue correctly display $0.00
4. Products > Single Product > Search for the product purchased
5. See the Net revenue show the cost of the product

**Comment by JScott-MSI** [comment] 2019-09-25 15:03
I see that you have the word "coupons" lined out, while coupons may be the instrument by which an order total is set to $0.00, in our case we don't utilize coupons for that purpose. Most of our $0.00 orders are manual orders discounted to $0.00 on the backend. I think the issue lies in $0.00 orders regardless how they were created.

**Comment by rrennick** [comment] 2019-09-25 15:36
@JScott-MSI Thanks for that additional info

> Most of our $0.00 orders are manual orders discounted to $0.00 on the backend.

I didn't dig into the code but that sounds like a fallback issue where there is a check if the price is non-zero vs exists.

**Comment by rrennick** [comment] 2019-10-24 14:25
> Most of our $0.00 orders are manual orders discounted to $0.00 on the backend.

@JScott-MSI How do you discount them to $0.00?

**Comment by JScott-MSI** [comment] 2019-10-24 16:54
Manual order entry…. Manually add product, set line item total to $0.00

**Comment by rrennick** [comment] 2019-10-24 19:59
> Manually add product, set line item total to $0.00

This should now be addressed in https://github.com/woocommerce/woocommerce-admin/pull/3095/commits/dee313e501358d8e20720e505fdbc94004a3fa3e . I added the commit to that branch because 2 PRs would have had conflicts.

Once that PR is merged we can revisit this issue to see if there are any outstanding items.

**Comment by rrennick** [comment] 2019-11-14 20:20
@JScott-MSI Could you check version 0.22.0 to see if it addresses the calculation issues you identified?

**Comment by rrennick** [comment] 2019-11-21 13:14
I'm going to close this one for lack of feedback. We're happy to re-open if this is still an issue.

**Closed by rrennick** 2019-11-21 13:14 UTC
Labels: [Many] Large, [Much] Small, [Priority] High, [Status] Needs feedback, [Type] Bug

**Comment by JScott-MSI** [comment] 2019-11-21 17:00
I’ll run some tests, I was out of the office for the past 10 days...
