### ISSUE TITLE
Activity Panels: Visual Issues on Narrow Viewport / Safari / Mobile Chrome

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#5556] opened 2020-11-06 22:47 UTC
**Describe the bug**
When playing around with the 1.7.0 pre-beta build, I saw a variety of glitches around the activity panels in narrow viewports on Safari. Confirmed some of the same things are happening in chrome on my Pixel 5 ( OMG I LOVE THE NEW PHONE BTW!!! )

__Safari 14, Narrow Viewport Examples__
<img width="575" alt="narrow-viewport-activity-panel-jank" src="https://user-images.githubusercontent.com/22080/98421568-7bae1700-203e-11eb-86f9-8a01d9e4fe80.png">

https://cloudup.com/cSm7uej917R

__Chrome on Android__

![Screenshot_20201106-143925](https://user-images.githubusercontent.com/22080/98421715-d3e51900-203e-11eb-9960-9e20382fd94d.png)

**To Reproduce**
Using 1.7.0-beta, interact with the activity panel "w" icon on small viewports or on mobile devices.

**Comment by timmyc** [comment] 2020-11-09 20:55
Confirmed that this is not a regression, and is happening in 4.6.x as well. Didn't test further back then that but giving this a low priority over bugs that were introduced in 1.7 or are related to new features.

**Comment by chihsuan** [comment] 2022-01-13 07:48
I'm closing this since this is over 6 months and I couldn't reproduce on the main branch.


![Screen Shot 2022-01-13 at 15 47 51](https://user-images.githubusercontent.com/4344253/149287654-61212bb2-5f0a-4688-8286-419cf5bef80c.png)

**Closed by chihsuan** 2022-01-13 07:48 UTC
Labels: type: bug, feature: activity panel, priority: low
