### ISSUE TITLE
[GlobalStep - WooCommerce Admin 2.1 Beta 1] Randomly error message “Could not install mailchimp-for woocommerce, creative-mail-by-constant-contact plugin...” is displayed upon clicking “Continue” button on Business details->Free features step during Onboarding wizard setup.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#6425] opened 2021-02-23 17:25 UTC
## Bug Description:
Randomly error message “Could not install mailchimp-for woocommerce, creative-mail-by-constant-contact plugin...” is displayed upon clicking “Continue” button on Business details->Free features step during Onboarding wizard setup.

## Environment:
Windows 10, macOS High Sierra v10.13.6
Browser: Chrome(Version 88.0.4324.104) (64-bit)
                Firefox(Version 83.0)(64-bit)
                Safari: v13.1.2(13609.3.5.1.5)

## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate WooCommerce, WooCommerce Admin 2.1 Beta Plugin.
1. Complete the Onboarding setup wizard till "Business details-Free features".
1. Click on "Continue" button.
1. Observe that randomly error message “Could not install mailchimp-for woocommerce, creative-mail-by-constant-contact plugin...” is displayed upon clicking “Continue” button on Business details->Free features step during Onboarding wizard setup.

## Actual Result:
Randomly error message “Could not install mailchimp-for woocommerce, creative-mail-by-constant-contact plugin...” is displayed upon clicking “Continue” button on Business details->Free features step during Onboarding wizard setup.

## Expected Result:
No error message should display upon clicking “Continue” button on Business details->Free features during Onboarding wizard setup.

## Attachment (Video):
https://user-images.githubusercontent.com/41110392/108882350-4e579a00-762a-11eb-9c67-9e2bf127ec4a.mov

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://physical-louse.jurassic.ninja
Site address (URL): https://physical-louse.jurassic.ninja
WC Version: 5.0.0
REST API Version: ✔ 5.0.0
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.1.0-beta.1
Log Directory Writable: ✔
WP Version: 5.6.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.15
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.0.0
WC Database Prefix: wp_
Total Database Size: 3.78MB
Database Data Size: 2.38MB
Database Index Size: 1.40MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.48MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 6
post: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (11) ###

Companion Plugin: by Osk – 1.18
Creative Mail by Constant Contact: by Constant Contact – 1.3.2
Facebook for WooCommerce: by Facebook – 2.3.0
Jetpack by WordPress.com: by Automattic – 9.4
Google Ads & Marketing by Kliken: by Kliken – 1.0.7
Mailchimp for WooCommerce: by Mailchimp – 2.5.0
WooCommerce Admin: by WooCommerce – 2.1.0-beta.1
WooCommerce Payments: by Automattic – 2.0.0
WooCommerce PayPal Payments: by WooCommerce – 1.1.0
WooCommerce Shipping & Tax: by Automattic – 1.25.7
WooCommerce: by Automattic – 5.0.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.8
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2021-02-23 13:04:24 +0000
Newest: 2021-02-23 13:04:24 +0000

`
```
</details>

**Comment by adrianduffell** [comment] 2021-02-25 05:27
I was not able to reproduce this on a Jurassic Ninja site. I wonder if it was caused by JN reliability issues at the time.

That said, the error reporting in the video could be better. Messages are repeated, and a success message is shown despite the failures above it.

<img width="1018" alt="Screen Shot 2021-02-25 at 1 20 11 pm" src="https://user-images.githubusercontent.com/9312929/109107339-7fd87e80-776c-11eb-855d-85efb168febe.png">

I will close this out and create a separate issue about the error reporting.

**Closed by adrianduffell** 2021-02-25 05:27 UTC

**Comment by gglobalstep** [comment] 2021-03-15 12:23
> I was not able to reproduce this on a Jurassic Ninja site. I wonder if it was caused by JN reliability issues at the time.
> 
> That said, the error reporting could be better. In the video, messages are repeated, and a success message is shown despite the failures above it.
> 
> <img alt="Screen Shot 2021-02-25 at 1 20 11 pm" width="1018" src="https://user-images.githubusercontent.com/9312929/109107339-7fd87e80-776c-11eb-855d-85efb168febe.png">
> 
> I will close this out and create a separate issue about the error reporting.

Observed the same issue for the following Environment:
Environment:
Woocommerce Version: WooCommerce 5.1 and 5.0
WordPress version: (v5.7)
WooCommerce Admin version: v2.1.3 

PC:
Windows 10, Mac 10.14.6
Chrome(Version 88.0.4324.104) 
Firefox(Version 86.0)
Safari: v13.1.1

![Screen Shot 2021-03-15 at 4 23 57 PM](https://user-images.githubusercontent.com/41110392/111152706-0a1b4200-85b7-11eb-8a32-c95af58f6f6c.png)
