### ISSUE TITLE
[WC 4.6 RC1] OBW: Presenting user with tracks after the user clicks on the option to exist Setup Wizard feels a bit out of order

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#5250] opened 2020-10-01 20:43 UTC
**Is your feature request related to a problem? Please describe.**

If you skip the setup wizard on the very first onboarding page, you are still presented with a pop-up to agree to participate in tracks. Once you get passed that, only then you are escaping from onboarding.

It is not a huge deal but feels a bit strange that after trying to exit onboarding you are still presented with something else which is in the onboarding section. Makes you wonder if skipping setup wizard work at all:

![](http://g.recordit.co/HAfMf7j5LI.gif)

**Describe the solution you'd like**

Not immediately sure. It is possible that the user won't be back to onboarding which is the only place where we ask them if they are OK to share data. If the user won't get back to onboarding, we are losing the opportunity to get that data permission. 

Perhaps we can show a prompt or notice in the Home Screen?

**Describe alternatives you've considered**

N/A. 

**Should this be prioritized? Why?**

Not a huge deal so I don't think this needs to be worked on right away. 

**Additional context**

N/A.

**Comment by pmcpinto** [comment] 2020-10-02 09:56
Thanks for your feedback. I'm going to close this one, as this is working as intended. We choose to display as a modal to keep it consistent with the approach that we have for users that decide to proceed with the store profiler. So both segments will see the option at the same stage using the same approach

**Closed by pmcpinto** 2020-10-02 09:56 UTC
