### ISSUE TITLE
SelectControl: Can't select options by clicking on underlined option text in Firefox or Safari

### ISSUE THREAD

**Issue by Pumpk1in** [woocommerce/woocommerce-admin#4209] opened 2020-04-24 10:19 UTC
Hi.

You can't filter by products when inside /admin.php?page=wc-admin&path=%2Fanalytics%2Fproducts

Also, same problem in categories when you want to filter by single cat... or in coupons when you want to filter with specific coupons. Any filter that needs you to fill an ajax text field will not work on Safari or Firefox.

**To reproduce the behavior:**
1. Use Safari 13 or Firefox
2. Go to the analytics products page
3. Open the "Show" filter
4. Select "Single product"
5. Type something
6. Select the product you want with a mouse click by **clicking directly on the underlined product name text**
7. It will do absolutely nothing and the text field will just reset.

It works perfectly with Chrome.

Woocommerce 4.0.1
WP 5.4

## Working correctly in Chrome

![Selecting product from search dropdown in Chrome](https://user-images.githubusercontent.com/2098816/83274391-bceef080-a19b-11ea-9c0f-86489339a99d.gif)

## Not working in Firefox

![Selecting product from search dropdown in Firefox](https://user-images.githubusercontent.com/2098816/83274404-c2e4d180-a19b-11ea-9dbf-4c5427b140e3.gif)

[original bug report edited by @mattsherman to provide additional context]

**Comment by psealock** [comment] 2020-05-11 00:23
I'm not able to reproduce this with Safari 13.1. I can select a single product with the mouse as well as keyboard.

@Pumpk1in are there any errors shown in the console?

**Comment by mattsherman** [comment] 2020-05-29 15:05
I can reproduce this in both Safari and Firefox. The bug exists when you click directly on the underlined text for an option in the `SelectControl`.

**Comment by mattsherman** [comment] 2020-05-29 15:08
I'm going to investigate a fix for this, as it manifests itself in many places.

**Closed** 2020-06-01 18:25 UTC
Labels: Components, [Many] Medium, [Much] Large, [Type] Bug
