### ISSUE TITLE
Fatal when WooCommerce is not active

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#1805] opened 2019-03-14 19:39 UTC
**Describe the bug**

With WooCommerce Admin installed and activated, if you disable the WooCommerce core plugin, the following error is thrown:

```
Fatal error: Uncaught Error: Class 'WC_Admin_Reports_Sync' not found in /srv/www/woo-one/public_html/wp-content/plugins/woocommerce-admin/woocommerce-admin.php:127 Stack trace: #0 /srv/www/woo-one/public_html/wp-includes/class-wp-hook.php(286): wc_admin_deactivate_wc_admin_plugin(false) #1 /srv/www/woo-one/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #2 /srv/www/woo-one/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #3 /srv/www/woo-one/public_html/wp-admin/includes/plugin.php(775): do_action('deactivate_wooc...', false) #4 /srv/www/woo-one/public_html/wp-content/plugins/woocommerce-admin/woocommerce-admin.php(116): deactivate_plugins('woocommerce-adm...') #5 /srv/www/woo-one/public_html/wp-includes/class-wp-hook.php(286): wc_admin_possibly_deactivate_wc_admin_plugin('') #6 /srv/www/woo-one/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #7 /srv/www/woo-one/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #8 /srv/ in /srv/www/woo-one/public_html/wp-content/plugins/woocommerce-admin/woocommerce-admin.php on line 127
```

**To Reproduce**

1. Install WooCommerce and WooCommerce Admin
2. Deactivate WooCommerce

**Comment by jeffstieler** [comment] 2019-03-14 21:22
Duplicate of https://github.com/woocommerce/woocommerce-admin/issues/1752.

**Closed by jeffstieler** 2019-03-14 21:22 UTC
Labels: [Type] Bug
