### ISSUE TITLE
Analytics > Orders > download > link not downloading anything

### ISSUE THREAD

**Issue by ns642** [woocommerce/woocommerce-admin#7476] opened 2021-08-02 03:11 UTC
The Analytics plugin has an "orders" tab. In the orders tab, you can select a date range of orders, see a graph, and below that, a line by line summary of orders by customers. This section has a download button which after clicking, says an email with the download will be sent. An email is received with a link to download the report - a new tab opens and closes as though a download would commence, but nothing is downloaded. 

The download should result in a csv file outlining all orders by customer for the selected time period.

**Comment by octaedro** [comment] 2021-08-24 18:29
Thank you @ns642 for reporting this issue. I couldn't reproduce it on my end.
Could you provide more information? How many orders do you have in your store?

**Comment by ns642** [comment] 2021-08-24 22:08
> Thank you @ns642 for reporting this issue. I couldn't reproduce it on my end.
> Could you provide more information? How many orders do you have in your store?

Hi Octaedro,
Thanks for looking into this - it seems after weeks of it not working for me, it successfully downloaded this morning doing nothing different!

**Comment by octaedro** [comment] 2021-08-25 13:52
Since this bug is not present anymore, I'm going to close this issue.

**Closed by octaedro** 2021-08-25 13:52 UTC
