### ISSUE TITLE
Exception Email from 0.25.1

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#3701] opened 2020-02-11 23:53 UTC
**Describe the bug**
@warrendholmes forwarded an email to me with an exception report from one of his sites, the error trace is as follows:

> Error Details
=============
An error of type E_ERROR was caused in line 35 of the file /srv/htdocs/wp-content/plugins/woocommerce-admin/src/Notes/WC_Admin_Notes_Onboarding_Email_Marketing.php. Error message: Uncaught Error: Undefined class constant 'PROFILE_DATA_OPTION' in /srv/htdocs/wp-content/plugins/woocommerce-admin/src/Notes/WC_Admin_Notes_Onboarding_Email_Marketing.php:35
Stack trace:
#0 /srv/htdocs/wp-content/plugins/woocommerce-admin/src/Events.php(70): Automattic\WooCommerce\Admin\Notes\WC_Admin_Notes_Onboarding_Email_Marketing::possibly_add_onboarding_email_marketing_note()
#1 /wordpress/core/5.3.2/wp-includes/class-wp-hook.php(288): Automattic\WooCommerce\Admin\Events->do_wc_admin_daily()
#2 /wordpress/core/5.3.2/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
#3 /wordpress/core/5.3.2/wp-includes/plugin.php(544): WP_Hook->do_action(Array)
#4 /wordpress/core/5.3.2/wp-cron.php(138): do_action_ref_array('wc_admin_daily', Array)
#5 {main}
  thrown

I have not seen this bug myself, and did a quick check in forums and don't see any reports there either. Further debug info from the email:

> When seeking help with this issue, you may be asked for some of the following information:
WordPress version 5.3.2
Current theme: Redhill (version 1.4.1)
Current plugin: WooCommerce Admin (version 0.25.1)
PHP version 7.2.27

**Comment by timmyc** [comment] 2020-02-18 01:09
@joshuatf any thoughts on what might have caused this one? Only had the one report of it from @warrendholmes

**Comment by joshuatf** [comment] 2020-02-20 10:22
I haven't been able to reproduce this either.  Tried from latest master as well as packaged version in WC core beta and no luck.

@warrendholmes Have you seen the issue pop up since the first occurrence?

**Comment by rrennick** [comment] 2020-02-24 20:18
This looks like it might have been a partial plugin install where the `Onboarding` class wasn't replaced in an update.

@warrendholmes I'm closing. If you encounter this again please let us know.

**Closed by rrennick** 2020-02-24 20:18 UTC
Labels: [4.0] Merge, [Type] Bug
