### ISSUE TITLE
On WP 5.8-beta2 WooCommerce > Home and the onboarding wizard fail to load

### ISSUE THREAD

**Issue by zhongruige** [woocommerce/woocommerce-admin#7192] opened 2021-06-16 02:00 UTC
**Describe the bug**

On WordPress 5.8-beta2, the onboarding Wizard and `WooCommerce > Home` pages fail to load (for the latter, this happens after going through the Wizard on WP 5.7). The JavaScript errors in both cases appear the same.

**To Reproduce**

In both flows below, you'll want to install the [WordPress Beta Tester plugin](https://wordpress.org/plugins/wordpress-beta-tester/) configured with `Bleeding edge` and `Beta/RC only` to pull in updates.

**Onboarding wizard flow**

For this testing, you'll want to make sure the site is upgraded to WordPress 5.8-beta2 first.

1. Install the WooCommerce plugin, which auto-redirects to the onboarding wizard.
2. Note the wizard fails to load. Open the console and note the JavaScript errors. See screenshot below for more context.

`WooCommerce > Home` flow

1. Install the WooCommerce plugin, and proceed through the onboarding wizard.
2. Upgrade WordPress to the latest beta, in this case WP 5.8-beta2
3. Proceed to open `WooCommerce > Home` and note it fails to load with JavaScript errors in the console.

**Expected behavior**

The Onboarding Wizard and `WooCommerce > Home` pages should load.

**Screenshots**

<img width="1600" alt="Screen_Shot_2021-06-15_at_2_55_42_PM" src="https://user-images.githubusercontent.com/71906536/122146618-a6522080-ce14-11eb-8baf-42a39dad61cc.png">

**Desktop (please complete the following information):**

* OS: macOS
* Browser: Firefox
* Version: 89.0

**Comment by zhongruige** [comment] 2021-06-16 14:42
One other area to note that I came across is every section in the Analytics menu also fails to load, with the same errors in the console:

https://user-images.githubusercontent.com/71906536/122240172-cae2e280-ce7e-11eb-8547-2ab9d09b275a.mov

**Comment by nerrad** [comment] 2021-06-16 18:34
For reference, Woo Blocks encountered this as well. I have a PR that fixes this for the blocks project here: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4362

However, there is real possibility this could be resolved in the next beta build of WordPress as this has to do with a [polyfill being removed from WP](https://core.trac.wordpress.org/ticket/52941) which is likely going to be added back in.

**Comment by joshuatf** [comment] 2021-06-16 19:42
Thank you very much for opening this issue, @zhongruige and thanks for the PR reference @nerrad!  I'm able to reproduce and can confirm that it appears to be the same babel issue with the current error coming from the data package.

I'm going to label this as high priority since we don't know whether or not that polyfill is going to be added back in yet or not.

**Closed** 2021-06-18 05:13 UTC
Labels: priority: high, type: bug
