### ISSUE TITLE
[GlobalStep - WooCommerce 4.9 Beta 1] At front-end, Razorpay option appears misaligned on Checkout Page and keeps varying in size as theme changes.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#5963] opened 2020-12-23 15:43 UTC
## Bug Description:
At front-end, Razorpay option appears misaligned on Checkout Page and keeps varying in size as theme changes.
 
 ## Environment:
 Windows 10, macOS Mojave v10.14.6 (18G103)
 Browser: Chrome(Version 87.0.4280.88 (64-bit))
  Firefox(Version 83.0)(64-bit)
  Safari: v13.1.1 (14609.2.9.1.3)
 
 ## Steps To Reproduce:
 1. Create any test site using Jurassic Ninja.
 1. Install and activate all required plugins.
 1. Complete the Onboarding setup wizard and set the store address to India.
 1. On WooCommerce->Home enable Razarpay option under Set up Payments
 1. Create products from Products->Add New option 
 1. Go to front end by reviewing the product after publishing it and add the product to cart
 1. Click on "Procced to Checkout" button
 1. Observe that at front-end, Razorpay option appears misaligned on Checkout Page and keeps varying in size as theme and platform changes.
 
**Note**:
Observed changes when Razorpay option viewed on:
Varied in size when Twenty twenty and Storefront theme was selected.

 ## Actual Result:
At front-end, Razorpay option appears misaligned on Checkout Page and keeps varying in size as theme changes.
 
 ## Expected Result:
At front-end, Razorpay option should appear properly on Checkout Page irrespective of the theme selected
 
 ## Artifacts:
[#28663.zip](https://github.com/woocommerce/woocommerce/files/5736014/28663.zip)

![#28663 2](https://user-images.githubusercontent.com/19143190/103294953-e9cce580-49c0-11eb-82ec-dd0935de5374.jpg)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by moon0326** [comment] 2020-12-28 20:49
This is caused by empty space in the logo file.

![Screen Shot 2020-12-28 at 12 48 44 PM](https://user-images.githubusercontent.com/4723145/103242445-0ad2ff00-490b-11eb-9954-ef08f8468fd2.jpg)

There is already an open [issue](https://github.com/razorpay/razorpay-woocommerce/issues/169) in the official repository.

I left a comment and pinged Razorpay's developer.

**Comment by timmyc** [comment] 2020-12-29 17:29
Thanks for looking into this @moon0326. Since this is a bug that needs to be fixed by the extension developer, I'm going to close this issue out.

But pinging @MechielCouvaras to see if you could follow up with our contact at RazorPay to inform them that this issue was found while testing the addition of the payment method to the setup checklist.

**Closed by timmyc** 2020-12-29 17:29 UTC
