### ISSUE TITLE
Navigation: Feature Opt-In Setting Reported Missing

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#6128] opened 2021-01-21 16:32 UTC
**Describe the bug**
Originally reported by @pmcpinto in Slack - but he mentioned that the check box to opt-in to the navigation beta is missing in the latest 5.0 Beta.

**To Reproduce**

1. Install the latest 5.0 beta along with RC of 1.9
2. Navigate to Settings > Advanced and note that features sub tab is missing 
3. I attempted to enable tracking to see if that would make it show, but it still did not appear.
![image](https://user-images.githubusercontent.com/22080/105380841-315f1f80-5bc3-11eb-9ad2-f8113e6fe5a1.png)

**Comment by joshuatf** [comment] 2021-01-21 16:36
I think this may be resolved by https://github.com/woocommerce/woocommerce-admin/pull/6075 - @timmyc can you confirm if you can reproduce on the latest `main`?

**Comment by joelclimbsthings** [comment] 2021-01-21 18:13
It looks like that PR is already a part of 1.9.0 rc2, @joshuatf ?

**Comment by joshuatf** [comment] 2021-01-21 19:04
@pmcpinto @timmyc Is this with the RC installed as a plugin or WooCommerce Admin packaged with core?

From Slack it appears that the navigation is meant to be disabled in core until February and was intentionally removed there - https://github.com/woocommerce/woocommerce-admin/pull/6007

If this issue appears when WooCommerce Admin is installed as a plugin, then a fix is warranted.

**Comment by timmyc** [comment] 2021-01-21 19:10
@joshuatf  I have been testing against [the .zip linked here](https://a8c.slack.com/archives/C01DT6U03HC/p1611241218012600?thread_ts=1611079045.017100&cid=C01DT6U03HC) which appears to have the wc-admin package built yesterday ( RC2 ) included:

![image](https://user-images.githubusercontent.com/22080/105400016-3a5aeb80-5bd9-11eb-8486-4d1ef21105ec.png)

No other plugins installed, just that build of 5.0 with 1.9 RC2 included.

**Comment by joelclimbsthings** [comment] 2021-01-21 20:10
To @joshuatf 's point, we need to bottom out on what the expected behavior is. 

Do we want the feature available when _wc-admin_ is installed as a package?
Do we want the feature available when it's installed as a feature plugin?

Regarding that last one, I'm attempting to test this with a JN site:

I've installed both the WC 5.0 beta as well as wc_admin 1.9.0 rc2 as a feature plugin:
![image](https://user-images.githubusercontent.com/444632/105406469-55315e00-5be1-11eb-93f9-3d0af25debc7.png)

Although it's still using the packaged version:
![image](https://user-images.githubusercontent.com/444632/105406400-3a5ee980-5be1-11eb-9416-90449b687515.png)


And the navigation feature is still unavailable. I'm not sure how to force it to use the external wcadmin, when they're the same version?

**Comment by psealock** [comment] 2021-01-21 20:27
>we need to bottom out on what the expected behavior is

The expected behaviour was outlined, reviewed, and implemented as part of https://github.com/woocommerce/woocommerce-admin/issues/5942

>And the navigation feature is still unavailable.

Thats a problem. I will double check this. Did you use the plugin build?

**Comment by joshuatf** [comment] 2021-01-21 20:37
I tested with a test zip of the WooCommerce Admin plugin alongside WC 5.0 beta on a JN site and everything ran as expected:

* No features shown with WooCommerce Admin deactivated and only using the packaged WC version
* Features and navigation shown when the WooCommerce Admin feature plugin was enabled.

**Comment by psealock** [comment] 2021-01-21 20:40
I see from Joel's screenshot and a look at my own status that the wc-admin being used is the one supplied by Core, not the feature plugin. This appears to be a false alarm because autoloader defaults to the Core version v. plugin when the version numbers are identical.

**Comment by joelclimbsthings** [comment] 2021-01-21 20:49
Confirmed on my JN site as well. So we can close this out, correct?

**Closed** 2021-01-21 20:51 UTC
Labels: feature: navigation, type: bug

**Comment by ecgan** [comment] 2021-08-19 19:02
How do I enable the WooCommerce Navigation feature if I want to have the latest version of WooCommerce Core and WooCommerce Admin?

My site is a Pressable site, running WC 5.6.0 and WC Admin 2.5.1, and this is what I'm seeing now, the WooCommerce Navigation feature is missing:

![image](https://user-images.githubusercontent.com/417342/130128576-df8e9109-045c-4680-ab47-13d5f7f16576.png)

**Comment by psealock** [comment] 2021-08-19 21:53
hi @ecgan 

Just for completeness, do you have WC Admin activated? When you go to Tools > System Status do you see WC Admin referencing the plugin or the version in Core? You'll need it to reference the plugin version.

Do you see the feature turned on in the console `window.wcAdminFeatures.navigation`?

If all else fails, you can force it on with this snippet

```
add_filter( 'pre_option_woocommerce_navigation_enabled', function() {
return 'yes';
});
add_filter( 'woocommerce_admin_features', function( $features ) {
	$features[] = 'navigation';
	return $features;
});
```

**Comment by ecgan** [comment] 2021-08-20 14:04
@psealock , thank you for getting back to me. 

> do you have WC Admin activated?

Yes, I do. 

![image](https://user-images.githubusercontent.com/417342/130244422-70d9d274-3411-481c-a855-45e5c228ab01.png)

> When you go to Tools > System Status do you see WC Admin referencing the plugin or the version in Core?

It is referencing the version in Core. 

![image](https://user-images.githubusercontent.com/417342/130244754-38e40b4b-6194-4ed1-8d50-d7317e40779f.png)

> You'll need it to reference the plugin version.

How do I do that? 🤔 

> Do you see the feature turned on in the console `window.wcAdminFeatures.navigation`?

No, it is undefined. 

![image](https://user-images.githubusercontent.com/417342/130244978-c00353e9-1d9e-4bfe-b0ef-05203a204d54.png)

> If all else fails, you can force it on with this snippet

I'm spinning up quite a number of sites to do some testings, so if possible, I would like to avoid using custom snippets. 😄

**Comment by ecgan** [comment] 2021-08-30 17:59
After discussion in [Isotope team slack channel](https://app.slack.com/client/T024FN1V2/CBKK5KM41) and in pcShBQ-6u-p2, the above issue shall be addressed in https://github.com/woocommerce/woocommerce-admin/issues/7581.
