### ISSUE TITLE
Note date stored as UTC but shown as local

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#2793] opened 2019-08-14 14:45 UTC
**Describe the bug**
I reset my install to recreate the initial notes. The date created is in UTC which is subsequently used in the notes panel as the local time. 

**To Reproduce**

1. Go to Analytics -> Settings
2. Delete previously imported data
3. Delete the WC Admin version option `wp option delete wc_admin_version`
4. Re-load the dashboard
5. Open the notes panel

**Expected behavior**
The date_created field should be used consistently as either local or UTC time.

**Screenshots**
<img width="502" alt="Screen Shot 2019-08-14 at 11 38 51 AM" src="https://user-images.githubusercontent.com/343847/63030406-a1bf2880-be88-11e9-88b5-87505e6be1fb.png">

**Comment by psealock** [comment] 2019-08-19 00:28
This a duplicate of https://github.com/woocommerce/woocommerce-admin/issues/2006. Closing this one out.

**Closed by psealock** 2019-08-19 00:28 UTC
Labels: Activity Panel, [Type] Bug
