### ISSUE TITLE
Select Control: Duplicate tag a string in search field

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#3241] opened 2019-11-14 03:19 UTC
**Describe the bug**

After filtering, Select Control renders the search string and tag

![Screen Shot 2019-11-14 at 4 13 20 PM](https://user-images.githubusercontent.com/1922453/68823999-4e17e180-06fa-11ea-8133-dfa29206f7c3.png)

**To Reproduce**

1. Product Report > Show > Make a selection (See https://github.com/woocommerce/woocommerce-admin/issues/3240 if you use keyboard)
2. Reopen the Show filter
3. See a tag and string rendered

**Expected behavior**

It should just show the tag

**Comment by joshuatf** [comment] 2019-11-14 08:32
I think this may be a duplicate of https://github.com/woocommerce/woocommerce-admin/issues/3199

**Closed** 2019-11-18 01:23 UTC
Labels: [Type] Bug
