### ISSUE TITLE
Errors on 'Analytics' section in wp-admin

### ISSUE THREAD

**Issue by jamieshulman** [woocommerce/woocommerce-admin#4510] opened 2020-06-05 05:14 UTC
**Describe the bug**
`/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/chunks/vendors~activity-panels-inbox~leaderboards~store-alerts~task-list.dd09e8a86b0bcaa9aff7.min.js` showing a 404 when attempting to load (seen on network tab of browser's dev console)

**To Reproduce**
1. Go to '/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Fsettings'
2. Settings show up briefly and after a few seconds appear to disappear.
3. Looking at the network tab in the browser's console shows a 404 for `/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/chunks/vendors~activity-panels-inbox~leaderboards~store-alerts~task-list.dd09e8a86b0bcaa9aff7.min.js`
4. Also seeing ChunkLoadError: "Loading chunk 3 failed. in the Console window followed by `/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/chunks/vendors~activity-panels-inbox~leaderboards~store-alerts~task-list.dd09e8a86b0bcaa9aff7.min.js`

**Expected behavior**
Settings on this page should be shown.  I suspect the issue is caused by many hosts not allowing the tilda in the filename and refusing to load the asset(s) containing the tilda's (~) as I cannot load the JS even when directly accessed on the host

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
**SiteGround** Production Site
```
```
</details>

**Comment by timmyc** [comment] 2020-06-05 16:11
Hello @jamieshulman - sorry you are encountering this issue. I've tried to reproduce this on a few different hosting environments with 4.2 installed and have not been able to do so. Could you share some details about your hosting setup - and/or possibly supply a WooCommerce System Report?

**Comment by AntonyXSI** [comment] 2020-06-09 00:47
I have the same issue, as I have the tilde character blocked. Is there a reason to use ~ over the common - ?

**Comment by timmyc** [comment] 2020-06-09 22:18
Hey @jamieshulman we have had another report of this which traced the issue back to a Firewall plugin that is blocking requests with `~`. So please see if that might be similar to your issue - please see #4519 for details.

We are working on a fix right now, but until that ships, you could look at modifying the firewall rules, or another current work around is to install the version of WooCommerce Admin which is in the .org repo which does not have the chunked JS file names with tildes in them.

**Comment by timmyc** [comment] 2020-08-05 22:42
Closing out as duplicate of #4519

**Closed by timmyc** 2020-08-05 22:42 UTC
