### ISSUE TITLE
[WC 4.4 beta1] OBW Store details: if the cursor is placed on any of the fields, Skip setup wizard option doesn't work right away

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4880] opened 2020-07-29 17:56 UTC
**Describe the bug**

During OBW on the `Store details` page, if the mouse cursor is placed on any of the fields, the `Skip setup wizard` option doesn't work right away. When you click on it, the field is highlighted with a warning that the field should be filled. 

**To Reproduce**

1. Start OBW.
2. On `Store details` page, click on any of the fields - for example, the first one as you are about to type something but don't type. 
3. Click on the `Skip setup wizard` option.
4. Observe that instead of exiting the OBW, the field where the cursor was is highlighted and the message is shown that the field needs to be filled. 

Screencast:

![](http://g.recordit.co/FPx3uswE4Y.gif)

Screenshot: 

![cursor](https://user-images.githubusercontent.com/19143190/88835277-090ddf80-d1a3-11ea-9bfa-e77a8bf01ad5.jpg)

**Expected behavior**

I expected to exist the OBW as soon as I click on the `Skip setup wizard` option even if I had a mouse cursor placed on any of the fields. 

**Screenshots**

See above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.5
* Browser: Chrome
* Version: 84.0.4147.89 (Official Build) (64-bit)

**Additional context**

N/A.

**Comment by timmyc** [comment] 2020-07-29 20:45
Ah I could see that being a wee bit annoying, but doesn't seem like a super critical bug to me. I'll add it to the milestone and see if we can get a fix in prior to RC. Thanks so much for the detailed bug report Julia, much appreciated!

**Comment by juliaamosova** [comment] 2020-07-29 20:55
Sure thing and thanks @timmyc! Not a high priority indeed but will be nice to fix.

**Comment by joshuatf** [comment] 2020-07-30 14:05
It looks like the reason this is happening is because the error that occurs on blurring the input field pushes the "Skip" button down the page further so the button isn't actually clicked.

If we want to change this, we could not show any errors until the form was submitted instead of showing after an input field was touched.  Does anyone have an opinion on this?

**Comment by timmyc** [comment] 2020-07-30 17:35
I think the real-time validation on the text fields is nice as-is myself. I totally get how it leads to this scenario too, but still feels like having the feedback while filling out the form is a great UX. Since we don't insert the cursor automatically into the field, this bug still feels very edge case to me.

**Comment by timmyc** [comment] 2020-07-30 22:54
Just going through the milestone again, and I think I'm going to remove this one because it just feels like kind of an edge case to me. We will keep it open though and circle back to it.

**Comment by becdetat** [comment] 2020-09-18 03:09
What is this was done with a popover to show the validation errors rather than pushing the other content down on blur? There are probably some other UX considerations with this.

![image.png](https://images.zenhubusercontent.com/5e4207fe3e11c3c09f1c2919/3d5a2c2e-3e10-464e-aeef-187661e2618d)

**Comment by octaedro** [comment] 2020-11-23 18:19
I'm trying this issue out but I couldn't reproduce the error.
It seems like it was already solved.

**Comment by timmyc** [comment] 2020-11-23 19:49
Thanks for looking into it @octaedro - if you can't reproduce this any longer, I think it is okay to close it out 👍

**Closed by timmyc** 2020-11-23 19:49 UTC
Labels: [Type] Bug
