### ISSUE TITLE
Onboarding: 502 Bad Gateway

### ISSUE THREAD

**Issue by dashkevych** [woocommerce/woocommerce-admin#6267] opened 2021-01-27 22:50 UTC
I am using [VVV](https://github.com/Varying-Vagrant-Vagrants/VVV) for a local development. Recently, I've noticed that WooCommerce is causing "502 Bad Gateway" issue in my WP installation. Here is a video of the issue: https://cloudup.com/cMjpwQAwn54

Here is also an info from php log:

```
[27-Jan-2021 22:31:50] WARNING: [pool www] child 11025 said into stderr: "Fatal error: Maximum execution time of 30+2 seconds exceeded (terminated) in /srv/www/wpcom/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Features/Onboarding.php on line 585"
[27-Jan-2021 22:31:50] WARNING: [pool www] child 11025 exited with code 124 after 503.511556 seconds from start
[27-Jan-2021 22:31:50] NOTICE: [pool www] child 11057 started
[27-Jan-2021 22:35:59] WARNING: [pool www] child 11077 said into stderr: ""
[27-Jan-2021 22:35:59] WARNING: [pool www] child 11077 said into stderr: "Fatal error: Maximum execution time of 30+2 seconds exceeded (terminated) in /srv/www/wpcom/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Features/Onboarding.php on line 585"
[27-Jan-2021 22:35:59] WARNING: [pool www] child 11077 exited with code 124 after 85.979090 seconds from start
[27-Jan-2021 22:35:59] NOTICE: [pool www] child 11083 started
[27-Jan-2021 22:37:15] WARNING: [pool www] child 11082 said into stderr: ""
[27-Jan-2021 22:37:15] WARNING: [pool www] child 11082 said into stderr: "Fatal error: Maximum execution time of 30+2 seconds exceeded (terminated) in /srv/www/wpcom/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Features/Onboarding.php on line 585"
[27-Jan-2021 22:37:15] WARNING: [pool www] child 11082 exited with code 124 after 84.033989 seconds from start
```

I cannot open any WooCommerce admin pages and edit any pages (post type = page) in my dashboard. It's a fresh WordPress installation with a default WordPress theme (2021).

Is it possible somehow to disable that Onboarding functionality?

**Comment by octaedro** [comment] 2021-02-04 16:09
Thank you @dashkevych for reporting this error.
I created a brand new `vvv` instance but I couldn't reproduce the error.

My instance has:
- WordPress `v5.6.1`.
- Theme `Twenty Twenty-One`.
- WooCommerce `v4.9.2`.

Could you share your site's status? (it should be in: `http://wpcom.test/wp-admin/admin.php?page=wc-status&tab=status`).
Thanks!

**Comment by dashkevych** [comment] 2021-02-04 19:51
Hi @octaedro,
Thank you for conducting an investigation.

Here is a site status:

`
### WordPress Environment ###

WordPress address (URL): http://wpcom.test
Site address (URL): http://wpcom.test
WC Version: 4.9.2
REST API Version: ✔ 4.9.2
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.8.3
Log Directory Writable: ✔
WP Version: 5.7-alpha-50026
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.19.6
PHP Version: 7.3.26-1+ubuntu18.04.1+deb.sury.org+1
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1i

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.17-MariaDB-1:10.4.17+maria~bionic
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.9.2
WC Database Prefix: wp_
Total Database Size: 4.85MB
Database Data Size: 3.06MB
Database Index Size: 1.79MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.06MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 23
page: 6
post: 2
product: 18
product_variation: 7

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (4) ###

Query Monitor: by John Blackbourn – 3.6.7
Jetpack by WordPress.com: by Automattic – 9.4
WooCommerce: by Automattic – 4.9.2
WordPress Importer: by wordpressdotorg – 0.7

### Inactive Plugins (5) ###

Akismet Anti-Spam: by Automattic – 4.1.8
Classic Editor: by WordPress Contributors – 1.6
Gutenberg: by Gutenberg Team – 9.8.4
RTL Tester: by <a href="http://blog.yoavfarhi.com">Yoav Farhi</a>
<a href="http://automattic.com">Automattic</a> – 1.2

WP Reset: by WebFactory Ltd – 1.85

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Canceled: 1
Oldest: 2021-01-27 22:19:44 +0000
Newest: 2021-01-27 22:19:44 +0000

Complete: 6
Oldest: 2021-01-27 22:19:44 +0000
Newest: 2021-01-28 03:24:41 +0000

Pending: 1
Oldest: 2021-02-04 19:46:36 +0000
Newest: 2021-02-04 19:46:36 +0000

`

**Comment by ilyasfoo** [comment] 2021-03-04 06:46
Thank you for sharing @dashkevych. The issue should be fixed in https://github.com/woocommerce/woocommerce-admin/pull/6401, where the function in question is practically removed altogether. Just to note that this fix is not in any release yet, you can expect the plugin to include the fix in the next release.

**Closed by ilyasfoo** 2021-03-04 06:46 UTC
Labels: needs feedback
