### ISSUE TITLE
[WC 4.4 beta1] "Business features" plugin installation dependency issue, and formatting issue in Snackbar

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-admin#4895] opened 2020-07-30 11:28 UTC
On the business details step I tried to install the recommended plugins but got an error saying that WooCommerce needed to be installed first. I suspect this maybe due to the beta plugin folder having a different name, so probably an edge case?

Also, the Snackbar content is output as plain text, so the link doesn't render:

![snack](https://cldup.com/xJSs4Ffgvb-3000x3000.png)

**Comment by pmcpinto** [comment] 2020-07-30 15:34
I'm seeing something similar:

<img width="1440" alt="Captura de ecrã 2020-07-30, às 16 17 07" src="https://user-images.githubusercontent.com/3380168/88942632-6f1d6400-d282-11ea-86a1-887499bf70b1.png">

Console info:

<img width="1440" alt="Captura de ecrã 2020-07-30, às 16 32 51" src="https://user-images.githubusercontent.com/3380168/88942652-780e3580-d282-11ea-9627-09ef8e40bc56.png">

**Comment by pmcpinto** [comment] 2020-07-30 15:36
It is happening in the Theme step as well

<img width="1440" alt="Captura de ecrã 2020-07-30, às 16 35 10" src="https://user-images.githubusercontent.com/3380168/88942947-cfaca100-d282-11ea-82e2-a505aaaa591a.png">

**Comment by timmyc** [comment] 2020-07-30 22:28
This is being caused by the MailChimp plugin which [does a call to `die()` with that message](https://github.com/mailchimp/mc-woocommerce/blob/fc96e79f55e375653230378e0c8dccc87fc8fed8/bootstrap.php#L525-L534) if WooCommerce is not installed at the `woocommerce/woocommerce.php` path. So @jameskoster I think your diagnosis is spot on that somehow/someway the install of woo happened in a different folder name for some reason on the sites you were testing with.

I'll notify the MC devs about this, and suggest they sniff for the `WC` classname instead of trying to use the plugin path to determine if Woo is installed or not. And perhaps not doing a `die()` - just deactivating instead.

**Comment by timmyc** [comment] 2020-07-30 22:55
I've followed up with the developers in our shared slack channel. Just noting that the code that is triggering this error in the MailChimp plugin is not new ( looks like it has been there for 2 years ) so this bug is present already, and not specific to anything in the 1.4.0 release of wc-admin, or the new bundled extension install. As such, I'm going to clear this from the 1.4.0 milestone.

**Comment by pmcpinto** [comment] 2020-08-10 17:01
I created a new store today with the 4.4RC installed and I was able to install the plugins. So perhaps they already fixed it in the MC plugin

**Comment by timmyc** [comment] 2020-08-12 19:35
Yes they did ship a fix! Thanks for the reminder @pmcpinto I'm going to close this one out.

**Closed by timmyc** 2020-08-12 19:35 UTC
Labels: Onboarding, [Type] Bug
