### ISSUE TITLE
ChunkLoadError with react-dom.min.js, WC back end does not load correctly since WC 5.0

### ISSUE THREAD

**Issue by fylgjur** [woocommerce/woocommerce-admin#6323] opened 2021-02-11 15:22 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

I have not personally reproduced this, however, the user who made the report performed a full conflict test and also saw the same error on two separate sites with separate hosting configurations.

**Describe the bug**

Since the update to WooCommerce 5.0 the user sees the following: "In the browser window itself, the WooCommerce Home page is blank, while the other pages load with the top bar and the inbox icon on the right, while the rest of the page is OK, even though the top bar is overlaid on top of the rest. You can click the inbox icon and the bar disappears, showing the page normally."

They see the following error in the browser console:

```
ChunkLoadError: Loading chunk 7 failed.
(error: https://billing.---.com/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/chunks/7.js?ver=1.9.0)
    at Function.a.e (https://billing.---.com/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js:1:2643)
    at https://billing.---.com/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js:1:163098
    at ri (https://billing.---.com/wp-includes/js/dist/vendor/react-dom.min.js:18:330)
    at zj (https://billing.---.com/wp-includes/js/dist/vendor/react-dom.min.js:228:56)
    at Th (https://billing.---.com/wp-includes/js/dist/vendor/react-dom.min.js:152:223)
    at tj (https://billing.---.com/wp-includes/js/dist/vendor/react-dom.min.js:152:152)
    at Te (https://billing.---.com/wp-includes/js/dist/vendor/react-dom.min.js:146:151)
    at https://billing.---.com/wp-includes/js/dist/vendor/react-dom.min.js:61:68
    at unstable_runWithPriority (https://billing.---.com/wp-includes/js/dist/vendor/react.min.js:25:260)
    at Da (https://billing.---.com/wp-includes/js/dist/vendor/react-dom.min.js:60:280)
```

My initial theory: I'm thinking this may be related to missing non-minified versions of Javascript assets, in which case setting SCRIPT_DEBUG to false (or not defined) may resolve it temporarily. Something similar was seen in https://github.com/woocommerce/woocommerce-admin/issues/4738 in July 2020. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).

The user could reproduce on two different sites in two separate hosting environments. I am so far unable to personally reproduce.

**WordPress Environment**

<details>
```
### WordPress Environment ###

WordPress address (URL): http://billing.---.com
Site address (URL): http://billing.---.com
WC Version: 5.0.0
REST API Version: ✔ 5.0.0
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.9.0
Log Directory Writable: ✔
WP Version: 5.6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.15
PHP Post Max Size: 64 MB
PHP Time Limit: 800
PHP Max Input Vars: 15000
cURL Version: 7.74.0
OpenSSL/1.1.1i

SUHOSIN Installed: –
MySQL Version: 5.7.31
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.0.0
WC Database Prefix: d13m01y2020_
Total Database Size: 89.02MB
Database Data Size: 65.66MB
Database Index Size: 23.36MB
d13m01y2020_woocommerce_sessions: Data: 0.05MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_woocommerce_order_items: Data: 0.09MB + Index: 0.06MB + Engine MyISAM
d13m01y2020_woocommerce_order_itemmeta: Data: 1.90MB + Index: 0.61MB + Engine MyISAM
d13m01y2020_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
d13m01y2020_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_actionscheduler_actions: Data: 0.21MB + Index: 0.07MB + Engine MyISAM
d13m01y2020_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
d13m01y2020_actionscheduler_logs: Data: 0.24MB + Index: 0.18MB + Engine MyISAM
d13m01y2020_aioseo_notifications: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
d13m01y2020_aioseo_posts: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
d13m01y2020_aioseo_terms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
d13m01y2020_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
d13m01y2020_comments: Data: 0.46MB + Index: 0.19MB + Engine MyISAM
d13m01y2020_csp3_subscribers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_eum_logs: Data: 0.10MB + Index: 0.02MB + Engine MyISAM
d13m01y2020_ewwwio_images: Data: 0.48MB + Index: 0.23MB + Engine MyISAM
d13m01y2020_gaplus_login: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
d13m01y2020_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
d13m01y2020_gf_addon_payment_callback: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
d13m01y2020_gf_addon_payment_transaction: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
d13m01y2020_gf_draft_submissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_gf_entry: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_gf_entry_meta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
d13m01y2020_gf_entry_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_gf_form: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_gf_form_meta: Data: 0.05MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_gf_form_revisions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_gf_form_view: Data: 0.38MB + Index: 0.17MB + Engine MyISAM
d13m01y2020_gpi_api_error_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_gpi_custom_urls: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_gpi_page_blacklist: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
d13m01y2020_gpi_page_reports: Data: 1.89MB + Index: 0.04MB + Engine MyISAM
d13m01y2020_gpi_page_stats: Data: 0.07MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_gpi_summary_snapshots: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_inbound_events: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_inbound_page_views: Data: 2.12MB + Index: 0.14MB + Engine MyISAM
d13m01y2020_inbound_tracked_links: Data: 1.59MB + Index: 0.04MB + Engine MyISAM
d13m01y2020_iqblock_logging: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_itsec_bans: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
d13m01y2020_itsec_distributed_storage: Data: 3.58MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_itsec_fingerprints: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_itsec_geolocation_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_itsec_lockouts: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
d13m01y2020_itsec_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_itsec_logs: Data: 1.27MB + Index: 0.09MB + Engine MyISAM
d13m01y2020_itsec_mutexes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_itsec_opaque_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_itsec_temp: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
d13m01y2020_itsec_user_groups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_msa_shortcodes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_ms_snippets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_options: Data: 3.68MB + Index: 0.15MB + Engine MyISAM
d13m01y2020_ph_members: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_ph_thread_members: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_postmeta: Data: 20.49MB + Index: 3.02MB + Engine MyISAM
d13m01y2020_posts: Data: 2.32MB + Index: 0.57MB + Engine MyISAM
d13m01y2020_po_plugins: Data: 0.11MB + Index: 0.02MB + Engine MyISAM
d13m01y2020_prli_clicks: Data: 0.02MB + Index: 0.05MB + Engine MyISAM
d13m01y2020_prli_groups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_prli_links: Data: 0.00MB + Index: 0.03MB + Engine MyISAM
d13m01y2020_prli_link_metas: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
d13m01y2020_rg_form_meta: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
d13m01y2020_rg_form_view: Data: 1.52MB + Index: 0.78MB + Engine InnoDB
d13m01y2020_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
d13m01y2020_rg_lead: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
d13m01y2020_rg_lead_detail: Data: 0.22MB + Index: 0.34MB + Engine InnoDB
d13m01y2020_rg_lead_detail_long: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
d13m01y2020_rg_lead_meta: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
d13m01y2020_rg_lead_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
d13m01y2020_rg_zapier: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_rp4wp_cache: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
d13m01y2020_shortpixel_folders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
d13m01y2020_shortpixel_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
d13m01y2020_sm_sessions: Data: 0.96MB + Index: 0.42MB + Engine MyISAM
d13m01y2020_snippets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_sucuri_lastlogins: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_termmeta: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
d13m01y2020_terms: Data: 0.04MB + Index: 0.06MB + Engine MyISAM
d13m01y2020_term_relationships: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
d13m01y2020_term_taxonomy: Data: 3.74MB + Index: 0.03MB + Engine MyISAM
d13m01y2020_usermeta: Data: 0.15MB + Index: 0.10MB + Engine MyISAM
d13m01y2020_users: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
d13m01y2020_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
d13m01y2020_wcs_payment_retries: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_wc_admin_notes: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_wc_customer_lookup: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
d13m01y2020_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_wc_order_coupon_lookup: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
d13m01y2020_wc_order_product_lookup: Data: 0.10MB + Index: 0.10MB + Engine MyISAM
d13m01y2020_wc_order_stats: Data: 0.07MB + Index: 0.05MB + Engine MyISAM
d13m01y2020_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
d13m01y2020_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
d13m01y2020_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_wpfm_backup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_wpsp_agent_settings: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_wpsp_attachments: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_wpsp_catagories: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_wpsp_custom_fields: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_wpsp_custom_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_wpsp_faq: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_wpsp_faq_catagories: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_wpsp_panel_custom_menu: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_wpsp_ticket: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_wpsp_ticket_thread: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_wptc_activity_log: Data: 1.02MB + Index: 0.23MB + Engine InnoDB
d13m01y2020_wptc_backups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
d13m01y2020_wptc_current_process: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
d13m01y2020_wptc_inc_exc_contents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
d13m01y2020_wptc_options: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
d13m01y2020_wptc_processed_files: Data: 9.52MB + Index: 11.09MB + Engine InnoDB
d13m01y2020_wptc_processed_iterator: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
d13m01y2020_wptc_processed_restored_files: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
d13m01y2020_wptc_query_recorder: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
d13m01y2020_wpum_fieldmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
d13m01y2020_wpum_fields: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
d13m01y2020_wpum_fieldsgroups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
d13m01y2020_wpum_registration_formmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
d13m01y2020_wpum_registration_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_wpum_search_fields: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
d13m01y2020_wsal_metadata: Data: 4.52MB + Index: 3.52MB + Engine InnoDB
d13m01y2020_wsal_occurrences: Data: 0.30MB + Index: 0.28MB + Engine InnoDB
d13m01y2020_wsal_options: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

amp_validated_url: 4
attachment: 34
cookielawinfo: 2
custom_css: 1
event: 12
fl-theme-layout: 2
gfw_report: 27
ig_campaign: 1
ig_message: 6
jetpack_migration: 2
location: 1
nav_menu_item: 16
oembed_cache: 29
page: 47
ph-website: 1
popup: 4
popup_theme: 1
product: 7
product_variation: 6
products: 4
project-huddle: 1
proposal: 1
rp4wp_link: 345
shop_coupon: 9
shop_order: 1465
shop_order_refund: 2
shop_subscription: 47
slide: 4
sm-proposal: 5
testimonials-widget: 38
tribe_events: 6
tribe_organizer: 7
tribe_venue: 7
view-template: 3
wdd-proposal: 19
widgetkit: 1
wp-call-to-action: 6
wp-types-group: 1
wpgform: 1

### Security ###

Secure connection (HTTPS): ❌
Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (3) ###

MainWP Child: by MainWP – 4.1.4
WooCommerce: by Automattic – 5.0.0
WP Activity Log: by WP White Security – 4.1.5.2

### Inactive Plugins (50) ###

Admin Page Spider Pro Pack: by J7 Digital – 4.41
Advanced Editor Tools (previously TinyMCE Advanced): by Automattic – 5.6.0
All in One SEO Pro: by All in One SEO Team – 4.0.15
Anti-Spam by CleanTalk: by СleanTalk <welcome@cleantalk.org> – 5.152.5
Backup and Staging by WP Time Capsule: by Revmakx – 1.22.0
BBQ Firewall: by Jeff Starr – 20201209
Beaver Builder Peek-a-Boo!: by MapSteps – 2.0.2
Beaver Builder Plugin (Standard Version): by The Beaver Builder Team – 2.4.2
Beaver Themer: by The Beaver Builder Team – 1.3.2.3
Classic Editor: by WordPress Contributors – 1.6
Easy Updates Manager: by Easy Updates Manager Team – 9.0.7
Email Templates: by Damian Logghe – 1.3.2.1
Font Awesome: by Font Awesome – 4.0.0-rc21
GDPR Cookie Consent Banner: by termly – 2.3.15
Google Pagespeed Insights: by Matt Keys – 4.0.3
GP Terms of Service: by Gravity Wiz – 1.3.14
Gravity Forms: by Gravity Forms – 2.4.22
Gravity Forms Mailchimp Add-On: by Gravity Forms – 4.8
Gravity Forms Signature Add-On: by Gravity Forms – 4.0
Gravity Forms Slack Add-On: by Gravity Forms – 1.13
Gravity Forms Stripe Add-On: by Gravity Forms – 3.9
Gravity Forms Zapier Add-on: by Gravity Forms – 3.3
Gravity Perks: by Gravity Wiz – 2.2.2
HTML Editor Syntax Highlighter: by James Bradford – 2.4.2
iQ Block Country: by Pascal – 1.2.10
iThemes Security: by iThemes – 7.9.0
Memcached Redux: by Scott Taylor - uses code from Ryan Boren
Denis de Bernardy
Matt Martz
Mike Schroder
Mika Epstein
Mohammad Jangda – 0.1.7

Nav Menu Roles: by Kathy Darling – 2.0.0
Page-list: by webvitaly – 5.2
Page Builder Framework Premium Addon: by David Vongries – 2.5.13
PowerPack for Beaver Builder: by IdeaBox Creations – 2.13.4
Really Simple SSL: by Really Simple Plugins – 4.0.8
Remove Product Image Links from WooCommerce: by Worcester Web Studio – 2.1.1
ShortPixel Image Optimizer: by ShortPixel – 4.21.1
Simple Page Ordering: by Jake Goldman
10up – 2.3.4

Site Kit by Google: by Google – 1.25.0
Tracking Code Manager: by IntellyWP – 2.0.0
Ultimate Addons for Beaver Builder: by Brainstorm Force – 1.29.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.16.47.25

Wallace Inline: by Bradley Kirby – 2.2.18
WooCommerce GoCardless Gateway: by WooCommerce – 2.4.13
WooCommerce Gravity Forms Product Add-Ons: by Lucas Stark – 3.3.17
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.8.2
WooCommerce Stripe Gateway: by WooCommerce – 4.8.0
WooCommerce Subscriptions: by WooCommerce – 3.0.12
WooPack for Beaver Builder: by Team IdeaBox - Beaver Addons – 1.3.11
WP Crontrol: by John Blackbourn & crontributors – 1.9.0
WP Rocket: by WP Media – 3.8.4
WP Rollback: by Impress.org – 1.7.1
WP User Manager: by WP User Manager – 2.5

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
maintenance.php: maintenance.php

### Must Use Plugins (1) ###

WP Time Capsule: by Revmakx –

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #2926 - /shop/
Basket: #2927 - /shop/basket/
Checkout: #2928 - /shop/checkout/
My account: #2929 - /shop/my-subscriptions/
Terms and conditions: #87 - /terms/

### Theme ###

Name: Twenty Twenty-One
Version: 1.1
Author URL: https://en-gb.wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 619
Oldest: 2021-01-11 15:09:08 +0000
Newest: 2021-02-11 13:32:31 +0000

Pending: 38
Oldest: 2021-02-11 13:33:08 +0000
Newest: 2022-01-01 03:30:46 +0000

Canceled: 13
Oldest: 2021-02-01 02:04:08 +0000
Newest: 2021-02-01 05:12:53 +0000
```
</details>

**Comment by fylgjur** [comment] 2021-02-11 15:25
Report was made in 1865623-hc and is to follow up in 3731486-zen

**Comment by louwie17** [comment] 2021-02-11 17:13
Thanks for reporting this @fylgjur, I was not able to reproduce this either. Timmy suggested a re-install:

> I know in the past that when sites have had issues with missing JS bundles a re-install of the WooCommerce plugin has fixed it.

Could we have the user try this? and see if it is still happening afterwards (maybe a clearing of caches or CDN would help as well).

**Comment by arunsathiya** [comment] 2021-02-12 01:14
>I reinstalled WC 5.0.0 and force cleared all the caches, both server/CDN and local. It was the local browser cache that was clearly at fault because it was only after force reloading the pages that the errors disappeared. Very strange, as this didn’t occur elsewhere.

It seems that the issue is resolved now! Closing GitHub issue.

**Comment by adrianduffell** [comment] 2021-02-16 03:20
We've had another report about this error, and it was able to be fixed by clearing the cache. Labelling this as critical due to the severity of causing a blank screen.

Is it possible to bust the local cache here?

**Comment by louwie17** [comment] 2021-02-17 17:48
@adrianduffell the versioning at the end of the script `?ver=1.9.0` is suppose to fix this, or enforce the browser cache to re-load. I am not sure if changing the version id to something more random would help.
I was also trying to figure out if this is a browser specific thing, but couldn't find which browser the users above where using.

It looks like gutenberg uses a format like this `ver=3574ea904d018d7755ea883529755548`.

**Comment by louwie17** [comment] 2021-02-17 17:56
Curious if the `chunk-src-version-param.js` webpack plugin could also have something to do with this https://github.com/woocommerce/woocommerce-admin/pull/5229, but that's been around since version `1.7.0`

**Comment by adrianduffell** [comment] 2021-02-18 00:16
@louwie17 thanks #5229 looks like a good find. I'm curious where the value of `window.wcAdminAssets.version` comes from.

Interestingly, the case reported to me has a different `ver` format to the original report: `1612307453`. It's a timestamp from 15 days ago.

![image](https://user-images.githubusercontent.com/9312929/108283855-09151180-71bf-11eb-906f-6e94307c5041.png)

This error occurred after they built WC Admin with `npm install && composer install && npm run build`.

**Comment by louwie17** [comment] 2021-02-18 01:06
Interesting @adrianduffell that they could reproduce it locally, have you been able to do so?
I believe if DEBUG is enabled it will use timestamps for the `ver=` instead (I forgot where I found that), I think in a similar place where `window.wcAdminAssets.` is [enqueued](https://github.com/woocommerce/woocommerce-admin/blob/dc104a0bdadc0877464d8f7fac2f26bedeba5d99/src/Loader.php#L457).
Found the file version logic [here](https://github.com/woocommerce/woocommerce-admin/blob/dc104a0bdadc0877464d8f7fac2f26bedeba5d99/src/Loader.php#L226)

**Comment by adrianduffell** [comment] 2021-02-18 06:17
@louwie17 I haven't been able to reproduce it locally. I've tried building an older version first, then re-building `main` but that didn't trigger it.

I'm not sure the `SCRIPT_DEBUG` timestamp works as intended though. It uses the modified time for the `/dist` folder as the timestamp, but this seemed to remain the same value between different builds.

**Comment by adrianduffell** [comment] 2021-02-19 05:31
This feels too complex to fix in time for the 2.1 release, so let's move it to the cool down period.

I think next we should investigate Gutenberg’s approach to cache busting, and perhaps take some direction from there.

**Comment by fishtankmike** [comment] 2021-03-02 10:36
This is happening to me in WC Analytics pages predominantly but lots of react issues throughout the admin...

![Screen Shot 2021-03-02 at 10 22 30](https://user-images.githubusercontent.com/33543845/109636182-2f359c80-7b43-11eb-973c-93fc0108c573.png)

**Comment by adrianduffell** [comment] 2021-03-02 23:55
Hi @fishtankmike, thanks for reporting this and I'm sorry to hear it is impacting your live site. I have a few questions to help try to debug this.

1. Could you please provide more detail about the caches you have cleared?

2. Do you know what might have triggered this, for example did you recently update WooCommerce?

3. What results do you get when requesting the missing URLs directly in a browser, such as `https://YOURDOMAIN/app/plugins/woocommerce/packages/woocommerce-admin/dist/chunks/store-alerts.js?ver=1.9.0`

4. Does the `/dist/chunks/store-alerts.js` file exist on the live server?

**Comment by fishtankmike** [comment] 2021-03-03 09:08
Hi @adrianduffell 

Thank you for your reply.

1. Could you please provide more detail about the caches you have cleared?
**I have cleared all browser cache, the analytcis cache in WC -> Status -> Tools.**

2. Do you know what might have triggered this, for example did you recently update WooCommerce?
**Yes I recently updated woocommerce but also since this started happening I completly remove WC and reinstalled it.**

3. What results do you get when requesting the missing URLs directly in a browser, such as https://YOURDOMAIN/app/plugins/woocommerce/packages/woocommerce-admin/dist/chunks/store-alerts.js?ver=1.9.0
![Screen Shot 2021-03-03 at 09 04 47](https://user-images.githubusercontent.com/33543845/109781132-8dc05080-7bff-11eb-983e-4055efaeda52.png)

4. Does the /dist/chunks/store-alerts.js file exist on the live server?
**Yep the file exists on the server**

**Comment by fishtankmike** [comment] 2021-03-03 09:26
Hi @adrianduffell 

Further to my last reply I decided to take a look at the file/folder permissions and ownership and found that they weren't quite right (not an expert).

I ran a couple of terminal commands within the WC plugin folder:

`chown -R MYUSERNAME:MYUSERNAME *`

`find . -type d -exec chmod 0755 {} \;`

`find . -type f -exec chmod 0644 {} \;`

This has fixed my issue and WC analytics pages etc are running fine again.

We use Source Tree and BitBucket for version control and this issue has cropped up before - in that it has changed file permissions when pushing local updates to production so I'm annoyed at myself for not checking sooner. 

Im sorry to have troubled you with my specific issue but maybe this might help someone else that is experiencing it.

Thanks again,
Mike

**Comment by adrianduffell** [comment] 2021-03-03 12:21
Thanks @fishtankmike, that's no problem - I'm glad you sorted it out.

**Comment by damiannep** [comment] 2021-03-30 13:46
Another report of this in 28723863-hc and I can replicate on my staging site on Pressable.

**Comment by moon0326** [comment] 2022-01-19 23:30
I'm closing this as it has been stale for 6+ months and no further similar bugs reported. Please feel free to re-open it if needed.

**Closed by moon0326** 2022-01-19 23:30 UTC
Labels: type: bug, priority: critical, cooldown period, Needs triage
