### ISSUE TITLE
The “set up payments” is marked as complete even if I didn’t choose a payments option

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#4241] opened 2020-04-28 20:16 UTC
**Is your feature request related to a problem? Please describe.**

Filing this on behalf of @andrewjkerr: pb22l9-8V-p2#comment-397.

Quoting:

>The “set up payments” is marked as complete even if I didn’t choose a payments option

>I clicked on “set up payments” on the setup and then clicked on “continue” without selecting an option but the set up showed it as complete (and took me to the main admin Panel 😅).

I agree with @andrewjkerr here. There is an option to click on `Done` without setting up any payment method:

![Screen Shot 2020-04-28 at 4 06 47 PM](https://user-images.githubusercontent.com/19143190/80533242-4deb6580-896b-11ea-85cf-1ce05f7c3181.png)

Once clicked, the task is being marked as completed and we show the message that the store is now ready to accept payments when it is not:

![pay](https://user-images.githubusercontent.com/19143190/80533330-74110580-896b-11ea-815b-45c861178400.jpg)

**Describe the solution you'd like**

Instead of `Done` we can say `Skip` and not show the message that the store is ready to accept payments. 

**Describe alternatives you've considered**

N/A

**Should this be prioritized? Why?**

It is not a deal-breaker but the experience is confusing here. 

**Additional context**

N/A

**Comment by dechov** [comment] 2020-05-19 15:56
👍 Came here to open an issue for this. Looks like a skip button is exactly what was intended for this, but there's a bug preventing it ([configuredMethods](https://github.com/woocommerce/woocommerce-admin/blob/d5a187dc4ce61b3280f357a54e4bd7a33282d689/client/dashboard/task-list/tasks/payments/index.js#L332) is already a `length`). 

Side-note: we might still want to be wary of saying "can now accept payments" even if one is configured, as it's possible that it still needs setup. cc @joshuatf

**Comment by joshuatf** [comment] 2020-06-09 08:26
https://github.com/woocommerce/woocommerce-admin/pull/3782 does handle skip/complete methods for this task, but as @dechov noted, the addition of any "configured" methods (e.g., COD which is pre-configured), will mean at least one method is already configured.

Probably the easiest option is to check for enabled gateways and allow "Done" to be shown when at least one is enabled.

>Side-note: we might still want to be wary of saying "can now accept payments" even if one is configured, as it's possible that it still needs setup. cc @joshuatf

This is my concern with marking any item as "configured" when it's not fully ready to accept payments.  I think it breaks the original intent of this task slightly, but we can reword the completion notice to something more open-ended if we're comfortable moving forward with partially configured payments.  /cc @pmcpinto and @jameskoster if you have any thoughts on re-wording or how this should work.

**Comment by jameskoster** [comment] 2020-06-09 09:16
> Probably the easiest option is to check for enabled gateways and allow "Done" to be shown when at least one is enabled.

Let's do this.

Then, if someone skips we know that no methods have been enabled, so there's no need to show the snackbar at all.

**Comment by joshuatf** [comment] 2020-06-09 10:01
@jameskoster One other consideration here is that the WC Pay method gets marked as configured even if it's not fully ready to accept payment so the "can now accept payments" portion of the success message may be inaccurate.

Related discussion on WC Pay configuration in https://github.com/Automattic/woocommerce-payments/pull/629

**Comment by pmcpinto** [comment] 2020-06-09 12:49
> Let's do this.
> Then, if someone skips we know that no methods have been enabled, so there's no need to show the snackbar at all.

Just to confirm: is the idea to display the button as "skip" if none of the options is turned on and as "done" if they have at least one option enabled? Just for reference, about 60% mark the step as done without having an option enabled.

> One other consideration here is that the WC Pay method gets marked as configured even if it's not fully ready to accept payment so the "can now accept payments" portion of the success message may be inaccurate.

Perhaps we should change the copy to something like: "...Don't forget to review your payments settings"

**Comment by joshuatf** [comment] 2020-06-09 13:05
>Just for reference, about 60% mark the step as done without having an option enabled.

Wow, that's a lot more than I would have expected.  Definitely sounds like the updated check for enabled methods is the way to go.

>Perhaps we should change the copy to something like: "...Don't forget to review your payments settings"

This does a good job of correcting the language, though I think some store owners may be confused when told to review payment settings after just setting them up.  That may just be me though; I don't have strong feelings on the text here.

**Comment by pmcpinto** [comment] 2020-06-09 15:36
> though I think some store owners may be confused when told to review payment settings after just setting them up. That may just be me though; I don't have strong feelings on the text here.

Yep that's a good point. We can use it as a reminder to test the store checkout, which is always important to do and it ends up being a way to see if everything is working properly on the payments side: Don't forget to test your store checkout flow, to make sure that everything is working fine.

**Comment by dechov** [comment] 2020-06-09 15:45
> the addition of any "configured" methods (e.g., COD which is pre-configured), will mean at least one method is already configured

@joshuatf I wasn't actually aware of any methods already being configured – I was referring to a double `.length` (first [here](https://github.com/woocommerce/woocommerce-admin/blob/d5a187dc4ce61b3280f357a54e4bd7a33282d689/client/dashboard/task-list/tasks/payments/index.js#L214) then [here](https://github.com/woocommerce/woocommerce-admin/blob/d5a187dc4ce61b3280f357a54e4bd7a33282d689/client/dashboard/task-list/tasks/payments/index.js#L332)) causing the skip action to never appear.

**Comment by jameskoster** [comment] 2020-06-09 17:32
Let's take a step back. 

Working on the premise that this screen could eventually replace the core payment settings screen, I'm going to explore how that might work in a little more detail tomorrow. 

In that eventuality we shouldn't need the done / skip links at all, so perhaps we can eliminate them here as well. If we can make this setup flow work without them, we'd solve the problems highlighted in this issue _and_ better prepare us for the future.

**Comment by jameskoster** [comment] 2020-06-11 10:54
I think we can remove the skip link and done button entirely.

But we should only mark the payments task as complete when a method has been configured and enabled.

As a part of the Home screen work, we're updating the task list to make the [entire thing dismissible](https://cloudup.com/itUTrSHtZ7J). That will enable the large number of people who don't want to set up a payment method (or complete any other of our tasks) to hide the task list. If that turns out to be inadequate, we can consider updating the payments task to include the inline [dismissal option](https://woostartp2.files.wordpress.com/2020/06/dismiss-1.gif?w=664&zoom=2) we're building for the "Setup wizard", "Install WooCommerce pages", and "Purchase `extension`" tasks, but I think it would be best to avoid this if possible to begin with, since setting up payments is so important.

The only thing that will be missing from the experience if we remove these buttons is a clear path back to the home screen once a user has finished setting up their payment methods. This seems like a perfect time to consider implementing [this](https://github.com/woocommerce/woocommerce-admin/issues/2811) feature.

**Comment by joshuatf** [comment] 2020-06-12 06:37
>The only thing that will be missing from the experience if we remove these buttons is a clear path back to the home screen once a user has finished setting up their payment methods.

@jameskoster This is my main concern here.  I'd be worried that the back button may be overlooked in the corner of the screen, but you may have testing that says otherwise.

If for some reason they can't find the button, they will have to navigate backwards via the browser's back button through all the payment gateways they set up in order to reach the task list.

If we move forward with https://github.com/woocommerce/woocommerce-admin/issues/2811 I still think we should implement this fix short-term as https://github.com/woocommerce/woocommerce-admin/issues/2811 will not be quick.

**Comment by jameskoster** [comment] 2020-06-12 09:49
@joshuatf they can always click the "Home" link in the main navigation as well.

Is there a middle-ground option for #2811 where we just hardcode it for this screen?

Another option would be to add a "back to setup" action to all the snackbars that are displayed when methods are enabled.

I'm keen to avoid the done button / skip links as they do not align with the direction we're moving in, whereas the back button (in the app bar) and the snackbar adjustment do.

**Comment by joshuatf** [comment] 2020-06-12 10:46
>Is there a middle-ground option for #2811 where we just hardcode it for this screen?

Good point @jameskoster.

>Is there a middle-ground option for #2811 where we just hardcode it for this screen?

I think we could, but it would be a pretty hacky solution and I'd like to give some more thought on the technical side, so we're not introducing really bad patterns into our code here.

>I'm keen to avoid the done button / skip links

I think ultimately removing them is a good solution, but these buttons already exist so this issue is mostly just about fixing what they do if a pre-configured option exists.

If we're okay relying on just the "Home" solution then we can fully remove them.

**Comment by jameskoster** [comment] 2020-06-12 16:02
> If we're okay relying on just the "Home" solution then we can fully remove them.

Would it be possible to remove the active state on that link when you navigate in to a task? If so I think we can definitely give this a shot :)

**Comment by joshuatf** [comment] 2020-06-15 05:17
>Would it be possible to remove the active state on that link when you navigate in to a task? If so I think we can definitely give this a shot :)

@jameskoster Would this happen on entering any task?  A quick solution might be a little hacky, but not the end of the world for a temporary solution.

I'm going to merge #4530 in the meantime which is a quick fix for the enabled methods and we can outline an issue to remove these buttons and the link issue in a follow-up based on your answer to the above.

**Closed** 2020-06-15 05:43 UTC
Labels: cooldown period

**Comment by jameskoster** [comment] 2020-06-15 09:29
> @jameskoster Would this happen on entering any task?

Yes. The task screens are ephemeral and not part of the home screen ito UX. I think removing the active state will help folks understand that they can navigate back to the home screen from a task.

**Comment by pmcpinto** [comment] 2020-06-17 13:38
> Another option would be to add a "back to setup" action to all the snackbars that are displayed when methods are enabled.

@jameskoster adding the Setup shortcode on the top bar (#4592) will solve this, right?

**Comment by jameskoster** [comment] 2020-06-18 08:51
Yes, that too! :)
