### ISSUE TITLE
Header should only show if current_user_can manage_woocommerce

### ISSUE THREAD

**Issue by khag7** [woocommerce/woocommerce-admin#3276] opened 2019-11-19 02:56 UTC
**Is your feature request related to a problem? Please describe.**
Users who have no capability to access the wc-admin page shouldn't be shown a link to that page.

**Describe the solution you'd like**
Ideally I don't think users should even be shown the WooCommerce Admin header if they don't have ability to use any of the plugin's features.

**Describe alternatives you've considered**
I have added css to hide the header from users who don't need it.

**Should this be prioritized? Why?**
No.

**Additional context**
I have users who can do nothing but view/edit orders. They process the orders for shipment. They can't view reports, they can't edit products, they can't do anything. In the screenshot below you can see on the left how empty their admin menu is. They shouldn't even be shown the wc-admin header. In fact, if they click that purple link, they get an error that they don't have access to the page. Why should they even be shown the link.

I could be wrong, but shouldn't that entire header bar only be shown if `current_user_can( 'manage_woocommerce' ) || current_user_can( 'view_woocommerce_reports' )`

![chrome_uix5VgjPVB](https://user-images.githubusercontent.com/1531746/69112219-bdb90400-0a4d-11ea-8ce8-029d16e1f57d.png)

**Comment by khag7** [comment] 2019-11-19 03:11
Similar situation:
HTTP requests to the wp-json/wc-analytics endpoint are happening, resulting in repeated 403 errors, since these users have no access to that endpoint. Just because a user can `edit_shop_orders` doesn't mean they can `manage_woocommerce`, these requests shouldn't even be made, should they?

**Comment by rrennick** [comment] 2019-11-19 12:23
> I could be wrong, but shouldn't that entire header bar only be shown if current_user_can( 'manage_woocommerce' ) || current_user_can( 'view_woocommerce_reports' )

The current permission requirement for WC Admin is `current_user_can( 'view_woocommerce_reports' )` and is filterable.

> I have users who can do nothing but view/edit orders.

I'll see if I can reproduce this in my dev install.

**Comment by rrennick** [comment] 2019-11-19 14:49
@khag7 Can you provide more info on the user role you have set up? I stripped a test user down to editing orders and the account cannot navigate to the dashboard.

**Comment by khag7** [comment] 2019-11-20 01:45
Yes I apologize, I did forget that I have a snippet of code that allows admin area access for more roles. By default WooCommerce requires `manage_woocommerce` to access the back end of the website, but I have several users who I do not want to change WooCommerce settings so I have given them access to admin area with the following filter:
```
add_filter( 'woocommerce_prevent_admin_access', function( $prevent_access ){
    if ( current_user_can( 'edit_shop_orders' ) ) $prevent_access = false;
    return $prevent_access;
}
```

As to the role I created, they have no problems editing orders, I just thought it would be sensible for WooCommerce Admin to not show for them since they can't use any of its features.

Their capabilities are as follows:
- read
- edit_shop_orders
- edit_others_shop_orders
- publish_shop_orders
- read_private_shop_orders
- read_private_shop_coupons
- edit_private_shop_orders
- edit_published_shop_orders
- read_private_products
- assign_shop_order_terms
- delete_shop_order_terms
- edit_shop_order
- edit_shop_order_terms
- read_product
- read_shop_coupon
- read_shop_order

**Comment by rrennick** [comment] 2019-11-20 17:20
I was able to reproduce this. The short term fix for this might be to remove the header for users who cannot access the WC v3 REST endpoints. Longer term, Stock should be visible to users with permission to edit products and Orders to users with permission to edit orders.

**Comment by khag7** [comment] 2019-11-26 03:17
@rrennick curiosity strikes me.. what does the tag "Many Small" mean. I gather that it has something to do with priority (small) but what is "many"?

**Comment by rrennick** [comment] 2019-11-26 11:44
@khag7 Many Small means it's a minor issue that would affect a significant number of users. In this case it's small because it doesn't adversely affect any of the designed use of the dashboard/analytics.

**Closed** 2019-12-10 14:04 UTC
Labels: Dashboard, [Many] Small, [Type] Bug
