### ISSUE TITLE
Fatal error if customer doesn't exist

### ISSUE THREAD

**Issue by n9yty** [woocommerce/woocommerce-admin#1985] opened 2019-04-02 19:40 UTC
**Describe the bug**
In processing the historical data, it aborts while importing batches. In our case, it seemed to be several orders that, for whatever reason, no longer have a customer in the system.

**To Reproduce**
Re-process historical orders with missing customers.

**Expected behavior**
The error should be handled so it does not cause a fatal error, which also seems to abort processing the rest of the items in that particular scheduled group.

One example:

Running 100 actions  36 % [=======================================>                                                                     ] 0:13 / 0:38
Started processing action 1335011
[02-Apr-2019 19:35:52 UTC] PHP Fatal error:  Uncaught Error: Call to a member function date() on null in /var/www/html/wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-customers-data-store.php:477
Stack trace:
#0 /var/www/html/wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-orders-stats-data-store.php(407): WC_Admin_Reports_Customers_Data_Store::get_or_create_customer_from_order(Object(WC_Admin_Order))
#1 /var/www/html/wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-orders-stats-data-store.php(368): WC_Admin_Reports_Orders_Stats_Data_Store::update(Object(WC_Admin_Order))
#2 /var/www/html/wp-content/plugins/woocommerce-admin/includes/class-wc-admin-reports-sync.php(269): WC_Admin_Reports_Orders_Stats_Data_Store::sync_order(16357)
#3 /var/www/html/wp-content/plugins/woocommerce-admin/includes/class-wc-admin-reports-sync.php(255): WC_Admin_Reports_Sync::orders_lookup_process_order(16357)
#4 /var/www/html/wp-includes/class-wp-hook.php(286): WC_Admin_Reports_Syn in /var/www/html/wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-customers-data-store.php on line 477
Fatal error: Uncaught Error: Call to a member function date() on null in /var/www/html/wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-customers-data-store.php:477
Stack trace:
#0 /var/www/html/wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-orders-stats-data-store.php(407): WC_Admin_Reports_Customers_Data_Store::get_or_create_customer_from_order(Object(WC_Admin_Order))
#1 /var/www/html/wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-orders-stats-data-store.php(368): WC_Admin_Reports_Orders_Stats_Data_Store::update(Object(WC_Admin_Order))
#2 /var/www/html/wp-content/plugins/woocommerce-admin/includes/class-wc-admin-reports-sync.php(269): WC_Admin_Reports_Orders_Stats_Data_Store::sync_order(16357)
#3 /var/www/html/wp-content/plugins/woocommerce-admin/includes/class-wc-admin-reports-sync.php(255): WC_Admin_Reports_Sync::orders_lookup_process_order(16357)
#4 /var/www/html/wp-includes/class-wp-hook.php(286): WC_Admin_Reports_Syn in /var/www/html/wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-customers-data-store.php on line 477

**Comment by joshuatf** [comment] 2019-04-03 02:06
@n9yty Thanks for posting this issue!  I think this may be a duplicate of https://github.com/woocommerce/woocommerce-admin/issues/1925 which was resolved by https://github.com/woocommerce/woocommerce-admin/pull/1926.

Are you running the latest version of master from this repo or the version from the WP plugins repo?

**Comment by n9yty** [comment] 2019-04-03 02:17
I was given the archive to install on the test site as we had some problems with it, I didn't come back to get the master which I should have. Thanks for clearing it up, I'll give it a go.

**Comment by timmyc** [comment] 2019-04-03 18:29
Thanks @n9yty for the bug report!

**Comment by josephsellers** [comment] 2019-04-26 07:57
I have a fatal error that may be related to the above. A user who did not sign up through WooCommerce and has no orders in WooCommerce signed into the site and got a fatal error. When I looked in the log I have the following:

```
[26-Apr-2019 07:13:17 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_billing_last_name() on boolean in /srv/users/appname/apps/appname/public/wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-customers-data-store.php:530
Stack trace:
#0 /srv/users/appname/apps/appname/public/wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-customers-data-store.php(625): WC_Admin_Reports_Customers_Data_Store::get_customer_name(4923, false)
#1 /srv/users/appname/apps/appname/public/wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-customers-data-store.php(87): WC_Admin_Reports_Customers_Data_Store::update_registered_customer(4923)
#2 /srv/users/appname/apps/appname/public/wp-includes/class-wp-hook.php(288): WC_Admin_Reports_Customers_Data_Store::update_registered_customer_via_last_active('2604532', 4923, 'wc_last_active')
#3 in /srv/users/appname/apps/appname/public/wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-customers-data-store.php on line 530
```

**Comment by KZeni** [comment] 2019-05-28 17:51
I got the following fatal PHP error during the import, myself:
```
Fatal error Uncaught Error: Call to a member function get_customer_id() on boolean in /wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-customers-data-store.php:441 Stack trace: #0 /wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-customers-data-store.php(464): WC_Admin_Reports_Customers_Data_Store::get_existing_customer_id_from_order(false) #1 /wp-content/plugins/woocommerce-admin/includes/class-wc-admin-order-refund.php(52): WC_Admin_Reports_Customers_Data_Store::get_or_create_customer_from_order(false) #2 /wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-orders-stats-data-store.php(419): WC_Admin_Order_Refund->get_report_customer_id() #3 /wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-orders-stats-d in /wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-customers-data-store.php on line 441
```
This is shown as "Failed" under WooCommerce => Status => Scheduiled Tasks after triggering the import (many other aspects of the import went along file & completed successfully, but this keeps returning as failed).

I'm running the current version of the plugin 0.12.0 where it seems both https://github.com/woocommerce/woocommerce-admin/pull/1926 & https://github.com/woocommerce/woocommerce-admin/pull/2190 should be present.

**Comment by KZeni** [comment] 2019-05-28 19:18
I've also come across
```
PHP Fatal error Uncaught Error: Call to a member function get_user_id() on boolean in /wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-customers-data-store.php:474 Stack trace: #0 /wp-content/plugins/woocommerce-admin/includes/class-wc-admin-order-refund.php(52): WC_Admin_Reports_Customers_Data_Store::get_or_create_customer_from_order(false) #1 /wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-orders-stats-data-store.php(419): WC_Admin_Order_Refund->get_report_customer_id() #2 /wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-orders-stats-data-store.php(392): WC_Admin_Reports_Orders_Stats_Data_Store::update(Object(WC_Admin_Order_Refund)) #3 /wp-content/plugins/woocommerce-admin/includes/class-wc-admin-reports-sync.php(406): WC_Admin_Repor in /wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-customers-data-store.php on line 474
```
after fixing the first issue I mentioned. I'll update my PR https://github.com/woocommerce/woocommerce-admin/pull/2326 to account for this new error as well.

**Comment by edwinho89** [comment] 2019-05-30 05:25
Hello! I'm referencing customer ticket #2071483-zen as it was recently reported - keep up the good work!

```
unexpected shutdown: PHP Fatal error Uncaught Error: Call to a member function get_customer_id() on boolean in /srv/htdocs/wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-customers-data-store.php:441 Stack trace: #0 /srv/htdocs/wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-customers-data-store.php(464): WC_Admin_Reports_Customers_Data_Store::get_existing_customer_id_from_order(false) #1 /srv/htdocs/wp-content/plugins/woocommerce-admin/includes/class-wc-admin-order-refund.php(52): ...
```

**Closed** 2019-06-20 03:22 UTC
Labels: REST API, [Type] Bug
