### ISSUE TITLE
Customer Analytics Data Anonymized for All Orders Belonging to Customer

### ISSUE THREAD

**Issue by adrianduffell** [woocommerce/woocommerce-admin#5187] opened 2020-09-23 14:19 UTC
**Describe the bug**
Customer analytics data is anonymized for orders selected to have personal information removed. For example:

![Screen Shot 2020-09-23 at 8 53 04 pm](https://user-images.githubusercontent.com/9312929/94015087-fbf62100-fdde-11ea-89b4-59dee428d3f6.png)

However, this process anonymizes the customer analytics data for **all** orders belonging to that customer, regardless of which orders were selected. This is because the orders share the same customer record in the `*wc_customer_lookup` table.

**To Reproduce**

1. Complete two or more orders with a new user.
2. Manually remove privacy information for one of the orders:
    1. Allow personal data to be removed in bulk from orders.
![Screen Shot 2020-09-23 at 8 48 31 pm](https://user-images.githubusercontent.com/9312929/94017690-4d53df80-fde2-11ea-83e5-3b842ee3b253.png)
    2. Select one of the new orders from the WooCommers orders page.
    3. Choose _Remove personal data_ from the _Bulk Actions_ menu.
![Screen Shot 2020-09-23 at 9 19 09 pm](https://user-images.githubusercontent.com/9312929/94017900-8a1fd680-fde2-11ea-8d69-2cd69b9e3bd6.png)
4. View the newly created orders in Analytics > Orders. All orders for the new customer are anonymized.

**Expected behavior**

- Only the orders which were selected to have personal information removed should have customer analytics data removed.
- Other orders belonging to the same customer should have customer analytics data retained. 

**Desktop (please complete the following information):**

* OS: macOS
* Browser: safari
* Version: 14

**Additional context**

This was discovered investigating #4946 . The issue also occurs when an order is automatically selected according to the personal data retention settings. 

 ![image](https://user-images.githubusercontent.com/9312929/94019972-f13e8a80-fde4-11ea-9cd2-7b754628b875.png)

**Comment by octaedro** [comment] 2022-01-28 18:14
I was able to reproduce this error.

After taking a glance, it looks like there is a problem in table `wp_wc_customer_lookup`.

In that table we're saving the `customer_id`, so when we trigger `remove_order_personal_data`, the information in the order is updated and then we update that information in `wp_wc_customer_lookup`. So, if the same customer has two different orders and we trigger `remove_order_personal_data` just for one, the change will affect both orders.
It seems like the solution would be to add a column to `wp_wc_customer_lookup` to save the `order_id` as well. Having the `order_id` we would be able to to delete the customer personal data for a specific order without affecting other orders' data.

Since this bug is older than a year, and the fix won't be trivial, I'm going to close this issue.

**Closed by octaedro** 2022-01-28 18:14 UTC
Labels: type: bug, feature: analytics, Needs triage
