### ISSUE TITLE
Customer Feedback modal translation strings not registered

### ISSUE THREAD

**Issue by starypop** [woocommerce/woocommerce-admin#7221] opened 2021-06-22 10:15 UTC
**Describe the bug**
Feedback modal translation strings are not registered as a string available for translations, it's always in English. The Polish translation of those strings is provided, eg. https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/pl/default/?filters%5Bterm%5D=Please+share+your+feedback&filters%5Bterm_scope%5D=scope_any

**To Reproduce**

1. Switch WP language to non-en.
2. Turn on WooCommerce plugin and go to WooCommerce Settings.
3. Change some setting, eg. Shipping location 
3. Look at the Screenshot above to see what fields are not registered:

- "**Give feedback**" button label
- "**Please share your feedback**" modal title
- Emojis labels
- Validation error notice
- "**Send**" button

**Expected behavior**
Those labels should be registered for translations.

**Screenshots**
![Zrzut ekranu 2021-06-22 o 11 48 48](https://user-images.githubusercontent.com/27000783/122906785-d0df3480-d352-11eb-8767-9036ae527f4d.png)
![Zrzut ekranu 2021-06-22 o 12 08 01](https://user-images.githubusercontent.com/27000783/122906798-d3da2500-d352-11eb-9fe1-eb94a39d0d14.png)

WP 5.7.2
WC 5.4.1
WC Admin 2.3.1 (bundled with WC)

**Comment by octaedro** [comment] 2021-06-23 15:26
Thank you @starypop for reporting this error.
I can reproduce it. This is happening because the text is still [available for translation](https://translate.wordpress.org/projects/wp-plugins/woocommerce-admin/stable/pl/default/?filters%5Bterm%5D=Please+share+your+feedback&filters%5Bterm_scope%5D=scope_any).
It looks like it's translated in WooCommerce but not in WooCommerce Admin.

**Comment by octaedro** [comment] 2021-06-23 18:08
As the untranslated text is currently enqueued (available) for translation, and there aren't any technical problems behind it, I'll close this issue.

**Comment by starypop** [comment] 2021-06-23 19:23
HI @octaedro,

I still think it is a bug, because it is a WC Admin version bundled with WooCommerce plugin, not a standalone WC Admin plugin installed, as I mentioned. In this case translations of WC Admin should be loaded from `woocommerce` domain instead of the `woocommere-admin`, I believe.

I think there's a missing `'wc-customer-effort-score'` element in the `$translated_scripts` array here:
https://github.com/woocommerce/woocommerce-admin/blob/6468742c6e1df872ad99e907dfbe67473d52e2b1/src/Loader.php#L389

When `'wc-customer-effort-score'` is added there, Polish translations from `woocommerce` domain are successfully loaded and the bug is fixed.

BTW In [the link you've provided](https://translate.wordpress.org/projects/wp-plugins/woocommerce-admin/stable/pl/default/?filters%5Bterm%5D=Please+share+your+feedback&filters%5Bterm_scope%5D=scope_any), You can see that only 14/1743 (less than 1%) of the strings are translated into Polish in WooCommerce Admin standalone project, but the Polish translations of any other WC Admin bundled with WooCommerce plugin areas work just fine. It means that they're taken from [WooCommerce project](https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/pl/default/) instead, as they should.

**Comment by octaedro** [comment] 2021-06-29 12:52
Thank you @starypop for your comment, what you said makes sense.
It seems that customer effort score JS is not translated properly even when the translation is available in Core.
I'll reopen this issue.

**Closed** 2021-07-06 19:30 UTC
Labels: category: i18n, type: bug
