### ISSUE TITLE
Analytics Reports (Orders and others) Do Not Match Overview Report Data

### ISSUE THREAD

**Issue by kcfgl** [woocommerce/woocommerce-admin#6529] opened 2021-03-07 18:22 UTC
**Describe the bug**
I'm getting some very weird behavior with all the reports other than Overview. Any filtering at all seems to break the reporting in multiple ways. One example is shown in these screenshots. If I search all of January, the orders and the metrics match exactly what the Overview report shows, which is accurate and matches real orders. 

However, if I change the date range to the last two days of January, the report results basically double. Not only that, but the individual order rows are essentially showing just the first row's data.  If I switch the number of rows per page to the max, then the rows change back into showing the correct information. Very weird.

I'm working on adding some advanced filters to the reports, through a separate plugin, following @psealock excellent extending WC-Admin post, but more recently through a suggestion of his in a forum to use woocommerce_admin_orders_report_advanced_filters. 

Because of the weirdness in the way the reports are generating, it is making it impossible to do these customizations.  At first, I thought the plugin was the culprit, so I deactivated it. Same results. Happy to provide any additional info. I'm hoping it has something to do with caching and even though my plugin is disabled, somehow that is still the culprit and it is an easy fix. I can provide any additional details you need. Thanks!

**To Reproduce**

1. Go to Overview and run a report for the entire month of Jan 2021. Note the amount
2. Run the same report but for the last 2 days of Jan 2021. Note the amount
3. Go to Orders and run the report for the entire month of Jan 2021. Note the amount
4. Run the same report but for the last 2 days of Jan 2021. Note the difference in the results.
5. Try to add advanced filters and the results will be variable, but not consistent

**Expected behavior**
The Orders report (and other reports) will match the actual orders and the data displayed by the Overview report.  The order rows will not be duplicates of the first row but will show the actual data for each row.

**Screenshots**
<img width="1593" alt="Screen Shot 2021-03-07 at 1 08 11 PM" src="https://user-images.githubusercontent.com/19731815/110250027-3dbaf400-7f47-11eb-8cc0-bcf71b9d15e9.png">

<img width="1602" alt="Screen Shot 2021-03-07 at 1 07 40 PM" src="https://user-images.githubusercontent.com/19731815/110250032-44e20200-7f47-11eb-8ad7-13021d7bd868.png">

**Desktop (please complete the following information):**

* Mac OS 10.15.7
* Chrome
* Version 88.0.4324.192 (Official Build) (x86_64)
* I also tried this incognito thinking maybe its a front end cache problem.  Same result.

**Comment by samueljseay** [comment] 2021-03-07 23:43
Hi @kcfgl thanks for raising this, it seems like a really frustrating problem.

I set up some test environments with 2 years of order data and I could not reproduce this. What version of wc-admin are you on? I know we had some past issues in this area that *may* have been resolved recently.

The only other thought I have at this point is if it was your custom plugin that somehow caused this, maybe @psealock would know more about what kind of thing could cause this weirdness?

**Comment by kcfgl** [comment] 2021-03-07 23:59
Thanks for the quick feedback @samueljseay, I appreciate it. Part of me is relieved to hear you can't replicate it and the other part is not, you know what I mean! You're right, it's a frustrating one and a confusing one. Even though my plugin is deactivated, I'm wondering if something is cached and needs to be busted? Happy to provide any additional details you and @psealock need to possibly point me to a resolution. Thanks again!

**Comment by psealock** [comment] 2021-03-08 04:32
I also tried to reproduce this but wasn't successful either.

When I was working on extensions that changed API results, then switched to other work I definitely came across cached results being returned despite deactivating the code. So this is a good place to start.

Have you tried running `wp cache flush`?

There is also a function that invalidates all caches

https://github.com/woocommerce/woocommerce-admin/blob/92bdbf69ac2049ba24429fdfd23608fafa55e532/src/API/Reports/Cache.php#L24-L26

You could run code to execute, something like 

```php
use \Automattic\WooCommerce\Admin\API\Reports\Cache as ReportsCache;
ReportsCache::invalidate();
```
Hopefully that works!

**Comment by kcfgl** [comment] 2021-03-08 20:01
Hi @psealock thanks for the tip on the report cache invalidation. I ran it and that cleared up the issue. So a bit more detail. The duplication only happens if I add a custom advanced filter to the list and attempt to filter the report. Initial load, without adding a custom filter, calculates just fine. Once I add it in, things go sideways. I'll keep at it and see if I can provide any additional details that would be helpful. At this point I'm operating under the assumption its me and not a bug, but here is some more info.

For some more background, I'm adding the filter using woocommerce_admin_orders_report_advanced_filters. But all the SQL modification, I'm following your post from last year around extending WC-Admin reports. Is there any additional documentation I should be following around using the advanced filters and not just adding a normal filter? The reason I went for advanced is that it supports the date component.  Thanks again!

**Comment by kcfgl** [comment] 2021-03-08 20:36
@psealock A bit more detail, in code this time. The moment I load up a report with the custom extension plugin - without even a filter - my numbers multiply by about 58 haha. I did see another bug report that mentioned duplication on the products report, but mine is clearly due to the plugin, but maybe a similar issue deeper down causing it? That is why I'm posting the code below. Maybe there is something going on.

I've attempted to follow the example post you wrote to the T, except that I'm keying off a custom meta field and its a date. If you can replicate this - or see the blatant error in my code, that would be awesome. Thanks again.

    function apply_custom_arg( $args ) {
	$shipped_date_from = '2020-01-01';
	$shipped_date_to = date('Y-m-d');

	if ( isset( $_GET['Shipped_between[0]'] ) ) {
		$shipped_date_from = sanitize_text_field( wp_unslash( $_GET['Shipped_between[0]'] ) );
	}

	if ( isset( $_GET['Shipped_between[1]'] ) ) {
		$shipped_date_to = sanitize_text_field( wp_unslash( $_GET['Shipped_between[1]'] ) );
	}

	$args['Shipped_between[0]'] = $shipped_date_from;
	$args['Shipped_between[1]'] = $shipped_date_to;

	return $args;
    }

    add_filter( 'woocommerce_analytics_revenue_query_args', 'apply_custom_arg' );
    add_filter( 'woocommerce_analytics_orders_query_args', 'apply_custom_arg' );
    add_filter( 'woocommerce_analytics_orders_stats_query_args', 'apply_custom_arg' );

    /**
     * Add a JOIN clause.
     *
     * @param array $clauses an array of JOIN query strings.
     * @return array augmented clauses.
     * Test_between[0]=2021-02-04&Test_between[1]=2021-03-05
     */
    function add_join_subquery( $clauses ) {
	global $wpdb;

	// Shipped Date
	$clauses[] = "JOIN {$wpdb->postmeta} order_was_shipped_postmeta ON {$wpdb->prefix}wc_order_stats.order_id = order_was_shipped_postmeta.post_id";

	return $clauses;
    }

    add_filter( 'woocommerce_analytics_clauses_join_orders_subquery', 'add_join_subquery' );
    add_filter( 'woocommerce_analytics_clauses_join_orders_stats_total', 'add_join_subquery' );
    add_filter( 'woocommerce_analytics_clauses_join_orders_stats_interval', 'add_join_subquery' );

    /*
    * Add a WHERE clause.
    *
    * @param array $clauses an array of WHERE query strings.
    * @return array augmented clauses.
    */
    function add_where_subquery( $clauses ) {
        // Set some defaults even though i do not want the defaults to be used if there is not a filter being applied
	$shipped_date_from = '2020-01-01';
	$shipped_date_to = date('Y-m-d');

	// Get the From Date
	if ( isset( $_GET['Shipped_between[0]'] ) ) {
		$shipped_date_from = sanitize_text_field( wp_unslash( $_GET['Shipped_between[0]'] ) );
	}
	// Get the To Date
	if ( isset( $_GET['Shipped_between[1]'] ) ) {
			$shipped_date_to = sanitize_text_field( wp_unslash( $_GET['Shipped_between[1]'] ) );
	} else {
			$shipped_date_to = date("Y-m-d");
	}

	if( isset( $_GET['Shipped_between[0]'] ) ){
		// Add the shipped date lause
		$clauses[] = "AND order_was_shipped_postmeta.meta_key = '_order_was_shipped' AND order_was_shipped_postmeta.meta_value BETWEEN {$shipped_date_from} AND {$shipped_date_to}";
	}

	return $clauses;
    }
    add_filter( 'woocommerce_analytics_clauses_where_orders_subquery', 'add_where_subquery' );
    add_filter( 'woocommerce_analytics_clauses_where_orders_stats_total', 'add_where_subquery' );
    add_filter( 'woocommerce_analytics_clauses_where_orders_stats_interval', 'add_where_subquery' );

    /**
     * Add a SELECT clause.
     *
     * @param array $clauses an array of WHERE query strings.
     * @return array augmented clauses.
     */
    function add_select_subquery( $clauses ) {

	$clauses[] = ', order_was_shipped_postmeta.meta_value AS order_was_shipped';

	return $clauses;
    }

    add_filter( 'woocommerce_analytics_clauses_select_orders_subquery', 'add_select_subquery' );
    add_filter( 'woocommerce_analytics_clauses_select_orders_stats_total', 'add_select_subquery' );
    add_filter( 'woocommerce_analytics_clauses_select_orders_stats_interval', 'add_select_subquery' );

The only thing in the JS file at the moment ... 

    import { addFilter } from '@wordpress/hooks';
    import { __ } from '@wordpress/i18n';

    // Add Shipped Date Filter
    const addShippedDateAdvancedFilter = (advancedFilters) => {
        advancedFilters.filters['Shipped'] = {
            labels: {
                add   : __('Shipped Date', 'woocommerce-admin'),
                remove: __(
                    'Remove Shipped Date filter',
                    'woocommerce-admin'
                ),
                rule  : __(
                    'Select Shipped Date',
                    'woocommerce-admin'
                ),
                title : __(
                    '{{title}}Shipped Date{{/title}} {{rule /}} {{filter /}}',
                    'woocommerce-admin'
                ),
                filter: __('Select Shipped Date', 'woocommerce-admin'),
            },
						rules: [
				{
					value: 'between',
					label: __( 'Between', 'woocommerce-admin' ),
				},
			],
			input: {
				component: 'Date',
			},
        };

    return advancedFilters;
    };
    addFilter(
    'woocommerce_admin_orders_report_advanced_filters',
    'lab-reporting-extension',
    addShippedDateAdvancedFilter
    );

**Comment by kcfgl** [comment] 2021-03-14 14:42
Hi @psealock. You probably have bigger fish to fry, but wanted to follow up on this and see if there are more details you need from me. 

Also wanted to see what your gut says … do you think my setup above “should” work and there is a legit issue, or should I keep digging into my own code because it’s not quite right? Just trying to plan my attack for some custom reports and really hoping I can leverage the existing reports and filter those. Thanks again for any feedback you can provide.

**Comment by louwie17** [comment] 2021-03-15 17:33
@kcfgl small update on this, it appears the reason it's happening is because of the second join causing a row for each meta field as well (that's why you see the increase by about 58). I tried this locally with this query it generates showing the increased revenue amount:
```
SELECT
				SUM( CASE WHEN wp_wc_order_stats.parent_id = 0 THEN 1 ELSE 0 END ) as orders_count, SUM(wp_wc_order_stats.net_total) AS net_revenue, SUM( wp_wc_order_stats.net_total ) / SUM( CASE WHEN wp_wc_order_stats.parent_id = 0 THEN 1 ELSE 0 END ) AS avg_order_value, SUM( wp_wc_order_stats.num_items_sold ) / SUM( CASE WHEN wp_wc_order_stats.parent_id = 0 THEN 1 ELSE 0 END ) AS avg_items_per_order , currency_postmeta.meta_value AS currency , order_was_shipped_postmeta.meta_value AS order_was_shipped
			FROM
				wp_wc_order_stats
				LEFT JOIN (
						SELECT
							order_id,
							SUM(discount_amount) AS discount_amount,
							COUNT(DISTINCT coupon_id) AS coupons_count
						FROM
							wp_wc_order_coupon_lookup
						GROUP BY
							order_id
						) order_coupon_lookup
						ON order_coupon_lookup.order_id = wp_wc_order_stats.order_id JOIN wp_postmeta currency_postmeta ON wp_wc_order_stats.order_id = currency_postmeta.post_id JOIN wp_postmeta order_was_shipped_postmeta ON wp_wc_order_stats.order_id = order_was_shipped_postmeta.post_id
			WHERE
				1=1
				AND ( wp_wc_order_stats.status NOT IN ( 'wc-trash','wc-pending','wc-failed','wc-cancelled' ) ) AND wp_wc_order_stats.date_created <= '2021-03-15 23:59:59' AND wp_wc_order_stats.date_created >= '2021-03-11 00:00:00' AND currency_postmeta.meta_key = '_order_currency' AND currency_postmeta.meta_value = 'CAD'
```
If you change the select to a `select * from ...` you can see the many duplicate rows (aside from the meta), now if you remove the last join `JOIN wp_postmeta order_was_shipped_postmeta ON wp_wc_order_stats.order_id = order_was_shipped_postmeta.post_id` it works fine.

I am not quite a SQL query expert, so don't have an exact fix. Although if it is already joining wp_postmeta you could use the same variable name without having to add a `JOIN`.

@psealock is there an easy way to view what queries get generated for the analytics report? I tried the query monitor plugin, but it didn't display the analytics queries.

**Comment by kcfgl** [comment] 2021-03-15 19:54
Ah... I see @louwie17. Thanks for the new info. Seems like maybe this is kind of similar to this issue https://github.com/woocommerce/woocommerce-admin/issues/6499 

Knowing most likely what is happening, maybe @psealock will have a more specific direction to go in and might crack the case on this one. We likely will add more custom filter options, so even if I could remove the last Join, I might not be able to do that every time (but who knows, maybe iIcan!)

Thanks again for taking a look. Maybe we're close here.

**Comment by psealock** [comment] 2021-03-17 01:24
It looks like figuring out what the constructed SQL statement comes out to will help here.

After this line you can `error_log( $this->subquery->get_query_statement() )` to see the final SQL statement made by the API's data store. 

https://github.com/woocommerce/woocommerce-admin/blob/b17aab156d9fb6e8fbc2ce59ba34d82fd20d9f5f/src/API/Reports/Orders/DataStore.php#L254

And after this line, you can `error_log( $this->total_query->get_query_statement() )` to see the full stats query constructed. 

https://github.com/woocommerce/woocommerce-admin/blob/b17aab156d9fb6e8fbc2ce59ba34d82fd20d9f5f/src/API/Reports/Orders/Stats/DataStore.php#L329

Remember to `wp cache flush` between calls to avoid caching issues. Maybe you can start with the original query and iteratively add parts until you reach the query you'd like?

>@psealock is there an easy way to view what queries get generated for the analytics report?

Just the manual one I went through above, but some kind of tooling in this space would be helpful

**Comment by mattsherman** [comment] 2021-03-23 16:51
@kcfgl Hi there! I'm just going through open issues to make sure that they are up-to-date... did you end up resolving this issue, or is there anything we can do to further assist you?

**Comment by kcfgl** [comment] 2021-03-24 16:41
thanks for checking in @mattsherman! Can't say this is 100% wrapped up, I'm still struggling a bit with this trying to unpack where things are breaking down. I wouldn't close the ticket just yet, I might be coming back soon with some specifics and a question. But thank you guys so much so far for the feedback and support.

**Comment by mattsherman** [comment] 2021-03-24 18:26
@kcfgl Sounds good. I'll leave this open for now.

**Comment by kcfgl** [comment] 2021-05-11 20:51
Hey @psealock and @louwie17 Just a quick update on this. The JOIN statement definitely seems to be the problem, but removing it kills the report altogether. I actually hired another developer to help solve this and he came to the same conclusion. Any additional thoughts on how to get around that? It seems to happen for any custom meta we would want to add. 

Also, sorry for my newbieness here, but I can't seem to figure out where I'd call wp cache flush. Is this just something I'll call between testing new pieces of code or is this something that would be called any time the reports need to change? Thanks again!

**Comment by kcfgl** [comment] 2021-06-07 10:58
Thanks @becdetat! Making progress here, everyone. Please don't close this out because I'd like to report back once this is 100%, in case it is useful for others. But we're getting close thanks to everyone's support and suggestions.

**Comment by kcfgl** [comment] 2021-06-09 23:22
Had a breakthrough on this (I think). I believe my issue was more to do with incorrectly checking the _GETs. Lets see if this makes sense.

```

function add_join_subquery( $clauses ) {
      global $wpdb;
  
		  if ( isset( $_GET['orderrole'] ) ) {
          $clauses[] = "JOIN {$wpdb->postmeta} order_user_role_postmeta ON {$wpdb->prefix}wc_order_stats.order_id = 
    order_user_role_postmeta.post_id";
      }
  
		  if( isset( $_GET['Shipped_between'] ) ){
			  // Seems we have to add this and it is now OK if we do (apparently - but we still have to check if invalidating 
 report cache every page load is a problem)
			  $clauses[] = "JOIN {$wpdb->postmeta} order_was_shipped_postmeta ON {$wpdb- 
 >prefix}wc_order_stats.order_id = order_was_shipped_postmeta.post_id";
		  }
		  
      return $clauses;
   }
  
   add_filter( 'woocommerce_analytics_clauses_join_orders_subquery', 'add_join_subquery' );
    add_filter( 'woocommerce_analytics_clauses_join_orders_stats_total', 'add_join_subquery' );
    add_filter( 'woocommerce_analytics_clauses_join_orders_stats_interval', 'add_join_subquery' );
  
  
  function add_where_subquery( $clauses ) {
      $role = 'all';
		  $shipped_date_from = '2019-01-01';
		  $shipped_date_to = date('Y-m-d');
  
		  //  Has to allow for ALL selection
  
      if ( isset( $_GET['orderrole'] ) ) {
          $role = sanitize_text_field( wp_unslash( $_GET['orderrole'] ) );
				  $clauses[] = "AND order_user_role_postmeta.meta_key = '_order_user_role' AND 
 order_user_role_postmeta.meta_value = '{$role}'";
      }
  
		  // Shipped Date Where
		  // Get the From Date
		  if ( isset( $_GET['Shipped_between'] ) ) {
			  $shipped_between =  $_GET['Shipped_between'];
			  $shipped_date_from = $shipped_between[0];
		  }
		  // Get the To Date
		  if ( isset( $_GET['Shipped_between'] ) ) {
			  $shipped_between =  $_GET['Shipped_between'];
			  $shipped_date_to = $shipped_between[1];
		  } else {
				  $shipped_date_to = date("Y-m-d");
		  }
  
		  if( isset( $_GET['Shipped_between'] ) ){
			  // Add the shipped date lause
			  //$clauses[] = "AND order_was_shipped_postmeta.meta_key = '_order_was_shipped' AND 
 order_was_shipped_postmeta.meta_value BETWEEN {$shipped_date_from} AND {$shipped_date_to}";
			  $clauses[] = "AND order_was_shipped_postmeta.meta_key = '_order_was_shipped' AND 
 order_was_shipped_postmeta.meta_value BETWEEN '{$shipped_date_from}' AND '{$shipped_date_to}'";
  
		  }
  
      return $clauses;
  }

```

I first check if the Shipped_between param is present.  But then if it is, I need to get the value of the array. Instead of checking if(isset($_GET['Shipped_between[01]'].

The massive duplication only occurs if I attempt to JOIN without actually having data to use in the JOIN or in the WHERE query. So before, the JOIN clause was being added but my WHERE wasn't populating anything. If everything is present, the numbers are spot on. 

The issue I am facing now is that the Advanced Filters are persisting. So if I have a filter on User Role and an Advanced Filter on Shipped Date ... and then I change the filter on User Role, the shipped date values drop from the query string and I lose the filtering and have to reapply it. I don't see in the example how I would persist an advanced query, any ideas? 

Other than that... I think we're rocking on this now!

**Comment by psealock** [comment] 2021-06-09 23:54
>The issue I am facing now is that the Advanced Filters are persisting. So if I have a filter on User Role and an Advanced Filter on Shipped Date ... and then I change the filter on User Role, the shipped date values drop from the query string and I lose the filtering and have to reapply it. I don't see in the example how I would persist an advanced query, any ideas?

I can reproduce this. The issue is because Filters don't respect Advanced Filters' queries and vice versa. Original designs don't include both so it wasn't taken into account. With extensibility, this is a valid scenario. I'll take a look and see if there is a solution

**Comment by kcfgl** [comment] 2021-06-10 00:02
@psealock Thank you for the quick feedback and confirmation. I'll move onto getting these filters working on other reports. And if you find a solution, that would be excellent.  Thanks again!

**Comment by kcfgl** [comment] 2021-06-10 00:25
@psealock If I try to add the filter to any other report I end up with an error 

```
react-dom.min.js?ver=16.13.1:125 TypeError: Cannot read property 'settings' of undefined
    at r.value (analytics-report-taxes.min.js?ver=2.2.1:1)
    at Ie (react-dom.min.js?ver=16.13.1:104)
    at rh (react-dom.min.js?ver=16.13.1:103)
    at zj (react-dom.min.js?ver=16.13.1:228)
    at Th (react-dom.min.js?ver=16.13.1:152)
    at tj (react-dom.min.js?ver=16.13.1:152)
    at Te (react-dom.min.js?ver=16.13.1:146)
    at react-dom.min.js?ver=16.13.1:61
    at unstable_runWithPriority (react.min.js?ver=16.13.1:25)
    at Da (react-dom.min.js?ver=16.13.1:60)
```

In this case I attempted to add a User Role filter to the Taxes report. In the same way as Orders. Looks like this: 

```
addFilter(
    'woocommerce_admin_orders_report_filters',
    'lab-reporting-extension',
    addRoleFilters
);

addFilter(
	'woocommerce_admin_taxes_report_filters',
  'lab-reporting-extension',
  addRoleFilters
);
```

Orders Report still works fine. But Products and Taxes error out. It is the same basic error if I try to add the Advanced Filter, too. 

Is there anything I need to do differently that might not be in the documentation? 

Thanks!

**Comment by psealock** [comment] 2021-06-10 00:38
@kcfgl Here is the fix to the Filters issue replacing values in the Advanced Filters. Good catch.

https://github.com/woocommerce/woocommerce-admin/pull/7155

>Orders Report still works fine. But Products and Taxes error out. It is the same basic error if I try to add the Advanced Filter, too.

Can you paste your `addRoleFilters` code?

**Comment by kcfgl** [comment] 2021-06-10 00:57
@psealock Excellent, I'll give the fix a test here in just a few minutes. 

And here is the addRoleFilters code:

```
const addRoleFilters = ( filters ) => {
    return [
        {
            label: __( 'User Role', 'lab-reporting-extension' ),
            staticParams: [],
            param: 'orderrole',
            showFilters: () => true,
            defaultValue: 'all',
            filters: [ ...( wcSettings.orderUserRole || [] ) ],
        },
        ...filters,
    ];
};
```

Feeling very optimistic I've almost got this now so thank you very much for the support!

**Comment by psealock** [comment] 2021-06-10 00:59
Thanks, and how is `wcSettings.orderUserRole` populated? I'm wondering if its only available on the Orders Report.

Otherwise, you may need to use the development version of WC Admin to get a better error message

**Comment by kcfgl** [comment] 2021-06-10 01:13
Here is the entire .js file. I was having issues with the advanced filters, too, but figured I would solve the Filters part first since the documentation covers that in depth. Might be the same issue though.
```

import { addFilter } from '@wordpress/hooks';
import { __ } from '@wordpress/i18n';



const addRoleFilters = ( filters ) => {
    return [
        {
            label: __( 'User Role', 'lab-reporting-extension' ),
            staticParams: [],
            param: 'orderrole',
            showFilters: () => true,
            defaultValue: 'all',
            filters: [ ...( wcSettings.orderUserRole || [] ) ],
        },
        ...filters,
    ];
};

addFilter(
    'woocommerce_admin_orders_report_filters',
    'lab-reporting-extension',
    addRoleFilters
);

addFilter(
	'woocommerce_admin_taxes_report_filters',
  'lab-reporting-extension',
  addRoleFilters
);


// Add Shipped Date Filter
const addShippedDateAdvancedFilter = (advancedFilters) => {
    advancedFilters.filters['Shipped'] = {
        labels: {
            add   : __('Shipped Date', 'woocommerce-admin'),
            remove: __(
                'Remove Shipped Date filter',
                'woocommerce-admin'
            ),
            rule  : __(
                'Select Shipped Date',
                'woocommerce-admin'
            ),
            title : __(
                '{{title}}Shipped Date{{/title}} {{rule /}} {{filter /}}',
                'woocommerce-admin'
            ),
            filter: __('Select Shipped Date', 'woocommerce-admin'),
        },
					rules: [
			{
				value: 'between',
				label: __( 'Between', 'woocommerce-admin' ),
			},
		],
		input: {
			component: 'Date',
		},
    };

return advancedFilters;
};
addFilter(
'woocommerce_admin_orders_report_advanced_filters',
'lab-reporting-extension',
addShippedDateAdvancedFilter
);



const addTableColumn = reportTableData => {
    if ( 'orders' !== reportTableData.endpoint ) {
        return reportTableData;
    }

    const newHeaders = [
        {
            label: 'User Role',
            key: 'role',
        },
        ...reportTableData.headers,
    ];
    const newRows = reportTableData.rows.map( ( row, index ) => {
        const item = reportTableData.items.data[ index ];
        const newRow = [
            {
                display: item.role,
                value: item.role,
            },
            ...row,
        ];
        return newRow;
    } );

    reportTableData.headers = newHeaders;
    reportTableData.rows = newRows;

    return reportTableData;
};

addFilter( 'woocommerce_admin_report_table', 'lab-reporting-extension', addTableColumn );


```

And here is some PHP code referencing the orderUserRole (only other spot I think I reference that variable. 
```

/*******
/* Add new filters
********/

function add_userrole_settings() {
    $roles = array(
			array(
					'label' => __( 'All', 'lab-reporting-extension' ),
					'value' => 'all',
			),
        array(
            'label' => __( 'Customer', 'lab-reporting-extension' ),
            'value' => 'customer',
        ),
        array(
            'label' => __( 'Retailer Level 1', 'lab-reporting-extension' ),
            'value' => 'retailer',
        ),
        array(
            'label' => __( 'Retailer Level 2', 'lab-reporting-extension' ),
            'value' => 'retailerlevel2',
        ),
    );

    $data_registry = Automattic\WooCommerce\Blocks\Package::container()->get(
        Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry::class
    );

    $data_registry->add( 'orderUserRole', $roles );
}

add_action( 'init', 'add_userrole_settings' );
```

**Comment by kcfgl** [comment] 2021-06-10 01:51
@psealock I'm not sure if this helps, but on the Taxes report even though it is erroring out with `TypeError: Cannot read property 'settings' of undefined`

If I look in the console with wcSettings.orderUserRole I get:
```
wcSettings.orderUserRole
(4) [{…}, {…}, {…}, {…}]
0: {label: "All", value: "all"}
1: {label: "Customer", value: "customer"}
2: {label: "Retailer Level 1", value: "retailer"}
3: {label: "Retailer Level 2", value: "retailerlevel2"}
length: 4
__proto__: Array(0)
```

**Comment by psealock** [comment] 2021-06-10 04:41
Using your code snippets, I get all the elements to display without error. What version WC Admin do you have? 

<img width="877" alt="Screen Shot 2021-06-10 at 4 40 09 PM" src="https://user-images.githubusercontent.com/1922453/121465925-a0220580-ca0a-11eb-8298-ac617061658a.png">


<img width="1013" alt="Screen Shot 2021-06-10 at 4 37 52 PM" src="https://user-images.githubusercontent.com/1922453/121465918-9d271500-ca0a-11eb-904a-63be961450be.png">

**Comment by kcfgl** [comment] 2021-06-10 15:27
@psealock Well thats odd. But in a good way, since it works for you. 

I'm on:
Woocommerce 5.4.1
Woo-Admin 2.3.1
Woo Blocks 5.3.0

But still getting these errors and warnings (the deprecation one is interesting):
```
admin.php?page=wc-admin&path=%2Fanalytics%2Ftaxes:2246 `woocommerce_shared_settings` filter in Blocks is deprecated. See https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/contributors/block-assets.md
(anonymous) @ admin.php?page=wc-admin&path=%2Fanalytics%2Ftaxes:2246

react-dom.min.js?ver=16.13.1:125 TypeError: Cannot read property 'settings' of undefined
```

Maybe a cache thing? I'll try to ensure its all cleared out. 

Thanks!

**Comment by kcfgl** [comment] 2021-06-10 17:29
Quik update and some success @psealock  ... if I use 2.4.0-beta.1 then the error is gone. I can also get the main User Role filter to load. But if I attempt to add an Advanced Filter, I am back to the same error. 

Adding this code:
```
addFilter(
'woocommerce_admin_orders_report_advanced_filters',
'lab-reporting-extension',
addShippedDateAdvancedFilter
);
```
Will result in this error:
```
TypeError: Cannot set property 'Shipped' of undefined
    at addShippedDateAdvancedFilter (index.js?ver=a59b3a55c81aca487a4e0554ad5090a0:26)
    at hooks.min.js?ver=50e23bed88bcb9e6e14023e9961698c1:2
    at Object.588 (analytics-report-taxes.js?ver=2.4.0-beta.1:1)
    at a (index.js?ver=2.4.0-beta.1:1)
    at Module.546 (analytics-report-taxes.js?ver=2.4.0-beta.1:1)
    at a (index.js?ver=2.4.0-beta.1:1)
```

And here is the addShippedDateAdvancedFilter code:
```

// Add Shipped Date Filter
const addShippedDateAdvancedFilter = (advancedFilters) => {
    advancedFilters.filters['Shipped'] = {
        labels: {
            add   : __('Shipped Date', 'woocommerce-admin'),
            remove: __(
                'Remove Shipped Date filter',
                'woocommerce-admin'
            ),
            rule  : __(
                'Select Shipped Date',
                'woocommerce-admin'
            ),
            title : __(
                '{{title}}Shipped Date{{/title}} {{rule /}} {{filter /}}',
                'woocommerce-admin'
            ),
            filter: __('Select Shipped Date', 'woocommerce-admin'),
        },
					rules: [
			{
				value: 'between',
				label: __( 'Between', 'woocommerce-admin' ),
			},
		],
		input: {
			component: 'Date',
		},
    };

return advancedFilters;
};
```

**Comment by kcfgl** [comment] 2021-06-14 21:46
@psealock Looks like Orders is the only report I can currently use both filters and advanced filters. Which isn’t great, but not terrible either, since a lot of the core metrics are displayed on the orders report anyway. 

But I would love to know if there is an underlying reason for other reports to not allow both types of filters. If there is anything less I can provide error-wise to help let me know. Thanks!

**Comment by psealock** [comment] 2021-06-15 04:30
>But I would love to know if there is an underlying reason for other reports to not allow both types of filters

Looks like another oversight on our part due to not extending our own reports. Thanks for bringing this up.

I got your code to work for Taxes in this Pull Request https://github.com/woocommerce/woocommerce-admin/pull/7186, which is a work in progress.

I made a better default so attempting to modify `advancedFilters.filters` works. It fails because `filters` is undefined. And I checked to see if any advanced filters are added and if so, added a regular filter for advanced filters. All of this can be done through the current filters by examining whats already there, but that feels like way too much onus on the extension developer.

I'll clean up that PR tomorrow and apply the same logic to other reports that don't have Advanced Filters

**Comment by kcfgl** [comment] 2021-06-15 21:11
Excellent @psealock thanks for all the effort you’re putting in here and for the continual updates!

**Comment by psealock** [comment] 2021-06-16 04:02
No problem, glad to see these filters getting extended! Here is the fix https://github.com/woocommerce/woocommerce-admin/pull/7186

**Comment by kcfgl** [comment] 2021-06-17 20:58
@psealock thanks for the fix! I'll be getting it integrated tonight and we should be good! I appreciate the support. The new Analytics suite is lightyears beyond the previous Reporting, so I'm very excited to get our clients squared away and using all the reports.

**Comment by kcfgl** [comment] 2021-06-26 12:42
@psealock We're almost there I think. But now I cannot add custom meta as columns in the reports because the data is not in reportTableData returned by the rest response (I assume). I saw a previous question on this but there was not a resolution. https://github.com/woocommerce/woocommerce-admin/issues/5730 

Any thoughts? Thanks!

**Comment by kcfgl** [comment] 2021-06-30 00:48
@psealock After getting some support in #5730, I'm almost to a solution.  Since there is so much info in here I am going to repost the detail I posted in 5730 (don't hate me). Do you have any thoughts here?

The whole problem (to getting the custom meta to be included in the reportTableData) seems to be right here in the Select. I cannot just add in the custom meta select clauses. If I try to add them, when the filters are not set, then the order report doesn't work. Not the summary data or the individual order rows. If I try to add the custom meta to the report using woocommerce_rest_prepare_report_orders, then I get a 500 error.

But if I have my filters setting the Order Role, or the Shipped Between (or both), and I only add the new Select clauses if they are being filtered, _the data is available and is in the reportTableData and I can add it as a column_.

```
function add_select_subquery( $clauses ) {
	 if ( isset( $_GET['orderrole'] ) ) {
    	     $clauses[] = ', order_user_role_postmeta.meta_value AS role';
		}

	if( isset( $_GET['Shipped_between'] ) ){
	     $clauses[] = ', order_was_shipped_postmeta.meta_value AS order_was_shipped';
		}
    return $clauses;
}
```

Any idea how I should be setting these clauses up so that I can select the custom meta even if I'm not filtering? Thank you as always.  Really close to a nicely extended report suite!

**Comment by kcfgl** [comment] 2021-06-30 15:20
@psealock All set on this. I'm switching up and using `woocommerce_rest_prepare_report_orders`

The only thing left is how to get these new custom columns to show up in the Downloaded reports.  Do you have documentation on where I can add those columns, too? Thanks!

**Comment by kcfgl** [comment] 2021-07-02 00:30
I've got a fix for adding custom meta to the reports. It was all in woocommerce_report_orders_export_columns.  It was the easiest option instead of messing with Selects, since we have had issues there. 

Once #7186 is in, I think we're good! Lots of power in these reports.  Last question I have is whether we can add additional Stats to the top of the reports. Like Gross Sales instead of just Net Sales. Thanks @psealock for the tremendous support on this, truly.

**Comment by psealock** [comment] 2021-07-02 01:38
Great to hear @kcfgl, looking forward to seeing the finished product. And thanks to. @joshuatf for stepping in here as well.

>Last question I have is whether we can add additional Stats to the top of the reports.

That is still a work in progress. The filter is available on the client, but the underlying query need to be filtered in order to make it work. See https://github.com/woocommerce/woocommerce-admin/issues/2110

**Comment by kcfgl** [comment] 2021-07-02 02:08
Very excited to hear this has been re-opened @psealock. You've got at least one end user who will integrate custom summary numbers the moment the first build is out!

**Closed** 2021-07-13 22:17 UTC
Labels: needs feedback
