### ISSUE TITLE
Hidden WordPress notices

### ISSUE THREAD

**Issue by dyszczo** [woocommerce/woocommerce-admin#3822] opened 2020-03-04 10:53 UTC
**Describe the bug**

I'm using WP `admin_notices` notices and now, after an upgrade to WC 4.0, they have stopped showing up anywhere in the WooCommerce admin (including the products list and the product page in admin).
The effect is that every plugin using the admin_notices to communicate with the users is now forcibly silenced.

Example: 
1. Let's say the plugin adds some functionality to the WooCommerce but you have to enter some API credentials to use it properly.
2. Info about the missing credentials normally would be accessible to a user trough the visible notice.
3. A user thinks everything is fine as s/he does not see any problems. Trying to use the functionality causes errors and even some of them are not shown as normally it would be, again, shown as a notice.

**To Reproduce**

1. Add a simple notice using https://developer.wordpress.org/reference/hooks/admin_notices/ code.
2. Go to any WooCommerce linked page.
3.  A notice is not visible and the message is lost forever for the user.

**Expected behavior**

Notices should be visible or at least the message provided by the notice is somehow readable to the user in the admin panel.

* Device: All.

**Additional context**

It breaks communication extension→user in the entire admin panel. 
I see that https://github.com/woocommerce/woocommerce-admin/issues/35 exists but "Handle Admin Notices" should not be "Hide Others Admin Notices".

**Comment by rrennick** [comment] 2020-03-04 13:06
@dyszczo Thank you for the feedback. This is by design. If there are notices, the header panel has a WordPress logo icon. Clicking the icon toggles the visibility of the notices. 

WordPress core is also working on the [notification system]9https://make.wordpress.org/core/2020/02/28/wp-notify-weekly-meeting-agenda-for-monday-2-march-2020/).

**Comment by dyszczo** [comment] 2020-03-04 13:34
@rrennick Thank you for the response. I'm aware that the current admin_notices routine needs a major refactor but the problem with the new design is that users do not know about the new WordPress logo icon. They only know that the plugin is broken and there is no notice to help them figure it out.

The lack of such a notice was a high priority bug in WC core https://github.com/woocommerce/woocommerce/issues/25646. As a plugin developer, I cannot decide when a user upgrades, like WC core can. As a result, I have multiple high priority bugs like that in about 30 of my plugins.

**Comment by potreb** [comment] 2020-03-04 14:02
Why do you hide WordPress core functionality? Also you may remove some filters or actions.

**Comment by rrennick** [comment] 2020-03-04 15:21
@dyszczo We appreciate that users are not initially familiar with the interface.

> The lack of such a notice was a high priority bug in WC core woocommerce/woocommerce#25646.

WC Admin does provide a way to have a notice left visible. We have written an example here: https://github.com/woocommerce/woocommerce-admin/tree/master/docs/examples/extensions/important-admin-notice

> Also you may remove some filters or actions.

@potreb Can you clarify what you are referring to?

**Comment by dyszczo** [comment] 2020-03-04 15:54
> WC Admin does provide a way to have a notice left visible.

I think it would be best to give users a few months to get used to a new functionality and after the introduction hide it by default. Otherwise, I expect hacks like `#wp__notice-list { display: block !important; } ` pretty quickly.

**Comment by psealock** [comment] 2020-03-09 01:48
Fixed by #3827

**Closed by psealock** 2020-03-09 01:48 UTC
Labels: [Type] Enhancement
