### ISSUE TITLE
Broken customers link from leaderboard

### ISSUE THREAD

**Issue by KarlisJ** [woocommerce/woocommerce-admin#8144] opened 2022-01-11 14:00 UTC
### Describe the bug
The link to customer in "Top Customers - Total Spend" leaderboard in Analytics->Overview page is broken and leads to an empty customers table being loaded.

### To Reproduce

1. Make at least one purchase
2. Go to 'Analytics -> Overview'
3. Scroll down to 'Leaderboards' and select 'Top Customers - Total Spend' leaderboard to be displayed
4. Click on any of the customers in the leaderboard
5. Notice that there's no table loaded

### Actual behavior:
The [generated link](https://github.com/Automattic/woocommerce-admin/blob/b30d2eaf39527d322fff844e294e265ae1fa2ca4/src/API/Leaderboards.php#L239) sets the path to be `/analytics/customers` but it should be just `/customers`. 

### Expected behavior
After clicking on the link we should be redirected to 'WooCommerce -> Customers' page and see a single customer selected.

**Comment by moon0326** [comment] 2022-01-11 17:51
Thank you for taking the time to report the bug @KarlisJ 

Unfortunately, I wasn't able to reproduce it with WC 6.0.

Could you see the screencast below and see if I missed any steps?

![Screen Capture on 2022-01-11 at 09-50-07 (1)](https://user-images.githubusercontent.com/4723145/148995319-5d2a78b3-3aec-4006-91ca-4466391bf222.gif)

**Comment by mattsherman** [comment] 2022-01-23 13:02
> The generated link sets the path to be /analytics/customers but it should be just /customers.

This is the correct path.

As with @moon0326, I too cannot reproduce this with WooCommerce 6.1.1.

@KarlisJ Can you please provide us with more details on your setup (WooCommerce version, WooCommerce Admin version -- you can view these at `/wp-admin/admin.php?page=wc-status`)?

**Comment by KarlisJ** [comment] 2022-01-24 08:23
After updating to the latest WC version I see that both `/analytics/customers` and `/customers` paths are handled the same and the issue is no longer there. 

The version I had when recording this issue was 5.8.x

**Comment by moon0326** [comment] 2022-01-26 00:26
@KarlisJ Thank you for reporting it back. I'm glad it's fixed in the latest version.

I'm closing this issue for now, but please feel free to re-open it if needed.

**Closed by moon0326** 2022-01-26 00:26 UTC
Labels: needs feedback
