### ISSUE TITLE
Onboarding - Task List: Implement Tracks

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#2483] opened 2019-06-21 09:01 UTC
We will want to add tracks for users who opted in on the first screen or have `woocommerce_allow_tracking` set to `yes`.

The list of events can be found via p1560449057014200-slack-wc-onboarding

<img width="542" alt="Screen Shot 2019-06-21 at 5 00 09 PM" src="https://user-images.githubusercontent.com/10561050/59911254-0be9bd00-9446-11e9-95f4-67f4c67e6b64.png">

**Comment by pmcpinto** [comment] 2019-09-26 13:37
@joshuatf we need to change the way we display the usage tracking auth message. See this [issue](https://github.com/woocommerce/woocommerce-admin/issues/2965)

**Comment by justinshreve** [comment] 2019-10-01 19:27
Closing this as a duplicate of https://github.com/woocommerce/woocommerce-admin/issues/2671

(the usage tracking is also updated in a separate issue)

**Closed by justinshreve** 2019-10-01 19:27 UTC
Labels: Onboarding, [estimate] 2
