### ISSUE TITLE
database update done persists

### ISSUE THREAD

**Issue by 7thcirclegit** [woocommerce/woocommerce-admin#4114] opened 2020-04-09 20:16 UTC
After updating to 4.0.1 and updating the db, the notice... WooCommerce database update done
reappears after clicking thanks

**Comment by timmyc** [comment] 2020-04-10 21:11
Hello @7thcirclegit and @ben72 - apologies for you all hitting this bug. We have a fix in progress for this, but I'm going to close this issue in favor of the original report woocommerce/woocommerce-admin#3497 

If you would like, I've also created a quick plugin that will set the DB notice as "actioned" and remove it from your Woo pages.

The plugin can be found here: https://gist.github.com/timmyc/ee0c6f4cb3ed82620efaa16386e62c6b

You could copy that into any other plugin/functions file as well, but once it has run one time, you can disable/remove the code.

**Closed by timmyc** 2020-04-10 21:11 UTC

**Comment by ben72** [comment] 2020-04-11 06:39
Thanks @timmyc! This works on all sites it was needed on. Some of the sites had cured themselves. Do you know why this happened on just some sites?

**Comment by timmyc** [comment] 2020-04-17 18:18
@ben72 glad it worked out for you. If someone clicks on the action button in the notice within 24 hours of it being created - then all is fine as the nonce value that was stored in the action is still valid. The bug only happens when the db update happens, the notice is created, and nobody clicks the button within that first 24 hours.

**Comment by 7thcirclegit** [comment] 2020-04-17 18:44
That is incorrect. The db update can be performed immediately after woocommerce update, and then clicking on "thanks" and it still fails.

**Comment by ben72** [comment] 2020-04-17 18:54
@timmyc Yes, it's like @7thcirclegit says. I clicked update and then the button to close the finished notice just a little while later and it took me to a page that didn't exist. And the notice would not go away.

**Comment by 7thcirclegit** [comment] 2020-04-17 18:57
I never got an error, the message just stayed or reappeared. I ended up fixing this by editing the db manually

the easiest fix is… In the xxx_wc_admin_notes table I updated wc-update-db-reminder from unactioned to actioned

**Comment by ben72** [comment] 2020-08-26 16:21
This happened on a few sites even with the latest update.

**Comment by timmyc** [comment] 2020-08-27 22:20
@ben72 indeed if the notice action is not clicked on within the nonce expiry time limit, the bug persists. The team over in `woocommerce/woocommerce` is aware and looking into it. Deleting the notice from the db, or using the fixer plugin above should remedy

**Comment by bozzmedia** [comment] 2020-10-07 21:04
I can confirm that this remains an issue on 4.5.2

**Comment by eazylaykzy** [comment] 2020-11-27 09:44
> I never got an error, the message just stayed or reappeared. I ended up fixing this by editing the db manually
> 
> the easiest fix is… In the xxx_wc_admin_notes table I updated wc-update-db-reminder from unactioned to actioned

This remains an issue on Version 4.7.1, it persisted no matter how many times I click the "Thanks!" button.
Thanks to @7thcirclegit tweak to the DB, this actually fixed mine.

**Comment by sandstones** [comment] 2021-01-18 18:12
Still a problem in version 4.9 January 2021

And the comment about 
     the easiest fix is… In the xxx_wc_admin_notes table I updated wc-update-db-reminder from unactioned to actioned
does not help either.

The table entry shows 'actioned' but the alert persists.

**Comment by richsadams** [comment] 2021-02-11 22:11
Still a problem with version 5.0 February 11, 2021

**Comment by samueljseay** [comment] 2021-02-11 23:56
Just adding some info for those watching this, it looks like this is addressed in WooCommerce here: https://github.com/woocommerce/woocommerce/pull/28500

This fix is slated for the 5.1.0 release due in March.

**Comment by Hund** [comment] 2021-06-16 09:36
This is still an issue for me with 5.4.1.

**Comment by Hund** [comment] 2021-06-16 09:49
This is still an issue for me with 5.4.1.

**Comment by JakeQZ** [comment] 2021-08-21 02:03
This is not fixed with 5.6.0.

**Comment by richsadams** [comment] 2021-08-21 03:20
> This is not fixed with 5.6.0.

It is not. I had to go into the database to correct it from "unactioned" to "actioned"... again.

**Comment by JakeQZ** [comment] 2021-08-21 03:25
> 
> 
> > This is not fixed with 5.6.0.
> 
> It is not. I had to go into the database to correct it from "unactioned" to "actioned"... again.

I just ignore it.  But it is a PITA.

**Comment by sparky672** [comment] 2021-09-16 20:52
Seriously!?  Version 5.8.1 and you still cannot figure this out?  Like stated above my post, not a big confidence boost when the simple things can't be figured out after more than a year.  Good grief... and I am a PAYING customer of WC products.

Yes, I have the issue yet again and yet again need to manually edit the database table... WTF

**Comment by JakeQZ** [comment] 2021-09-16 20:56
See woocommerce/woocommerce#32241 this is the current open issue for this.
