### ISSUE TITLE
Zero value items in report listing

### ISSUE THREAD

**Issue by gravnetic** [woocommerce/woocommerce-admin#2614] opened 2019-07-09 03:40 UTC
There are several orders with no value listed in the reports for the new Analytics which are now shown in the existing reports.  This is because these products have zero value composite / bundles. 
![Year-To-Date_Composite-Products-which-have-zero-added-value](https://user-images.githubusercontent.com/475331/60857756-f1933b80-a1c8-11e9-907a-5c4895c9a949.jpg)

**Comment by psealock** [comment] 2019-07-09 20:29
Thanks for bringing this up @gravnetic.

I believe zero filling of endpoints was done for the benefit of comparing and searching for specific items in other reports. https://github.com/woocommerce/woocommerce-admin/pull/1722, for example. The Revenue Report doesn’t seem to require these values though.

cc @LevinMedia to double check, but I agree we should remove these.

**Comment by LevinMedia** [comment] 2019-07-10 04:05
>There are several **orders** with no value listed in the reports for the new Analytics which are now shown in the existing reports. This is because these products have zero value composite / bundles.

@gravnetic did you mean **Days** rather than **Orders**? Just wanna make sure I'm understanding 100% 

Based on what I'm seeing in that screen shot, the day's you've indicated with the arrows saw zero new orders, is that not actually the case? Sounds like maybe it's not, because you mentioned composite products and bundles. 

@psealock when we weren't zero filling results, we were getting undesirable behaviors in the charts (IE it wasn't flat lining on intervals with zeros. for example, if you were looking at a week of data, and Monday had 10 of something, and Friday had four of something, but Tuesday and Wednesday were all at 10, down to Friday at 4 for example, with no points in between) 

![IMG_7698](https://user-images.githubusercontent.com/4500952/60939548-f5889180-a28c-11e9-82ce-a90a8d96f0f5.jpeg)

**Comment by timmyc** [comment] 2019-07-10 18:30
Related, perhaps duplicate of #1997

**Comment by psealock** [comment] 2019-07-11 02:54
Thanks for the clarification @LevinMedia, that makes a lot of sense.

The solution appears to be to remove zero value **days** from the table, but not the api response or chart.

**Comment by timmyc** [comment] 2019-12-05 20:32
@psealock since we've only had one report of this as an undesirable experience ( the zero values in the table ) I'm thinking we close this out or move it to the icebox. Thoughts?

**Comment by rrennick** [comment] 2019-12-05 20:54
> Thoughts?

I did some initial looking at this & it would be a fairly involved project because we need to keep the current API results for the chart. That means creating a second data path with the zero rows removed so that the number of rows in the result matches the table `per_page` setting. Filtering out the zero rows on the front end for example would have it say 25 rows and only showing 19 days.

**Comment by timmyc** [comment] 2019-12-05 21:54
Thanks for the comment Ron. I'm going to close this out.

**Closed by timmyc** 2019-12-05 21:54 UTC
Labels: Analytics, [Much] Small, [Priority] High, [Type] Enhancement, [estimate] 1
