### ISSUE TITLE
Implement experiment package in WC Admin and WC Payments

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6660] opened 2021-03-24 07:23 UTC
**Description:** one of the top priorities for cycle 11 is implementing an a/b testing package in the WC Admin and WC Payments plugins, as we're going to run experiments on both. Currently, there are two options: the ExPlat Calypso/JS Client released a couple of days ago (pbmo2S-HC-p2) and the work done with Raz (#6536). The goal is to assess which one is the best path forward and implement it on both plugins until the end of the cycle.

Below is a list of features that we'd like to have in the experiments package and during the assessment and implementation it would be good to confirm which ones are going to be available and if there's a possibility to implement them in the future:

**Targeting (Determine if a store is eligible for an experiment)**

- [ ] Can define a set of rules / conditions to determine if a store is eligible for an experiment
- [ ] Available dimensions for those rules:
- Location - store’s setting location (Country)
- Current plugin configuration
Is a plugin installed or not
Is the plugin active or not
What version of the plugin is installed
- Age of Store / GMV - to distinguish between new and established stores
- In an ideal world, we can target stores based on any data we collect about them or their admins via Tracks, WCTracker snapshots, etc.
- [ ] Stores associated with A8C employees / JN are automatically excluded from experiments
- [ ] Advanced: define subgroups to set up for [stratified random sampling](https://en.wikipedia.org/wiki/Stratified_sampling).

**Assignment (Determine what variant an eligible store will receive in an experiment)**

- [ ] Eligible stores (as determined by the targeting rules) are randomly assigned to an experiment variant (will only have a test and control variant to start with).
- Initially, simplified random sampling should work
- In the future, supporting stratified random sampling would be great.
- [ ] Once assigned to a variant, a user continues to receive the same variant through the duration of the experiment.
- If a store is assigned to a variant, all users that log into that store see the same experience
- If a user is assigned to a variant for one store, they see the same variant if they come across the same path in a different store
- [ ] If there is a problem assigning a target store for any reason, it receives the control variant
- [ ] We track how a store was assigned to a specific variant
- Normal assignment - randomly assigned
- Default assignment - fell back on default because of a problem
- User consistency - was assigned to ensure a user continues to receive the same experience
- [ ] Stores can be assigned to multiple experiments concurrently
- Stores are excluded from an experiment if they are already in another experiment affecting that part of the experience
- Assignment in an experiment is independent of assignment in another experiment (unless we explicitly identify that the experience in one experiment would affect the experience available in another experiment)

**Deployment (launch the experiment)**
- [ ] We can set a start date for an experiment and an end date (and/or a threshold of samples to reach at which point it turns off, i.e. after each variant is served to X stores, the experiment ends). 
- A rule for this would be something like “End the experiment on this date or after 7 days if it has reached this threshold of stores”
- [ ] We can ramp up deployment of the experiment, i.e. only start with 10% of the total target audience being eligible for assignment, until we are sure there aren’t any problems with the experiment in production.
- [ ] If we detect a problem in an experiment, it can be turned off in a reasonable amount of time (i.e. all stores continue to receive the default control experience until the issue is resolved).

**Instrumentation (measuring the experiment)**
- [ ] Any time a store is assigned to a variant, we have an event recording what variant it was assigned to and how it was assigned (normal assignment, default, user consistency).
- [ ] Any time a store is served a variant, we have an event recording what variant it was served. 
- Under an ideal scenario, a store would have only one assignment event but potentially multiple served variant events
- This is to help identify any stores that should be excluded from final analysis, to determine how the assignment mechanism is working, etc.
- [ ] We have an event indicating when a store enters an experiment funnel. If the assignment occurs when a store enters the experiment funnel, then the variant assignment event could work here.
- This helps us identify every store that was in the experiment for analysis.
- [ ]  Any events tied to an experiment have the experiment name / identifier included as a property.

| Criteria                                                                                                                           | ExPlat | WC Admin | Comments              |
| ---------------------------------------------------------------------------------------------------------------------------------- | ------ | -------- | --------------------- |
| Can define a set of rules / conditions to determine if a store is eligible for an experiment                                       | ✅     | ✅       |                       |
| Location                                                                                                                           | ✅     | ✅       |                       |
| Current plugin configuration                                                                                                       | ✅     | ✅       |                       |
| Age of Store                                                                                                                       | ✅     | ✅       | Using snapshot method |
| A8C employees / JN are automatically excluded from experiments                                                                     | ✅     | ❌       | Requires ETL pipeline |
| Advanced: define subgroups to set up for stratified random sampling.                                                               | ❌     | ❌       |                       |
| Eligible stores are randomly assigned to an experiment variant                                                                     | ✅     | ✅       |                       |
| Once assigned to a variant, a user continues to receive the same variant through the duration of the experiment                    | ✅     | ✅       |                       |
| If a store is assigned to a variant, all users that log into that store see the same experience                                    | ❌     | ✅       |                       |
| If a user is assigned to a variant for one store, they see the same variant if they come across the same path in a different store | ✅     | ❌       |                       |
| If there is a problem assigning a target store for any reason, it receives the control variant                                     | ✅     | ✅       |                       |
| We track how a store was assigned to a specific variant (Normal, default, or user consistency)                                     | ✅     | ✅       |                       |
| Stores can be assigned to multiple experiments concurrently                                                                        | ✅     | ✅       |                       |
| Stores are excluded from an experiment if they are already in another experiment affecting that part of the experience             | ❌     | ❌       |                       |
| Assignment in an experiment is independent of assignment in another experiment, unless explicitly identify correlated experiments  | ✅     | ✅       |                       |
| We can set a start date for an experiment and an end date                                                                          | ✅     | ✅       |                       |
| We can set threshold for stores for an experiment to end                                                                           | ❌     | ❌       |                       |
| We can ramp up deployment of the experiment, ie 10% to 50%                                                                         | ❌     | ❌       |                       |
| If we detect a problem in an experiment, it can be turned off in a reasonable amount of time                                       | ✅     | ❌       |                       |
| We have an event indicating when a store enters an experiment funnel                                                               | ✅     | ✅       |                       |
| Any events tied to an experiment have the experiment name / identifier included as a property                                      | ✅     | ✅       |                       |

**Comment by jessie-ross** [comment] 2021-03-25 08:28
A fundamental design choice in ExPlat is that we use Users as our "randomisation unit" as opposed to Stores - we perform assignments per user, we filter by user, we measure events and revenue by user. 

While we can filter out A8C-store-related events and revenue, assign experiments to store owners, decide whether to run an experiment on a store-by-store basis and possibly add a new metric type to support store needs, using a different randomisation unit such as Stores would require a backend and client overhaul.

Is it possible for you to use Users as your randomisation unit? What was the reasoning behind choosing to use Stores?

**Comment by psealock** [comment] 2021-03-25 09:53
Interesting distinction here. Some of the targeting rules can be achieved using data we already have access to on the client. Here is an example using pseudo code:

```js
if ( storeAge > oneYear && WCPayIsActive && locale === 'Netherlands' ) {
	return (
		<Experiment
			name="woocommerce_dutch_age_one_year_wcpay_experiment"
			defaultExperience={ Layout }
			treatmentExperience={ LayoutVariation }
			loadingExperience={ LayoutLoading }
		/>
	);
}
return <Layout />;
```

However, this part is a bit harder.

>In an ideal world, we can target stores based on any data we collect about them or their admins via Tracks, WCTracker snapshots, etc.

For instance, WCTracker has data on cumulative gross sales. How could we target stores with more than $10,000 cumulative gross sales with Users as a randomisation unit? I _think_ WC Tracker data includes `home_url` which could be used to associate a User and Store, but this is just me guessing 😄

**Comment by pmcpinto** [comment] 2021-03-25 11:00
> While we can filter out A8C-store-related events and revenue, assign experiments to store owners only, decide whether to run an experiment on a store-by-store basis and possibly add a new metric type to support store needs, using a different randomisation unit such as Stores would require a backend and client overhaul.

> Is it possible for you to use Users as your randomisation unit? What was the reasoning behind choosing to use Stores?

@jessie-ross thanks for your feedback. The main reason behind using stores was due to the fact that a store can have more than one admin, shop manager, etc. But given that limitation, I think that we can stick with using users. @oneillo in case you have more feedback on this and the checklist was mainly created by you 😄

**Comment by jessie-ross** [comment] 2021-03-25 11:33
> How could we target stores with more than $10,000 cumulative gross sales with Users as a randomisation unit? I think WC Tracker data includes home_url which could be used to associate a User and Store, but this is just me guessing.

You could for example get a snapshot at some point in time of all the stores with more than $10,000 cumulative gross sales and decorate all stores with some kind of `isStoreGroup1234` boolean metadata, then add that into your `if` statement.

**Comment by oneillo** [comment] 2021-03-25 14:41
Yeah. I was thinking of two reasons for store as the randomization unit: 

1. From a business perspective / reporting, we normally talk about stores not users - i.e. live stores, active stores, etc, [like in our Looker dashboards](https://looker.a8c.com/dashboards/99). That carries through to experiment design and target audiences - how do we get stores that aren't using WCShip to start using it, how can we get hit GMV stores to start using WCPay, etc. 

2. What @pmcpinto brought up - users having multiple stores and stores having multiple users. We have a Hue table that maps users to stores based on wcadmin events over the last 2 years (woocommerce_data.user_store_mapping), and from that data, it looks like 20% of users have multiple stores and 8% of stores have multiple users. 

@jessie-ross - I'm definitely open to alternatives. Like if we could target by store characteristics, execute the experiment by user, and then do some kind of reconciliation in the analysis.

 
<img width="749" alt="stores_with_multiple_users" src="https://user-images.githubusercontent.com/730723/112490933-0e74f700-8d3d-11eb-9f59-75469dc5be2c.png">
<img width="873" alt="users_with_multiple_stores" src="https://user-images.githubusercontent.com/730723/112490939-103eba80-8d3d-11eb-8d2d-52d811bbb8cb.png">

**Comment by oneillo** [comment] 2021-03-25 14:49
Regarding instrumentation, I was discussing this with @jonathan-marsan yesterday, and ignore the prescriptive nature of Tracks events. 

The main things I was hoping to get out of the instrumentation is:

- Knowing who is in the experiment
- Knowing what variant they are served
- Being able to detect the case where a person/store is served multiple variants for any reason

The original instrumentation specs were based on our homebrew variant assignment code, where I wanted to have more info to be able to validate the code was assigning RUs to variants appropriately and debug any problems if they came up.

**Comment by psealock** [comment] 2021-03-28 22:55
With the experimental work that has gone into https://github.com/woocommerce/woocommerce-admin/pull/6669 and https://github.com/woocommerce/woocommerce-admin/pull/6536 to form the basis for discussion and identification of pitfalls, I'm estimating this at 5 to choose tooling and fully work out the details.

**Comment by psealock** [comment] 2021-03-29 03:58
Here is a matrix to help things out. I'll be filing this out by editing the comment

| Criteria                                                                                                                           | ExPlat | WC Admin | Comments             |
| ---------------------------------------------------------------------------------------------------------------------------------- | ------ | -------- | -------------------- |
| Can define a set of rules / conditions to determine if a store is eligible for an experiment                                       | ✅     | ✅       |                      |
| Location                                                                                                                           | ✅     | ✅       |                      |
| Current plugin configuration                                                                                                       | ✅     | ✅       |                      |
| Age of Store                                                                                                                       | ❔     | ❔       |                      |
| A8C employees / JN are automatically excluded from experiments                                                                     | ✅     | ✅       | JN can't be excluded |
| Advanced: define subgroups to set up for stratified random sampling.                                                               | ✅     | ❌       |                      |
| Eligible stores are randomly assigned to an experiment variant                                                                     | ✅     | ✅       |                      |
| Once assigned to a variant, a user continues to receive the same variant through the duration of the experiment                    | ✅     | ✅       |                      |
| If a store is assigned to a variant, all users that log into that store see the same experience                                    | ❌     | ✅       |                      |
| If a user is assigned to a variant for one store, they see the same variant if they come across the same path in a different store | ✅     | ❌       |                      |
| If there is a problem assigning a target store for any reason, it receives the control variant                                     | ✅     | ✅       |                      |
| We track how a store was assigned to a specific variant (Normal, default, or user consistency)                                     | ✅     | ✅       |                      |
| Stores can be assigned to multiple experiments concurrently                                                                        | ✅     | ✅       |                      |
| Stores are excluded from an experiment if they are already in another experiment affecting that part of the experience             | ❔     | ❌       |                      |
| Assignment in an experiment is independent of assignment in another experiment, unless explicitly identify correlated experiments  | ❔     | ✅       |                      |
| We can set a start date for an experiment and an end date                                                                          | ✅     | ✅       |                      |
| We can set threshold for stores for an experiment to end                                                                           | ❔     | ❌       |                      |
| We can ramp up deployment of the experiment, ie 10% to 50%                                                                         | ❔     | ❌       |                      |
| If we detect a problem in an experiment, it can be turned off in a reasonable amount of time                                       | ✅     | ❌       |                      |
| We have an event indicating when a store enters an experiment funnel                                                               | ✅     | ✅       |                      |
| Any events tied to an experiment have the experiment name / identifier included as a property                                      | ✅     | ✅       |                      |

**Comment by jessie-ross** [comment] 2021-03-29 05:20
Sorry I didn't get round to this on Friday, here are some ExPlat clarifications:

> Age of Store

This should be possible with the snapshot method I mentioned above.

>  A8C employees / JN are automatically excluded from experiments

While A8C employees are filtered their stores currently wouldn't be. We have an ETL pipeline where we should be able to add additional filtering, @yanirs to confirm.

> Advanced: define subgroups to set up for stratified random sampling.

ExPlat doesn't do stratified random sampling as far as I known and I don't think we will. [Netflix found that at-assignment stratification wasn't worthwhile](https://dl.acm.org/doi/10.1145/2939672.2939733) and [there are some post-assignment stratification recommended in the literature which we might eventually utilise to improve sensitivity](https://www.researchgate.net/publication/237838291_Improving_the_Sensitivity_of_Online_Controlled_Experiments_by_Utilizing_Pre-Experiment_Data).

> Eligible stores are randomly assigned to an experiment variant

Users will be assigned variants and not stores, I think it is important here to make a distinction here between two user types (if I am understanding Woo correctly):
- Store Admins
- Store Users

Generally I would see you experimenting on one or the other and it wouldn't make sense to experiment on both, that might be the difference between WC Admin and WC Payments?

Experimenting on Store Users should be straightforward and should be very close to our other experiments, e.g. tracking Average Revenue per User, and User conversion metrics.

Experimenting on Store Admins might require some new metrics or a new metric type to track their Store Users e.g. increases in payments to their stores. This could be quire tricky @yanirs to confirm that this is possible. 
However tracking general admin usage, e.g. conversions like launching a store, more products created, more subscriptions purchased, or subscription revenue, these should be straight forward.

> If a store is assigned to a variant, all users that log into that store see the same experience

Yep, ExPlat's participants won't see the same variant. But to be technically correct stores aren't assigned a variant. 


> We track how a store was assigned to a specific variant (Normal, default, or user consistency)

Yep roughly, except for the client we rely on logstash to 

> Stores are excluded from an experiment if they are already in another experiment affecting that part of the experience

We don't have this yet but we have it in our short-term roadmap, we call it "Exclusion Groups", however it would be centred around users not stores - "users are excluded from an experiment if they are already in another experiment affecting that part of the experience"

> Assignment in an experiment is independent of assignment in another experiment, unless explicitly identify correlated experiments

✅ 

> We can set threshold for stores for an experiment to end

❌ Not something we offer built-in

🤔 We do have a nice management API which could be used for automation like this.  

> We can ramp up deployment of the experiment, ie 10% to 50%

This is on our longer-term roadmap but not sure when we will get to it. 

> We have an event indicating when a store enters an experiment funnel

"We have an event indicating when a **user** enters an experiment funnel"

**Comment by yanirs** [comment] 2021-03-29 07:38
Good comments, @jessie-ross!

@pmcpinto @psealock @oneillo it may be worth moving this discussion to a P2. I don't have enough context on how Woo works together with our backends, but it's worth noting that adding a new A/B testing library is often much trickier than it seems and there are many subtle pitfalls (e.g., around unbiased assignment and consistent and reproducible analysis). Our first goal was to replace the A/B testing libraries on Calypso and the WP.com backend to help experimenters overcome many known issues, but this is just the beginning. In the long term, we are planning on expanding ExPlat to support things like different randomisation units, so it'd be good to understand your needs better.

> > Age of Store
>
> This should be possible with the snapshot method I mentioned above.

I'm not familiar with how Woo connects to WP.com on the backend, but this sounds like something we may also be able to support with a custom eligibility check (= PHP backend code).

> > A8C employees / JN are automatically excluded from experiments
>
> While A8C employees are filtered their stores currently wouldn't be. We have an ETL pipeline where we should be able to add additional filtering, @yanirs to confirm.

Yeah, if there's an easy way to identify such stores. Wouldn't the association with an A8C employee be enough, though?

> Experimenting on Store Admins might require some new metrics or a new metric type to track their Store Users e.g. increases in payments to their stores. This could be quire tricky @yanirs to confirm that this is possible.

Yeah, that's quite indirect and tricky. I'm not sure we're in a position to track that, as it's similar to a WP.com intervention that'd affect users of the site. It may be better to focus on direct effects.

**Comment by psealock** [comment] 2021-03-29 23:13
Thanks for the round of feedback @jessie-ross @yanirs 

>it may be worth moving this discussion to a P2

Yes, the details are best suited to P2, but I will address some points here and bring this discussion to an action point.

The first goal of this issue is to determine the best solution (ExPlat v. a wc-admin compenent). I think we have enough here to make a decision on this front. It would be in Woo's best interest to leverage the wealth of knowledge of ExPlat and its authors. The distinction of Stores v. Users as a randomization unit appears to be the biggest hurdle, but there are already a variety of proposed solutions at hand. @pmcpinto to confirm, but I'd like to go [all in on ExPlat](https://github.com/woocommerce/woocommerce-admin/pull/6669). 

>Users will be assigned variants and not stores, I think it is important here to make a distinction here between two user types (if I am understanding Woo correctly):

Yes, it's an important distinction. Typically, we refer to admins as Merchants and users as Customers. As far as WC Admin is concerned, all experiments will be with respect to Merchants and the same will be true for WC Pay. I can see a scenario where experiments on Customers could be of value for WooCommerce Blocks, but its safe to say the focus is Merchants and criteria for evaluating an experiment will be Merchant conversion based on events exactly as described by @jessie-ross:

>However tracking general admin usage, e.g. conversions like launching a store, more products created, more subscriptions purchased, or subscription revenue, these should be straight forward.

And just to clarify this point

>Experimenting on Store Admins might require some new metrics or a new metric type to track their Store Users e.g. increases in payments to their stores.

This is out of scope, although quite an interesting topic indeed

**Comment by pmcpinto** [comment] 2021-03-31 12:16
>  I think we have enough here to make a decision on this front. It would be in Woo's best interest to leverage the wealth of knowledge of ExPlat and its authors. The distinction of Stores v. Users as a randomization unit appears to be the biggest hurdle, but there are already a variety of proposed solutions at hand. @pmcpinto and @oneillo to confirm, but I'd like to go all in on ExPlat.

@psealock I agree that it makes sense to move forward with the ExPlat option and it seems that there are ways to overcome the stores/users issue. @oneillo what do you think?

**Closed** 2021-04-15 01:32 UTC
Labels: Packages
