### ISSUE TITLE
Variable products with a hyphen surrounded by two spaces " - " do not always display attributes in name

### ISSUE THREAD

**Issue by melek** [woocommerce/woocommerce-admin#7183] opened 2021-06-14 19:39 UTC
**Describe the bug**
Naming a Variable Product with a hyphen surrounded by two spaces (` - `) causes that product to display without attribute values in some places.

I believe this is because we check for the first index of the separator to determine if the variation attributes are already included in the passed name string, which can produce a false positive if the name includes the ` - ` pattern:

*woocommerce-admin/client/lib/async-requests/index.js: 98:103*
```
98		export function getVariationName( { attributes, name } ) {
99			const separator = getSetting( 'variationTitleAttributesSeparator', ' - ' );
100	
101		if ( name.indexOf( separator ) > -1 ) {
102			return name;
103		}
```
*woocommerce-admin/packages/components/src/search/autocompleters/variations.js: 102*
```
100		function getVariationName( { attributes, name } ) {
101			const separator =
102				window.wcSettings.variationTitleAttributesSeparator || ' - ';
103		
104			if ( name.indexOf( separator ) > -1 ) {
105				return name;
106			}
```

**To Reproduce**

1. Add a variable product named "Test Product" without a ` - ` in the product name with at least one attribute/variation such as Size: M
2. Create a completed order with the product
3. Go to **Analytics → Variations** once the order is imported for analytics
4. See the normal listing in Variations table with "Test Product - M"
5. Rename the product to "Test - Product" with the ` - `
6. Reload  **Analytics → Variations**
7. Observe error: Product is listed as "Test - Product" without the attribute value.

**Expected behavior**
I expect to see attribute values in variation names even if they have ` - ` in the product's name.

**Screenshots**
![image](https://user-images.githubusercontent.com/220149/121949237-14abbb80-cd0d-11eb-9702-7a31ce67e8b8.png)

**Additional context**
May impact other views across Analytics.

4058979-zen

**Comment by joshuatf** [comment] 2021-06-15 13:02
Thanks for the thorough testing instructions, @melek!  I'm able to reproduce this bug and ran into a couple more errors while testing this:

* Occasionally my variations did not seem to fully resolve.
<img width="793" alt="Screen Shot 2021-06-15 at 8 57 29 AM" src="https://user-images.githubusercontent.com/10561050/122056853-06ff4000-cdb8-11eb-9ab4-1cd10da3e7ed.png">

* The labels in the chart appear to be double appended with the variation attribute (Product name: "Test - Variation", Attribute: "Red"
<img width="351" alt="Screen Shot 2021-06-15 at 8 57 46 AM" src="https://user-images.githubusercontent.com/10561050/122056864-09fa3080-cdb8-11eb-9cc8-44f15dc76f9b.png">

We could use the last index of the found separator which would work as long as the separator was not also found in the attribute.  But since the separator can't be used reliably to split the string, we probably should instead extend the info with the original product name if possible and split the string using that value.

**Comment by moon0326** [comment] 2021-07-01 00:06
Hey @joshuatf Could you try to reproduce this bug again when you get a chance please? @melek and I tried to reproduce this bug again with the provided steps and we both could not reproduce it again for some reason 🤔 

I always get the correct Product/Variation Title despite having ` - ` within the product name.

**Comment by louwie17** [comment] 2021-11-30 14:21
I couldn't reproduce this either, I will close this. Feel free to re-open if the issue is still present.

**Closed by louwie17** 2021-11-30 14:21 UTC
Labels: type: bug, feature: analytics
