### ISSUE TITLE
[Setup Wizard]- (Minor UI)- When the user clicks on Activate Woo Plugin then the label shown to user while navigating to Setup Wizard page is not user-friendly.

### ISSUE THREAD

**Issue by raj007champ** [woocommerce/woocommerce-admin#7899] opened 2021-11-04 07:35 UTC
### Describe the bug
[Setup Wizard]- (Minor UI Bug)- When the User clicks on Activate Woo Plugin or click on the finish setup option, then the label/heading is shown to the user while navigating to Setup Wizard page is not user-friendly. 
Currently, it is showing `/setup-wizardSetup Wizard` which is distorted and unreadable for non-technical person

### To Reproduce
1. Install WooCommerce plugin
2. Activate the WooCommerce plugin and wait for the following label to show up on top of the page `/setup-wizardSetup Wizard`

### Actual behavior:
Currently following lable/heading is shown to user--> '/setup-wizardSetup Wizard` 

### Screenshots

https://user-images.githubusercontent.com/19307354/140274088-abd69fcb-980b-4125-81c5-8fa6d09b3ed7.mp4

![WrongLabel](https://user-images.githubusercontent.com/19307354/140274475-1ee5db5f-89e0-40aa-9ec4-252fe522c10f.JPG)

### Expected behavior
Lable shown to the user should be readable and meaningful.

### Desktop (please complete the following information):

* OS: Windows OS
* Browser: Chrome
* Version: 95.0.4638.69

**Comment by moon0326** [comment] 2021-11-04 22:29
Thank you @raj007champ for taking the time to report this issue. I was able to reproduce it. We'll work on it as soon as possible.

**Comment by joshuatf** [comment] 2021-12-09 15:51
Duplicate of https://github.com/woocommerce/woocommerce-admin/issues/6598

**Closed by joshuatf** 2021-12-09 15:51 UTC
Labels: type: enhancement, feature: onboarding
