### ISSUE TITLE
Table comparison button not enabled when 2 or more items selected

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#1636] opened 2019-02-20 05:38 UTC
**Describe the bug**
When selecting 2 or more items above any table that uses a comparison (taxes, coupons, or categories), the "Compare" button remains disabled even after selecting 2 items.

**To Reproduce**

1. Go to any report with a table that uses a comparison search.
2. Select 2 or more items.
3. Note that the compare button is disabled and you can't submit the comparison search.

**Expected behavior**
Expected to be able to search or compare after selecting 2 or more items.

**Screenshots**
<img width="697" alt="screen shot 2019-02-20 at 1 27 26 pm" src="https://user-images.githubusercontent.com/10561050/53068815-c3140d00-3514-11e9-917d-c2a33b5581e4.png">

**Comment by justinshreve** [comment] 2019-02-20 15:31
@joshuatf I can't seem to reproduce this. Are you getting a console error? I tested categories, taxes, products, and coupons. I also tested a tax rate with slashes like yours just in case.

The button activated each time. The only issue I had was clicking compare on taxes didn't do anything, but this will be fixed with #1571.

<img width="509" alt="screen shot 2019-02-20 at 10 27 43 am" src="https://user-images.githubusercontent.com/689165/53102864-89360d00-34fa-11e9-9e16-7aaf4d2ab6c6.png">

<img width="509" alt="screen shot 2019-02-20 at 10 27 43 am" src="https://user-images.githubusercontent.com/689165/53102878-8fc48480-34fa-11e9-8975-384f4a20de2b.png">

**Comment by joshuatf** [comment] 2019-02-21 01:01
@justinshreve Sorry, I may have misinterpreted how this is supposed to work.

Is the compare button supposed to become enabled when adding items to the search box or only for selecting the checkbox next to rows?

The latter works for me, but no changes to the search box occur or have effect on the compare button.
<img width="577" alt="screen shot 2019-02-21 at 9 00 05 am" src="https://user-images.githubusercontent.com/10561050/53135707-3c643c00-35b7-11e9-8f3d-ff875ee4406c.png">

**Comment by joshuatf** [comment] 2019-02-21 01:03
Also this isn't specific to taxes on my environment- same behavior on coupons and categories as well.

**Comment by justinshreve** [comment] 2019-02-21 15:24
> Is the compare button supposed to become enabled when adding items to the search box or only for selecting the checkbox next to rows?

I thought it was for the checkboxes -- (the search happens immediately as soon as a item/search is selected so I never had to use the compare button for that) -- but I'm not 100% sure.

@LevinMedia Is the compare button meant to submit the search box?

**Comment by Aljullu** [comment] 2019-02-22 13:44
> @LevinMedia Is the compare button meant to submit the search box?

Not @LevinMedia, but AFAIK, no. The table search input is a tool to filter results, but it should not activate any comparison. That's important because they show different charts.

Search (`time-comparison` chart):
![image](https://user-images.githubusercontent.com/3616980/53246031-ca235280-36af-11e9-843e-536c75d040c8.png)

Comparison (`item-comparison` chart):
![image](https://user-images.githubusercontent.com/3616980/53246086-f63ed380-36af-11e9-9da6-64635cc9a81d.png)

**Comment by joshuatf** [comment] 2019-02-26 06:41
@Aljullu Thanks for that great explanation.

In that case, I think this is a bit more of a UI issue as I expected the search box to be somehow connected to the adjacent compare button.  A small change on the compare button tooltip to something like "Check at least 2 items to compare" might help clear up some of this confusion.

However, if I'm in the minority here and this was obvious to everyone else, let's close this issue. /cc @LevinMedia

**Comment by Aljullu** [comment] 2019-02-27 13:48
> A small change on the compare button tooltip to something like "Check at least 2 items to compare" might help clear up some of this confusion.

@joshuatf But that's already happening, isn't it? Or I understood you wrong?

![image](https://user-images.githubusercontent.com/3616980/53494604-6ed1d580-3a9e-11e9-8fe7-fde0323a7137.png)

**Comment by LevinMedia** [comment] 2019-02-27 15:34
Heya @joshuatf yeah, as it stands it's built out to spec. Perhaps we can change the tool tip to read:

"Check at least two products below to compare" or "Select at least two products below to compare"

**Comment by joshuatf** [comment] 2019-03-14 04:20
>But that's already happening, isn't it? Or I understood you wrong?

@Aljullu Very subtle change here and I'm probably nitpicking, but using the work "Check" instead of "Select" I think clears things up a bit as I was expecting select to refer to a select dropdown (autocomplete options in this case).

>"Check at least two products below to compare"

@LevinMedia I like this one and should add some idiot-proofing for people like me trying to compare dropdown items 😆

**Closed** 2019-03-15 01:00 UTC
Labels: Analytics, [Type] Bug
