### ISSUE TITLE
Coupon Search Not Filtering the Coupon List and Summary Data

### ISSUE THREAD

**Issue by kcfgl** [woocommerce/woocommerce-admin#7258] opened 2021-06-26 13:16 UTC
**Describe the bug**
On the Coupons Report (Analytics>Coupons), when you attempt to filter the coupon list using the search box (next to the Compare button), the auto-suggest drop down displays with a link, tapping the link will add the search text as a filter, but it will not return results. Even if the search text matches the coupon exactly

**To Reproduce**

1. Go to Analytics>Coupons
2. Ensure there are coupons returned in the results
3. Enter the exact name of a coupon in the search/filter input field
4. Tap on the link the "All coupon codes that contain..."
5. 0 Results will show up

**Expected behavior**
If there are coupons that match the search, only those should show up in the list and the summary data should be updated to reflect only orders that leveraged the searched/selected coupon code.

**Screenshots**
<img width="2358" alt="Screen Shot 2021-06-26 at 9 09 33 AM" src="https://user-images.githubusercontent.com/19731815/123513986-3dfa0f00-d65e-11eb-9624-7cd6ba727529.png">

**Desktop (please complete the following information):**

* OS: iOS
* Browser: Chrome
* Version 91.0.4472.114

**Comment by ilyasfoo** [comment] 2021-07-01 10:58
Hi, @kcfgl! 

Thank you for taking the time to report this bug, we really appreciate your help. I was able to reproduce this, it seems that the API does return the data but it was not rendered in the search result. This also seems to be intermittent, as the next search actually renders the data. I think that's important to the context.

![image](https://user-images.githubusercontent.com/3747241/124113415-00521780-da9e-11eb-9047-0117555836d9.png)

**Comment by kcfgl** [comment] 2021-07-02 02:16
Thanks for confirming the bug @ilyasfoo! It is interesting that the second search works for you. I haven't been able to recreate that, but I'll try a few more times and see if I can.

**Comment by chihsuan** [comment] 2022-02-07 07:56
@ilyasfoo I'm going to close this since this bug is over 6 months old. Free free to reopen it whenever you have the bandwidth to work on it!

**Closed by chihsuan** 2022-02-07 07:56 UTC
Labels: type: bug, feature: analytics

**Comment by ilyasfoo** [comment] 2022-02-07 11:09
Hey, @chihsuan. Thanks for bringing this to my attention. I tried to reproduce this again with WCA 3.2 beta 2, and I wasn't able to. I think this may have been fixed by one of your analytics PR in the past 😄
