### ISSUE TITLE
Multisite super admin blank screen since wcadmin 2.1.2

### ISSUE THREAD

**Issue by ilyasfoo** [woocommerce/woocommerce-admin#7004] opened 2021-05-18 01:07 UTC
**Describe the bug**
Originally reported in https://github.com/woocommerce/woocommerce-admin/issues/6857, a multisite super admin is unable to access WooCommerce pages (blank screen, no errors) without explicitly adding the super admin user in each of the sites.

This issue is identified to occur since WCAdmin 2.1.2 (WooCommerce 5.2). It also seems that pairing any WooCommerce and WCAdmin that has suspected breakage will produce the issue (ex: WCAdmin 2.0.3 with WooCommerce 5.3 or WCAdmin 2.1.2 with WooCommerce 5.1).

**To Reproduce**

1. In a JN multisite instance, go to network admin > plugins.
2. Install [WooCommerce 5.1](https://github.com/woocommerce/woocommerce/releases/tag/5.1.0) and [WCAdmin 2.1.2](https://github.com/woocommerce/woocommerce-admin/releases/tag/v2.1.2-plugin).
3. Add a new site.
2. Go to the new site's wp-admin dashboard, activate WooCommerce.
3. Observe that the setup wizard loads without a problem, skip the setup.
4. Activate WCAdmin.
5. Navigate to WooCommerce > Home.
6. Observe the blank page.

**Expected behavior**
It should not be displaying a blank page and multisite super admin should be able to access WooCommerce pages without explicitly adding the user in every site.

**Screenshots**
![image](https://user-images.githubusercontent.com/3747241/118574540-3faafa00-b7b7-11eb-8281-6b088cf7688c.png)

**Additional context**
A [change comparison](https://github.com/woocommerce/woocommerce-admin/compare/release/2.0.3...release/2.1.2) between 2.0.3 and 2.1.2 may contain the culprit.

**Comment by moon0326** [comment] 2021-05-19 10:26
After looking into the problem, it looks like this bug appeared after merging this [PR](https://github.com/woocommerce/woocommerce-admin/pull/6365), but the underlying problem is in the core's `wp_get_current_user`

`wp_get_current_user` doesn't return `roles` and `capabilities` for the super admin on a multisite if you create a new site with an email address that is different from the super admin's email address.

I'm not exactly sure if this is expected behavior, but I've submitted a bug ticket [here](https://core.trac.wordpress.org/ticket/53231#ticket) for now.

**Comment by moon0326** [comment] 2021-05-19 18:34
Closing this as this is expected behavior. See comment on [here](https://core.trac.wordpress.org/ticket/53231#comment:3).

I also left a workaround on the original [issue](https://github.com/woocommerce/woocommerce-admin/issues/6857).

**Closed by moon0326** 2021-05-19 18:34 UTC
Labels: type: bug

**Comment by adrianduffell** [comment] 2021-05-20 02:43
I'm not sure this is ready to close as the blank screen is still a problem. It leaves users with no information about how to fix the issue.

Maybe we could solve it with a simple error message about not having permission to view this page?
