### ISSUE TITLE
Inventory and Reviews empty states are still being displayed alongside the store setup task list

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6095] opened 2021-01-19 10:00 UTC
**Describe the bug**
The Inventory and Reviews empty states are being displayed alongside the store setup task list, which can distract and confuse the user. #5952 should have addressed this, so I don't know what happened. Ideally this should be fixed in 5.0 

**To Reproduce**

1. Create a new store with 4.9 installed
2. Complete or skip the store profiler
3. Visit the home screen
4. See the inventory and reviews empty states.

**Expected behavior**
To only see the store setup tasks, as I'm a new user and I still don't have any products, reviews or orders

**Screenshots**
https://d.pr/i/K9RXOP

**Comment by octaedro** [comment] 2021-01-20 21:55
Hello @pmcpinto,
Just to confirm, we shouldn't show the `Review` and the `Inventory` panels if they are empty? Did I understand correctly?
Thanks!

**Comment by pmcpinto** [comment] 2021-01-21 10:43
@octaedro no. They shouldn't be displayed if the setup task list is enabled. This was supposed to be fixed in #5952 and shipped in 4.9, but I don't know what happened. Maybe it wasn't cherry picked. Can you confirm?

**Comment by psealock** [comment] 2021-01-22 02:44
>Maybe it wasn't cherry picked. Can you confirm?

I see changes from https://github.com/woocommerce/woocommerce-admin/pull/5973 in the release branch

**Comment by moon0326** [comment] 2021-01-22 03:11
The WC Admin 1.8.3 tag (included in WC 4.9) does not have Jeff's [changes](https://github.com/woocommerce/woocommerce-admin/pull/5973/files), but the WC Admin 1.9.0-* tags have them now.

**Comment by psealock** [comment] 2021-01-22 03:17
Tested with WC 5.0.0-beta.2 and 1.9.0-rc.2 and there are no empty states for reviews or inventory. I think its safe to close this out.

<img width="1436" alt="Screen Shot 2021-01-22 at 4 15 36 PM" src="https://user-images.githubusercontent.com/1922453/105441364-458f4380-5ccd-11eb-9afe-f9e53d468019.png">

**Comment by octaedro** [comment] 2021-01-22 19:24
Hi @psealock and @moon0326 
I was testing this and the `Reviews` panel will be shown if there are [any published products](https://github.com/woocommerce/woocommerce-admin/blob/main/client/homescreen/activity-panel/panels.js#L53).

So, they will be visible even when the [setup task list is enabled](https://github.com/woocommerce/woocommerce-admin/issues/6095#issuecomment-764545999).

![Screen Capture on 2021-01-22 at 16-05-17](https://user-images.githubusercontent.com/1314156/105534055-b3d30680-5ccb-11eb-84f5-5735e7546776.gif)
_Tested on WooCommerce 5.0.0-beta.2_

Maybe @pmcpinto could confirm if this is the expected behavior or not.
Thank you

**Comment by pmcpinto** [comment] 2021-01-25 11:32
> So, they will be visible even when the setup task list is enabled.

The reviews and inventory tasks should be hidden while the task list is enabled. Tks in advance.

**Comment by louwie17** [comment] 2021-01-27 21:15
> The reviews and inventory tasks should be hidden while the task list is enabled. Tks in advance.

@pmcpinto should the orders panel also be hidden while the task list is enabled? Or is it ok for it to be present?

**Closed** 2021-01-27 21:40 UTC
Labels: type: bug

**Comment by pmcpinto** [comment] 2021-01-28 10:14
> @pmcpinto should the orders panel also be hidden while the task list is enabled? Or is it ok for it to be present?

The panel should also be hidden. AFAIR this one was solved in December.

**Comment by octaedro** [comment] 2021-01-28 18:00
Thank you @pmcpinto for your answer,

> The panel should also be hidden. AFAIR this one was solved in December.

Currently, the Orders panel will be shown even when the setup task list is visible.
I created the [PR 6220](https://github.com/woocommerce/woocommerce-admin/pull/6220) to address that problem.
After merging that PR no panels will be visible before hiding the setup task list.
Do we need this fix in `1.9.0`?

**Comment by pmcpinto** [comment] 2021-01-29 07:57
> Do we need this fix in 1.9.0?

Ideally it should go on 1.9, if we still have time

**Comment by octaedro** [comment] 2021-02-01 16:01
Hi @pmcpinto,
Last week we released to [core](https://github.com/woocommerce/woocommerce/pull/28976) and [wp.org](https://wordpress.org/plugins/woocommerce-admin/).
Maybe we can ask @timmyc about adding this change in another `1.9` release or wait for a later one.

**Comment by timmyc** [comment] 2021-02-01 23:25
I think we missed the cut-off of 1.9 already since the final has been published to wp.org, and smoke testing for 5.0 has already happened with that version. As such, this will go out in 2.0 of woocommerce-admin and 5.1 of core @pmcpinto

**Comment by psealock** [comment] 2021-02-01 23:26
>As such, this will go out in 2.0 of woocommerce-admin and 5.1

Agree on this one. I don't think this warrants a 1.9.1

**Comment by pmcpinto** [comment] 2021-02-04 14:17
Ok. @octaedro @becdetat can we include this in 2.0?
