### ISSUE TITLE
Can't `npm i` on v2.2.6 or main branch.

### ISSUE THREAD

**Issue by WraithKenny** [woocommerce/woocommerce-admin#6970] opened 2021-05-11 16:34 UTC
**Describe the bug**
I've done a fresh clone of this repo, and `npm i` which fails. I've checked out `v2.2.6` and `npm i` also fails.
 
**To Reproduce**
1. Clone this repo
2. run `npm i`
3. See error

**Expected behavior**
It's expected that npm would install without error.

**Additional context**

Seems related to https://github.com/Automattic/puppeteer-utils/issues/8

❯ npm i
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /usr/local/Cellar/node/16.1.0/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/ken/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
npm ERR! > @automattic/puppeteer-utils@0.0.1 postinstall
npm ERR! > npm run build
npm ERR! 
npm ERR! 
npm ERR! > @automattic/puppeteer-utils@0.0.1 build
npm ERR! > babel --presets=@babel/preset-env src -d lib
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /Users/ken/.npm/_cacache/tmp/git-clone-c7fe3f0d/node_modules/@babel/helper-compilation-targets/package.json
npm ERR!     at new NodeError (node:internal/errors:363:5)
npm ERR!     at throwExportsNotFound (node:internal/modules/esm/resolve:321:9)
npm ERR!     at packageExportsResolve (node:internal/modules/esm/resolve:546:3)
npm ERR!     at resolveExports (node:internal/modules/cjs/loader:478:36)
npm ERR!     at Function.Module._findPath (node:internal/modules/cjs/loader:518:31)
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:27)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:774:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1013:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:93:18)
npm ERR!     at Object.<anonymous> (/Users/ken/.npm/_cacache/tmp/git-clone-c7fe3f0d/node_modules/@babel/preset-env/lib/debug.js:8:33) {
npm ERR!   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
npm ERR! }
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /Users/ken/.npm/_cacache/tmp/git-clone-c7fe3f0d
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c npm run build
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/ken/.npm/_logs/2021-05-11T16_27_01_418Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ken/.npm/_logs/2021-05-11T16_27_43_879Z-debug.log

**Comment by becdetat** [comment] 2021-05-12 00:10
Hi @WraithKenny !

I can't reproduce this, I performed a fresh clone and ran `npm i` and didn't get any errors. Possibly it's a node/nvm version issue? I'm using node 12.16.1 and nvm 6.14.8.

**Comment by samueljseay** [comment] 2021-05-13 03:26
@WraithKenny I'm going to close this for now, since the bug is not actually in wc-admin. Please let me know if downgrading npm does not work for you because that would indeed be a problem.

Thanks for raising this!

**Closed by samueljseay** 2021-05-13 03:26 UTC
Labels: category: won't fix, priority: low, type: bug
