### ISSUE TITLE
Category Analytics change when looking at a single category

### ISSUE THREAD

**Issue by fhaps** [woocommerce/woocommerce-admin#7597] opened 2021-08-31 00:31 UTC
### Describe the bug
The numbers displayed on the Analytics > Categories page change when you click to see a single category. 

### Screenshots

These are the numbers shown for the `Uncategorized` category under Analytics > Categories:

![](https://d.pr/i/ZkTaPa+)
Image Link: https://d.pr/i/ZkTaPa

After I click on that category to see details for that single item, the numbers update to be vastly different:

![](https://d.pr/i/jb6Yhd+)
Image Link: https://d.pr/i/jb6Yhd

### To Reproduce

I have seen this behavior in more than one site, but I haven't been able to reproduce this reliably or pin-point what exactly is causing it. 

In my testing, I ruled out deleted products being the cause of this. One of the products (Ticket Example 1) seen in the Single Category view was deleted, but that didn't change the numbers on that page.

It isn't caused by multiple categories added to the same product, as the products listed there are only part of that single category.

### Desktop (please complete the following information):

* macOS
* Chrome
* Version 92.0.4515.131

### Additional context

Also reported in 4260576-zen

I was able to find several other issues that reference discrepancies in the Categories reports, but none of them are exactly like the behavior described above. For reference:

#6376
#6627
#6770

**Comment by moon0326** [comment] 2021-09-01 21:15
Thank you @fhaps for taking the time to report this bug. I wasn't able to reproduce it locally, but this looks like it might be related to caching as cache time is a [week](https://github.com/woocommerce/woocommerce-admin/blob/main/src/API/Reports/Cache.php#L73). I think that might be too long for the endpoint. We'll look into it further.

**Comment by joshuatf** [comment] 2021-12-07 20:32
@fhaps I was also unable to reproduce this.

Do you still have access to the site with this issue?  I'm curious if we can rule out caching if the issue has persisted.

**Comment by fhaps** [comment] 2022-01-18 16:31
@joshuatf I tested on one of my sites and could still reproduce the issue. Here's how the line for Uncategorized displays in the report:

![](https://d.pr/i/TmGZjf+)
Image Link: https://d.pr/i/TmGZjf

Here's what shows once I expand that category:

![](https://d.pr/i/EoNcyC+)
Image Link: https://d.pr/i/EoNcyC

Date range is the same on both instances. I cleared WordPress and WooCommerce transients, as well as the analytics cache and the template cache. Verified that historical data has been imported. 

The issue is still present.

**Comment by joelclimbsthings** [comment] 2022-02-02 22:04
I also haven't been able to reproduce this issue on my local. Can I ask which version of WooCommerce & WooCommerce Admin you've seen this on @fhaps ?

**Comment by joelclimbsthings** [comment] 2022-03-01 21:42
Since this is ~6 months old, and we've been unable to reproduce, I'm going to close it until we receive more information.

**Closed by joelclimbsthings** 2022-03-01 21:42 UTC
Labels: type: bug, feature: analytics, needs feedback, priority: low
