### ISSUE TITLE
Fatal Error When Deactivating WC Admin

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-admin#6516] opened 2021-03-04 14:30 UTC
**Describe the bug**
I was doing some testing and wanted to deactivate the plugin, but when I do so I see a fatal error and the plugin is not deactivated. Stack trace:

```
2021-03-04T14:23:26+00:00 CRITICAL Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, bool given in /Users/mikejolley/Sites/plugins/woocommerce-admin/src/RemoteInboxNotifications/ComparisonOperation.php:36
Stack trace:
#0 /Users/mikejolley/Sites/plugins/woocommerce-admin/src/RemoteInboxNotifications/ComparisonOperation.php(36): in_array('payments', false, true)
#1 /Users/mikejolley/Sites/plugins/woocommerce-admin/src/RemoteInboxNotifications/OptionRuleProcessor.php(29): Automattic\WooCommerce\Admin\RemoteInboxNotifications\ComparisonOperation::compare(false, 'payments', 'contains')
#2 /Users/mikejolley/Sites/plugins/woocommerce-admin/src/RemoteInboxNotifications/RuleEvaluator.php(47): Automattic\WooCommerce\Admin\RemoteInboxNotifications\OptionRuleProcessor->process(Object(stdClass), Object(stdClass))
#3 /Users/mikejolley/Sites/plugins/woocommerce-admin/src/RemoteInboxNotifications/EvaluateAndGetStatus.php(32): Automattic\WooCommerce\Admin\RemoteInboxNotifications\RuleEvaluator->evaluate(Array, Object(stdClass))
#4 /Users/mikejolley/Sites/plugins/woocommerce-admin/src/RemoteInboxNotifications/SpecRunner.php(44): Automattic\WooCommerce\Admin\RemoteInboxNotifications\EvaluateAndGetStatus::evaluate(Object(stdClass), 'pending', Object(stdClass), Object(Automattic\WooCommerce\Admin\RemoteInboxNotifications\RuleEvaluator))
#5 /Users/mikejolley/Sites/plugins/woocommerce-admin/src/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php(95): Automattic\WooCommerce\Admin\RemoteInboxNotifications\SpecRunner::run_spec(Object(stdClass), Object(stdClass))
#6 /Users/mikejolley/Sites/plugins/woocommerce-admin/src/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php(131): Automattic\WooCommerce\Admin\RemoteInboxNotifications\RemoteInboxNotificationsEngine::run()
#7 /Users/mikejolley/Sites/local/store/app/public/wp-includes/class-wp-hook.php(289): Automattic\WooCommerce\Admin\RemoteInboxNotifications\RemoteInboxNotificationsEngine::run_on_deactivated_plugin('woocommerce-adm...')
#8 /Users/mikejolley/Sites/local/store/app/public/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#9 /Users/mikejolley/Sites/local/store/app/public/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#10 /Users/mikejolley/Sites/local/store/app/public/wp-admin/includes/plugin.php(837): do_action('deactivated_plu...', 'woocommerce-adm...', false)
#11 /Users/mikejolley/Sites/local/store/app/public/wp-admin/plugins.php(208): deactivate_plugins('woocommerce-adm...', false, false)
#12 {main}
  thrown in /Users/mikejolley/Sites/plugins/woocommerce-admin/src/RemoteInboxNotifications/ComparisonOperation.php on line 36
```

**To Reproduce**
Deactivate from the plugins screen.

**Additional context**
In this case I was only running woo core and the trunk version of wc admin with a dev build.

**Comment by moon0326** [comment] 2021-03-05 01:28
Thank you @mikejolley to report the bug 👍  We've identified the cause and made a [PR](https://github.com/Automattic/woocommerce.com/pull/9672). We will also make a PR in WC Admin as well.

**Comment by moon0326** [comment] 2021-03-05 05:23
@mikejolley The issue should be fixed by now. Please try again. Closing this ticket for now.

**Closed by moon0326** 2021-03-05 05:23 UTC
