### ISSUE TITLE
4.6.0 RC 1 - Mobile App banner still shows after clicking on the "view" link, and then refreshing the page.

### ISSUE THREAD

**Issue by anant1811** [woocommerce/woocommerce-admin#5268] opened 2020-10-04 15:24 UTC
This is for WooCommerce 4.6.0 RC 1 Testing Instruction: 

```
Back on the test site, refresh the WooCommerce page, and verify the app banner is no longer shown.
```

On iPhone XR running iOS 14.0.1, after clicking the "View" link if we come back to the site and refresh the WooCommerce page, the app banner still shows. Here's a screencast: https://d.pr/v/O1De1E

**Comment by timmyc** [comment] 2020-10-06 16:24
@samueljseay could you look into this issue?

**Comment by samueljseay** [comment] 2020-10-06 22:40
@timmyc @anant1811 I'm sorry for any confusion being caused by the iOS banner, but its a banner controlled by iOS and we can't close it. Its possible that any testing instructions forwarded on were not clear that they are different for iOS.

I believe with the iOS banner if you click the "x" on the left it will disappear for that website (but may reappear in future if you clear browser history etc). I also believe if the app is already installed it should not show, but again these behaviours are controlled by Apple not us.

I'm going to close this for now, but please reopen if you feel that this is incorrect.

**Closed by samueljseay** 2020-10-06 22:40 UTC
Labels: [Type] Bug

**Comment by timmyc** [comment] 2020-10-06 22:44
Thanks for the clarification Sam, TIL.

**Comment by anant1811** [comment] 2020-10-07 04:25
Thanks, Sam. TIL as well!
