### ISSUE TITLE
Navigation Inbox note showing up when navigation isn't available

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#7807] opened 2021-10-15 19:07 UTC
### Describe the bug
I received this Inbox note on my self hosted WooCommerce site this week. Upon clicking "Enable", I was directed to the Advanced settings area but there was no way to enable the new navigation.

### Actual behavior:
This Inbox note should be turned off for all sites that don't have the option to turn on the new WooCommerce navigation.

### Screenshot
<img width="916" alt="Screen Shot 2021-10-13 at 9 47 33 AM" src="https://user-images.githubusercontent.com/5121465/137539875-000dcecb-a34f-4842-952a-e83303014ffa.png">
<img width="996" alt="Screen Shot 2021-10-13 at 9 48 34 AM" src="https://user-images.githubusercontent.com/5121465/137539879-d5c84313-6f14-4ddc-bb15-bc67c699ecb5.png">

cc @pmcpinto

**Comment by becdetat** [comment] 2021-10-19 00:20
> @becdetat are you aware of any changes that may have caused this?

No, I haven't seen anything come through that would have changed this. The note was last modified back in March. Looks like @joshuatf did all the work for this note, Joshua do you know what could have caused this?

**Comment by mattsherman** [comment] 2021-11-03 14:12
@jacob-sewell has been looking into this. Moving it to In Progress pipeline to reflect that.

**Comment by jacob-sewell** [comment] 2021-11-05 21:53
I finally have a nice repeatable reproduction of this issue. Here's what I did:
* Start with a clean WordPress site.
* Installed WooCommerce via the plugin search (currently version 5.8.0)
* Installed WooCommerce Admin via the plugin search (currently version 2.8.0)
  * (I had to deactivate and reactivate the WC Admin plugin before the NavigationNudge note was created.)
* Deactivate WC Admin plugin
  * Note still displays because it's already in the database, but checkbox is gone because the navigation feature isn't supported in the core admin package.

Now this sequence isn't likely in a real use case, but consider what happens if WooCommerce core is updated to a point where its packaged WooCommerce Admin overrides the plugin.

**Comment by mattsherman** [comment] 2021-11-06 13:48
@jacob-sewell The [`WooCommercePayments`](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Notes/WooCommercePayments.php) nudge note does some checking to account for actioning the note if WooCommercePayments has been installed after the note was created. It seems like we could do something similar in this note to action the note (or, maybe there is some better action to take on the note? /cc @becdetat). We'd want to ideally handle if the Navigation feature became available again in the future, to re-show the note.

I think that as far as fixing this, we could just fix it in WCA (likely, 3.0.0 at this point, since 2.9.0 is in beta). Once that version gets in WC core, all will be well. In the mean time, it is a confusing annoyance, for sure, but not too harmful. Especially since the only way this seems to be able to occur if if the installation once had WCA installed. So, the admin is likely to consider re-installing WCA if they see this note and want to do something with Navigation.

**Comment by becdetat** [comment] 2021-11-07 22:29
> It seems like we could do something similar in this note to action the note (or, maybe there is some better action to take on the note? /cc @becdetat)

I think just actioning the note is fine

**Closed** 2021-11-16 04:51 UTC
Labels: type: bug, feature: inbox, feature: navigation
