### ISSUE TITLE
[4.0 beta1] New OBW: formatting of the text in the tracking pop-up window is off

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#3693] opened 2020-02-10 12:42 UTC
**Describe the bug**

Testing 4.0 beta1 pre-public release. The formatting of the text in the tracking pop-up window is off. It doesn't happen all the time. 

**To Reproduce**

1. Start new OBW;
2. Click on the `Get started` button. Note that the formatting of the text in the tracking pop-up window is off (the font seems to be different and no padding between lines):

![formatting](https://user-images.githubusercontent.com/19143190/74150379-b6933380-4c01-11ea-9c08-1cc65acc795f.jpg)

**Expected behavior**

I expected the text to be formatted as follows:

![Screen Shot 2020-02-10 at 12 41 36 PM](https://user-images.githubusercontent.com/19143190/74150845-b2b3e100-4c02-11ea-9f93-7a5d9a2b06ee.png)

**Screenshots**

See above. 

**WordPress (please complete the following information):**

* Core version: 5.3.2
* Gutenberg version (if installed): not installed
* WooCommerce version: 4.0 beta1
* WooCommerce Blocks version: not installed
* Site language: English
* Any other plugins installed: Jetpack by WordPress.com

**Desktop (please complete the following information):**

* OS: macOS Catalina v 10.15.3
* Browser: Chrome
* Version: 80.0.3987.87 (Official Build) (64-bit)

**Additional context**

Beta 4.0 was not released to the public yet - this is found during testing the package we tagged before tagging beta and releasing it to the public.

**Comment by timmyc** [comment] 2020-02-13 18:56
@pmcpinto given some of @jameskoster's latest designs on changes to the OBW, this modal window is going away soon ( it will just become a checkbox on the first step of the profiler ), so thinking this isn't a critical bug to fix right now if we don't have time for it. Also it isn't always reproducible it seems

**Comment by joshuatf** [comment] 2020-02-13 20:16
>It doesn't happen all the time.

@juliaamosova Are you able to sometimes reproduce this on the same site after refreshing?  So far, I haven't had any luck in recreating it.

Are there any other plugins you have active besides WC when this occurs?

**Comment by pmcpinto** [comment] 2020-02-14 09:43
> @pmcpinto given some of @jameskoster's latest designs on changes to the OBW, this modal window is going away soon ( it will just become a checkbox on the first step of the profiler ), so thinking this isn't a critical bug to fix right now if we don't have time for it. Also it isn't always reproducible it seems

Hey @timmyc,  we need to keep the modal. Actually, we already show it in the "Store details" when the user already has Jetpack & WCS installed (ignore the copy on the screenshot as it's the old copy version):

<img width="1440" alt="Captura de ecrã 2020-02-14, às 09 38 13" src="https://user-images.githubusercontent.com/3380168/74519640-0299ed00-4f0e-11ea-8315-53e76af85d35.png">

The part in the mockup with the checkbox was from another alternative that ended up not implementing.

**Comment by jeffstieler** [comment] 2020-03-16 15:51
I'm also unable to reproduce this - using latest WooCommerce `master`:

![Screen Shot 2020-03-16 at 9 50 51 AM](https://user-images.githubusercontent.com/63922/76775934-b5f33d00-676b-11ea-9739-f25885065902.png)

**Comment by juliaamosova** [comment] 2020-03-16 16:12
I couldn't reproduce this ever since. And it was on JN site so I can't go back to it to check again. I think this issue can be safely closed.

**Comment by jeffstieler** [comment] 2020-03-16 16:13
Thanks for the follow up @juliaamosova! Closing.

**Closed by jeffstieler** 2020-03-16 16:13 UTC
Labels: Onboarding, [Status] Needs feedback, [Type] Bug
