### ISSUE TITLE
Onboarding Profile API casts booleans as strings

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#2299] opened 2019-05-23 18:27 UTC
**Describe the bug**
The `skipped` field in the onboarding API is saving `true`/`false` as strings.

**To Reproduce**
* Make a `POST` request to `/wc-admin/v1/onboarding/profile?skipped=true`
* See success message.
* Make a `GET` request to `/wc-admin/v1/onboarding/profile`
* See `"true"` in quotes.

<img width="314" alt="Screen Shot 2019-05-23 at 2 26 55 PM" src="https://user-images.githubusercontent.com/689165/58277054-dd08fa00-7d66-11e9-8623-56dcd7448607.png">

**Comment by joshuatf** [comment] 2019-05-24 08:20
This should be resolved once #2283 is merged.  We should double check after merging #2283 and #2300 to make sure the issue is fully resolved.

**Closed** 2019-05-28 14:43 UTC
Labels: Onboarding, REST API, [Type] Bug
