### ISSUE TITLE
Setup Wizard: Currency symbols and formats not updated for other locales

### ISSUE THREAD

**Issue by zhongruige** [woocommerce/woocommerce-admin#5750] opened 2020-11-26 20:51 UTC
**Describe the bug**
While currency values change correctly for certain countries (Germany, the United Kingdom), the currency symbol for other countries isn’t updated. For example: The Japanese Yen currency symbol doesn’t show– it only shows the dollar–when selecting Japan (tried Osaka and Tokyo). Similar behavior is observed for South Korea, China, etc. However, we do support them in the Currency options area under settings:

![image](https://user-images.githubusercontent.com/71906536/100390484-c263b100-2fed-11eb-8cd7-a69fa789f2d0.png)

**To Reproduce**

1. Go to the 'Store Details' step in the Setup Wizard.
2. Select a country such as Japan, South Korea, or China.
3. Continue the setup to the Business Details section.
4. Select that you are currently selling elsewhere (any of the positive options)
5. Note the "current annual revenue" is still shown with the `$`.
6. Switch to the UK or Germany and note that the currency symbol changes, to the Pound Sterling (£) and Euro (€) respectively. Additionally, the formatting changes, with 2.000,000 instead of 2,000.00 for the Euro, for example.

**Expected behavior**
Currency formatting and symbol should reflect the primary currency used in the country.

**Screenshots**

![Screen Shot 2020-11-26 at 1 50 29 PM](https://user-images.githubusercontent.com/71906536/100390649-60f01200-2fee-11eb-84e5-6b8aed607d6d.png)

**Desktop (please complete the following information):**

* OS: macOS Big Sur
* Browser FireFox, Chrome
* Version 83.0, 86

**Comment by joshuatf** [comment] 2021-01-25 23:32
Thanks for reporting this issue @zhongruige!

I think this may have been solved by https://github.com/woocommerce/woocommerce-admin/pull/5969. Would you mind testing on the latest release to see if the issue is resolved for you?

Possible duplicate of https://github.com/woocommerce/woocommerce-admin/issues/5760.

**Comment by joshuatf** [comment] 2021-01-26 20:53
Thanks, @zhongruige!  I am able to reproduce this on WC 4.9.2 and even the latest `main`.  Checking out https://github.com/woocommerce/woocommerce-admin/pull/5969 does resolve the issue, so there must have been something introduced between now and then that broke this.

The country and locale info is properly set in onboarding and appears to be set correctly in https://github.com/woocommerce/woocommerce-admin/blob/3fa3dd067069fc36eaa1759435d5ac9371c20202/packages/currency/src/index.js#L14 however, changes to currencies aren't reflected in the client after calling `setCurrency()`

**Comment by zhongruige** [comment] 2021-01-26 21:00
> Thanks, @zhongruige! I am able to reproduce this on WC 4.9.2 and even the latest `main`. Checking out #5969 does resolve the issue, so there must have been something introduced between now and then that broke this.
> 
> The country and locale info is properly set in onboarding and appears to be set correctly in
> 
> https://github.com/woocommerce/woocommerce-admin/blob/3fa3dd067069fc36eaa1759435d5ac9371c20202/packages/currency/src/index.js#L14
> however, changes to currencies aren't reflected in the client after calling `setCurrency()`

Thanks for the follow up @joshuatf!

**Comment by hsingyuc** [comment] 2021-03-31 21:51
I have a fix for this; push shortly.

**Comment by becdetat** [comment] 2021-04-28 02:38
@hsingyuc's fix has been approved, I'm going to tidy up the readme and merge it in.

**Closed** 2021-04-28 02:54 UTC
Labels: feature: onboarding, priority: high, type: bug
