### ISSUE TITLE
Deadlock on init

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce-admin#4684] opened 2020-06-24 12:54 UTC
**Describe the bug**
Deadlock reported on some sites, e.g. on our wooperf site.

```
 [20-Jun-2020 02:59:13 UTC] WordPress database error Deadlock found when trying to get lock; 
try restarting transaction for query INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('_transient_wc_admin_installing', 'yes', 'no') ON DUPLICATE KEY UPDATE `option_name` = VALUES(`option_name`), `option_value` = VALUES(`option_value`), `autoload` = VALUES(`autoload`)
 made by require('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, Automattic\WooCommerce\Admin\Install::check_version, Automattic\WooCommerce\Admin\Install::install, set_transient, add_option, QM_DB->query
```

Some more info about wooperf site problem: p1592924646101500-slack-C0E1AV8T0

A similar problem got reported in community slack: 
https://woocommercecommunity.slack.com/archives/C1LM8BFAB/p1592930369027800?thread_ts=1592930369.027800&cid=C1LM8BFAB

**To Reproduce**
Not exactly sure about steps to reproduce, our site was just getting hammered by a bot, so maybe it happens under higher load?

**Expected behavior**
No deadlocks.

It seems like it started with 4.3 beta.

**Additional context**

**Comment by jeffstieler** [comment] 2020-06-24 16:37
There's a chance this is caused by a missing database version callback, which would trigger the [setting of this transient](https://github.com/woocommerce/woocommerce-admin/blob/6a6bd85edbfe974b73f2ff79a9b2473b702639b9/src/Install.php#L155) to occur on every `init`.

This was fixed in https://github.com/woocommerce/woocommerce-admin/pull/4668 and cherry picked into our `1.3.0-rc.1` branch.

We'll need to cut an `rc.2` in order to update core.

**Comment by psealock** [comment] 2020-07-01 00:38
Closing as this was fixed in https://github.com/woocommerce/woocommerce-admin/pull/4668 and rc2 includes the fix.

**Closed by psealock** 2020-07-01 00:38 UTC
Labels: [Type] Bug, [Type] Performance
