### ISSUE TITLE
[GlobalStep][Mac] Randomdly PHP Errors (undefined constant JETPACK_MASTER_USER) is observed when user navigates to WooCommerce->Home after completing the OBW setup

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#6844] opened 2021-04-21 15:50 UTC
## Bug Description:
Randomdly PHP Errors (undefined constant JETPACK_MASTER_USER) is observed when user navigates to WooCommerce->Home after completing the OBW setup

## Environment:
Woocommerce Version : WooCommerce 5.2.2
WooCommerce Admin: v5.3 Beta 1
WordPress version: (v5.7)

**PC:**
Mac 10.14.6
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins 
1. Complete the onboarding setup wizard.
1. Observe that Randomdly PHP Errors (undefined constant JETPACK_MASTER_USER) is observed when user navigates to WooCommerce->Home after completing the OBW setup

## Actual Result:
Randomdly PHP Errors (undefined constant JETPACK_MASTER_USER) is observed when user navigates to WooCommerce->Home after completing the OBW setup

## Expected Result:
Website should be free from Jetpack PHP errors.

## ScreenShot:
![#6844](https://user-images.githubusercontent.com/41110392/115583592-a7b90e00-a2e7-11eb-9dc0-41087e72713c.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by joelclimbsthings** [comment] 2021-04-21 20:35
I _believe_ this is related to [another issue regarding the OBW completed button](https://github.com/woocommerce/woocommerce-admin/issues/6836), since I encountered it consistently while reproducing that one. Closing as a duplicate.

**Closed by joelclimbsthings** 2021-04-21 20:35 UTC

**Comment by gglobalstep** [comment] 2021-04-22 12:40
@joelclimbsthings We have found a scenario on which we are consistently able to repro the above issue 
**Environment**:
Woocommerce Version : WooCommerce 5.2.2 and 5.3.0 Beta 1 
WooCommerce Admin: v5.3 Beta 1
WordPress version: (v5.7)

**PC:**
Windows 10, Mac 10.14.6
Chrome(Version 89.0.4389.90) 
Firefox(Version 87.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using the JN site.
1. Install and activate all the required plugins 
1. Complete the onboarding setup wizard and set the Store Address to Canada or any address which displays the WooCommerce Payments option in Business Detail Step.
1. Complete the OBW setup, go to Plugins->Installed Plugins
1. Deactivate The Jetpack plugin, Note a popup is displayed stating it is linked to WooCommerce Payments
1.  Click on Deactivate and Continue button
1. Observe that PHP Errors (undefined constant JETPACK_MASTER_USER) is observed 

Note: When you try to deactivate the "WooCommerce Payments" plugin after the above steps, a new set of errors are displayed regarding it 

Please refer to the Attachment:


https://user-images.githubusercontent.com/41110392/115715648-f9b86d00-a395-11eb-92a0-feb0af6d13cc.mp4
