### ISSUE TITLE
WooCommerce Analytics

### ISSUE THREAD

**Issue by PetrusVermaak** [woocommerce/woocommerce-admin#6573] opened 2021-03-11 07:14 UTC
**Describe the bug**
WooCommerce Analytics does not report multi currency for a product correctly.

**Expected behavior**
It should convert the different currencies to one single currency before counting the total together.

**Actual behavior**
It counts different currencies together, resulting in a skewed total.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Install multi currency, sell product in two different currencies.

**Screenshots**
Here is a view of my orders:
https://prnt.sc/10imyt5

WooCommerce Analytics report an incorrect product sales price (bottom right)
https://prnt.sc/10in2r4

**Comment by psealock** [comment] 2021-03-12 01:25
@tivnet I believe this is functionality introduced in multi-currency. Do you have any updates on this?

**Comment by tivnet** [comment] 2021-03-12 13:15
@psealock Yes, https://woocommerce.com/products/multi-currency/ has a dropdown to filter the currency.

P.S. Additional functionality is regularly requested by clients: when not filtered by currency, convert all totals to the base currency. The conversion rate is stored in the order meta, but WC Admin does not let me access that in Analytics.

**Comment by psealock** [comment] 2021-03-17 00:22
I'll close this as Multi currency isn't offered by WooCommerce Admin or WooCommerce. The feature requested could be solved by a plugin, and in the meantime we will evaluate a multi currency solution if the feature continues to be requested.

**Closed by psealock** 2021-03-17 00:22 UTC
Labels: needs feedback

**Comment by tivnet** [comment] 2021-03-17 16:44
@josegallo The solution in Analytics exists for more than a year already: the possibility to filter the reports by currency. If WPML does not use that, it's their (and unfortunately your) problem. WooCommerce is not multi-currency (and not multilingual) by itself, everything is done by extensions.

**Comment by josegallo** [comment] 2021-03-17 16:46
@tivnet, in what analytics exist, beacause we have checked today it with woocommece support and they confirmed not

**Comment by tivnet** [comment] 2021-03-17 16:49
![image](https://user-images.githubusercontent.com/1696330/111505513-13bfb980-871f-11eb-9a83-53743bb0e993.png)

As I said, Analytics provides the support for filtering by currency. Our extension is using that for a long time.

**Comment by josegallo** [comment] 2021-03-17 16:52
@tivnet , yes thank you, that is what I was commenting about your solution. I was referring that woocommerce analytics has not a "native" solution like that. We are going to try https://woocommerce.com/products/multi-currency/

**Comment by tivnet** [comment] 2021-03-17 16:56
Do not forget to switch OFF the WMPL's multi-currency part. You can keep the multi-lingual.

Analytics can not have a "full" native solution because WooCommerce has no native multi-lingual. Even though the currency code is stored in the order, to have the full support, need to store the exchange rate, too - and that is already the whole new code.

**Comment by josegallo** [comment] 2021-03-17 17:01
@tivnet thanks again, yes we had already on the scope to switch off WMP's multi-currency part. 
Do you happen to know a plugin that allows to have currencies price for each product (example 25 usd, 20 € for a product 1 , 20 USD, 10 € for a product 2 ... with no exchange rate fixed) that be also compatible with https://woocommerce.com/products/multi-currency/?

**Comment by tivnet** [comment] 2021-03-17 17:12
https://woocommerce.com/products/multi-currency/ allows to set currency price per product (Simple and Variable)

![image](https://user-images.githubusercontent.com/1696330/111508700-60f15a80-8722-11eb-8705-175dd650e67b.png)

**Comment by tivnet** [comment] 2021-03-17 18:58
There is a filter that can be used for that.
