### ISSUE TITLE
`<Chart>` component does not react on changing the `currency` property

### ISSUE THREAD

**Issue by tomalec** [woocommerce/woocommerce-admin#7694] opened 2021-09-22 10:05 UTC
### Describe the bug

When I create and render `<Chart>` component with a given current, let's say `{code: 'CAD', symbol: '$', …}`  The chart renders correctly and put the `$` symbol on the y-axis. But when I then change the object to a new one, like: `{code: 'EUR', symbol: '€', …}`, it does not update and still renders `$`.

### To Reproduce

1. Render `<Chart currency={ {code: 'CAD', symbol: '$', …} }>`
2. See if it shows correct value on y axis.
3. Change the currency to `{code: 'EUR', symbol: '€', …}`

### Actual behavior:
`$` Is still rendered

### Screenshots
![chart-currency](https://user-images.githubusercontent.com/17435/134319270-32a63772-117a-4b5a-a794-85fe680203f0.gif)

### Expected behavior
`€` should be rendered

### Desktop (please complete the following information):

* OS: Ubuntu 20.04
* Browser Chrome, Firefox

**Comment by joshuatf** [comment] 2021-09-30 21:04
@tomalec I was not able to reproduce this bug.  Does the change have to occur without a page refresh to trigger this issue?

Using `<Chart currency={ {code: 'EUR', symbol: '€', …} } />` did render the expected currency for me:

![Screen Shot 2021-09-30 at 5.02.16 PM.png](https://images.zenhubusercontent.com/5d7fd4b446611c000130d6f9/7ee38a72-7a59-4cbf-9095-dc4291bd18d3)

**Comment by joshuatf** [comment] 2021-12-07 21:18
@tomalec Do you still need any help with this?  If not, I'll close this issue for now.

**Comment by tomalec** [comment] 2021-12-08 12:42
Ah, thanks for the heads up, I missed the notification. I'll check again this week.

**Comment by mattsherman** [comment] 2022-01-17 15:14
@tomalec Do you still need help with this issue? Please let me know!

**Comment by joelclimbsthings** [comment] 2022-02-02 22:07
Closing this issue for now, feel free to let us know if you're still having trouble here @tomalec .

**Closed by joelclimbsthings** 2022-02-02 22:07 UTC
Labels: type: bug, feature: components, Packages, needs feedback, Needs triage
