### ISSUE TITLE
Net Revenue numbers don't match

### ISSUE THREAD

**Issue by JScott-MSI** [woocommerce/woocommerce-admin#2855] opened 2019-08-28 23:43 UTC
**Describe the bug**
The Net Revenue total on the Revenue page and the Orders page match, however they do not match the Net Revenue on the Product page or the Net Revenue on the Categories page. However the Product and Category page Net revenues match each other.

Woo Admin 1.8.1
Woo 3.7.0

**To Reproduce**
Run the analytics reports

**Expected behavior**
If these are representing Net revenue the total should be the same in all reports, if they are not calculating the same way they need to be labeled in a way that represents what is actually calculated.

**Screenshots**
If applicable, add screenshots to help explain your proble
![Revenue Net Discrepencies](https://user-images.githubusercontent.com/52297130/63899633-6fe2b180-c9b2-11e9-97fa-58a45c75301c.jpg)

**Desktop (please complete the following information):**

* OS: iOS 
* Browser Firefox
* Version Latest

**Comment by JScott-MSI** [comment] 2019-08-28 23:45
Also a pop-up would be nice describing how the totals are calculated.

**Comment by rrennick** [comment] 2019-09-04 16:18
I can confirm the net totals are not the same in my dev install.

**Comment by LevinMedia** [comment] 2019-09-04 22:15
@JScott-MSI thanks for the report - I've run into similar things in my own testing, and I've seen other issues directly related to this popping up elsewhere too:

For example: https://github.com/woocommerce/woocommerce-admin/issues/2836

I'm going to do a deep dive on what's going on here and come back with a master issue to resolve the issues.

cc: @psealock

**Comment by JScott-MSI** [comment] 2019-09-05 00:33
@LevinMedia It's got to be more than coupons, we didn't have $70k in coupons in 2018. Somewhere along the line I noticed that the number of orders matched up, but the number of items sold didn't. I'll have to try to recreate that as I don't remember specifically. I think it was a difference between the woo-admin report and the legacy report. I'll post that if I find it again.

**Comment by LevinMedia** [comment] 2019-09-05 03:10
@JScott-MSI understood! Any additional information you can provide will be very helpful in solving this one. Thanks!

**Comment by Mikcx** [comment] 2019-10-09 20:32
We are seeing a difference in 'Revenue' figures within Analytics > Revenue and Analytics > Products for example. The Analytics > Revenue figure matches that of WooCommerce > Reports.

I initially thought that it was only down to many instances of duplicate orders which were showing within 'Products' report:

<img width="1274" alt="Screenshot 2019-10-09 at 08 38 13" src="https://user-images.githubusercontent.com/3281365/66517512-2ae68a80-eadb-11e9-83db-9d1d637c38ac.png">

... so carried out a reset of the analytics records, and re-imported.

Now the figures are closer, but the revenue figures are still not matching. Now that all the duplicates are out of the way, I can see that the difference is now being caused by Subscription renewals which have a coupon applied, so that the renewal is going through each month at £0.00 instead of £1.99. WooCommerce > Reports shows the product sales as 3x 0.00 whereas the Analytics > Products reports as 3x £1.99 = £5.97.

<img width="256" alt="Screenshot 2019-10-09 at 21 29 23" src="https://user-images.githubusercontent.com/3281365/66518004-1f479380-eadc-11e9-9f81-573ca073e3bc.png">

<img width="1091" alt="Screenshot 2019-10-09 at 21 29 42" src="https://user-images.githubusercontent.com/3281365/66518011-25d60b00-eadc-11e9-8bec-8c4666849f14.png">

**Comment by Mikcx** [comment] 2019-10-09 21:14
...a bit more digging into the calculations, it would seem that our example can be worked out (now that the duplicates were cleaned by emptying/re-importing) - but the titles of 'Net Revenue' don't seem to be correct or what is actually being summed is not correct :

<img width="636" alt="Screenshot 2019-10-09 at 22 03 18" src="https://user-images.githubusercontent.com/3281365/66520307-d2b28700-eae0-11e9-82bb-8b632df645ae.png">

![reports](https://user-images.githubusercontent.com/3281365/66520917-ff1ad300-eae1-11e9-9d93-6c478d05ed56.png)

**Comment by psealock** [comment] 2019-10-10 21:05
>the title of 'Net Revenue' on the products report doesn't seem to be a real 'net revenue' or what is actually being summed is not correct :

Thanks so much for the detailed analysis @Mikcx ! Indeed, the Net Revenue displayed in Products Report is not correct. We're hoping to address this in the coming sprint.

**Comment by rrennick** [comment] 2019-10-22 21:29
A bit of further research shows that partial refunds are not attributed to products so the product & category totals do not have the partial refunds deducted. I'll investigate tomorrow to see if coupons & fees are similar.

**Comment by rrennick** [comment] 2019-10-23 19:01
I've found the following discrepancies

- Rounding - Amounts in the order stats table are rounded to wc_decimals while they aren't in the product lookup table
- `wc-auto-draft` orders are still imported (fixed in a local branch)
- amounts deducted from order net revenue not deducted from product net revenue
 - coupons
 - partial refunds
- amounts added to order net revenue not added to product net revenue
 - fees

**Closed** 2019-10-25 12:29 UTC
Labels: [Many] Medium, [Much] Medium, [Priority] High, [Type] Bug, [estimate] 1
